### ISSUE TITLE
### MySqlConnector ### Couldn't connect to server

### ISSUE THREAD

**Issue by ttosic92** [mysql-net/MySqlConnector#1003]
On project upgrade from 3.1.1 .NET Core version to .NET 5.0 MySqlConnector driver keeps throwing 
"### MySqlConnector ### Couldn't connect to server. More information - Cannot determine the frame size or a corrupted frame was received.". But mind boggling thing was the fact that driver worked when ran from Visual Studio 19.0 but didn't work from docker container.

Base image is .NET5 is 5.0-alpine.

First i thought connection strings are wrong or maybe grants to DB but those generate different kind of exception. I checked connection strings inside container and everything matches. Tried both 1.3.1 and 1.3.9 version of MySqlConnector and same exception happens. 

Thought maybe reverse proxy SSL is issue on server (Debian 10.0) but when i used curl from local network i got same error.
Also tried to host container from WSL, same issue persisted.

**Comment by bgrainger** [comment]
What's the full exception call stack with all inner exceptions?

**Comment by ttosic92** [comment]
Maybe it is old SQL server version that supports TLS 1.0 and 1.1? It wasn't issue before migrating to .NET5.

**Comment by bgrainger** [comment]
This sounds like it could be related to the known breaking changes for SSL on Linux in .NET 5.0: https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux

Given that MySqlConnector works fine under .NET 3.1 but fails under .NET 5.0, it seems like it's more likely to be a runtime issue than a MySqlConnector issue. 

> But mind boggling thing was the fact that driver worked when ran from Visual Studio 19.0 but didn't work from docker container.

I assume this means that the code works on Windows, but not Linux? That also points to it being a .NET runtime issue.

**Comment by ttosic92** [comment]
Thanks for help! That was exactly the issue.
