### ISSUE TITLE
Unable to use MySqlParameter to parameterize a table identifier in queries.

### ISSUE THREAD

**Issue by joshuahomer** [mysql-net/MySqlConnector#1004]
The [Analyze Table Query](https://dev.mysql.com/doc/refman/8.0/en/analyze-table.html) expects a table identifier, and not a string. Whenever I configure a command with a parameter that has the table name, the connector is adding in single quotes around the table name. This of course causes a syntax error in the mysql engine and the query fails. 

Specific details:
Query Text: "ANALYZE TABLE @TableName"
Parameter value: "mytable"

What I expect to be produced from the parameterized query: ANALYZE TABLE mytable;

What is produced from the parameterize query: ANALYZE TABLE 'mytable';

**Comment by bgrainger** [comment]
Command Parameters cannot be used to parameterise table names. That's a fundamental limitation of ADO.NET and generally not an anticipated use of parameterised SQL: https://stackoverflow.com/a/33254802/23633

Construct your query with string concatenation (and add appropriate safeguards if the table name comes from untrusted data).
