### ISSUE TITLE
MySqlBulkCopy inserts 0 rows and fails to surface diagnostic information

### ISSUE THREAD

**Issue by masonwheeler** [mysql-net/MySqlConnector#1005]
I'm attempting to use `WriteToServer(IDataReader)` to copy data from another database.  The destination table exists, and is empty, and the columns I'm writing to exist in the table, so there's no good reason why it should fail.  But it errors out on me, saying that 0 rows out of 10 were written.

When I debug into the source I find, in `ResultSet.ReadResultSetHeaderAsync`, that the server is returning 10 skipped rows with 30 warnings... and then it never does anything to retrieve the warnings from the server, so I have no idea what the problem is or how to deal with it!

Is there any way I can retrieve this information?

**Comment by bgrainger** [comment]
You can possibly retrieve them with [`SHOW WARNINGS`](https://dev.mysql.com/doc/refman/8.0/en/show-warnings.html). Do you have sample code with a repro?

**Comment by bgrainger** [comment]
You can also retrieve them during the operation by attaching an event handler to `MySqlConnection.InfoMessage` and reading the `Errors` collection on the `MySqlInfoMessageEventArgs` object supplied to the event handler.

**Comment by bgrainger** [comment]
Specific question answered in comments above.

Opened https://github.com/mysql-net/MySqlConnector/issues/1012 to discuss future improvements to the API. Thanks for reporting this.

**Comment by masonwheeler** [comment]
> You can also retrieve them during the operation by attaching an event handler to `MySqlConnection.InfoMessage` and reading the `Errors` collection on the `MySqlInfoMessageEventArgs` object supplied to the event handler.

Thanks!  It took a couple days to get back to this, but now I see the problem and have some idea how to fix it.

I also see a different problem, which I'll open another issue for, probably tomorrow because it'll take a bit of time to dig around in the code and make enough sense of it to describe coherently.

**Comment by masonwheeler** [comment]
Looking into things further, the root cause of the second problem turned out to be on my end and not an error in MySqlConnector.
