### ISSUE TITLE
System.FormatException when reading data from char(36) column

### ISSUE THREAD

**Issue by swjain23** [mysql-net/MySqlConnector#1006]
Hi,

We have a table with char(36) column, when we read column data from that table we are hitting this error:

"Exception thrown: Type:FormatException, Error Code:0x80131537, Exception Error Id:10024330350131265534, Source:MySqlConnector.Core.TextRow.GetValueCore"

This is our code:

using (var connection = new MySqlConnection())
{
    connection.ConnectionString = ConnectionString;
    connection.Open();
                   
    using (var command = connection.CreateCommand())
    {
        command.CommandText = queryText;
        command.CommandType = CommandType.Text;
   
        using (var reader = await command.ExecuteReaderAsync(
                            CommandBehavior.CloseConnection,
                            cancellationToken))
                            {
                                return await resultHandler(reader, cancellationToken).ConfigureAwait(false);
                            }
    }
}

private async Task<object> resultHandler(DbDataReader reader, CancellationToken cancelToken)
{
            if (!await reader.ReadAsync(cancelToken))
            {
                return null;
            }

            return reader.GetValue(0);           
}

We hit the error on reader.GetValue(0), we also tried reader.GetString(0) but it failed with the same issue. 

I looked at the source code and this is how char(36) and char(32) is handled by default to be GUID in https://github.com/mysql-net/MySqlConnector/blob/36f961890cf18bed199793262ce4df13cffa6bd9/src/MySqlConnector/Core/TextRow.cs:

case ColumnType.String:
				if (Connection.GuidFormat == MySqlGuidFormat.Char36 && columnDefinition.ColumnLength / ProtocolUtility.GetBytesPerCharacter(columnDefinition.CharacterSet) == 36)
					return Utf8Parser.TryParse(data, out Guid guid, out int guid36BytesConsumed, 'D') && guid36BytesConsumed == 36 ? guid : throw new FormatException();
				if (Connection.GuidFormat == MySqlGuidFormat.Char32 && columnDefinition.ColumnLength / ProtocolUtility.GetBytesPerCharacter(columnDefinition.CharacterSet) == 32)
					return Utf8Parser.TryParse(data, out Guid guid, out int guid32BytesConsumed, 'N') && guid32BytesConsumed == 32 ? guid : throw new FormatException();
				goto case ColumnType.VarString;

This causes a formatException if that column does not have a valid GUID as data.

How should we read data from a char(36) column when it does not have GUID? We are able to insert and read via MySQL Workbench.

**Comment by bgrainger** [comment]
Set `GuidFormat=None` in your connection string.

https://mysqlconnector.net/connection-options/#GuidFormat
