### ISSUE TITLE
Better exception if `DELIMITER` is used

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#1010]
If a client tries to use `DELIMITER` in their SQL script, it'll fail:

* https://github.com/mysql-net/MySqlConnector/issues/645
* https://github.com/mysql-net/MySqlConnector/issues/692
* https://github.com/mysql-net/MySqlConnector/issues/1009
* https://github.com/mysql-net/MySqlConnector/issues/1017

MySqlConnector could detect this scenario (in the exception handler after it fails? or when parsing the SQL upfront?) and throw a more informative exception with a link to a documentation page explaining what to do instead.

**Comment by SIBA-FEMD** [comment]
Hi Bradley 

These comment that you linked me helped but it did not solve the case .

I can now see the MYSQL procedure script turning up in the MYSQL log file.

So it is sort of working but not really 

Does not like the following MYSQL SQL text script items though 

1.		MYSQL script    -- text comments

2.		MYSQL procedure script   DELIMITER //   //DELIMITER ;

3.		MYSQL procedure script variables which start with @

With these 3 items block it , and so it is very hard to load up big and complicated MSYQL procedures .  

I have some MYSQL procedures which 30K size in text and 400 lines of SQL code script , in effect mini sql programs .

These programs run fine in MYSQL workbench but I need to be able to load them from the vb.net program.

So now my working SQL procedure scripts get trashed by the mysqlconnector when it tries hand over the mysql procedure script file 

How do I do this to get the write type of connection into the MYSQL DB ?

Best wishes 

SIBA





Dump of the VB.net code run . the function which loads the mysql script to the mysql db
========================================================================================

    Public Function load_sql_procedure_to_db(sql_text As String) As Boolean
        ' select version();

        ''   ref   https://stackoverflow.com/questions/2593458/executable-directory-where-application-is-running-from
        ''  ref https://github.com/mysql-net/MySqlConnector/issues/645#issuecomment-495767223


        Dim test_result As Boolean = False

        Try
            ' ---------------------------------------------------------------------------------------------------
            '   
            '    not  working
            '
            '----------------------------------------------------------------------------------------------------
            '
            '   Function to load bulk sql script to the db 
            '

            Dim db_connection As MySqlConnection = New MySqlConnection(sql_connection)

            Using db_connection
                db_connection.Open()

                Dim db_table_select As String = sql_text     ' check if the db talks back with erors 

                Debug.WriteLine(vbCrLf + vbCrLf + sql_text + vbCrLf + vbCrLf)

                Dim db_command As MySqlCommand = New MySqlCommand(sql_text, db_connection)
                Dim reader As Integer
                reader = db_command.ExecuteNonQuery

                Debug.WriteLine(vbCrLf + vbCrLf + "ExecuteNonQuery reader result" + CStr(reader) + vbCrLf + vbCrLf)


                db_connection.Close()
            End Using

            test_result = True

        Catch ex As Exception
            test_result = False

            Debug.WriteLine(vbCrLf + vbCrLf + "ExecuteNonQuery reader result error " + CStr(ex.Message) + vbCrLf + vbCrLf)


        End Try


        Return test_result
    End Function
