### ISSUE TITLE
MySQL procedure script is not working

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#1014]
These comment that you linked me helped but it did not solve the case .

I can now see the MYSQL procedure script turning up in the MYSQL log file.

So it is sort of working but not really 

Does not like the following MYSQL SQL text script items though 

1.		MYSQL script    -- text comments

2.		MYSQL procedure script   DELIMITER //   //DELIMITER ;

3.		MYSQL procedure script variables which start with @

With these 3 items block it , and so it is very hard to load up big and complicated MSYQL procedures .  

I have some MYSQL procedures which 30K size in text and 400 lines of SQL code script , in effect mini sql programs .

These programs run fine in MYSQL workbench but I need to be able to load them from the vb.net program.

So now my working SQL procedure scripts get trashed by the mysqlconnector when it tries hand over the mysql procedure script file 

How do I do this to get the write type of connection into the MYSQL DB ?

Best wishes 

SIBA

Dump of the VB.net code run . the function which loads the mysql script to the mysql db
========================================================================================

    Public Function load_sql_procedure_to_db(sql_text As String) As Boolean
        ' select version();

        ''   ref   https://stackoverflow.com/questions/2593458/executable-directory-where-application-is-running-from
        ''  ref https://github.com/mysql-net/MySqlConnector/issues/645#issuecomment-495767223

        Dim test_result As Boolean = False

        Try
            ' ---------------------------------------------------------------------------------------------------
            '   
            '    not  working
            '
            '----------------------------------------------------------------------------------------------------
            '
            '   Function to load bulk sql script to the db 
            '

            Dim db_connection As MySqlConnection = New MySqlConnection(sql_connection)

            Using db_connection
                db_connection.Open()

                Dim db_table_select As String = sql_text     ' check if the db talks back with erors 

                Debug.WriteLine(vbCrLf + vbCrLf + sql_text + vbCrLf + vbCrLf)

                Dim db_command As MySqlCommand = New MySqlCommand(sql_text, db_connection)
                Dim reader As Integer
                reader = db_command.ExecuteNonQuery

                Debug.WriteLine(vbCrLf + vbCrLf + "ExecuteNonQuery reader result" + CStr(reader) + vbCrLf + vbCrLf)

                db_connection.Close()
            End Using

            test_result = True

        Catch ex As Exception
            test_result = False

            Debug.WriteLine(vbCrLf + vbCrLf + "ExecuteNonQuery reader result error " + CStr(ex.Message) + vbCrLf + vbCrLf)

        End Try

        Return test_result
    End Function

_Originally posted by @SIBA-FEMD in https://github.com/mysql-net/MySqlConnector/issues/1010#issuecomment-874711979_

**Comment by bgrainger** [comment]
@SIBA-FEMD Please provide a minimal repro that demonstrates the problem.

As you can see from the integration test code, multi-statement SQL commands are supported: https://github.com/mysql-net/MySqlConnector/blob/68b99fe49fa780f538059b80fcdb8d1c67802c5e/tests/SideBySide/StoredProcedureFixture.cs#L10-L134

**Comment by SIBA-FEMD** [comment]
Hi 

I reviewed the name space for "mysqlconnector"  and the the execute command is not in the namespace .

The **execute** command is in the "Dapper" . I downloaded the whole project from Github to investigate
See below
![image](https://user-images.githubusercontent.com/84386395/127825967-a4767050-7ee7-46f7-adf0-9bf94c57674c.png)

I would suggest you directly add the **execute** command ability to the "mysqlconnector" namespace so that users can have direct control directly through to the underlying mysql db.  

This is a very very useful programing feature to be able to have direct control over the underlying db.

**Comment by SIBA-FEMD** [comment]
This seems be the reason why I can not execute SQL code directly in VB.net when using the statement 

Imports mysqlconnector

**Comment by bgrainger** [comment]
> I would suggest you directly add the execute command ability to the "mysqlconnector" namespace so that users can have direct control directly through to the underlying mysql db.

I want to let Dapper continue to provide this functionality. MySqlConnector implements the core ADO.NET functionality; Dapper or Pomelo or RepoDb etc. all provide different wrappers over it.

Closing this out as there doesn't seem to be a specific problem being reported in this issue. As already noted, `DELIMITER` is not supported and must not be used: https://mysqlconnector.net/troubleshooting/delimiter/
