### ISSUE TITLE
DataReader creates DataTable with SERIAL-column as Int32

### ISSUE THREAD

**Issue by Lemmes** [mysql-net/MySqlConnector#1015]
I have a table like this:
```sql
CREATE TABLE test
(id SERIAL, bigintucolumn BIGINT UNSIGNED);

INSERT INTO test (bigintucolumn) VALUES (4711);
```
Now I'm creating a DataTable from a DataReader:
```csharp
var connectionString = "Server=192.168.0815.4711; Port=3307; User ID=mySecretId; Password=mySecretPassword; Database=mySecretDatabase;";

using (var connection = new MySqlConnector.MySqlConnection(connectionString))
{
    connection.Open();
    using (var command = connection.CreateCommand())
    {
        var dataTable = new DataTable();

        command.CommandText = @"
SELECT 
  *
FROM
  test";
        using (var reader = command.ExecuteReader())
        {
            dataTable.BeginLoadData();
            dataTable.Load(reader);
            dataTable.EndLoadData();
        }

        foreach (DataColumn column in dataTable.Columns)
            Console.WriteLine($"{column.ColumnName} is of type {column.DataType}");
    }
}
```
Which yields:
```
id is of type System.Int32
bigintucolumn is of type System.UInt64
```
Shouldn't ```id``` be ```System.UInt64``` as well?

**Comment by bgrainger** [comment]
`reader.GetColumnSchema()` and `reader.GetSchemaTable()` both show `id` as a `BIGINT` and of type `UInt64`.

I get the same results (an `Int32` column) if I explicitly declare `id` as `BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT`. However, if I drop `UNSIGNED` and create it as `id BIGINT PRIMARY KEY AUTO_INCREMENT` then the `DataTable` has an `Int64` column. Or if I create it as `id BIGINT UNSIGNED PRIMARY KEY DEFAULT 0` then the `DataTable` has a `UInt64` column.

I'm suspecting this is a `DataTable` problem (where `Int32` is inferred for an `IsAutoIncrement` column, but one might have to test with other DB providers to confirm this.

**Comment by bgrainger** [comment]
> Using MySql.Data produces a UInt64 column, as expected.

MySql.Data returns `AllowDBNull = true`, `IsAutoIncrement = false` in the schema table; both of those values are incorrect. 

It still seems possible that the correct values MySqlConnector returns are triggering a different automatic schema generation in the `DataTable`.

**Comment by bgrainger** [comment]
My guess about `IsAutoIncrement` appears to be correct: `DataColumn` will coerce the type to `Int32` if that's true: https://github.com/dotnet/runtime/blob/d91e11a2bc2f21f3f9df6e16603aa097bea1bd16/src/libraries/System.Data.Common/src/System/Data/DataColumn.cs#L241-L249

MySqlConnector is returning the correct values in `GetColumnTable`; the schema should reflect what's actually in the MySQL database. (And thus MySql.Data has a bug.) This is a bug that could be reported against `DataTable`/`DataColumn` (but I would guess it's unlikely to be fixed, due to backwards compatibility constraints).

**Comment by Lemmes** [comment]
> My guess about `IsAutoIncrement` appears to be correct: `DataColumn` will coerce the type to `Int32` if that's true: https://github.com/dotnet/runtime/blob/d91e11a2bc2f21f3f9df6e16603aa097bea1bd16/src/libraries/System.Data.Common/src/System/Data/DataColumn.cs#L241-L249
> 
> MySqlConnector is returning the correct values in `GetColumnTable`; the schema should reflect what's actually in the MySQL database. (And thus MySql.Data has a bug.) This is a bug that could be reported against `DataTable`/`DataColumn` (but I would guess it's unlikely to be fixed, due to backwards compatibility constraints).

Oh, I see. I *thought* (but didn't check it) DataTable was generic too (which obviously is bogus as there is no such thing as a MySqlDataTable or OracleDataTable). Thanks for taking the time looking into it.
