### ISSUE TITLE
"delimiter" is not supported

### ISSUE THREAD

**Issue by cnhongv** [mysql-net/MySqlConnector#1017]
**When I execute these SQL commands:**

DELIMITER $$
CREATE TRIGGER `trigger_AddNickName` BEFORE INSERT ON `fundchange` FOR EACH ROW
BEGIN
IF new.NickName is null THEN
set new.NickName = (select `NickName` from `member` where `Account` = new.Account);
END IF;
END;$$

**an error occurs:**

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIMITER $$
CREATE TRIGGER `trigger_AddNickName` BEFORE INSERT ON `fundchange...' at line 1

**After that, I continued to try and found that when I deleted "delimiter", it could be executed correctly.**

**These commands have no errors and can be executed correctly in phpMyadmin, so I think there is a bug**

**Comment by bgrainger** [comment]
`DELIMITER` is unnecessary and is not supported: https://github.com/mysql-net/MySqlConnector/issues/1010

**Comment by bgrainger** [comment]
Duplicate of #1010
