### ISSUE TITLE
MySqlConnectionStringBuilder does not implement ICustomTypeDescriptor correctly

### ISSUE THREAD

**Issue by masonwheeler** [mysql-net/MySqlConnector#1030]
`DbConnectionStringBuilder`, the base class for connection string builders, implements `ICustomTypeDescriptor` so that the class can interface properly with UI inspector components such as the WinForms [PropertyGrid](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.propertygrid?view=net-5.0) or the various property grid implementations available on WPF.

When attempting to inspect a `MySqlConnectionStringBuilder` to one of these, it does not display the values properly; everything displays as a `null` value regardless of whether or not the property actually has a value.

**Comment by bgrainger** [comment]
The background to this request is in this SO question and the extended discussion in the comments: https://stackoverflow.com/questions/69080255/why-do-dbconnectionstringbuilder-descendants-break-property-grid-binding-so-thor

**Comment by bgrainger** [comment]
@masonwheeler From related issues you've posted and SO questions, it sounds like you might have already built a test harness that demonstrates the problem (with various property grids); do you have sample code that reproduces this problem available?

**Comment by bgrainger** [comment]
Is the fundamental issue here that `connectionStringBuilder.TryGetValue("PropName", out var value)` always returns `false` for MySqlConnector?

**Comment by bgrainger** [comment]
Still not sure what the bug here is. This code works fine with MySqlConnector:

```csharp
var csb = new MySqlConnectionStringBuilder();
csb.MinimumPoolSize = 5;

ICustomTypeDescriptor td = csb;
td.GetProperties().Cast<PropertyDescriptor>().Count(x => x.DisplayName == "Minimum Pool Size"); // 1
csb.ContainsKey("Minimum Pool Size"); // true
csb.TryGetValue("Minimum Pool Size", out var value); // true, 5
```

Interestingly, in Connector/NET that code returns `1`, `true`, `false / null`, which seems like a bug.

**Comment by bgrainger** [comment]
OK, I'm seeing a problem. `((ICustomTypeDescriptor) csb).GetProperties()` returns a property named `MinimumPoolSize`. However once the `MinimumPoolSize` C# property is set, it also returns `Minimum Pool Size` in that collection. Retrieving the property using the name with spaces works, but using the name without spaces doesn't work.

Oracle's Connector/NET always fails for `TryGetValue` but can return the value via `csb["Prop Name"]` (which also works in MySqlConnector). The bug appears to be that property names are incorrect when returned from `ICustomTypeDescriptor`.

**Comment by masonwheeler** [comment]
@bgrainger  [Here's a very simple repro case.](https://github.com/mysql-net/MySqlConnector/files/7139520/MySql.Repro.zip)

**Comment by masonwheeler** [comment]
Very nice work, especially adding the categories.  That makes it much more readable in the editor.

Can you ping me on here when a new version is up on NuGet?

**Comment by bgrainger** [comment]
Yep; I'll need your feedback on whether this has resolved the issue, or if additional work is needed.

**Comment by bgrainger** [comment]
@masonwheeler Please try 1.4.0-beta.3 and let me know if this is fixed! https://www.nuget.org/packages/MySqlConnector/1.4.0-beta.3

**Comment by masonwheeler** [comment]
Yes, this appears to be fixed.  Thanks for getting this taken care of so quickly!
