### ISSUE TITLE
Support all MySql.Data Connection String options

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#105]
From [Connection String Options Reference](https://dev.mysql.com/doc/connector-net/en/connector-net-8-0-connection-options.html):

Option | Status | Issue | Comments
--- | --- | --- | ---
`AllowBatch` | ❌ | | it's `true` by default, and there doesn't seem to be much point in supporting `false`
`AllowLoadLocalInfile` | ✔️ | #643 | New in 8.0.16
`AllowUserVariables` | ✔️ | |
`AllowZeroDateTime` | ✔️ | #507 |
`AutoEnlist` | ✔️ | #13 |
`CacheServerProperties` | ❌ | | optimisation for Connector/NET because it always retrieves `@@max_allowed_packet, @@character_set_client` etc. when connecting
`CertificateFile` | ✔️ | #88 | 
`CertificatePassword` | ✔️ | #88 |
`CertificateStoreLocation` | ✔️ | #536 |
`CertificateThumbprint` | ✔️ | #536 |
`CharacterSet` | ❌ | | hard-coded to `utf8mb4` in this connector; unclear if being able to use a different encoding on the wire has clear benefits
`CheckParameters` | ❌ | | `true` by default; `check parameters=false` seems to be recommended only as a work around for Connector/NET bugs or MySQL permission problems
`CommandInterceptors` | ❌ | #420 |
`ConnectionLifeTime` | ✔️ | #212 |
`ConnectionReset` | ✔️ | |
`ConnectionTimeout` | ✔️ | #57 |
`Connect_Attrs` | ❌ | | Documented, but [not supported](https://bugs.mysql.com/bug.php?id=75322) by Connector/NET |  
`ConvertZeroDateTime` | ✔️ | | 
`Database` | ✔️ | | aka `InitialCatalog`
`DefaultCommandTimeout` | ✔️ | #67 |
`DefaultTableCacheAge` | ❌ | | see remarks on `TableCache` |
`DnsSrv` | ❌ | #761 | see remarks on #761
`EnableSessionExpireCallback` | ❌ | | default is `false`; manipulates `my_aspnet_sessions` table |
`Encrypt` | ❌ | | this setting is deprecated
`ExceptionInterceptors` | ❌ | #420 |
`FunctionsReturnString` | ❌ | | default is `false`; unaware of any clients that need this |
`Host` | ✔️ | |
`IgnorePrepare` | ✔️ | #534 |
`includesecurityasserts` | ❌ | | for partial trust environments
`InteractiveSession` | ✔️ | #510 |
`IntegratedSecurity` | ❌ | | Windows-only |
`Keepalive` | ✔️ | #145 |
`Logging` | ❌ | | Implemented custom logging framework |
`MinimumPoolSize` | ✔️ | #85 |
`OldGuids` | ✔️ | #26 | 
`OldSyntax` | ❌ | | this setting is deprecated
`Password` | ✔️ | |
`PersistSecurityInfo` | ✔️ | |
`PipeName` | ✔️ | #454 | Windows-only |
`Pooling` | ✔️ | #2 | also `MaximumPoolsize`
`Port` | ✔️ | |
`ProcedureCacheSize` | ❌ | | Cached procedures are very small objects; enforcing a limit of 25 seems unnecessary |
`ConnectionProtocol` | ❌ | | Only `socket` and `unix` are supported (and auto-detected) |
`Replication` | ❌ | | not well documented; this just seems to ensure (client-side) that only read-only commands are executed
`RespectBinaryFlags` | ❌ | | `true` by default |
`SharedMemoryName` | ❌ | | Windows-only |
`SshHostName`, `SshPort`, `SshUserName`, `SshPassword`, `SshKeyFile`, `SshPassPhrase` | | #671 | New in 8.0.17
`SslCa` | ✔️ | #640 | New in 8.0.16
`SslCert` | ✔️ | #641 | New in 8.0.16
`SslKey` | ✔️ | #641 | New in 8.0.16
`SslMode` | ✔️ | #88 | 
`Sql Server Mode` | ❌ | | Enables square brackets instead of backticks; seems unnecessary |
`TableCache` | ❌ | | Only supported by Connector/NET for `CommandType.TableDirect`; seems low-value; caching is better handled at the application layer |
`tlsversion` | ✔️ | #760 | New in 8.0.19
`TreatBlobsAsUTF8` | ❌ | | only necessary for connecting to pre-5.5.3 servers that don't support `utf8mb4`; also includes `BlobAsUTF8ExcludePattern`, `BlobAsUTF8IncludePattern`
`TreatTinyAsBoolean` | ✔️ | #141 |
`UseAffectedRows` | ✔️ | #104 |
`UseProcedureBodies` | ❌ | | this setting is deprecated |
`UserID` | ✔️ | | aka `User name`
`UseCompression` | ✔️ | #31 |
`UseUsageAdvisor` | ❌ | | Recommend using third-party DB profiling tools |
`UsePerformanceMonitor` | ❌ | | Windows-only |

**Comment by caleblloyd** [comment]
AFAIK, `ConvertZeroDateTime` and `ConnectionReset` are also done

**Comment by mguinness** [comment]
What is the possibility for getting "Treat Tiny As Boolean" support?

`System.InvalidOperationException: Option 'treattinyasboolean' not supported.`

Is the current handling set to true? I'm having an issue with Pomelo.EntityFrameworkCore.MySql when tinyint(1) is used.

`System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.SByte'.`

I tried unsuccessfully to see what code would need changing, but I did find what the [official connector does](https://github.com/mysql/mysql-connector-net/blob/5864e6b21a8b32f5154b53d1610278abb3cb1cee/Source/MySql.Data/Field.cs#L311-L327).

**Comment by bgrainger** [comment]
The current default for `TreatTinyAsBoolean` is `true` in this library (same as Connector/Net); it can't currently be configured. Opened #141 for adding it.

**Comment by bgrainger** [comment]
(FWIW, converting `TINYINT(1)` to `bool` only happens when the column length is explicitly `1`. A `TINYINT` or `TINYINT(2)` column shouldn't be converted in this way.)

**Comment by mguinness** [comment]
@bgrainger Thanks, that's the workaround I'm currently using.  Also `TINYINT` will end up as `TINYINT(3)` (to avoid any confusion).

**Comment by jemiller0** [comment]
I have a question about IgnorePrepare. It states above that the default it true. I have found this to be false with MySQL 5.7. According to the MySQL documentation at https://dev.mysql.com/doc/connector-net/en/connector-net-programming-prepared.html, IgnorePrepare enables "server side" prepared statements and uses a binary protocol for communicating with the server. I had been seeing very poor bulk insert performance and couldn't figure out why. Then, I found that setting. I tested with Oracle's driver and watched the server logs with general_log enabled. I could see that it was preparing the statements on the server site with that setting set to false. I did the same test with this driver. It's not using server side prepared statements.

**Comment by AccessViolator** [comment]
The link in the first post is dead, this is the current one
https://dev.mysql.com/doc/connector-net/en/connector-net-8-0-connection-options.html

**Comment by bkonia** [comment]
Are you planning to support the TableCaching option? I'm surprised this isn't supported, particularly since this library emphasizes performance. In many scenarios, table caching could make reading hundreds of times faster.

**Comment by mguinness** [comment]
Have you previously used the [Table Caching](https://dev.mysql.com/doc/connector-net/en/connector-net-programming-tablecaching.html) option with Connector/NET?  The documentation seems very sparse and the only scenario I'd see it being compatible with is when `CommandType.TableDirect` is used.

**Comment by bkonia** [comment]
I have not used it yet, but was intending to use it for a project in which each API request triggers a database read, yet the data changes slowly, so most reads are redundant. This is an extremely common scenario; for example any website that loads a user's account data with each page load.

I'm not sure what you mean about it only being compatible with CommandType.TableDirect. It should work fine with any MySqlDataReader object for normal SQL queries.  I reviewed the source at [mysql-connector-net](https://github.com/pdonald/mysql-connector-net/blob/master/Source/MySql.Data/datareader.cs) and it seems to do exactly what you'd expect in terms of caching queries and result sets. See lines 851 - 854. You can also review the [TableClass](https://github.com/pdonald/mysql-connector-net/blob/master/Source/MySql.Data/TableCache.cs), which uses a simple dictionary to manage the cache, with the CommandText as the keys.

**Comment by jemiller0** [comment]
The data may not be changed frequently, but, it does change. In my apps, I would rather have accurate data. So, I would be inclined to stay away from something like that. Particularly, for something like user or role information. I guess it depends on what the cache timeout is.

**Comment by mguinness** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.
&nbsp;
-- Phil Karlton

**Comment by bgrainger** [comment]
@mguinness Thanks for the analysis; I had not researched the `TableCache` option until now. 

@bkonia Caching seems like an application-level concern that should be handled at a higher level, not a feature of an ADO.NET library. (I'm not aware of an analogous option in any other ADO.NET library.) Also, since this is effectively a no-op for almost all Connector/NET queries (I suspect very few clients actually use `CommandType.TableDirect`) I do not plan to implement this connection string option. I've updated the table above accordingly.

**Comment by AccessViolator** [comment]
This is typically referred to as 2nd level cache. Some ORMs, e.g. NHibernate, implement it, EF6/Core don't, though there are extension packages.

Somewhat off topic: I personally prefer to steer clear and do things like user profile caching on application level. Some modern web API apps using JWT auth may not need it at all - depends on whether you need any sensitive user data on your every API request or not. If you do, cache in the app, if you don't just add to your JWT. That's actually one of the main "selling points" of JWTs compared to traditional session IDs - to be able to avoid hitting the DB on every request.

**Comment by bgrainger** [comment]
Every option is either implemented, deliberately not implemented, or (just one: SSH settings) isn't implemented yet but has a documented workaround.

**Comment by langfordcd** [comment]
Any plans for supporting `DefaultAuthenticationPlugin`?

**Comment by bgrainger** [comment]
> Any plans for supporting `DefaultAuthenticationPlugin`?

What's the use case where you'd want to use it?

**Comment by langfordcd** [comment]
As I understand, it's required for password-less Kerberos authentication.

**Comment by bgrainger** [comment]
Right, but MySqlConnector doesn't support `authentication_kerberos_client` so what would be the point?
