### ISSUE TITLE
Add Connecting event handler/callback

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#1056]
There are a number of instances where users would like to provide information that can't be stored in a regular connection string:

* https://github.com/mysql-net/MySqlConnector/issues/800 - a dynamic/changing password
* https://github.com/mysql-net/MySqlConnector/issues/976 - a client certificate as an `X509Certificate2` object, not a file path

This could be accommodated via a new event handler:

```csharp
public sealed class MySqlConnection
{
	public static event EventHandler<MySqlConnectingEventArgs>? Connecting;
}

public sealed class MySqlConnectingEventArgs : EventArgs
{
	public string ConnectionString { get; }
	public string? Password { get; set; }
	public X509Certificate2? ClientCertificate { get; set; }
	public X509Chain? CACertificateChain { get; set; }
}
```

The `Connecting` event would be raised whenever a new connection is being made to a backend server. (This is not necessarily 1-1 with `MySqlConnection.Open()`, because `Open` may just retrieve a pooled connection and not establish a new connection to the MySQL Server.) The `MySqlConnectingEventArgs.ConnectionString` would be populated with the connection string supplied to the `MySqlConnection.ConnectionString` property. (TODO: would it be the exact same `string` object, or perhaps a normalized string?)

Event handlers can populate the `Password`, `ClientCertificate`, or `CACertificateChain` properties. If the event handler chain sets a property to a non-`null` value, it will be used to make the connection to the MySQL Server, and the respective connection string option (`Password`; `Certificate File`, `SSL Cert`, `SSL Key`; `CA Certificate File`) would be ignored.

The event will be `static` so that it's easy to insert the callback in scenarios where your code doesn't create the `MySqlConnection` objects directly (e.g., EF Core). Additionally, it's more efficient to attach just one event handler and dispatch based on connection string, rather than attaching an event handler to every single `MySqlConnection` instance. (And in most applications, there's just one connection string, so logic to check the connection string may not even be necessary.)

It's an event so that multiple event handlers can be attached in complex scenarios. Each event handler will be able to inspect and modify the results of the previous one.

This could provide a mechanism for malicious code to intercept all passwords (by attaching the event handler and inspecting all connection strings), but malicious code can already acquire all passwords by reflecting over `ConnectionPool` so this doesn't create any new vulnerabilities. (If malicious code is already running in your process, there are bigger problems anyway.)

**Comment by ejball** [comment]
My concern with a static event is that it is too easy for multiple MySQL clients in the same app to interfere with each other. Named "sources" would make dynamic passwords and certificate files explicitly opt-in on a per-connection-string basis. It might also simplify development vs. production connection strings. Perhaps:

```csharp
public sealed class MySqlConnection
{
	public static void AddPasswordSource(string name, Func<string> getPassword);
}
```

and a corresponding `PasswordSource` connection string property that would be set to the source name. Similarly for `Certificate Source` and `CA Certificate Source`.

**Comment by fberasategui** [comment]
@bgrainger instead of adding three new properties (and then having to add more when required) I suggest using a design similar to the `.Configure()` methods you normally find in ASP.NET's `Startup` class, like this:

```csharp
public sealed class MySqlConnection
{
	public static void Configure(string configurationName, Func<MySqlConnectionOptions> getConnectionOptions);
}
```

you would then add only a single `ConfigurationSource` property in the connection string:

```csharp
var b = new MySqlConnectionStringBuilder
{
    ConfigurationSource = "xxxxx"
};
```

and the `Configure` method may set (or in fact override) any of the connection string properties:

```csharp
public sealed class MySqlConnectionOptions
{
	public string? Password { get; set; }
	public X509Certificate2? ClientCertificate { get; set; }
	public X509Chain? CACertificateChain { get; set; }
        // More Properties here as required
}
```

**Comment by bgrainger** [comment]
I like collapsing it down to just one API. I don't think it's necessary to try to emulate the ASP.NET Core API exactly; we're not using the full Options/Configure pattern. (And the Options class has non-serializable types that can't be provided by JSON or environment settings; that's the whole purpose of this new API.)

```csharp
public sealed class MySqlConnection
{
	// allow configuration to be supplied asynchronously
	public static void AddConnectionOptions(string name, Func<ValueTask<MySqlConnectionOptions>> getConnectionOptions);

	// helper function for above for less complex scenarios
	public static void AddConnectionOptions(string name, Func<MySqlConnectionOptions> getConnectionOptions);
}

public sealed class MySqlConnectionStringBuilder
{
 	public string? ConnectionOptionsName { get; set; }
}

public sealed class MySqlConnectionOptions
{
	public string? Password { get; set; }
	public X509Certificate2? ClientCertificate { get; set; }
	public X509Chain? CACertificateChain { get; set; }
}
```

`AddConnectionOptions` adds a new named connection options provider, and throws if that provider has already been added. The provider can run asynchronously; it can pool and return `MySqlConnectionOptions` instances if allocations are important.

**Comment by michaeljon** [comment]
I'm not a fan, well right now, of the static and up-front configuration. One of our services dynamically discovers its database servers during runtime and can't be restarted to take on a new configuration. The way we handle this on our postgres side is to wire up a handler to `UserCertificateValidationCallback`. We do some caching based on the requested connection's details (if it's SSL-enabled, where to find the PEM online) and use that to do our own cert validation based on an expected certificate thumbprint. This might work better with Npgsql because it has access to the underlying SSL stream and can hand its events out to the user. I haven't had a chance to look the your code to see if there are places to hook it in.

**Comment by bgrainger** [comment]
> the static and up-front configuration

It's not static.

You do have to call `MySqlConnection.AddConnectionOptions("my unique name", () => new MySqlConnectionOptions { ... })` "up front" before you use those named connection options, but it fully supports dynamic, runtime configuration. The following example shows how you can dynamically create a new connection string with a new callback at runtime:

```csharp
string GetDynamicConnnectionString()
{
    var csb = new MySqlConnectionStringBuilder
    {
        Server = "dynamically discovered",
        UserID = "dynamic",
        ConnectionOptionsName = Guid.NewGuid().ToString(),
    };
    MySqlConnection.AddConfigurationOptions(csb.ConnectionOptionsName, () => new MySqlConnectionOptions { Password = "totally dynamic" });
    return csb.ConnectionString;
}
```

**Comment by bgrainger** [comment]
Very much in favour of the `DbDataSource` idea, particularly if core concerns (e.g., high performance, lock-free pooling; connection management; etc.) can be implemented in shared code.

I agree that it would be a natural place to configure these kind of callbacks, so I can see adding callbacks to `MySqlConnection` right now to be a step towards that direction. (If nothing else, `MySqlDataSource` can copy the callbacks to new `MySqlConnection` objects when it creates them, or perhaps it can do something more efficient behind the scenes.)

**Comment by bgrainger** [comment]
Per https://github.com/mysql-net/MySqlConnector/issues/976#issuecomment-840297732, per-MySqlConnection properties/callbacks are useful for the scenario of connecting to dozens of different servers (e.g., a tool/utility, not a web application).

I'm going to close this approach in favour of the original linked issues.

**Comment by scastria** [comment]
Why isn't the ProvidePasswordCallback Async?  Generating an IAM DB Auth token requires I/O which should be awaited.

**Comment by bgrainger** [comment]
Use `MySqlDataSourceBuilder.UsePeriodicPasswordProvider` (https://mysqlconnector.net/api/mysqlconnector/mysqldatasourcebuilder/useperiodicpasswordprovider/) to specify an async password provider.
