### ISSUE TITLE
MySqlConnector Performance Issue: MySqlCommandBuilder.DeriveParameters too slow when execute on the instance with a large of routines(more than 70.000 routines)

### ISSUE THREAD

**Issue by mkbyme** [mysql-net/MySqlConnector#1063]
Hi, I'm using this library to connect the database by model ADO.NET.
My system runs on.NETCore 3.1.

Our system support multi-tenants, so **each tenant is a separate database**. **A database** contains **more than 300 routines**.
We load balancing our database, **A MySQL Server instance** has around **800-1000 databases**( schemas).

Current our product MySql Server instance has more than 800 databases
The **total routines** is about 800 x 300 = **240.000 (routines).**

When we trace query execute by **MySqlCommandBuilder.DeriveParameters**, it took **more than 0.3 seconds per time**.
The query executes **using 'LIKE' instead of '='(equal)** to check that routines exist on information_schema.routines.

As we measure on our system has more than 240.000 routines:
[Routines Count](https://prnt.sc/1woad4g)
<img width="453" alt="total_routines_query" src="https://user-images.githubusercontent.com/8275893/137832671-2c1966ea-dc00-4332-b607-f6d2e7639e8f.png">
+ LIKE performance costs more than 30 times
    - LIKE costs average **0.3 seconds** per time [view image of LIKE query costs](https://prnt.sc/1woahls)
    - <img width="657" alt="like_query_performance" src="https://user-images.githubusercontent.com/8275893/137833030-a48b3e76-a456-49a3-a1e1-54b2643a2cd0.png">
    - Equal costs average **0.01 seconds** per time [view image of Equal query costs](https://prnt.sc/1woak2l)
    - <img width="654" alt="equal_query_performance" src="https://user-images.githubusercontent.com/8275893/137833058-cae590c5-9d01-4528-af78-8fa2e71a00e2.png">
  
Can you change the query which checks exist(We think that) routines from LIKE into Equals, it will have better performance on MySQL Server has huge of routines.

Thank you!
Best Regard!

**Comment by bgrainger** [comment]
Are you using MySql.Data? Based on the code, it appears that you might be: https://github.com/mysql/mysql-connector-net/blob/dd1d93a13e42766bff57fd3d3f1e5834cb533036/MySQL.Data/src/ISSchemaProvider.cs#L407

This is the repo for MySqlConnector. The bug reporting site for MySql.Data is https://bugs.mysql.com and you can report the problem there.

Alternatively, and what I would recommend, switch to [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/) instead. It doesn't have the issue you reported, and fixes [lots of other bugs](https://mysqlconnector.net/tutorials/migrating-from-connector-net/#fixed-bugs) too.

https://github.com/mysql-net/MySqlConnector/blob/bb2a03b297aa0b8e2bf7b5ada0331a2b11e91d2c/src/MySqlConnector/Core/CachedProcedure.cs#L65-L67
