### ISSUE TITLE
Implement MySqlDecimal

### ISSUE THREAD

**Issue by sumitdvlp** [mysql-net/MySqlConnector#1070]
Hi,

The GetDecimal() or GetValue() functions of MySqlDataReader [class](https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlDataReader.cs) are unable to handle very large value like
'1234567890123456789012345678901234567890123456789012345678901234.5'
They throw exception like value is too large because it return C# decimal datatype.

We saw MySQL connecter net has this functionality [here](https://github.com/mysql/mysql-connector-net/blob/8.0/MySQL.Data/src/datareader.cs). which return MySqlDecimal data type.

Can you please add method like GetMySqlDecimal which can support very large Decimal values.

**Comment by sumitdvlp** [comment]
Created a PR https://github.com/mysql-net/MySqlConnector/pull/1075

**Comment by bgrainger** [comment]
Added in [2.1.0](https://github.com/mysql-net/MySqlConnector/releases/tag/2.1.0); thanks for the PR!
