### ISSUE TITLE
Connect Timeout expired. All pooled connections are in use

### ISSUE THREAD

**Issue by eduschell** [mysql-net/MySqlConnector#1071]
I’m using hangfire with mysql and I get the following error message.
Connect Timeout expired. All pooled connections are in use.

it looks like it's a problem with mysql connector.

![27fcfc812b089d47f59e905f394e7aa8b575f231_2_690x210](https://user-images.githubusercontent.com/21362968/139475362-f8e32a18-5cea-4e7d-98f4-b30ee746f096.png)

**Comment by bgrainger** [comment]
What software versions are you using?

* MySqlConnector
* Hangfire.MySqlStorage
* .NET
* MySQL Server, MariaDB, Aurora, etc.

Please provide a code sample that reproduces the problem.

**Comment by bgrainger** [comment]
This line of code (in Hangfire) looks like it could _potentially_ be a connection leak: https://github.com/arnoldasgudas/Hangfire.MySqlStorage/blob/0bd1016f715c8c6617ce22fb7b2ce5b6c328d2fb/Hangfire.MySql/JobQueue/MySqlJobQueue.cs#L38

**Comment by bgrainger** [comment]
Closing issue filed on an old version of the library without a consistent repro.
