### ISSUE TITLE
Issue while connecting Proxy SQL server with Amazon Aurora MySQL server

### ISSUE THREAD

**Issue by Janakiraman-Jeyakumar** [mysql-net/MySqlConnector#1078]
While connecting ProxySQL server with AWS Amazon aurora MySQL server using the MySqlConnector, we are facing the below issue.

MySQL Version: 5.7
ProxySQL Version:  2.2.2-11
MySQLConnector Version: 0.64.0

> **Unable to retrieve schema. Reason: Couldn't connect to server.**

> **at MySqlConnector.Core.ServerVersion..ctor(System.ReadOnlySpan`1 versionString) in /_/src/MySqlConnector/Core/ServerVersion.cs:line 10:col 3 at MySqlConnector.Core.ServerSession.<ConnectAsync>d__68.MoveNext() at offset 1196 in /_/src/MySqlConnector/Core/ServerSession.cs:line 374:col 6 at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__110.MoveNext() at offset 889 in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs:line 681:col 3 at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__26.MoveNext() at offset 471 in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs:line 339:col 3 at MySql.Data.MySqlClient.MySqlConnection.Open() at offset 30 in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs:line 285:col 34 at System.Data.Common.DbDataAdapter.FillInternal(System.Data.DataSet dataset, System.Data.DataTable[] datatables, System.Int32 startRecord, System.Int32 maxRecords, System.String srcTable, System.Data.IDbCommand command, System.Data.CommandBehavior behavior) at offset 149 at System.Data.Common.DbDataAdapter.Fill(System.Data.DataSet dataSet, System.Int32 startRecord, System.Int32 maxRecords, System.String srcTable, System.Data.IDbCommand command, System.Data.CommandBehavior behavior) at offset 105 at System.Data.Common.DbDataAdapter.Fill(System.Data.DataSet dataSet) at offset 41 at**

whenever trying to connect to the server, We are getting this issue multiple times.

We suspect the there is a problem in MySQLConnector, Because same server working fine in Mysql.data connector. 

Please share any idea to connect MySqlConnector with proxySQL connection.

**Comment by bgrainger** [comment]
> MySQLConnector Version: 0.64.0

This version is pretty old; there have been a lot of bug fixes since then. Can you update to 2.0.0 (or 1.3.14)?
