### ISSUE TITLE
lower performance with version >=1.3.10.

### ISSUE THREAD

**Issue by rxjhfmf** [mysql-net/MySqlConnector#1087]
**Software versions**
MySqlConnector version: >= 1.3.10
Server type (MySQL, MariaDB, Aurora, etc.) and version: Mysql (v8.0.18)
.NET version: .net core 3.1
(Optional) ORM NuGet packages and versions: Dapper 2.0.78

**Describe the bug**
lower performance with version >=1.3.10.
my sample query (e.g. select * from account where id =@Id) takes about 8ms(p95) with version 1.3.3;
but it takes about 13ms(p95) with version >=1.3.10 (e.g. 1.3.10  1.3.14  2.0.0 );

**Exception**
no exception
![6F95D157-F56C-4301-870C-A7530BC23603](https://user-images.githubusercontent.com/17841020/143369402-1380c398-508e-4dab-a380-de6cd89a82d8.png)

**Comment by rxjhfmf** [comment]
does the default value of `DeferConnectionReset` to `true`  cause the problem ?

**Comment by bgrainger** [comment]
Versions 1.3.0 to 1.3.9 had logic to reset connections in the background. This was designed to improve the performance of `MySqlConnection.Open`. 

However, at high request rates, this could dramatically increase p99 latency (see https://github.com/mysql-net/MySqlConnector/pull/982); moreover, there were sporadic reports of connection pools getting completely deadlocked.

Consequently, this code was disabled by default in 1.3.10 and removed in 2.0.0.

Resetting the connection (which is best for reliability) will always incur a small amount of overhead. For maximum performance, you can opt out with `Connection Reset = False;` in your connection string. However, please take note of the caveats and downsides here: https://mysqlconnector.net/connection-options/#ConnectionReset

**Comment by bgrainger** [comment]
Opened https://github.com/mysql-net/MySqlConnector/issues/1088 to reset connections more efficiently, which should reduce latency to the same level you were seeing with 1.3.3.
