### ISSUE TITLE
Can't do user=username@127.0.0.1

### ISSUE THREAD

**Issue by storm37000** [mysql-net/MySqlConnector#1100]
**Software versions**
MySqlConnector version: `2.1.0`
Server type (MySQL, MariaDB, Aurora, etc.) and version: `MySQL 5.7.33`
.NET version: `5.0 on Debian 10`
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Can't do user=username@127.0.0.1 which is required when dns lookups are disabled on the server when using unix sockets.  It returns  username@127.0.0.1@localhost instead.

**Exception**
`Unhandled exception. MySqlConnector.MySqlException (0x80004005): Access denied for user 'username@127.0.0.1'@'localhost' (using password: YES)`

**Code sample**
```csharp
new MySqlConnection("server=/var/run/mysqld/mysqld.sock;user=steam@127.0.0.1")
```

**Expected behavior**
connect and work

**Comment by bgrainger** [comment]
> Can't do user=username@127.0.0.1 which is required when dns lookups are disabled on the server when using unix sockets.

Do you have a link to the documentation that states this is required? I'm not familiar with this requirement.

**Comment by bgrainger** [comment]
It's not permissible/possible for the client to "spoof" the host name. (I.e., `username@127.0.0.1` is a username with a literal `@` in it, not a combination of user name and host name.) The host name is determined by the server and the user accounts on the server have to match it. See the remarks at the end of https://dev.mysql.com/doc/refman/8.0/en/account-names.html.

**Comment by storm37000** [comment]
I am able to do this with the command line mysql client -h option, where I can use 127.0.0.1 instead of "localhost" as the account cant be logged in using "localhost" but can be with the raw IP.

**Comment by bgrainger** [comment]
The `-h` option causes the mysql client to use TCP/IP instead of Unix sockets:

> To ensure that the client makes a TCP/IP connection to the local server, use --host or -h to specify a host name value of 127.0.0.1 (instead of localhost), or the IP address or name of the local server. 

If you want to do that, use `Server=127.0.0.1;User=steam`.

**Comment by storm37000** [comment]
I would like to use unix socket but with '127.0.0.1' instead of 'localhost'

**Comment by bgrainger** [comment]
As per the MySQL docs, that's not a valid combination. `127.0.01` implies TCP/IP, i.e., not a Unix socket.
