### ISSUE TITLE
Pool's MinimumPoolSize is not working

### ISSUE THREAD

**Issue by ikpil** [mysql-net/MySqlConnector#1108]
**Software versions**
MySqlConnector version: "MySqlConnector" Version="2.1.0"

Server type (MySQL, MariaDB, Aurora, etc.) and version: 5.0.45-Xpand-5.3.17
.NET version: LTS dotnet core 3.1
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Pool's MinimumPoolSize is not working.

I set it up like this
            var builder = new MySqlConnectionStringBuilder();
            builder.Server = dbHost;
            builder.Port = (uint)dbPort;
            builder.Database = dbName;
            builder.UserID = dbUserID;
            builder.Password = dbUserPassword;
            builder.CharacterSet = "utf8mb4";
            builder.SslMode = MySqlSslMode.None;
            builder.ConvertZeroDateTime = true;
            builder.Pooling = true;
            builder.MinimumPoolSize = 32;
            builder.MaximumPoolSize = 100;

After about 3 minutes, only one connection is maintained.

However, if you set it as follows, 32 connections are maintained.

            var builder = new MySqlConnectionStringBuilder();
            builder.Server = dbHost;
            builder.Port = (uint)dbPort;
            builder.Database = dbName;
            builder.UserID = dbUserID;
            builder.Password = dbUserPassword;
            builder.CharacterSet = "utf8mb4";
            builder.SslMode = MySqlSslMode.None;
            builder.ConvertZeroDateTime = true;
            builder.Pooling = true;
            builder.MinimumPoolSize = 32;
            builder.MaximumPoolSize = 32;
            builder.ConnectionIdleTimeout = 0;

**Exception**
none

**Code sample**

```csharp
```

**Expected behavior**

**Additional context**

**Comment by bgrainger** [comment]
I can't reproduce this. What's your server's `wait_timeout` value (`SELECT @@wait_timeout;`)? If it were set to something low, like `180`, the server will close the client's pooled connections while they're still in use (by the pool). The fix would be to increase this value to a more appropriate value for your application.

**Comment by ikpil** [comment]
> 

![image](https://user-images.githubusercontent.com/313821/147893791-f6a4c37f-9eb4-413b-90ea-e8800814ba3f.png)

**Comment by ikpil** [comment]
If you haven't been able to reproduce this.
I'll take a log and check it again when I service it.

and i'll share it again

**Comment by ikpil** [comment]
I confirmed the problem.
It was an AWS NLB issue.

We have the following structure.
Server -> AWS NLB -> max scale -> xpand nodes

here
NLB -> max scale

The connection is broken.

Thanks for posting the answer.

@bgrainger
