### ISSUE TITLE
DO SLEEP(0) is syntax error in xpand db

### ISSUE THREAD

**Issue by ikpil** [mysql-net/MySqlConnector#1115]
Software versions
MySqlConnector version: "MySqlConnector" Version="2.1.2"

Server type (MySQL, MariaDB, Aurora, etc.) and version: 5.0.45-Xpand-5.3.17
.NET version: LTS dotnet 6.0.10
(Optional) ORM NuGet packages and versions:

Describe the bug
DO SLEEP(0) is not working

Exception
exception message
    MySqlConnector.MySqlException : [33792] syntax error: syntax error near "DO"
    LINE: DO SLEEP(0);

    Data:
      Server Error Code: 1064
      SqlState: HY000

call stack
    ServerSession.FinishQuerying() Line 322
    MySqlConnection.FinishQuerying(Boolean hasWarnings) Line 876
    MySqlDataReader.DisposeAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) Line 609
    MySqlDataReader.Dispose(Boolean disposing) Line 428
    DbDataReader.Dispose()
    SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+<>m__Finally1() Line 1125
    SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() Line 1115
    List`1.ctor(IEnumerable`1 collection)
    Enumerable.ToList[TSource](IEnumerable`1 source)
    SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) Line
 721

**Comment by bgrainger** [comment]
Does `SELECT SLEEP(0) INTO @dummy` work for Xpand DB? That syntax suggestion came from https://github.com/gopigment/MySqlConnector/commit/b548db420db97e059a1f9e7185370976fdc76776#diff-22f5eec5ea345b8f0fd8c96f47bb2a7e59d35071c7ad2525d6f251a5ece19d5cR319.

**Comment by ikpil** [comment]
> Does `SELECT SLEEP(0) INTO @dummy` work for Xpand DB? That syntax suggestion came from [gopigment@b548db4#diff-22f5eec5ea345b8f0fd8c96f47bb2a7e59d35071c7ad2525d6f251a5ece19d5cR319](https://github.com/gopigment/MySqlConnector/commit/b548db420db97e059a1f9e7185370976fdc76776#diff-22f5eec5ea345b8f0fd8c96f47bb2a7e59d35071c7ad2525d6f251a5ece19d5cR319).

works fine!

If applied to library, when will it be released?

**Comment by bgrainger** [comment]
The `SELECT SLEEP(0) INTO @dummy` syntax is also a necessary workaround for SingleStore (see https://github.com/memsql/SingleStoreNETConnector/commit/d8f808e45898b702b12cb1bfa6aa34937fc6c1bb) so it seems reasonable to make it the default in MySqlConnector.

**Comment by bgrainger** [comment]
Fixed in [2.1.5](https://github.com/mysql-net/MySqlConnector/releases/tag/2.1.5).

**Comment by bgrainger** [comment]
This syntax may not be compatible with Manticore: https://github.com/mysql-net/MySqlConnector/discussions/1356.
