### ISSUE TITLE
MySqlParameterCollection : Add Constructor/Method to MySqlParameterCollection which allow memory allocation in advance for m_parameters if the size is known 

### ISSUE THREAD

**Issue by sumitdvlp** [mysql-net/MySqlConnector#1119]
**Is your feature request related to a problem? Please describe.**

Everytime I add new Parameter in MySqlParameterCollection, it might have to resize which might cause perf issues if I am adding many Parameters, If i know number parameters I planning to add , it does make sense for me allocate that much memory upfront to avoid overfill or allocating again and again.

**Describe the solution you'd like**

Current constructor is internal not sure why but maybe we can add new method which can allocate the element in the list (m_parameters) or assign a list to m_parameters.

**Describe alternatives you've considered**
I looked at the code I haven't found anything which can be used to pre allocate number of items to m_parameters.

**Additional context**

**Comment by badbod99** [comment]
m_parameters within MySqlParameterCollection is a List.  Sure, it might have to internally resize, but this is optimised in dotnet.  The internal array resized to double it's current size.  It starts at a size of 4.

This really isn't going to cause you any performance issues.

**Comment by sumitdvlp** [comment]
We actually in some cases (where perf matters) add thousands of parameters to MySqlParameterCollection.
We are hoping that because its ArrayList( worse if its a LinkedList) it will give us slight improvement in perf when we pre allocate the size in memory.

Where we use MySqlParameterCollection? To make bulk insert statement.
Why not use MySqlBulkCopy? MySqlBulkCopy use file stream which is where we cannot implement our retry strategy, 
we are afraid that in case of failure it might leave some data behind (maybe we are wrong) and we want write parallelly to a single table.

**Comment by sumitdvlp** [comment]
> m_parameters within MySqlParameterCollection is a List. Sure, it might have to internally resize, but this is optimised in dotnet. The internal array resized to double it's current size. It starts at a size of 4.
> 
> This really isn't going to cause you any performance issues.

I think it will when you have thousands of parameters and they are re-allocated everytime when it resizes.

**Comment by bgrainger** [comment]
> MySqlBulkCopy use file stream

Are you thinking of `MySqlBulkLoader`? `MySqlBulkCopy` can load from a `DataTable` or even `IEnumerable<DataRow>`.

>> This really isn't going to cause you any performance issues.
> 
> I think it will when you have thousands of parameters and they are re-allocated everytime when it resizes.

Resizing `List<T>` will have a (small) cost, but I'd like to see a performance trace that concretely identifies it as one of the top bottlenecks before putting much effort into optimising it. (And it's not true that the parameters will be reallocated every time.)

**Comment by bgrainger** [comment]
No evidence that this is a real problem in practice.
