### ISSUE TITLE
SHOW VIEW permission required to query view after upgrade from 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by kampilan** [mysql-net/MySqlConnector#1129]
Did something change  between versions 2.0.0 and 2.10 that now requires the db user to have SHOW VIEW permission granted on MySql 8.0.28 when querying a view? I upgraded Pomelo from 6.0.0 to 6.0.1  and started getting access denied errors when querying views until I granted the user SHOW VIEW permission.

According to MySql docs SHOW VIEW permission is required to call DECRIBE, EXPLAIN and SHOW COLUMNS on a view. I'm perfectly happy with my solution but I find it disconcerting that I can't find anything confirming this.

Thanks
Jim

**Comment by bgrainger** [comment]
There are no known changes that require this permission. The major change in 2.1.0 was support for query attributes (#930); I don't know if this is perhaps an unexpected side effect (in MySQL Server) of how query attributes are handled when querying a view?

**Comment by kampilan** [comment]
The query attributes, that's exactly what I thought when I read the release notes and it prompted this ticket. 

Thanks for the clarification.

**Comment by bgrainger** [comment]
I just tested with MySQL 8.0.28, logging in with user that only has `SELECT` permission, and I was able to `SELECT * FROM myview` with no problems.

Are you able to create a self-contained repro for the problem (just using MySqlConnector, not Pomelo)?

**Comment by kampilan** [comment]
Not only was I not able to duplicate the behavior using MySqlConnector directly, the problem when using Pomelo is no longer occurring either. Weird. Yesterday I was able to toggle the behavior by simply adding/removing the permission.  Sorry to waste your time.
