### ISSUE TITLE
Received an Unknown Command (code=31)

### ISSUE THREAD

**Issue by AndyKingent** [mysql-net/MySqlConnector#1130]
**Software versions**
MySqlConnector version: v2.1.5
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL
.NET version: .NET framework 4.5
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Hi, so sorry for bugging you. We wrote a helper function to basically connect sphinx distributed index by using MySQL and get the last index. Then we called this function twice in one of our major functions. The connection was successfully built for the first time. However, when we call it again for the second time, an exception was thrown when the openAsync() was called. And the error message shown that "unknown command (code=31)". Really appreciate the help.

**Exception**
Full exception message and call stack (if applicable)
```
ex.Message: "unknown command (code=31)" & vbNullChar
```
**Code sample**

```vb.net

Async Function GetLastIndexedID(IndexName As String) As Task(Of Long)
        Try
            Dim conDB As New MySqlConnection
            conDB.ConnectionString = GetConnectionString()
            Await conDB.OpenAsync()

            Dim comDB As New MySqlCommand
            comDB.Connection = conDB
            comDB.CommandText = String.Format("cotent", IndexName)

            Dim dbrDB As MySqlDataReader = Await comDB.ExecuteReaderAsync

            While Await dbrDB.ReadAsync
                ...
            End While
            Await conDB.CloseAsync() 
        Catch ex As Exception
            WriteLogEvent("Error: " + If(ex.Message, ex.Message, ""), 0000,
                 EventLogEntryType.Error, "RTIndexer")
            Throw ex
        End Try
```
**Expected behavior**
It can still get connected to the MySQL database the second time it get called and get the last index as expected
**Additional context**

**Comment by bgrainger** [comment]
Command Code 31 is "Reset Connection".

> Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL

What's the actual server and version you're connecting to? It appears to be something that claims to be at least MySQL 5.7.3, but doesn't support the reset connection feature.

You could work around it for now by adding `Connection Reset = false;` to your connection string, which will stop MySqlConnector from sending that command.

**Comment by AndyKingent** [comment]
Thank you so much for the help. We're trying to connect to MySQL 6.9.6. The given solution works :) Thanks again

**Comment by bgrainger** [comment]
I'm confused, because 6.9.x was never a release version of MySQL Server: https://en.wikipedia.org/wiki/MySQL#Release_history

Are you using the NuGet package MySql.Data 6.9.6? That's a different library, and bugs for it can be reported at https://bugs.mysql.com/.
