### ISSUE TITLE
Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by hugo2jusdado** [mysql-net/MySqlConnector#1139]
**Software versions**
MySqlConnector version: 2.1.6
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL 8.0.28
.NET version: 4.6.1

**Describe the bug**
When the app tries to open the connection, this error raises. The app references System.Threading.Tasks.Extensiones 4.5.5.

**Exception**
[FileLoadException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
   MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) +0
   MySqlConnector.MySqlConnection.Open() +36

**Code sample**
var cn = new MySqlConnector.MySqlConnection(Config.Current.ConnectionString);
cn.Open();
var cm = new MySqlConnector.MySqlCommand(query, cn);
cm.ExecuteNonQuery();
cn.Close();
cn.Dispose();

**Comment by hugo2jusdado** [comment]
> > The app references System.Threading.Tasks.Extensiones 4.5.5.
> 
> That version doesn't exist on NuGet: https://www.nuget.org/packages/System.Threading.Tasks.Extensions/
> 
> You need an assembly binding redirect, which will look something like this:
> 
> ```
> <dependentAssembly>
> 	<assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
> 	<bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1"/>
> </dependentAssembly>
> ```
> 
> For more information, see https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions.

First, library version is 4.5.4.

I have that and it doesn´t work. In dev environment works fine but in preprod it doesn´t. This error raises from MySqlConnector library. Could you recompile it or something like that?

**Comment by bgrainger** [comment]
> First, library version is 4.5.4.

That's the NuGet package version, which is different than the strong name of the assembly (which you need to use in the binding redirect).

> This error raises from MySqlConnector library.

No, it raises from your application.

**Comment by kimboslice99** [comment]
Same errors here, binding redirect does not work.

**Comment by bgrainger** [comment]
> <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="6.0.0.0"/>

You have to use the correct version number in `newVersion`. The latest version appears to be `Version=4.2.0.1`. (Note that this is the version from the assembly strong name, not the NuGet package vesrion.)

**Comment by kimboslice99** [comment]
For `System.Threading.Tasks.Extensions` you would be correct, in my case I had the same error but for `System.Runtime.CompilerServices.Unsafe` and its latest version is 6.0.0.0

**Comment by nagsist** [comment]
kimboslice99,
<runtime>
	<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
		<dependentAssembly>
			<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
			<bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="6.0.0.0"/>
		</dependentAssembly>
	</assemblyBinding>
</runtime>

Friend, you saved my life with this solution, thank you.
