### ISSUE TITLE
Documentation: Migrating from MySql.Data

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#114]
List changes users may need to be aware of to migrate from `MySql.Data` to this library.
- [x] Connection String defaults
  - `ConnectionReset` defaults to `true` (not `false`)
  - `UseAffectedRows` defaults to `true` (not `false`); affects `ROW_COUNT`
  - other connection string options aren't implemented
- [x] Fixed bugs that may no longer need client workarounds
  - `Server` supports multiple comma-delimited hosts
  - null values in bool columns

**Comment by caleblloyd** [comment]
Only thing I didn't understand was the bug you were referring to in:

> null values in bool columns

I've written the rest of this up in #134 - [view here](https://mysql-net.github.io/MySqlConnector/tutorials/migrating-from-connector-net/)

**Comment by bgrainger** [comment]
> null values in bool columns

It's [this bug](https://bugs.mysql.com/bug.php?id=78917), exposed by [this test](https://github.com/mysql-net/MySqlConnector/blob/da3d978cce55373f5bc919179310f6657294ebff/tests/SideBySide.New/DataTypes.cs#L126-L136).

**Comment by bgrainger** [comment]
The latest version of [Migrating from Connector/Net](https://mysql-net.github.io/MySqlConnector/tutorials/migrating-from-connector-net/), updated in 0a97e236ff3e58199aab0cf6f519a416bb49ceed, fixes this.
