### ISSUE TITLE
Unknown issue when inserting

### ISSUE THREAD

**Issue by andrewdci03** [mysql-net/MySqlConnector#1145]
**Software versions**
MySqlConnector version:
Server type (MySQL, MariaDB, Aurora, etc.) and version: 
.NET version: 
(Optional) ORM NuGet packages and versions: 

**Describe the bug**

**Exception**

143 rows have been copied but 0 has been inserted

**Code sample**

` var connection = new MySqlConnection("[redacted]");

            //creating object of MySqlBulkCopy
            MySqlBulkCopy objbulk = new MySqlBulkCopy(connection);

            //Mapping Table column
            MySqlBulkCopyColumnMapping columnMapping;
            foreach (var column in csvdt.Columns)
            {
                columnMapping = new MySqlBulkCopyColumnMapping(csvdt.Columns[column.ToString()].Ordinal, column.ToString());
                objbulk.ColumnMappings.Add(columnMapping);
            }

            //inserting Datatable Records to DataBase
            connection.Open();
            MySqlConnector.MySqlBulkCopyResult result = objbulk.WriteToServer(csvdt);
            //test.Load();
            connection.Close();`

**Expected behavior**
I expected for it insert the rows

**Additional context**
It's a csv file that's being inserted into a MariaDB. This function is being called in a Foreach loop and inserts different csv files into different tables based on the file name. It inserts the first csv file and then fails on the remaining. I have forced it to skip the first file and start on the second and it still fails.

**Comment by bgrainger** [comment]
Hmm, it may be the case that the errors aren't exposed if the `Write` method throws an exception; cf. https://github.com/mysql-net/MySqlConnector/issues/1012#issuecomment-874407976.

Please try this workaround:

```csharp
var connection = new MySqlConnection("[redacted]");
connection.InfoMessage += (s, e) =>
{
	// use logging infrastructure of your choice
	foreach (var error in e.Errors)
		Console.WriteLine(error.Message);
};

// ...

connection.Open();
MySqlConnector.MySqlBulkCopyResult result = objbulk.WriteToServer(csvdt);
```

Does the `InfoMessage` event handler provide enough information to diagnose the data issue causing no rows to be inserted?

**Comment by andrewdci03** [comment]
@bgrainger that looks like it did it!

Apparently it's violating a foreign key constraint. I'll share the output snippet below:
"Cannot add or update a child row: a foreign key constraint fails..."

So I should be able to make some adjustments from that. Thanks!
