### ISSUE TITLE
Could not open a mysql connection: Cannot Open when State is Open.

### ISSUE THREAD

**Issue by storm37000** [mysql-net/MySqlConnector#1155]
**Software versions**
MySqlConnector version: 2.1.8
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL 5.7.33
.NET version: 5
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Throws the exception at random times when I try to open a new connection in the connection pool.

**Exception**
Full exception message and call stack (if applicable)

**Code sample**

```csharp
private static readonly MySqlConnection SqlConn = new MySqlConnection(sqlstr);
...
try
{
	if (!SqlConn.State.Equals(ConnectionState.Connected))
	{
		SqlConn.Open();
	}
}
catch (Exception e)
{
	logErrorMSG("Could not open a mysql connection: " + e.Message);
}
```

**Expected behavior**
Open a new connection on the pool and not throw an exception.

**Additional context**
I am using connection pools and close the  created pool connection as soon as I am done with it.

**Comment by bgrainger** [comment]
This sample code doesn't compile; `ConnectionState.Connected` is not a valid enum value for [ConnectionState](https://docs.microsoft.com/en-us/dotnet/api/system.data.connectionstate?view=net-6.0).

As the exception message states, you may not call `Open` on an open connection; this is an invalid operation.

This is a bad pattern and should be avoided: `private static readonly MySqlConnection SqlConn = new MySqlConnection(sqlstr);`. `MySqlConnection` objects are cheap and should be created on an as-needed basis (generally within the scope of one method), not stored in a `static` field and potentially shared between threads.

**Comment by storm37000** [comment]
Then what is the point of connection pooling?

**Comment by bgrainger** [comment]
> I expect it to be rapidly using multiple connections as needed under the same constructor

Each new `MySqlConnection` object (that has the same connection string) will (under the hood) retrieve a physical connection from a pool of connections. `MySqlConnection` is designed to be used once and disposed; you should not be keeping one long-lived object and reusing it. The "pooling" is what makes multiple `MySqlConnection` objects share the same underlying connection.
