### ISSUE TITLE
Replace `UnixEndPoint` with `UnixDomainSocketEndPoint`

### ISSUE THREAD

**Issue by mguinness** [mysql-net/MySqlConnector#1160]
While looking into https://stackoverflow.com/questions/71742985 I noticed that `OpenUnixSocketAsync()` uses the [UnixEndPoint](https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/Utilities/UnixEndPoint.cs) class that was added with PR https://github.com/mysql-net/MySqlConnector/pull/119 back in 2016.

https://github.com/mysql-net/MySqlConnector/blob/e5cc8114730eaaa2c45921db688da3e17152c8ae/src/MySqlConnector/Core/ServerSession.cs#L1139-L1186

Since .NET Standard 2.1 the [UnixDomainSocketEndPoint](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.unixdomainsocketendpoint) class is available which should provide the same functionality as `UnixEndPoint` that was copied from Mono.

It probably doesn't offer any benefits other than code maintainability, but if the code implementing Unix Domain Sockets can easily switch to the new class that would be worthwhile.  The Postgres driver also made this switch in  https://github.com/npgsql/npgsql/pull/3314,

The question as to why the `uid` option is needed in the connection string for the unix socket [authentication plugin](https://dev.mysql.com/doc/refman/8.0/en/socket-pluggable-authentication.html) to work is another issue which I asked the OP to submit.

**Comment by bgrainger** [comment]
> The question as to why the uid option is needed in the connection string for the unix socket [authentication plugin](https://dev.mysql.com/doc/refman/8.0/en/socket-pluggable-authentication.html) to work is another issue which I asked the OP to submit.

MySqlConnector always sends a [handshake response packet](https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse) (when connecting via any protocol, including Unix sockets), which contains a "username" field. In the SO poster's case, it will contain the empty string. The MariaDB documentation makes it sound as if the client doesn't need to provide a user name:

> The `unix_socket` authentication plugin works by calling the [getsockopt](http://man7.org/linux/man-pages/man7/socket.7.html) system call with the `SO_PEERCRED` socket option, which allows it to retrieve the `uid` of the process that is connected to the socket. It is then able to get the user name associated with that `uid`. Once it has the user name, it will authenticate the connecting user as the MariaDB account that has the same user name.

Maybe client libraries are supposed to implicitly set the user name to `whoami` when connecting via Unix sockets, and this is just undocumented expected behaviour?

**Comment by mguinness** [comment]
That's really not clear to me either, some examples show the command line client with `--user` option and others don't.

The [MySQL plugin](https://github.com/mysql/mysql-server/blob/8.0/plugin/auth/auth_socket.cc) documentation shows how to map a DB user to a different OS user which necessitates providing the user.

Maybe the answer is when connection protocol is set to unix and user is empty then just replace it with `Environment.UserName`?

Would you be able to do a packet capture on mysql client without user to see what is sent in the handshake response packet?

**Comment by bgrainger** [comment]
Implemented in [2.1.9](https://github.com/mysql-net/MySqlConnector/releases/tag/2.1.9).
