### ISSUE TITLE
Allow implicit data type conversion from JSON

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#1165]
From https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1638#issuecomment-1109849539

The `JSON_EXTRACT` MySQL function allows a property of an object stored in a JSON column to be extracted and returned. This property may be a simple number, string, or Boolean, in which case it would be useful for `GetInt32` etc. to be called to read the value. That currently fails with the exception `Can't convert JSON to Int32`.

Since plain JSON values are unambiguously encoded, the following regex patterns (illustrative, not normative) could be used to determine whether a value can be coerced:

Pattern | Allowed method
--- | ---
`^-?[0-9]+$` | `GetInt32`
`^-?[0-9]+(\.[0-9]+)?([Ee][+-]?[0-9]+$` | `GetDouble`
`^".*?"$` | `GetString` (requires JSON decoding)
`^(true\|false)$` | `GetBoolean`

**Comment by bgrainger** [comment]
This might create ambiguous behaviour for `GetString`: does it return the original JSON as a string, or decode a JSON string into a C# string? If it already does the former, it would be a breaking change to change it to the latter.

**Comment by mguinness** [comment]
Would it be too expensive to use [JsonElement](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement) from [System.Text.Json](https://www.nuget.org/packages/System.Text.Json) and avoid re-inventing the wheel?

**Comment by bgrainger** [comment]
Are you suggesting that `GetValue` should be changed to return a `JsonElement` (for a `JSON` column or the results of `JSON_EXTRACT`), or just suggesting that it be used behind-the-scenes to implement the feature?

**Comment by bgrainger** [comment]
Makes sense for platforms that have System.Text.Json built-in; doesn't feel worth taking a new dependency (on other TFMs) for a niche feature.

The implementation should still test the first character of the value; it doesn't make sense to parse an arbitrarily-large JSON object (that begins with `{`) with `JsonElement` only to find out its `ValueKind` is `Object`.

**Comment by bgrainger** [comment]
> `GetString` (requires JSON decoding)

The user should call [`JSON_UNQUOTE`](https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-unquote) in their SQL if they want to call `MySqlDataReader.GetString` and retrieve the "real" string value; there shouldn't be any special handling in MySqlConnector.

**Comment by mguinness** [comment]
Yes, that is already possible in Pomelo by wrapping `EF.Functions.JsonExtract()` with `EF.Functions.JsonUnquote()`.

**Comment by bgrainger** [comment]
Workaround (or alternate solution): the user should use MySQL functions to cast a JSON value to the appropriate data type before calling `GetInt32`, `GetBoolean`, etc. The examples below use the entire column value but apply w.l.o.g. to values returned by `JSON_EXTRACT`:

Data Type | Reader Method | SQL
--- | --- | ---
int | `GetInt32` | `CAST(value AS SIGNED)`
double | `GetDouble` | `CAST(value AS DOUBLE)`
string | `GetString` | `JSON_UNQUOTE(value)`
Boolean | `GetBoolean` | `CAST(value AS UNSIGNED)`

Example SQL:

```sql
drop table if exists json_test;
create table json_test(value json not null);
insert into json_test(value) values('1'), ('"a"'), ('1.5'), ('true'), ('false');
select cast(value as SIGNED) from json_test where value = 1;
select json_unquote(value) from json_test where value = 'a';
select cast(value as DOUBLE) from json_test where value = 1.5;
select cast(value as SIGNED) from json_test where value = true;
```

Sample C#:

```csharp
using var command = new MySqlCommand(@"select cast(value as SIGNED) from json_test where value = 1;
select json_unquote(value) from json_test where value = 'a';
select cast(value as DOUBLE) from json_test where value = 1.5;
select cast(value as SIGNED) from json_test where value = true;", connection);
using var reader = command.ExecuteReader();
reader.Read();
reader.GetInt32(0).Dump();
reader.NextResult();
reader.Read();
reader.GetString(0).Dump();
reader.NextResult();
reader.Read();
reader.GetDouble(0).Dump();
reader.NextResult();
reader.Read();
reader.GetBoolean(0).Dump();
```

**Comment by mguinness** [comment]
Issue can be closed, suggested changes being made in Pomelo with PR [#1649](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1649).

**Comment by bgrainger** [comment]
The user should use the solution in https://github.com/mysql-net/MySqlConnector/issues/1165#issuecomment-1110189613 to modify the data in the SQL engine; MySqlConnector shouldn't perform any implicit JSON ↔ string/int/bool conversions.
