### ISSUE TITLE
MySqlTransaction.BeginTransaction() Hangs Forever If Connection Not Open

### ISSUE THREAD

**Issue by turc1656** [mysql-net/MySqlConnector#1166]
I accidentally put this line of code above the code I had to check the ConnectionState and call Open() if needed:
`MySqlConnector.MySqlTransaction mySQLTransaction = mySqlConnection.BeginTransaction();`

This seems to result in BeginTransaction() never returning control back to the calling process.  Nor does it produce and error or throw an exception.  Once I moved that line below the call to Open() everything worked fine.  I believe this is a bug and should throw an error about the ConnectionState property not being acceptable.

**Comment by bgrainger** [comment]
```csharp
using var connection = new MySqlConnection("...");
using var transaction = connection.BeginTransaction();
```

I get an immediate `InvalidOperationException` with the message "Connection is not open".

Can you provide a code snippet that reproduces the problem?

**Comment by turc1656** [comment]
I made a simplified version of my code that shows the structure of how the methods are being executed in order.  When I do that, I can replicate.  However, it seems to be related to the many asynchronous tasks I have in execution and the `SemaphoreSlim` that controls it.  When I get rid of the many tasks and the `SemaphoreSlim`, I can replicate and get the exception on the call to `Task.WaitAll()`.  With the many tasks and the use of the SemaphoreSlim, it appears to hang, but I think that's because it's a very long running process and therefore the call to `Task.WaitAll()` doesn't actually get invoked until near the end.

Here is the code sample just so you can see how I have things structured.  I suspect this is not a bug and has to do with the way I structured the code and how the C# stack operates.

```
namespace ConnectorTest
{
    public partial class MainWindow : Window
    {
        MySqlConnector.MySqlConnection mySqlConnection;
        SemaphoreSlim mySemaphore;

        public MainWindow()
        {
            mySemaphore = new SemaphoreSlim(10);
            mySqlConnection = new MySqlConnector.MySqlConnection("connection string");
        }

        public void TaskWaiter(List<Task> tasksToWaitFor)
        {
            Task.WaitAll(tasksToWaitFor.ToArray());

            MessageBox.Show("DONE");
        }

        public async void Button_Click(object sender, RoutedEventArgs e)
        {
            Task.Run(() => DoWorkAsync());
        }

        public async void DoWorkAsync()
        {
            List<Task> tasks = new List<Task>();

            for (int i = 0; i < 10000; i++)
            {
                while (mySemaphore.CurrentCount == 0)
                {
                    //wait for semaphore entry to be available.
                    Thread.Sleep(100);
                }

                tasks.Add(ProcessDataAsync());
            }

            Task.Run(() => TaskWaiter(tasks));
        }

        public async Task ProcessDataAsync()
        {
            await mySemaphore.WaitAsync();
            Thread.Sleep(1000);  //simulate wait for preprocessing data
            mySemaphore.Release();

            await InsertDataAsync();
        }

        public async Task InsertDataAsync()
        {
            MySqlConnector.MySqlTransaction mySQLTransaction = mySqlConnection.BeginTransaction();

            MessageBox.Show("Control was returned");
        }
    }
}
```
