### ISSUE TITLE
MySqlException: Parameter '@.....' must be defined. To use this as a variable, set 'Allow User Variables=true' in the connection string.

### ISSUE THREAD

**Issue by PaulatElf** [mysql-net/MySqlConnector#1172]
**Software versions**
MySqlConnector version: 0.69.10
Server type (MySQL) and version: 8.0
.NET version: 6.02

**Describe the bug**
I have this issue too but only on my live website, when running from Visual Studio (localhost) don't have any problems but when using Hangfire (1.8.0) Dashboard on the live published site I can access a few pages (/hangfire, /hangfire/servers, /hangfire/jobs) but for all the other pages (such as hangfire/recurring, hangfire/retries, hangfire/jobs/succeeded ect.) I always get that same message: 'MySqlException: Parameter '@.....' must be defined. To use this as a variable, set 'Allow User Variables=true' in the connection string.'

Even though I already do have 'Allow User Variables=true' in the connection string.

If anyone has any ideas how to fix this it would be very helpful.

**Exception**
MySqlException: Parameter '@rank' must be defined. To use this as a variable, set 'Allow User Variables=true' in the connection string.

MySqlException: Parameter '@rownum' must be defined. To use this as a variable, set 'Allow User Variables=true' in the connection string.

MySqlConnector.Core.StatementPreparer.GetParameterIndex(string name) in StatementPreparer.cs, line 48

**Comment by bgrainger** [comment]
> MySqlConnector version: 0.69.10

This version is pretty old; can you update to 2.1.9?

> I always get that same message: 'MySqlException: Parameter '@.....' must be defined. To use this as a variable, set 'Allow User Variables=true' in the connection string.'

Please provide the full exception message, including the full call stack, and a code sample that reproduces the problem.
