### ISSUE TITLE
Do you support ShardingSphere-Proxy connection?

### ISSUE THREAD

**Issue by Peterosh** [mysql-net/MySqlConnector#1181]
There will be an error when connecting ShardingSphere-Proxy's sharding_db."Unsupported command: [COM_RESET_CONNECTION]"

**Comment by Peterosh** [comment]
Ok, thanks for your reply

**Comment by TOP-LH** [comment]
> 好的，感谢您的回复

Do you know how to change the version number?

**Comment by bgrainger** [comment]
Based on https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/yaml-config/props/ maybe you can use `proxy-mysql-default-version` in `server.yaml` to configure this?

**Comment by Peterosh** [comment]
> > 好的，感谢您的回复
> 
> Do you know how to change the version number?

I lowered the mysql version.I feel shardingSphere-proxy support the latest version of mysql is not very good

**Comment by TOP-LH** [comment]
> > > 好的，感谢您的回复
> > 
> > 
> > Do you know how to change the version number?
> 
> I lowered the mysql version.I feel shardingSphere-proxy support the latest version of mysql is not very good

How did you solve the problem, can you please tell me

**Comment by Peterosh** [comment]
> > > > 好的，感谢您的回复
> > > 
> > > 
> > > Do you know how to change the version number?
> > 
> > 
> > I lowered the mysql version.I feel shardingSphere-proxy support the latest version of mysql is not very good
> 
> How did you solve the problem, can you please tell me

Using low version of mysql server or use the official library

**Comment by TOP-LH** [comment]
> > > > > 好的，感谢您的回复
> > > > 
> > > > 
> > > > Do you know how to change the version number?
> > > 
> > > 
> > > I lowered the mysql version.I feel shardingSphere-proxy support the latest version of mysql is not very good
> > 
> > 
> > How did you solve the problem, can you please tell me
> 
> Using low version of mysql server or use the official library

Do you want to change the proxy-mysql-default-version property in server.yaml?

**Comment by TOP-LH** [comment]
> > > > > > > 好的，感谢您的回复
> > > > > > 
> > > > > > 
> > > > > > Do you know how to change the version number?
> > > > > 
> > > > > 
> > > > > I lowered the mysql version.I feel shardingSphere-proxy support the latest version of mysql is not very good
> > > > 
> > > > 
> > > > How did you solve the problem, can you please tell me
> > > 
> > > 
> > > Using low version of mysql server or use the official library
> > 
> > 
> > Do you want to change the proxy-mysql-default-version property in server.yaml?
> 
> Low version of the mysql server installation, not modify server.yaml configuration.

官方说他解决了, 降低mysql实际版本号代价太大了https://github.com/apache/shardingsphere/issues/6861#issuecomment-1333294566

**Comment by Peterosh** [comment]
> > > > > > > > 好的，感谢您的回复
> > > > > > > 
> > > > > > > 
> > > > > > > Do you know how to change the version number?
> > > > > > 
> > > > > > 
> > > > > > I lowered the mysql version.I feel shardingSphere-proxy support the latest version of mysql is not very good
> > > > > 
> > > > > 
> > > > > How did you solve the problem, can you please tell me
> > > > 
> > > > 
> > > > Using low version of mysql server or use the official library
> > > 
> > > 
> > > Do you want to change the proxy-mysql-default-version property in server.yaml?
> > 
> > 
> > Low version of the mysql server installation, not modify server.yaml configuration.
> 
> 官方说他解决了, 降低mysql实际版本号代价太大了[apache/shardingsphere#6861 (comment)](https://github.com/apache/shardingsphere/issues/6861#issuecomment-1333294566)
This is a good news
