### ISSUE TITLE
Failed to read the result set

### ISSUE THREAD

**Issue by tomeroto** [mysql-net/MySqlConnector#1184]
**Software versions**
MySqlConnector version: 2.1.10
Server type MySQL and version: 4.1.14
.NET version: 
.Net Core 3.1

**Describe the bug**
My program just execute for query "SELECT * FROM TABLE_NAME LIMIT 10"

**Exception**
Failed to read the result set.

**Code sample**

```csharp
using (var connection = new MySqlConnection(String.Format("Server={0};User ID={1};Password={2};Port={3};Database={4};", textBoxDBHost.Text, textBoxDBUsername.Text, textBoxDBPassword.Text, textBoxDBPort.Text, textBoxDBName.Text)))
{
    try
    {
        connection.Open();

        using (var command = new MySqlConnector.MySqlCommand())
        {
            command.Connection = connection;

            String query = textBoxPushQueryRecord.Text;
            command.CommandText = query;
            command.ExecuteNonQuery();

       }


        MessageBox.Show("OK");
    }
    catch (Exception ex)
    {
        MessageBox.Show(ex.Message);
    }
    connection.Close();
}
```

**Expected behavior**
I hope nothing to show on exception.

**Additional context**
I test in other environtment for Mysql 5.7.17 on other PC is normal.

Thank you!

**Comment by badbod99** [comment]
This code does not execute any query, only tries to open the connection, so I don't think it could throw the error mentioned.  Best to post complete code to reproduce the issue.

> Server type MySQL and version: 14.7

I can't find any MySQL version 14.7.  MySQL 8 is latest.  Is this a typo?

**Comment by bgrainger** [comment]
> Server type MySQL and version: 4.1.14

This version will be 17 years old (in two weeks). MySqlConnector has not been tested with MySQL versions earlier than 5.6 (which itself is out of support); it's likely there are protocol differences that make it incompatible.

You may need to update to MySQL 5.7 or 8.0 to use MySqlConnector. Alternatively, a really old version of MySql.Data (earlier than the ones on NuGet) may allow you to connect if you can find it.
