### ISSUE TITLE
[ClickHouse Compatibility] +/-Infinity values parsing

### ISSUE THREAD

**Issue by MaceWindu** [mysql-net/MySqlConnector#1185]
ClickHouse supports NaN, Infinity and -Infinity values for float/double types, which cannot be parsed by MySqlConnector [here](https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/Core/TextRow.cs#L99-L102):
- NaN value sent as"nan" and parsed successfully
- Infinity and -Infinity sent as "inf" and "-inf" and result in `FormatException`

**Describe the solution you'd like**

Would be nice to support those two values (always or using some ClickHouse compatibility switch/connection string parameter).

I cannot find any information on float/double encoding in spec, probably looking at wrong place as I'm not familiar with it at all (https://dev.mysql.com/doc/internals/en/string.html)

**Comment by bgrainger** [comment]
`double.Parse("∞")` returns `double.PositiveInfinity`; doesn't seem unreasonable to add hard-coded support for `inf` and `-inf`.

**Comment by bgrainger** [comment]
I didn't actually test with ClickHouse, but added support for `-inf` and `inf` as described in the case.

**Comment by bgrainger** [comment]
Implemented in [2.1.11](https://github.com/mysql-net/MySqlConnector/releases/tag/2.1.11).

**Comment by MaceWindu** [comment]
Thanks, it works!
