### ISSUE TITLE
Schema / FieldCount ending in type BIT uploads incorrect data into DB

### ISSUE THREAD

**Issue by vernonfranklin** [mysql-net/MySqlConnector#1191]
**Software versions**
MySqlConnector version: 2.1.10
Server type (MySQL, MariaDB, Aurora, etc.) and version:  Aurora
.NET version: : .NetCore 6
(Optional) ORM NuGet packages and versions: 

**Describe the bug**

Example Table:

```
CREATE TABLE `AuditLog`
(
    `AuditLogId`   BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `UserId`       BIGINT(20)                   DEFAULT NULL,
    `Log`          TEXT COLLATE utf8mb4_unicode_ci,
    `Context`      TEXT COLLATE utf8mb4_unicode_ci,
    `MachineName`  TEXT COLLATE utf8mb4_unicode_ci,
    `CreateDate`   DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `IsProtected`  BIT(1)              NOT NULL DEFAULT b'0',
    `IsAdminEntry` BIT(1)              NOT NULL DEFAULT b'0',
    PRIMARY KEY (`AuditLogId`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

```

Notice the table ends in BIT(1) data type.  

This causes issue with MySqlBulkCopy.cs:275; AddColumnMapping() is only called 1 time, not twice as expected.  
It causes bad data in the DB because an invalid value for the last entry of 'IsAdminEntry'

My current work around to get it to work correctly, is add a faux column to the end of the DataTable.  Ie: 
> DataTable.Columns.Add("@_");
> DataTable.Rows.Add(_other valid values_, null);
> MySqlBulkCopy.WriteToServerAsync(DataTable);

While not ideal, I have wrapped this behavior so it is not impacting internal usage. 

Thanks! 
-Vernon

**Comment by bgrainger** [comment]
I can't reproduce a problem when using multiple `BIT(1)` columns. Note that `BIT(n)` columns are tested with MySqlBulkCopy here, and are passing in integration tests: https://github.com/mysql-net/MySqlConnector/blob/1920eb8865c1cffd07b7989c88b4885ba0d3622e/tests/SideBySide/DataTypes.cs#L1487-L1489

Are you setting any `ColumnMappings` explicitly?

Please provide a short C# program that demonstrates the issue.

**Comment by vernonfranklin** [comment]
Here is a basic example of what I was doing. 

[Example](https://dotnetfiddle.net/CpAXRp)

Basically:
1. Trying to set up a custom data table based on attributes within my dto
2. Pack my DataTable up until I cross my threshold 
3. Then push it out via bulk copy with my uploader.

Note, I commented out where I had to inject the work around (Ending column) to get things to flush correctly.

Let me know if you have any further questions.

**Comment by bgrainger** [comment]
Your code has a bug.

```csharp
public ValueTask<MySqlBulkCopyResult> UploadAsync(DataTable dataTable)
{
	using var connection = new MySqlConnection(ConnectionString);

	// ...

	return bulkCopy.WriteToServerAsync(dataTable);
}
```

This code disposes the connection while `WriteToServerAsync` is still running, which will cause unpredictable exceptions. This pattern of code is not permitted: https://mysqlconnector.net/troubleshooting/connection-reuse/#dispose-while-in-use

You need to change it to `return await bulkCopy.WriteToServerAsync(dataTable);`.

**Comment by bgrainger** [comment]
If you fix the bugs, `WriteToServerAsync` will return two warnings:

* Data too long for column 'IsProtected' at row 1
* Data too long for column 'IsAdminEntry' at row 1

This is because you're overriding MySqlConnector's default column mappings and supplying your own, which are not loading the `BIT` columns correctly. As [per the documentation](https://dev.mysql.com/doc/refman/8.0/en/load-data.html):

> `BIT` values cannot be loaded directly using binary notation

Instead, you have to use an expression to cast them from a numeric value (written in binary or decimal). This could be done with custom mappings as follows:

```csharp
switch (dataTable.Columns[index].ColumnName)
{
	case "IsProtected":
	case "IsAdminEntry":
		bulkCopy.ColumnMappings.Add(new MySqlBulkCopyColumnMapping(index, $"@tmp{index}", $"{dataTable.Columns[index].ColumnName} = CAST(@tmp{index} AS UNSIGNED)"));
		break;

	default:
		bulkCopy.ColumnMappings.Add(new MySqlBulkCopyColumnMapping(index, dataTable.Columns[index].ColumnName));
		break;
}
```

With these changes, you should be able to load your table with `MySqlBulkCopy`.

(FWIW, I would strongly recommend storing Boolean values as `BOOL` aka `TINYINT(1)` instead of `BIT(1)` as it avoids a lot of this trouble.)

**Comment by vernonfranklin** [comment]
Thanks for the help!
