### ISSUE TITLE
MySqlBulkCopy with byte array

### ISSUE THREAD

**Issue by axhero** [mysql-net/MySqlConnector#1199]
**Software versions**
MySqlConnector version: 2.1.11
Server type (MySQL, MariaDB, Aurora, etc.) and version: MariaDB 10.8.3
.NET version:  6.0.7

**Describe the bug**
Example table:
```
CREATE TABLE IF NOT EXISTS `_test` (
  `key` INT NOT NULL AUTO_INCREMENT
  , `data` MEDIUMBLOB NOT NULL DEFAULT 0

  , PRIMARY KEY `_test_pk` (`key`)
)
ENGINE = InnoDB
;
```

Use MySqlBulkCopy as described in the example:
```
// bulk copy the data
var bulkCopy = new MySqlBulkCopy(connection);
bulkCopy.DestinationTableName = "_test";
var result = await bulkCopy.WriteToServerAsync(dataTable);
```
The DataTable column for table column 'data' is of type byte[] (System.Byte[])
The value is "new byte[] { 0, 1, 2, 3, 4, 5 };"

**Expected behavior**
The value of column 'data' in the table '_test' shall be "00 01 02 03 04 05" (hex)

**Behavior/Issue**
The value of column 'data' in the table '_test' is "30 30 30 31 30 32 30 33 30 34 30 35" (hex)

How can I insert byte arrays (exact hex value) with MySqlBulkCopy to DB correctly?

**Comment by bgrainger** [comment]
MySqlBulkCopy has integration tests that verify it can insert `byte[]` data into a `BLOB` column: https://github.com/mysql-net/MySqlConnector/blob/87879c9c4173c7a89d46b031f64953f96b33823d/tests/SideBySide/BulkLoaderSync.cs#L646-L683

Please provide sample code that reproduces the issue.

**Comment by bgrainger** [comment]
Here's a better test example, perhaps, which verifies the contents of the BLOBs that were inserted: https://github.com/mysql-net/MySqlConnector/blob/87879c9c4173c7a89d46b031f64953f96b33823d/tests/SideBySide/BulkLoaderSync.cs#L918-L943

**Comment by axhero** [comment]
Many thanks for your answer! I checked the second UnitTest in my environment and everything works well.

Then I modified the test to get the issue:
`
            {
                int datacolumn = 5;
                string tablename = "_test2";
                string sql = @$"
DROP TABLE IF EXISTS `{tablename}`
;

CREATE TABLE IF NOT EXISTS `{tablename}` (
  `key` INT NOT NULL AUTO_INCREMENT
  , `date1` DATETIME(6) NOT NULL DEFAULT NOW()
  , `date2` DATETIME(6) NOT NULL DEFAULT NOW()
  , `text1` VARCHAR(255) NOT NULL DEFAULT ''
  , `text2` VARCHAR(255) NOT NULL DEFAULT ''
  , `data` MEDIUMBLOB NOT NULL DEFAULT 0

  , PRIMARY KEY (`key`)
)
ENGINE = InnoDB
;
";

                using (var cmd = new MySqlCommand(sql, connection))
                {
                    cmd.ExecuteNonQuery();
                }

                var bulkCopy = new MySqlBulkCopy(connection)
                {
                    DestinationTableName = tablename,
                    ColumnMappings =
                        {
                            //new(1, "@val", "intvalue = @val + 1"),
                            //new(3, "text"),
                            new(4, "data"),
                        },
                };

                var dataTable = new DataTable()
                {
                    Columns =
                        {
                            new DataColumn("c1", typeof(int)),
                            new DataColumn("c2", typeof(int)),
                            new DataColumn("c3", typeof(string)),
                            new DataColumn("c4", typeof(string)),
                            new DataColumn("c5", typeof(byte[])),
                        },
                    Rows =
                        {
                            new object[] { 1, 100, "a", "A", new byte[] { 0x00, 0x01 } },
                            new object[] { 2, 200, "bb", "BB", new byte[] { 0x02, 0x03 } },
                            new object[] { 3, 300, "ccc", "CCC", new byte[] { 0x04, 0x05 } },
                        }
                };

                var result = bulkCopy.WriteToServer(dataTable);
                Assert.Equal(3, result.RowsInserted);
                Assert.Empty(result.Warnings);

                using var command = new MySqlCommand(@$"select * from `{tablename}`;", connection);
                using var reader = command.ExecuteReader();
                Assert.True(reader.Read());
                Assert.Equal(1, reader.GetValue(0));
                Assert.Equal(new byte[] { 0x00, 0x01 }, reader.GetValue(datacolumn)); // => Test fails!!!
                Assert.True(reader.Read());
                Assert.Equal(2, reader.GetValue(0));
                Assert.Equal(new byte[] { 0x02, 0x03 }, reader.GetValue(datacolumn));
                Assert.True(reader.Read());
                Assert.Equal(3, reader.GetValue(0));
                Assert.Equal(new byte[] { 0x04, 0x05 }, reader.GetValue(datacolumn));
                Assert.False(reader.Read());
            }
`
blob data is modified from 0x00 -> 0x30 0x30, 0x01 -> 0x30 0x31, etc.
But if I remove one or many of the columns date1, date2, text1 or text2 everything works well?!

**Comment by axhero** [comment]
I read in documentation of property 'ColumnMappings' "If one column mapping is specified, then all must be specified."
If I do this it works well.
But how is the column 'key' mapped with autoincrement?

**Comment by bgrainger** [comment]
> The marked test fails.

Your column mapping for the `data` column is incorrect; it should be something like: `new(4, "@data", "data = unhex(@data)"),`. You have to explicitly convert string to binary data for a `BLOB` column.

> "If one column mapping is specified, then all must be specified." ... But how is the column 'key' mapped with autoincrement?

The documentation is probably slightly inaccurate here. Only columns without default values need to be specified; an autoincrement column should be populated correctly by MySQL if no input column is mapped to it.
