### ISSUE TITLE
Application hanging while trying to connect to Aurora with custom domain name.

### ISSUE THREAD

**Issue by bondarchook** [mysql-net/MySqlConnector#1200]
**Software versions**
MySqlConnector version: 2.1.2
Server type (MySQL, MariaDB, Aurora, etc.) and version: Aurora 5.7.12
ORM NuGet packages and versions: Pomelo.EntityFrameworkCore.MySql 6.0.1

**Describe the bug**
Aurora does not support pipelining 
When MySqlConnector connecting it has code to detect that it connecting to Aurora and turn off pipelining.
It checking for Aurora by looking at HostName of the server:

https://github.com/mysql-net/MySqlConnector/blob/87879c9c4173c7a89d46b031f64953f96b33823d/src/MySqlConnector/Core/ServerSession.cs#L478-L481

But if Aurora instance has custom domain (not ".rds.amazonaws.com") then this check will not detect Aurora and will enable pipelining.

As result application hanging indefinitely on connect.

**Exception**
No error. Application just hanging indefinitely.

**Expected behavior**
Different way of detecting Aurora without using HostName.

Problem was introduces when pipelining support was added: https://github.com/mysql-net/MySqlConnector/pull/1089/commits/1b5f4db380c12995d0c1479fef46187c33ce47d1

**Comment by bgrainger** [comment]
Turn it off by adding `;Pipelining = false` to your connection string.

https://mysqlconnector.net/connection-options/#Pipelining

**Comment by bondarchook** [comment]
I don't think you should close this so quick.

Now I know that I can turn off pipelining in connection string. And it is exactly what I did at the end.
But to get to that point I had to debug and carefully read your code to discover concept of pipelining and then understand that Aurora does not support it. And then find code that check for Aurora.
I is quite a journey. And not all developers can or will be willing to make journey like this, to find why stuff does not work.

For a user of this library in this situation application just hanging without showing any errors. And it is very hard to diagnose what is happening. And it is very hard to get to conclusion that this is happening because of pipelining. It is not obvious at all.

Some people will just assume that it just does not work. And will stop using it. And they will have to stop using libraries that build on top of this. And some times there is no alternatives.

So I encourage you to try to actually fix it. I understand it might be hard.
But this will save people a lot of headache and frustration.

Thank you.

**Comment by bgrainger** [comment]
This issue is clearly covered in the documentation I already linked to, and it's also the very first "Troubleshooting" article in the documentation: https://mysqlconnector.net/troubleshooting/aurora-freeze/

Sorry that you had to go to the code to figure this out; maybe this issue itself may even help future people who are googling for it?

> So I encourage you to try to actually fix it. I understand it might be hard.

I would fix it if I could, but it's clearly a bug in Amazon Aurora (that they have fixed in the latest version). MySqlConnector does also work "out of the box" with the default RDS domain.

Open to suggestions for approaches (that I haven't thought of) to auto-detect Aurora and compensate for its bugs.
