### ISSUE TITLE
'PasswordAuthenticationMethod' does not contain a definition for 'Dump' 

### ISSUE THREAD

**Issue by neonleo** [mysql-net/MySqlConnector#1215]
**Software versions**
MySqlConnector version: 2.1.13
Server type (MySQL, MariaDB, Aurora, etc.) and version: MariaDB 8.0
.NET version: Core 6.0
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Following the guide - [Connecting to MySQL Server with SSH from C#](https://mysqlconnector.net/tutorials/connect-ssh/)
But it is error because no Dump() method defined.

**Exception**
'PasswordAuthenticationMethod' does not contain a definition for 'Dump' and no accessible extension method 'Dump' accepting a first argument of type 'PasswordAuthenticationMethod' could be found (are you missing a using directive or an assembly reference?)	

**Code sample**

```csharp
authenticationMethods.Add(new PasswordAuthenticationMethod(sshUserName, sshPassword).Dump());
```

**Comment by bgrainger** [comment]
The call to `.Dump()` is an error in the code (left over from debugging it). Please just delete those seven characters.
