### ISSUE TITLE
Support Custom Data Types

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#123]
Proposal is to allow any type that can cast to/from byte[] to work with MySqlConnector.  Goal is to allow the following code to work in Dapper / Entity Framework:

```
// JsonObject is a custom object that maps to a JSON Type
// GeoPoint is a custom object that maps to a Geometry Type

public class Restaurant
{
    public int Id { get; set; }
    public int Name { get; set; }
    public JsonObject<List<string>> Tags { get; set; }
    public GeoPoint Location { get; set; }
}

// dapper
var food = db.Connection.Query<Restaurant>("select Id = @Id, Name = @Name, Tags = @Tags, Location = @Location");

// entity framework
db.Restaurants.ToList();
```

Reflection will most likely be needed so that `MySqlDataReader.GetFieldValue<T>` can work for arbitrary `T` (that supports implicit conversion).  A change to `GetFieldValue<T>` should try to get the base type without reflection first (like we do now), and fall back on reflection as a last resort.  Code would look something like [this](https://gist.github.com/caleblloyd/1659b365fc86acd774ce7034400b05ce)

**Comment by bgrainger** [comment]
IMO this should be addressed at a higher layer (e.g., in EF Core, Dapper or some other ORM), not with the use of reflection in MySqlConnector itself.
