### ISSUE TITLE
how to set query CharacterSet ?

### ISSUE THREAD

**Issue by winxp2002** [mysql-net/MySqlConnector#1243]
Mysql verson is 5.5
connstring is "server=localhost;User Id=root;password=;Persist Security Info=True;database=gdb0101;allow zero datetime=true;CharacterSet=Latin1"
CharacterSet param is not work well (set Latin1 or  gbk or gb2312)

----

column char_name  datatype is  varbinary  , the column value is an gbk encoding string

----

mysql  character
character_set_client	latin1
character_set_connection	latin1
character_set_database	latin1
character_set_filesystem	binary
character_set_results	latin1
character_set_server	latin1
character_set_system	utf8
character_sets_dir	D:\mysql50\share\charsets\
collation_connection	latin1_swedish_ci
collation_database	latin1_swedish_ci
collation_server	latin1_swedish_ci

----

when i query  like  `select count(*) from pc where char_name='月月酱'` or  `select count(*) from pc where char_name =?char_name` it may return zero 

```
MySqlConnector.MySqlCommand cmd2 = conn.CreateCommand();
cmd2.CommandText = "select count(*) from pc where char_name =?char_name";
var param = new MySqlParameter("char_name", MySqlDbType.Binary);
param.Value = "月月酱";
cmd2.Parameters.Add(param);
var retinfo2 = cmd2.ExecuteScalar();

MySqlConnector.MySqlCommand cmd2 = conn.CreateCommand();
cmd2.CommandText = "select count(*) from pc where char_name =?char_name";
var param = new MySqlParameter("char_name","月月酱");
cmd2.Parameters.Add(param);
var retinfo2 = cmd2.ExecuteScalar();

MySqlConnector.MySqlCommand cmd = conn.CreateCommand();
cmd.CommandText = "select count(*) from pc where char_name='月月酱'";
var retinfo = cmd.ExecuteScalar();
```

 but query it in navicat is right , maybe return count 1
 navicat  client charset is    (Simplified Chinese GB2312)
 I think it client character problem， whether a way to change the client Character like in navicat

**Comment by bgrainger** [comment]
MySqlConnector only supports UTF-8 (`utf8mb3` or `utf8mb4`) as the client character set.

Can you create a mysqldump file and C# program that reproduces the problem?

Note that MySQL 5.5 has been end-of-life for four years: https://endoflife.date/mysql. It seems quite possible that this could be a server-side charset conversion bug. Are you able to update to a supported version of MySQL?

**Comment by winxp2002** [comment]
I try it use MySql.Data.MySqlClient , It not found this problem  ,MySql.Data.MySqlClient  CharacterSet param supports gbk or gb2312 and any other charset  ，I don't know whether this is a bug or whether it can provide such features，utf8mb3 or utf8mb4 is not enough in my work

**Comment by bgrainger** [comment]
I still need a repro to show that this is a bug in MySqlConnector and not in the other libraries you've been using. It's quite possible that MySql.Data is causing data corruption on insert, then undoing the data corruption when it reads the values out. That is, it might be storing [Mojibake](https://en.wikipedia.org/wiki/Mojibake) in the database, but also stripping it out when it reads the values.

Here's a test that shows that MySqlConnector can read values in a `gb2312` column without having to set the Character Set option in the connection string.

```csharp
[Fact]
public void Gb2312()
{
	using var connection = new MySqlConnection(AppConfig.ConnectionString); // NOTE: No CharSet option specified
	connection.Open();

	using var command = new MySqlCommand("DROP TABLE IF EXISTS gb2312; CREATE TABLE gb2312 (id int, value VARCHAR(100) CHAR SET gb2312)", connection);
	command.ExecuteNonQuery();

	command.CommandText = "INSERT INTO gb2312 VALUES(1, 0xB9FABCD2B1EAD7BC)";
	command.ExecuteNonQuery();
		
	command.CommandText = "SELECT value from gb2312 order by id";
	using var reader = command.ExecuteReader();
	Assert.True(reader.Read());

	Assert.Equal("国家标准", reader.GetString(0));
}
```

Can you provide a test that shows that MySqlConnector isn't storing or reading values correctly?

**Comment by winxp2002** [comment]
column type is not varchar , it 's  birary
```
[Fact]
        public void Gb2312()
        {
            using var connection = new MySqlConnector.MySqlConnection(Constring); // NOTE: No CharSet option specified
            connection.Open();

            using var command = new MySqlConnector.MySqlCommand("DROP TABLE IF EXISTS gb2312; CREATE TABLE gb2312 (id int, value  varbinary(16))", connection);
            command.ExecuteNonQuery();

            command.CommandText = "INSERT INTO gb2312 VALUES(1, 0xB9FABCD2B1EAD7BC)";
            command.ExecuteNonQuery();

            command.CommandText = "SELECT count(*) as cnt from gb2312 where value = '国家标准'";
            using var reader = command.ExecuteReader();
            Assert.True(reader.Read());

            using MySql.Data.MySqlClient.MySqlConnection connectionMysqldata = new MySql.Data.MySqlClient.MySqlConnection(Constring);
            connectionMysqldata.Open();
            MySql.Data.MySqlClient.MySqlCommand commandMysqldata = connectionMysqldata.CreateCommand();
            commandMysqldata.CommandText = "SELECT count(*) as cnt from gb2312 where value = '国家标准'";
            using var reader2 = commandMysqldata.ExecuteReader();

            Assert.True(reader2.Read());

            Assert.Equal(reader.GetInt32("cnt"), reader2.GetInt32("cnt"));
        }
```

**Comment by bgrainger** [comment]
Thank you for the example; I now see what you're saying.

You're making a feature request that MySqlConnector should support matching Unicode strings against `BINARY` columns by performing a particular character set conversion (from C# `string` to binary) when sending a query, and that this should be controlled by a connection string option.

This is not currently supported, but I can think of a few workarounds:

1. Store text in `VARCHAR` or `TEXT` columns, not `BINARY`. This will allow MySQL Server to perform the appropriate charset conversion.
2. Perform a charset conversion explicitly in your query: `SELECT count(*) as cnt from gb2312 where value = CONVERT('国家标准' USING gb2312)`

**Comment by winxp2002** [comment]
Expect this feature to support，I hope it can appear in the next version
This design is very common in game design, mainly because the character encoding is uncertain, so the data stored in the database can be designed regardless of language family, similar to multilingual, depending on the client encoding

**Comment by bgrainger** [comment]
This change is not planned. Character set conversions are outside the scope of MySqlConnector.

Two workarounds are listed earlier, or one could create a helper method that converts a `string` to a `byte[]` (with the appropriate conversion) when setting `MySqlParameter.Value`.
