### ISSUE TITLE
[Bug] TreatTinyAsBoolean will soon become no more relevant in current version of MySqlConnector

### ISSUE THREAD

**Issue by adriancs2** [mysql-net/MySqlConnector#1255]
**Software versions**
MySqlConnector version: **2.2.2**
Server type (MySQL, MariaDB, Aurora, etc.) and version: **MySQL 8.0.31**
.NET version: .**NET Framework 4.8**
(Optional) ORM NuGet packages and versions: **MySqlExpress v1.6**

**Describe the bug**
The connection string option of TreatTinyAsBoolean will convert MySQL column data type of TINYINT(1) into Boolean in C#.
But however, if I set MySQL table column datatype as TINYINT(1), MySQL returns this warning message:
```
Warning: Integer display width is deprecated and will be removed in a future release.
```
Which means, setting TINYINT to whatever display number such "TINYINT(1)" or "TINYINT(2)" or "TINYINT(3)" will all be converted into TINYINT in future release of MySQL, regardless how many "display int number" set.

Therefore, I apply the advice of this warning and set the datatype to TINYINT.

But, here's the problem, MySqlConnector converts TINYINT into byte (ignoring TreatTinyAsBoolean=true).

**Exception**
no exception raise.

**Sample Sql Table**
```sql
CREATE TABLE `mytable` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(45) DEFAULT NULL,
  `name` varchar(300) DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `is_default` tinyint DEFAULT NULL,
  PRIMARY KEY (`id`)
);
```

**Expected behavior**
TreatTinyAsBoolean=true, should converts TINYINT into boolean, regardless the assigned displayed int number.
Such as, all the following:
```
TINYINT
TINYINT(1)
TINYINT(2)
TINYINT(3)
```
should converts data into `Boolean` in C#

**Comment by bgrainger** [comment]
> Which means, setting TINYINT to whatever display number such "TINYINT(1)" or "TINYINT(2)" or "TINYINT(3)" will all be converted into TINYINT in future release of MySQL, regardless how many "display int number" set.

It's not actually known that this will happen.

Per https://dev.mysql.com/worklog/task/?id=13127:

> F-2: Creating a table with a TINYINT, SMALLINT, MEDIUMINT, INT or BIGINT column that has an explicit display width shall give a warning.

It just gives a warning, which you can ignore. I haven't seen a worklog item to remove width from the InnoDB engine or the MySQL protocol.

Finally, from https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html:

> `BOOL`, `BOOLEAN`

>
> These types are synonyms for `TINYINT(1)`. A value of zero is considered false. Nonzero values are considered true.

You can keep using `BOOL` in your SQL even though `TINYINT(1)` is deprecated. The `TreatTinyAsBoolean` option (which has a very poor name, but is named that way for backwards compatibility with MySql.Data) will work as expected with it.

Thus `BOOL` and `TINYINT` produce different column types in MySQL 8.0 and MySqlConnector correctly converts them to `bool` and `byte` respectively.

> TreatTinyAsBoolean=true, should converts TINYINT into boolean, regardless the assigned displayed int number.

This would be an significant breaking change for many existing database users, and won't be done.

**Comment by bgrainger** [comment]
> Therefore, I apply the advice of this warning and set the datatype to TINYINT.

Use `BOOL` instead.
