### ISSUE TITLE
GetSchema should only return information for the current database

### ISSUE THREAD

**Issue by Elrinth** [mysql-net/MySqlConnector#1257]
**Software versions**
MySqlConnector version:
v4.0.30319

Server type (MySQL, MariaDB, Aurora, etc.) and version: 
MySQL 8.0.31-0ubuntu0.20.04.1
.NET version: 
.NET Framework 4.7.2

(Optional) ORM NuGet packages and versions: 
?

**Describe the bug**
GetSchema returns columns from ALL databases on the whole server which has the table instead of the specific database. So I'm getting repeat columns of 12*6 = 72. So I'm getting the same 12 columns per database... It doesn't restrict itself to only the database it's supposed to be connected to. Why?

**Exception**
No exception, just unwanted behaviour. Well actually I get an exception, but that's because I have repeat columns from the database.

**Code sample**
1. have user which has access to all databases on the mysql server.
2. have same table in a bunch of databases (6 in my case)
3. MysqlConnector will return schema from all databases the user can see combined rather than what Mysql.Data.Client would do.

```csharp
/* A concise code sample to reproduce the bug */
DataTable schema = scope.Connection.GetSchema("COLUMNS", restrictions);
```

**Expected behavior**
I expect to only get the table columns of the database I'm connected to, not the whole database.

**Additional context**
Make it work like the normal Mysql.Data.Client please.

**Comment by bgrainger** [comment]
MySql.Data does this by explicitly adding a restriction for the current database: https://github.com/mysql/mysql-connector-net/blob/3ebd5c49432a7bcff96438a7f9b193576acda30a/MySQL.Data/src/SchemaProvider.cs#L1037-L1047

The [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.getschema?view=net-7.0) says:

> If a restriction value is not passed in, the default values are used for that restriction.

Which leaves it unclear if `GetSchema` should be implicitly "scoped" to the current connection's current database or not.

For now, you can use the `restrictions` parameter as a workaround:

```csharp
connection.GetSchema("columns", new[] { null, connection.Database });
```
