### ISSUE TITLE
Make AOT and trimming friendly

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#1265]
https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-8.0/plan.md#aot-and-trimming-for-adonet

> We will also work with the authors of other ADO.NET data providers to help make them AOT and trimming friendly.

See https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming for helpful information.

**Comment by Soundman32** [comment]
This is over 15 months old now.  Is trimming going to be supported any time soon?

**Comment by bgrainger** [comment]
Fixed in [2.4.0](https://github.com/mysql-net/MySqlConnector/releases/tag/2.4.0).
