### ISSUE TITLE
Support MySqlParameterCollection.AddWithValue

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#127]
Oracle's upcoming 7.x Connector/NET release adds a public [AddWithValue](https://github.com/mysql/mysql-connector-net/blob/7.0/Source/MySql.Data/parameter_collection.cs#L104) method to `MySqlParameterCollection`

MySqlConnector's `MySqlParameterCollection` should add this method as well in order to maintain BC.  Also, it seems like a convenient method to have.

**Comment by bgrainger** [comment]
This public API appears to be [in 6.9](https://github.com/mysql/mysql-connector-net/blob/6.9/Source/MySql.Data/parameter_collection.cs#L104) as well, so even more reason to add it.

**Comment by bgrainger** [comment]
Fixed in [0.16.0](https://www.nuget.org/packages/MySqlConnector/0.16.0).
