### ISSUE TITLE
Add password rotation support to MySqlDataSource

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#1270]
This would be similar to the equivalent Npgsql feature: https://github.com/npgsql/npgsql/issues/4497.

At a minimum, `MySqlDataSource` can expose a writable `Password` property, which could be passed to `MySqlConnection` via `ProvidePasswordCallback`.

**Comment by jkuek** [comment]
@bgrainger Documentation on how to use this and MySqlDataSource is a bit sparse, but if my understanding is correct then UsePeriodicPasswordProvider isn't suitable for the AWS RDS multi-user rotation strategy (https://docs.aws.amazon.com/secretsmanager/latest/userguide/getting-started.html#rotation-strategy)

Given the username is also rotating (between user and user_clone), then I would need to detect this externally and update the data source.

**Comment by bgrainger** [comment]
Correct, this wouldn't work for multi-user rotation; you would need multiple connection strings (which would create multiple connection pools). 

I don't know much about AWS but I think a better approach might be [IAM tokens](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html) rather than multi-user rotation, if you can. This would be compatible with `UsePeriodicPasswordProvider`, since the username isn't changing. (And is the use case that `UsePeriodicPasswordProvider` was designed for.)

**Comment by jkuek** [comment]
Thanks for the response. The reason I previously discarded IAM auth was due to its limits on new connections/sec https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.html#UsingWithRDS.IAMDBAuth.Limitations

Possibly this could be mitigated by increasing the minimum pool size.

**Comment by bgrainger** [comment]
Yes, hopefully using a large enough pool (perhaps even with `Minimum Pool Size` if you needed to "pre seed" it) could avoid the application creating over 200 new database connections per second.
