### ISSUE TITLE
IsolationLevel.ReadUncommitted not working

### ISSUE THREAD

**Issue by sethconyers** [mysql-net/MySqlConnector#1284]
**Software versions**
MySqlConnector version: 2.1.13.0
Server type (MySQL, MariaDB, Aurora, etc.) and version: Windows 10 Pro
.NET version: 6.0

**Describe the bug**
I'm using IsolationLevel.ReadUncommitted because I need to run this code against a busy database in production.  Despite this, I still get "MySqlConnector.MySqlException: 'Deadlock found when trying to get lock; try restarting transaction'"

**Exception**
MySqlConnector.MySqlException: 'Deadlock found when trying to get lock; try restarting transaction'

   at MySqlConnector.Core.ResultSet.<ReadResultSetHeaderAsync>d__2.MoveNext()
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken)
   at MySqlConnector.MySqlDataReader.<CreateAsync>d__111.MoveNext()
   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext()
   at MySqlConnector.MySqlCommand.<ExecuteNonQueryAsync>d__78.MoveNext()
   at MySqlConnector.MySqlCommand.ExecuteNonQuery()
   at LMSDataExport.Program.Main(String[] args) in C:\Users\sconyers\source\repos\LMSDataExport\LMSDataExport\Program.cs:line 104

**Code sample**

```csharp
string connStr = "server=mysqlserver;user=user;database=db;password=password;Treat Tiny As Boolean=false;Connect Timeout=600;DefaultCommandTimeout=600;Interactive=true;IgnoreCommandTransaction=true;";

string sql;
MySqlCommand cmd;

using var conn = new MySqlConnection(connStr);
conn.Open();
sql = "CALL SetupForExportUsers();";
cmd = new MySqlCommand(sql, conn);
using var transaction = conn.BeginTransaction(IsolationLevel.ReadUncommitted);
cmd.Transaction = transaction;
cmd.ExecuteNonQuery();
transaction.CommitAsync();
transaction.Dispose();

using var conn2 = new MySqlConnection(connStr);
conn2.Open();
sql = "CALL UpdateUserExport();";
cmd = new MySqlCommand(sql, conn2);
using var transaction4 = conn2.BeginTransaction(IsolationLevel.ReadUncommitted);
cmd.Transaction = transaction4;

cmd.ExecuteNonQuery();
transaction4.CommitAsync();
```

**Expected behavior**
There are a few more sql statements but all set up exactly like this.  I get deadlock errors in either the second or third sql statement every time I run the code unless it's late at night.  This seems to indicate that ReadUncommitted isn't working.  Also, running this code with a try/catch (MySqlConnector.MySqlException) or even with just a generic exception still treats the exception as unhandled.

**Additional context**

**Comment by bgrainger** [comment]
Is there documentation that states that ReadUncommitted will prevent deadlocks?

According to https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks.html:

> The possibility of deadlocks is not affected by the isolation level, because the isolation level changes the behavior of read operations, while deadlocks occur because of write operations.

Also, from https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks-handling.html:

> Normally, you must write your applications so that they are always prepared to re-issue a transaction if it gets rolled back because of a deadlock.

Nothing on that page implies that `READ UNCOMMITTED` will prevent deadlocks.

Is there any evidence that MySqlConnector is not setting the isolation level correctly? If not, then this isn't a MySqlConnector issue, it's a MySQL issue and you should use the techniques on the page above to identify and minimise deadlocks.

**Comment by sethconyers** [comment]
Can you confirm I'm doing the above correctly at least?  What you say makes sense but I don't understand why writing to brand new tables that only exist for this code would cause deadlocks.  Do I somehow need to make sure the previous connections/queries are done before moving on?  I would think the procedural nature of this code already does that but I guess not?

**Comment by sethconyers** [comment]
After more investigation, this was due to our Galera cluster choosing my queries as deadlock victims every time.  I'll close this bug.
