### ISSUE TITLE
Support System.Transactions

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#13]
On desktop (full) .NET, implement support for auto-enlisting in ambient transactions. This will enable .NET 4.5 code that uses `TransactionScope` to be ported to this connector without having to rewrite it. (This connector will throw when #12 is implemented, even if the underlying platform could support `System.Transactions`.)

See related issues for EF: aspnet/EntityFramework#1530, aspnet/EntityFramework#5595.

Note that `System.Transactions` isn't supported in .NET Core: dotnet/corefx#2949

**Comment by bgrainger** [comment]
It appears that `System.Transactions` is coming to .NET Core dotnet/corefx#10089 so implementing this will be useful for all platforms.

**Comment by bgrainger** [comment]
MySQL [XA Transactions](https://dev.mysql.com/doc/refman/5.7/en/xa.html) may be a good way to implement `TransactionScope`.

**Comment by bgrainger** [comment]
Implemented in [0.18.0](http://www.nuget.org/packages/MySqlConnector/0.18.0).

**Comment by sidhoda** [comment]
@bgrainger is there still the possibility this could be implemented without XA transactions, like MySql.Data? Some of the restrictions with XA make it look less attractive option, particularly if running MySQL prior to 5.7.7 and using replication: https://dev.mysql.com/doc/refman/5.7/en/xa-restrictions.html

**Comment by bgrainger** [comment]
It's possible; I've created #254 to track it. If this is affecting you, could you please add a comment there to describe the specific issues you're running into? (MySQL 5.7.9 was the first GA release, so I'm not extremely concerned about limitations/errors in 5.7.x versions prior to that.)

I'm open to receiving a PR that implements a non-XA implementation of `IEnlistmentNotification` in order to support `TransactionScope` without using XA transactions.

An alternative of course is to explicitly use `BeginTransaction`/`Commit` in client code that doesn't want distributed transactions (which is a core feature of `TransactionScope` and part of the point of using it in the first place).
