### ISSUE TITLE
Implement Keepalive Connection String Options

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#132]
`Keep Alive, Keepalive` (default: 0) For TCP connections, idle connection time measured in seconds, before the first keepalive packet is sent. A value of 0 indicates that keepalive is not used.

Should call `socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, value)` on TCP Socket if `value > 0`

**Comment by caleblloyd** [comment]
**Respecting System-Wide TCP Keepalive**

Operating Systems (both Windoows and Linux) have default TCP Keepalive values, but TCP Keepalive must be enabled on the socket in order for Keepalive to be used. ([Windows Reference](https://blogs.technet.microsoft.com/nettracer/2010/06/03/things-that-you-may-want-to-know-about-tcp-keepalives/), [Linux Reference](http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/#setsockopt))

This setting is achieved by calling `socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, 1)`

Should we always enable TCP Keepalive on the Socket?  Or only if the `Keepalive` connection string parameter is set?  I'm partial to always enabling it due to the nature of pooled connections potentially being idle.

**Overriding System-Wide settings with Per-Socket settings**

There are 3 settings that can be overridden, outlined [here](http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html).  Example:

	tcp_keepalive_time = 7200
	tcp_keepalive_intvl = 75
	tcp_keepalive_probes = 9

> The first two parameters are expressed in seconds, and the last is the pure number. This means that the keepalive routines wait for two hours (7200 secs) before sending the first keepalive probe, and then resend it every 75 seconds. If no ACK response is received for nine consecutive times, the connection is marked as broken.

Overriding the system-wide parameters on Windows is described in [this stackoverflow post](http://stackoverflow.com/questions/169170/what-is-the-best-way-to-do-keep-alive-socket-checking-in-net)

Overriding the system-wide parameters on Linux needs to be done with socket options, described [here](http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/#setsockopt).  I will have to dig into .NET's socket option ENUMs and see if these are defined

**Comment by caleblloyd** [comment]
I can't get the socket-level options to work on Linux or OSX, the proper Socket Options are not available in .NET Core. Opened upstream:

https://github.com/dotnet/corefx/issues/14237

**Comment by bgrainger** [comment]
Shipped in [0.8.0](https://www.nuget.org/packages/MySqlConnector/0.8.0).
