### ISSUE TITLE
Is the data type mapping BIT and TINYINT (1) to C# correct?

### ISSUE THREAD

**Issue by tsaiggo** [mysql-net/MySqlConnector#1320]
When I used MySqlConnector to convert data from MySQL data type to C # data type, I found the following two issues:

1. BIT will be mapped as UInt64, but in BIT can only store 0 or 1 in MySQL.
2. TINYINT (1) will be mapped as Boolean, but the value range of TINYINT (1) is -128-127. If we want to use MySqlConnector to read data from Table A and write it to Table B. In Table A, there is a column of type TINYINT (1) that stores a value of 100. We can only obtain Boolean by reading data through MySqlConnector, and then write it to Table B, is the data written to Table B 1 or 100 at this time?

I don't understand if this is an issue or by design. Should BIT be mapped to Boolean and TINYINT (1) to INT be more reasonable?

**Comment by bgrainger** [comment]
### BIT

> BIT will be mapped as UInt64, but in BIT can only store 0 or 1 in MySQL.

That isn't correct. From [Bit-Value Type - BIT](https://dev.mysql.com/doc/refman/8.0/en/bit-type.html):

> The `BIT` data type is used to store bit values. A type of `BIT(M)` enables storage of M-bit values. `M` can range from 1 to 64.

### TINYINT 

> TINYINT (1) will be mapped as Boolean, but the value range of TINYINT (1) is -128-127

That is correct, but if you want a `TINYINT` column (with the full range of values), use `TINYINT` as the column data type, not `TINYINT(1)`. The (now deprecated) width specifier (`(1)`) is used as a hint that this type is being used as an alias for `BOOL`. From [Numeric Data Type Syntax](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html):

> `BOOL`, `BOOLEAN`
> 
> These types are synonyms for `TINYINT(1)`. A value of zero is considered false. Nonzero values are considered true

To stop this mapping, either:

1. Update your database schema to use `TINYINT` as the column type
2. Use `Treat Tiny As Boolean = False` in your connection string; see https://mysqlconnector.net/connection-options/#TreatTinyAsBoolean.

**Comment by tsaiggo** [comment]
Thanks!!!
