### ISSUE TITLE
Add ability to see the initiator of `COMMIT` in slow query log

### ISSUE THREAD

**Issue by eranikid** [mysql-net/MySqlConnector#1333]
**Is your feature request related to a problem? Please describe.**
Seeing lots of plain `COMMIT` entries in MySQL slow query log isn't helpful, as it does not contribute to identifying the slow transaction.

**Describe the solution you'd like**
It would be convenient to be able to specify some user-provided transaction name/tag/type as an argument in either `BeginTransaction` or `Commit` method, which would later be prepended to a `COMMIT` query, making it possible to correlate slow query entries to transactions.

@bgrainger you might remember leaving [this](https://github.com/dodopizza/MySqlConnector/pull/4#issuecomment-1356374886) comment in a PR in our fork of MySqlConnector. That PR contains exactly those changes - it prepends `/* <transaction_tag> */` before `COMMIT`, so slow query logs could help identify the slow-committing transaction.

We were wondering if similar functionality could be implemented in an upstream, which would save us from maintaining a fork

**Comment by bgrainger** [comment]
Probably the "right" place to analyze this data is in a proper distributed tracing system. For example, Application Insights produces a timeline view like the following (cropped to mask proprietary data):

![image](https://github.com/mysql-net/MySqlConnector/assets/188129/3d23bcaf-8935-4e18-8cd4-c0f9b6883ced)

One could probably also bypass MySqlConnector and just execute `BEGIN` and `/* transaction tag */ COMMIT` statements explicitly as commands, to have full control over the SQL that's sent to the server.

**Comment by eranikid** [comment]
I think you are right and the subject of this issue is way too specific to be addressed in MySqlConnector repo. I'll see this issue closed, thanks!
