### ISSUE TITLE
EscapeString should also escape backtick

### ISSUE THREAD

**Issue by LennardF1989** [mysql-net/MySqlConnector#1363]
Currently, it does not, making it unreliable to prevent SQL injection in some situations. 

For example:
```
var name = "a`; DROP SCHEMA `test";
var query = $"CREATE SCHEMA `{name}`;"
```

EDIT: You ~~can~~ can't use prepared statements in this situation.

EDIT 2: I just realized that MySQL doesn't allow you to escape this character when it's used inside a string literal...

**Comment by bgrainger** [comment]
It sounds like you're discussing identifiers, not string literals.

Please read the documentation here: https://dev.mysql.com/doc/refman/8.0/en/identifiers.html

The summary is that identifiers can be quoted with a backtick `` ` `` and that backtick can be escaped by doubling it.

You probably want a method like:

```csharp
public static string QuoteIdentifier(string id) => $"`{id.Replace("`", "``")}`";
```

**Comment by bgrainger** [comment]
Also, you should almost never use `MySqlHelper.EscapeString`: it indicates you're using string concatenation to build queries and there is a high risk of SQL injection. Prefer to use `MySqlParameter`; its implementation is completely safe and highly optimised.

**Comment by LennardF1989** [comment]
Thanks, I could not find anything about escaping the backticks. I ended up making an extended version of the EscapeString to optionally also escape backticks, since it's a more optimal implementation than just doing `.Replace`.

I'm aware prepared statements are always better, but MySQL won't accept them for DDL instructions (eg. CREATE SCHEMA). It's unlikely someone can actually manage to get SQL injection in, but I wanted to lower the chances ever further. Escaping the backticks as you've shown, will result in a table with the name `a`; DROP SCHEMA `test` in the above example, which is exactly what I wanted :)

**Comment by bgrainger** [comment]
Correct: `MySqlParameter` cannot be used for identifiers (schema or table names, etc.); in that case you do have to build SQL with concatenation and appropriate escaping.
