### ISSUE TITLE
Support for Multiple Queries in a Statement?

### ISSUE THREAD

**Issue by jeffreywstevens** [mysql-net/MySqlConnector#1374]
Maybe I am looking in the wrong place, but so far, I can't locate how to do this with this connect. I do this all the time with SQL Server, Dapper, and C#.

I want to execute multiple commands in a query separated by semicolons.  It works in MySQLWorkbench but throws a syntax error in the connector using c#.

Is there a way to do this? A connect string argument?  I see references to CLIENT_MULTI_STATEMENTS. Is there an example somewhere?

**Comment by bgrainger** [comment]
It should "just work". For an example, see https://github.com/mysql-net/MySqlConnector/blob/849ad4667241c415044fed9966e5e3cf03f095a7/tests/IntegrationTests/QueryTests.cs#L27-L42

Can you give the full exception message and sample code that reproduces the problem?

**Comment by jeffreywstevens** [comment]
My statement is something simple similar to this:
 DECLARE @ID INT;SELECT ID INTO @ID FROM TABLE WHERE STATUS='READY';UPDATE TABLE SET STATUS = 'PENDING' WHERE ID = @ID;SELECT @ID

I am using Dapper too. Maybe I need to look there instead or remove it to troubleshoot.

**Comment by bgrainger** [comment]
Did you put `Allow User Variables = true;` in your connection string? That's required to use variables with MySQL.

**Comment by jeffreywstevens** [comment]
I have that setting. The error is a syntax error points to the status delimiter ending too soon.  The where clause is: status in ('sendState1', 'sendState2') and the error displays syntax error: status in ('sen').  Looks weird.

If I remove the variables, etc., the statement executes fine. Works fine in MySQL Workbench. 

Is it a delimiter problem?

**Comment by bgrainger** [comment]
> Is it a delimiter problem?

I can't tell, because you haven't pasted a small code sample that reproduces the problem. The where clause you just gave ("status in ('sendState1', 'sendState2')") doesn't match the previous SQL you posted ("WHERE STATUS='READY'"). This makes me suspect that these examples are heavily edited and don't reflect what your program is actually doing.

**Comment by jeffreywstevens** [comment]
You are correct. I simplified the original. It was an IN statement. I appreciate your help. I will do some more troubleshooting and report if I solve it. I probably posted too soon and need to just get to work solving this.
