### ISSUE TITLE
Wrong port connection given on your website

### ISSUE THREAD

**Issue by Savageboitim13** [mysql-net/MySqlConnector#1377]
**Software versions**
MySqlConnector version:
2.2.7

Server type and version:
mariadb Ver 15.1 Distrib 10.11.3-MariaDB, for debian-linux-gnu (x86_64)

.NET version:
4.0 (actually 4.8.09032)

**Describe the bug**
It's not really a bug, but I found out that on your website https://mysqlconnector.net/tutorials/connect-ssh/ under prerequisites, you `return (sshClient, **forwardedPort.BoundPort**);` and use it for the DB CSB.
Actually it should be `return (sshClient, **forwardedPort.Port**);`, because you connect not to your local port, no?

**Code sample**

```csharp
public static (SshClient, uint) ConnectSSH() {
    using SshClient sshClient = new(connectionInfo);
    sshClient.Connect();

    // Port forwarding to MariaDB server
    ForwardedPortLocal portForwarding = new("127.0.0.1", dbServer, dbPort));
    sshClient.AddForwardedPort(portForwarding);
    portForwarding.Start();

    return (sshClient, portForwarding.Port);
}

public static MySqlConnection ConnectDB() {
    var (sshClient, localPort) = ConnectSSH();
    using(sshClient) {
        MySqlConnectionStringBuilder csb = new MySqlConnectionStringBuilder {
            Server = "127.0.0.1",
            Port = localPort,
            UserID = dbUser,
            Password = dbPass,
            Database = dbName,
        };

        using MySqlConnection connection = new(csb.ConnectionString);
        connection.Open();

        return connection;
    }
}
```

**PS**
I guess, this is the wrong place to put such "reports".
Where should I actually have done that?

**Comment by bgrainger** [comment]
`BoundPort` is correct: https://stackoverflow.com/a/57989461/23633. This is the port that was bound to locally, which will forward traffic to the remote server.

**Comment by bgrainger** [comment]
If you're connecting to port 3306 on 127.0.0.1, then you're just connecting to the MySQL Server directly, right? In that case, I don't see how SSH port forwarding is relevant.
