### ISSUE TITLE
2.2.7: Expected to read 890 payload bytes but only received 262

### ISSUE THREAD

**Issue by tsaiggo** [mysql-net/MySqlConnector#1380]
**Software versions**
MySqlConnector version: v2.1.6, v2.2.7
Server type (MySQL, MariaDB, Aurora, etc.) and version: 5.7

When there are more than 110 fields in one MySQL table, the following error will be encountered when reading data using the SDK:
System.IO.EndOfStreamException,Message=Expected to read 890 payload bytes but only received 262

**Comment by bgrainger** [comment]
Please provide a code sample that reproduces the problem. I was able to create and query a table with 200 columns without error using the following code:

```csharp
using var connection = new MySqlConnection("server=localhost;user=root;password=pass;database=mysqltest");
connection.Open();

const int fieldCount = 200;
using var cmd = new MySqlCommand($"""
	drop table if exists bug1380;
	create table bug1380({string.Join(",", Enumerable.Range(0, fieldCount).Select(x => $"field{x} int"))});
	insert into bug1380 values({string.Join(",", Enumerable.Range(0, fieldCount).Select(x => $"{x}"))});
	""", connection);
cmd.ExecuteNonQuery();

cmd.CommandText = "select * from bug1380;";
using var reader = cmd.ExecuteReader();
while (reader.Read())
{
	var values = new object[reader.FieldCount];
	reader.GetValues(values);
	values.Dump();
}
```
