### ISSUE TITLE
The file or assembly "System.Buffers" was not found

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#1381]
the log4net Logfile says this:

```
16:54:08,152 [MySqlConnector.ConnectionPool] INFO - Pool1 creating new connection pool for ConnectionString: Server=XXX;User ID=XXX;Database=XXX;SSL Mode=Required;Allow Zero DateTime=True;Character Set=utf8;Convert Zero DateTime=True;Keep Alive=10;Persist Security Info=True
16:54:08,187 [MySqlConnector.ConnectionPool] DEBUG - Pool1 no pooled session available; created new Session1.1
16:54:08,315 [MySqlConnector.ServerSession] DEBUG - Session1.1 made connection; ServerVersion=5.5.5-10.10.6-MariaDB-1:10.10.6+maria~ubu2204; ConnectionId=1043224; Compression=False; Attributes=True; DeprecateEof=True; Ssl=True; SessionTrack=True; Pipelining=True; QueryAttributes=False
16:54:08,350 [MySqlConnector.ServerSession] WARN - Session1.1 failed negotiating TLS; falling back to TLS 1.1
System.IO.FileLoadException: Die Datei oder Assembly "System.Buffers, Version=4.5.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
Dateiname: "System.Buffers, Version=4.5.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" ---> System.IO.FileLoadException: Die Datei oder Assembly "System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
Dateiname: "System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"

=== Zustandsinformationen vor Bindung ===
LOG: DisplayName = System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/DevOps/ESProject/991/BIN/
LOG: Ursprünglicher PrivatePath = NULL
Aufruf von Assembly : MySqlConnector, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92.
===
LOG: Diese Bindung startet im default-Load-Kontext.
LOG: Die Anwendungskonfigurationsdatei wird verwendet: C:\DevOps\ESProject\991\BIN\ESProfairsSyncService.exe.Config
LOG: Die Hostkonfigurationsdatei wird verwendet: 
LOG: Die Computerkonfigurationsdatei von C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config wird verwendet.
LOG: In der Anwendungskonfigurationsdatei wurde eine Umleitung gefunden. 4.0.3.0 wird nach 4.5.1.0 umgeleitet.
LOG: Verweis nach der Richtlinie: System.Buffers, Version=4.5.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
LOG: Download von neuem URL file:///C:/DevOps/ESProject/991/BIN/System.Buffers.DLL.
WRN: Der Vergleich des Assemblynamens führte zum Konflikt: Nebenversion.
ERR: Das Setup der Assembly konnte nicht abgeschlossen werden (hr = 0x80131040). Die Suche wurde beendet.

   bei MySqlConnector.Protocol.Serialization.ByteBufferWriter..ctor(Int32 capacity)
   bei MySqlConnector.Protocol.Payloads.HandshakeResponse41Payload.CreateCapabilitiesPayload(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, Boolean useCompression, CharacterSet characterSet, ProtocolCapabilities additionalCapabilities) in /_/src/MySqlConnector/Protocol/Payloads/HandshakeResponse41Payload.cs:Zeile 10.
   bei MySqlConnector.Protocol.Payloads.HandshakeResponse41Payload.CreateWithSsl(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, Boolean useCompression, CharacterSet characterSet) in /_/src/MySqlConnector/Protocol/Payloads/HandshakeResponse41Payload.cs:Zeile 52.
   bei MySqlConnector.Core.ServerSession.<InitSslAsync>d__102.MoveNext() in /_/src/MySqlConnector/Core/ServerSession.cs:Zeile 1509.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei MySqlConnector.Core.ServerSession.<ConnectAsync>d__83.MoveNext() in /_/src/MySqlConnector/Core/ServerSession.cs:Zeile 541.
16:54:08,374 [MySqlConnector.ServerSession] DEBUG - Session1.1 closing stream/socket
```

I referenced the System.Buffers Nuget package in the .exe and the .dll, but the message remains the same.

_Originally posted by @ThomasX12 in https://github.com/mysql-net/MySqlConnector/issues/1376#issuecomment-1777417946_

**Comment by bgrainger** [comment]
This sounds like a simple assembly binding redirect issue in `C:\DevOps\ESProject\991\BIN\ESProfairsSyncService.exe.Config`. 

https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by ThomasX12** [comment]
I have added the bindingRedirects to the exe.config file, but the error remains the same.

<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.5.0.0" newVersion="4.5.1.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.2" newVersion="4.0.1.2" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

I have tried a different approach by using the AssemblyResolve Event 

static Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
        {
            AssemblyName assemblyName = new AssemblyName(args.Name);
            if (assemblyName.Name == "System.Runtime.CompilerServices.Unsafe")
            {
                return typeof(System.Runtime.CompilerServices.Unsafe).Assembly;
            }
            else if (assemblyName.Name == "System.Buffers")
            {
                return typeof(System.Buffers.BuffersExtensions).Assembly;
            }
            else if (assemblyName.Name == "System.Memory")
            {
                return typeof(System.MemoryExtensions).Assembly;
            }
            else if (assemblyName.Name == "MySqlConnector")
            {
                return typeof(MySqlConnector.MySqlConnection).Assembly;
            }
            return null;
            
        }

witch leads to a different error message: 

Der Typ "System.Buffers.ArrayPool`1" in der Assembly "System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" konnte nicht geladen werden.

   bei MySqlConnector.Protocol.Serialization.ProtocolUtility.WritePacketAsync(IByteHandler byteHandler, Int32 sequenceNumber, ReadOnlyMemory`1 contents, IOBehavior ioBehavior)
   bei MySqlConnector.Protocol.Serialization.ProtocolUtility.WritePayloadAsync(IByteHandler byteHandler, Func`1 getNextSequenceNumber, ReadOnlyMemory`1 payload, IOBehavior ioBehavior)
   bei MySqlConnector.Protocol.Serialization.StandardPayloadHandler.WritePayloadAsync(ReadOnlyMemory`1 payload, IOBehavior ioBehavior)
   bei MySqlConnector.Core.ServerSession.<DisposeAsync>d__82.MoveNext()
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MySqlConnector.Core.ConnectionPool.<ConnectSessionAsync>d__22.MoveNext()
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext()
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext()
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MySqlConnector.MySqlConnection.<CreateSessionAsync>d__124.MoveNext()
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MySqlConnector.MySqlConnection.<OpenAsync>d__26.MoveNext()
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MySqlConnector.MySqlConnection.Open()

I have also tried to add the nuget package to the project, but it doesnt help. 

Could you please explain, how to make that redirect?

**Comment by bgrainger** [comment]
Can you produce a self-contained example that reproduces the problem?

**Comment by ThomasX12** [comment]
Finally i have found the error. I had a post build Action in my solution witch copies every file into an other folder.
`copy /Y "$(TargetPath)" "$(TargetDir)\..\$(TargetFileName)"`
This copy-action didnt include the referenced System.Buffers.dll. This was the reason for the Execption. When i execute the exe from the /Debug folder no errors occur. 

The InvalidOperationException  
[https://github.com/mysql-net/MySqlConnector/issues/1376]
only occurs if the System.Buffers.dll is missing in the folder of the execution exe. 

Please close this issue, because it has nothing to do with die MySqlConnector driver.
