### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by RafalMiazga** [mysql-net/MySqlConnector#1390]
**Software versions**
MySqlConnector version: 8.0.31
.NET version:  4.5.2

Hello,
I got an error like below in Windows Service written in C# and using MySql component.
It was a random error that never happened before.

I've try/catch everywhere so don't understand how could it be unhandled?
I'm unable to relate it to any particular line of code.
Any ideas? Could it be an internal problem of MySql library?

 The process was terminated due to an unhandled exception. Exception Info: System.NotSupportedException at
 System.Net.Security._SslStream.ProcessRead(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest) at
 System.Net.Security.SslStream.Read(Byte[], Int32, Int32) at MySql.Data.MySqlClient.TimedStream.Read(Byte[], Int32, Int32) at
 MySql.Data.MySqlClient.MySqlStream.ReadFully(System.IO.Stream, Byte[], Int32, Int32) at MySql.Data.MySqlClient.MySqlStream.LoadPacket() at 
 MySql.Data.MySqlClient.MySqlStream.ReadPacket() at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32 ByRef, Int64 ByRef) at
 MySql.Data.MySqlClient.Driver.NextResult(Int32, Boolean) at MySql.Data.MySqlClient.MySqlDataReader.NextResult() at 
 MySql.Data.MySqlClient.MySqlDataReader.Close() at
 MySql.Data.MySqlClient.MySqlConnection.Close() at
 MySql.Data.MySqlClient.MySqlConnection.Finalize()

**Comment by bgrainger** [comment]
"MySql.Data.MySqlClient" is the MySQL Driver from Oracle: https://dev.mysql.com/doc/connector-net/en/

This repo is for [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/). Read our documentation to learn how to switch to using MySqlConnector instead: https://mysqlconnector.net/tutorials/migrating-from-connector-net/.

**Comment by bgrainger** [comment]
> `MySql.Data.MySqlClient.MySqlConnection.Finalize()`

FYI, it looks like you're "leaking" a `MySqlConnection` object without calling `.Close()` or `.Dispose()` on it. Make sure you always use `using (var connection = new MySqlConnection()) {...}` to automatically close your connections when you're done with them.
