### ISSUE TITLE
Add support for keyed services in DI

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#1391]
.NET 8.0 is adding support for [keyed services](https://github.com/dotnet/runtime/issues/64427); we should add `AddMySqlDataSource` overloads which accept a key. This is ideal for registering multiple data sources in the same DI container, and later selecting which one you want via e.g. `[FromKeyedServices]`.

See related Npgsql issue: https://github.com/npgsql/npgsql/issues/5134.

**Comment by roji** [comment]
@bgrainger you can check out [the Npgsql implementation](https://github.com/npgsql/npgsql/pull/5387) by @ninofloris; we ended up just adding an optional parameter to do it, rather than add method overloads with the "Keyed" prefix (you can see the discussion there if interested).

**Comment by bgrainger** [comment]
Thanks. Not sure yet if I follow (or agree with) the rationale for avoiding `Keyed` in the method names, but I'll do some more reading on it. (My initial reaction is that `AddKeyedMySqlDataSource` would be better for clarify and disambiguating overloads.)
