### ISSUE TITLE
Procedure metadata loading badly hindering performance

### ISSUE THREAD

**Issue by wtaisto** [mysql-net/MySqlConnector#1402]
**Software versions**
MySqlConnector version: 2.3.1
Server type (MySQL, MariaDB, Aurora, etc.) and version:  MySQL 8.0.32
.NET version: net6.0
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Production database has 2600 stored procedures.  Performance has slowed over time as number of procedures grows.  MySQL logs show the majority of the working time on the mysql server is taken up by these queries:

```
SELECT `ORDINAL_POSITION` , `PARAMETER_MODE` , `PARAMETER_NAME` , `DTD_IDENTIFIER` FROM `information_schema` . `parameters` WHERE `SPECIFIC_SCHEMA` = ? AND `SPECIFIC_NAME` = ? ORDER BY `ORDINAL_POSITION`
SELECT COUNT ( * ) FROM `information_schema` . `routines` WHERE `ROUTINE_SCHEMA` = ? AND `ROUTINE_NAME` = ?
```

**Exception**
No exception is thrown; it just appears that procedure metadata is being retrieved redundantly which degrades performance.

**Code sample**
If I call my DataContext to retrieve a row via a sproc in a sequential loop (where each rep will get a new connection from the pool), I see the metadata retrieved once.  If I call the same method in a parallel loop, the metadata is retrieved again for every call.

**Expected behavior**
Caching procedure definitions, or disabling caching of them at all

**Comment by bgrainger** [comment]
MySqlConnector doesn't currently enforce serialized access to the procedure cache; if multiple threads simultaneously need the information, multiple requests will be sent concurrently to the DB server. This may be what you're observing? (And also a potential optimisation to be made in MySqlConnector.)

> If I call the same method in a parallel loop, the metadata is retrieved again for every call.

This seems like the root of your problem. As a workaround, can you retrieve one procedure (which will populate the cache) then kick off all the parallel work (which will use it)?

**Comment by bgrainger** [comment]
> if multiple threads simultaneously need the information, multiple requests will be sent concurrently to the DB server

Looking at the code more closely, this is intentional. Because information is retrieved for one procedure at a time, we would need to have a per-procedure semaphore to enforce serialized access (which seems far too heavy weight). Or limit MySqlConnector to retrieving information for just one procedure at-a-time per connection pool (which seems too restrictive).

**Comment by bgrainger** [comment]
> I wondered if perhaps there could be an option to run a cache warmup method at startup which would build CachedProcedure instances for all procedures in the database and place them in a shared tier 1 cache which individual connections would probe first

You could build this yourself (and honestly, application logic seems like the best place for this). E.g., in response to a [startup probe](https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-6-adding-health-checks-with-liveness-readiness-and-startup-probes/) enumerate all the stored procedures you care about (e.g., either a hard-coded list, or query `information_schema.routines`) and call `MySqlCommandBuilder.DeriveParameters(Async)`. This will have the side-effect of retrieving the procedure definitions and populating the cache without the overhead of executing a sproc. From then on, your application should be fully warmed up and ready to run at full speed.

**Comment by wtaisto** [comment]
Oh brilliant, I hadn't followed the calling chain through to see that MySqlConnection accesses a shared procedure cache on the ConnectionPool.  Easy!
