### ISSUE TITLE
Add TreatTinyAsBoolean connection string option

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#141]
Implement the `TreatTinyAsBoolean` connection string option:

* `false` - `TINYINT(1)` is a `byte`/`sbyte`
* `true` (default) - `TINYINT(1)` is a `bool`

**Comment by caleblloyd** [comment]
I am about to start work on this, but I think it is worth discussing if `TreatTinyAsBoolean=true` is a sensible default.  In my opinion, changing the data types based off length is unpredictable and therefore is not a sensible default, I would prefer to use `TreatTinyAsBoolean=false` as the default

I can see how it is confusing if somebody was using `BOOL` or `BOOLEAN` as their field types, however.  MySql has [created an alias](http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html) of `BOOL` and `BOOLEAN` to map to `TINYINT(1)` (they should have made the alias map to `BIT(1)`, but too late for that).  In this case, I understand why somebody would expect `TreatTinyAsBoolean=true` as the default.

@bgrainger what is your opinion?

**Comment by bgrainger** [comment]
Since MySQL doesn't support `BOOL` (but just aliases `BOOL` to `TINYINT(1)`), any .NET developer would be highly surprised if `BOOL` columns didn't map to `bool` by default. We should match Connector/Net here and keep `true` as the default.

I'm unsure of the value of supporting this option at all; when would a `TINYINT(1)` column be created explicitly in a table schema? The default for `TINYINT` is `TINYINT(3)`. (Maybe if someone thinks `(1)` is the number of bytes, not the number of decimal digits to use when formatting the column by default?)

**Comment by bgrainger** [comment]
It's not popular, but [it is used](https://github.com/search?utf8=%E2%9C%93&q=%22Treat+Tiny+As+Boolean%3Dfalse%22&type=Code&ref=searchresults).

**Comment by caleblloyd** [comment]
> I'm unsure of the value of supporting setting this option to false; when would a `TINYINT(1)` column be created explicitly in a table schema?

Sometimes I see `TINYINT(1)` used as a small status field, like 0=invited, 1=activated, 2=deactivated.  Lots of times I see it used as a boolean.  But you're right, the number really only applies to zerofill even though there's a common misconception that it represents the number of bytes.

I'll implement it with `true` as the default.

**Comment by bgrainger** [comment]
Shipped in [0.9.0](https://www.nuget.org/packages/MySqlConnector/0.9.0).

**Comment by AccessViolator** [comment]
@bgrainger 
Strangely enough I can't read TINYINT(1) as bool with default setting with Pomelo: [link](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/654). I closed that issue, as there's a workaround, but it still feels like a bug, though most likely Pomelo's. What do you think?

**Comment by bgrainger** [comment]
@AccessViolator I don't know enough about Pomelo and EF.Core to comment, but I would naively expect `System.Boolean` in .NET to be mapped to/from `TINYINT(1)` (aka `BOOL`) in MySQL.

**Comment by caleblloyd** [comment]
It is mapped to `bit(1)`: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/4c099402e3c044fe0cc0d876d8e73630f2eb36c6/src/EFCore.MySql/Storage/Internal/MySqlBoolTypeMapping.cs#L29

**Comment by a-patel** [comment]
@bgrainger
Any update, I am facing a similar issue using ADO.NET.

**Comment by bgrainger** [comment]
@a-patel This issue is for tracking the implementation of the connection string option, which is done. If you have a bug report or question, please open a new issue.
