### ISSUE TITLE
Request to support config LoggerFactory without using MySqlDataSource

### ISSUE THREAD

**Issue by yang-xiaodong** [mysql-net/MySqlConnector#1410]
According to the document description at https://mysqlconnector.net/diagnostics/logging/, it seems that MySqlConnector currently does not support configuring LogFactory without using `MySqlDataSourceBuilder`. This makes it impossible to initialize loggerfactory in some scenarios where dataSourceBuilder cannot be used.

Request to add static objects to support config logfactory without using  datasource like pgsql.

See: 
https://www.npgsql.org/doc/diagnostics/logging.html#configuration-without-npgsqldatasource

**Comment by bgrainger** [comment]
See "Global logging" here: https://mysqlconnector.net/diagnostics/logging/.

**Comment by bgrainger** [comment]
Npgsql's API is documented as "legacy only": https://github.com/npgsql/npgsql/blob/074703eb3596eb2451f7858bf9ea04b6f3e2e720/src/Npgsql/NpgsqlLoggingConfiguration.cs#L48-L49

MySqlConnector already has a legacy interface; I don't know if there's really a need to add a new, legacy interface?

**Comment by bgrainger** [comment]
There are instances where it could be nice to set a global `ILoggerFactory` without having to pull in the MySqlConnector.Logging.Microsoft.Extensions.Logging package; this could be done via a new `MySqlConnectorLogManager.InitializeLogging(ILoggerFactory)` method.
