### ISSUE TITLE
Add logging for transaction start, commit, roll back

### ISSUE THREAD

**Issue by yang-xiaodong** [mysql-net/MySqlConnector#1411]
Request to classify logs. Each category can be distinguished by Logger Name.

For example, the transaction log cannot currently be directly viewed such as transaction commit, transaction rollback, etc.

Refer: 

https://github.com/npgsql/npgsql/blob/main/src/Npgsql/NpgsqlLoggingConfiguration.cs#L21

**Comment by bgrainger** [comment]
Those existing logs won't change because that's in common code. Reclassifying this as a feature request for new Info-level logging.

**Comment by bgrainger** [comment]
Just to make sure I'm understanding the purpose correctly, what's the use case for this new logging?

**Comment by yang-xiaodong** [comment]
I know that using logs is not a good way and as you said it might change at any time, but in reality, the likelihood of this change happening for transactions logs maybe very small.

If I add the code for sending transactions, you should be able to see the difference. The former is an extension method that creates a CAPTransaction object, while the latter uses the IDbTransaction object.

```cs
using (var connection = new MySqlConnection(ConnectionString))
{
    using (var capTrans = connection.BeginTransaction(_capBus, autoCommit: false))
    {
        connection.Execute("insert into test(name) values('test')", transaction: (IDbTransaction)transaction.DbTransaction);

        _capBus.Publish("xxx.services.show.time", DateTime.Now);

        capTrans.Commit();                
    }
}
```
VS

```cs
using (var connection = new MySqlConnection(ConnectionString))
{
    using (var transaction = connection.BeginTransaction())
    {
        connection.Execute("insert into test(name) values('test')", transaction: transaction);

        _capBus.Publish(transaction, "xxx.services.show.time", DateTime.Now);

        transaction.Commit();                
    }
}
```

Overall, thank you for your reply, it made me think again.

**Comment by bgrainger** [comment]
Planning to add Debug messages for "Starting", "Committed", "Rolled Back" (to match npgsql), as well as Trace messages for "Started", "Committing", "Rolling Back".
