### ISSUE TITLE
Stored Procedure with where clause that contains a white space is not retrieving data when called from .netcore

### ISSUE THREAD

**Issue by csk1nn3r** [mysql-net/MySqlConnector#1414]
**Software versions**
MySqlConnector version: 2.3.1
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL
.NET version: 7.0
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
I have a stored procedure that has a where clause that is a string (test test).  When called from the mysql in ubuntu this where clause behaves as expected; data is returned.  When called from .netcore no results are found.  When the space is removed and the string contains no breaks the stored procedure returns data to .netcore.  The parameter has been set to the 'test test' string directly before passing to mysql.  This does not change behavior.  I'm currently working around this issue by not using a stored procedure when the where clause requires a string as spaces might be a part of it.  

Is there a way that the command.Parameters need setup to allow this to work correctly?  I'm guessing that something is filtering out the spaces before the query is ran.

```sql
delimiter // 
drop procedure if exists retrieveaccount;
Create procedure retrieveaccount(IN p_glfydid varchar(40), OUT p_userid bigint, OUT p_id varchar(64), OUT p_blocknum int, 
	OUT p_blocktime datetime, OUT p_elapsed int, OUT p_netusage int, OUT p_scheduled bit, OUT p_accountid bigint) 
begin
	select userid, id, blocknum, blocktime, elapsed, netusage, scheduled, accountid 
	into
	p_userid, p_id, p_blocknum, p_blocktime, p_elapsed, p_netusage, p_scheduled, p_accountid
	from account
	where glfydid = p_glfydid;
end //
delimiter
```

**Exception**
No data is returned

**Code sample**

```csharp
/* A concise code sample to reproduce the bug */

using (var command = new MySqlCommand("retrieveaccount", connection))

command.CommandType = System.Data.CommandType.StoredProcedure;
command.Parameters.AddWithValue("@p_glfydid", glfydId);
command.Parameters["@p_glfydid"].Direction = System.Data.ParameterDirection.Input;
command.Parameters["@p_glfydid"].Value = MySqlDbType.VarChar;

 var result = await command.ExecuteNonQueryAsync();
 if (result > 0) 
{
   //Build entity
}
```

**Expected behavior**
Data needs to be returned as the stored procedure runs correctly in mysql on Ubuntu.

**Additional context**

```sql
--Build out table
CREATE TABLE account
(
	accountid bigint  NOT NULL AUTO_INCREMENT,
	id varchar(64) UNIQUE,
	blocknum int,
	blocktime datetime,
	elapsed int,
	netusage int,
	scheduled boolean,
	glfydid varchar(40),
	userid bigint,
	primary key(accountid)
);
```

**Comment by bgrainger** [comment]
```csharp
command.Parameters["@p_glfydid"].Value = MySqlDbType.VarChar;
```

This line introduces a bug because it's overwriting the value of the `@p_glfydid` parameter. (And unless there is a row with the literal value `"VarChar"` for the `glfydid` column, it will find no rows. FWIW, setting parameter types with MySqlConnector is unnecessary so just delete that line.

**Comment by csk1nn3r** [comment]
Hello @bgrainger Thanks for pointing this out.  Tested and preforms as expected.  Thanks again.
