### ISSUE TITLE
When the .exe file name is changed, the .exe.config file name must be changed accordingly

### ISSUE THREAD

**Issue by beligg** [mysql-net/MySqlConnector#1415]
MySqlConnector version: 2.3.1
Server type and version:  MySQL 5.5.45
.NET version: 4.6.2

I have an application that uses MySqlConnector, which users would change the .exe file name. When the .exe file name is changed, the .exe.config must be changed accordingly, or the execution would throw. This is very inconvenient for the users. How can I tell MySqlConnector to read from another .exe.config file instead the one with the same name of the .exe file,  or even better, ignore the .exe.cofig file at all, for I wont put any information there? 

Here is my test code:
```
private static async Task TestAsync()
{
    await using var connection = new MySqlConnection(_connectionString);
    await connection.OpenAsync();
    using var cmd = new MySqlCommand();
    cmd.Connection = connection;
    cmd.CommandText = "INSERT INTO Students (Name) VALUES ('ABC')";
    await cmd.ExecuteNonQueryAsync();
}

```

And the thrown exception, when the .exe filename was changed: 
```
System.TypeInitializationException: The type initializer for 'MySqlConnector.Core.ConnectionPool' threw an exception.
   at MySqlConnector.Core.ConnectionPool.GetPool(String connectionString, MySqlConnectorLoggingConfiguration loggingConfiguration, Boolean createIfNotFound)
   at MySqlConnector.MySqlConnection.<OpenAsync>d__28.MoveNext()

```

**Comment by bgrainger** [comment]
> How can I tell MySqlConnector to read from another .exe.config file instead the one with the same name of the .exe file

AFAIK this is a limitation of .NET Framework. However, I'm not aware of any MySqlConnector-related information that needs to be in the `.exe.config` file. What is it looking for?

> The type initializer for 'MySqlConnector.Core.ConnectionPool' threw an exception.

What's the inner exception?

**Comment by beligg** [comment]
It is actually related to .net framework, I sovlved the problem by adding the following code:

```
AppDomain.CurrentDomain.AssemblyResolve += new(
    (s, e) =>
    {
        if (e.Name.Contains("System.Runtime.CompilerServices.Unsafe"))
            return Assembly.LoadFrom("System.Runtime.CompilerServices.Unsafe.dll");
        return null;
    }
);

```
