### ISSUE TITLE
session_connect_attrs not being set on MariaDB

### ISSUE THREAD

**Issue by madelson** [mysql-net/MySqlConnector#1416]
**Software versions**
MySqlConnector version: 2.3.1
Server type (MySQL, MariaDB, Aurora, etc.) and version: MariaDB 11.2.2
.NET version: .NET 8

**Describe the bug**
I'm leveraging MySqlConnector to set the application name on my connection. However, this does not appear to be populating `performance_schema.session_connect_attrs` on MariaDB like it does in MySQL.

**Exception**
n/a

**Code sample**
```csharp
using var conn = new MySqlConnection(new MySqlConnectionStringBuilder
{
	Server = "localhost",
	Database = "...",
	Port = 3306,
	UserID = "...",
	Password = "...",
	ApplicationName = "myapp"
}.ConnectionString);
conn.Open();

var cmd = conn.CreateCommand();
cmd.CommandText = "SELECT * FROM performance_schema.session_connect_attrs";
using var reader = cmd.ExecuteReader();
while (reader.Read())
{
	Console.WriteLine("ROW:");
	for (var i = 0; i < reader.VisibleFieldCount; ++i)
	{
		Console.WriteLine($"{reader.GetName(i)}: {reader.GetValue(i)}");
	}
}
```
**Expected behavior**
On MySQL I get one of the rows printing out:

```
ROW:
PROCESSLIST_ID: 782
ATTR_NAME: program_name
ATTR_VALUE: myapp
ORDINAL_POSITION: 6
```

**Additional context**
I've seen this work in the past with an older version of MariaDB along with an older version of MySqlConnector.

Thanks for maintaining this great library!

**Comment by bgrainger** [comment]
Do you have the performance schema activated? It's off by default.

https://mariadb.com/kb/en/performance-schema-overview/#activating-the-performance-schema

**Comment by madelson** [comment]
🤦‍♂️ this was it exactly. Apologies for this misfiled ticket but really appreciate the quick and helpful response!
