### ISSUE TITLE
System.Diagnostics.DiagnosticSource 

### ISSUE THREAD

**Issue by BenjaminKempe** [mysql-net/MySqlConnector#1441]
**Software versions**
MySqlConnector version: 2.3.5
Server type (MySQL, MariaDB, Aurora, etc.) and version: 
.NET version: 4.8.2
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
When i update the NuGet package "System.Diagnostics.DiagnosticSource" to the latest Version, 8.0.0, i get an error: Version 7.0.0.2 not found

**Exception**
Die Datei oder Assembly "System.Diagnostics.DiagnosticSource, Version=7.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)

at MySqlConnector.MySqlConnection.<OpenAsync>d__28.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlConnection.Open()

**Comment by bgrainger** [comment]
You most likely need a binding redirect in your app.config: https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/bindingredirect-element
