### ISSUE TITLE
DbUpdateException Entries Behaves Differently When First Fails vs Others Fail

### ISSUE THREAD

**Issue by philvmx1** [mysql-net/MySqlConnector#1449]
Using EF Core 6.0.8 with Pomelo 6.0.0, when we have the following:

Table - Person
| Id | Name (max 3) |

```
context.Add<Person>(new Person { Name = "Three" });
context.Add<Person>(new Person { Name = "A" });
context.Add<Person>(new Person { Name = "B" });
context.Add<Person>(new Person { Name = "C" });

try
{
  context.SaveChanges();
}
catch (DbUpdateException ex)
{
  ex.Entries.Count(); // 4
}
```

However, when we have it where the first record does not have an error:

```
context.Add<Person>(new Person { Name = "Three" });
context.Add<Person>(new Person { Name = "A" });
context.Add<Person>(new Person { Name = "Three" });
context.Add<Person>(new Person { Name = "B" });
context.Add<Person>(new Person { Name = "C" });

try
{
  context.SaveChanges();
}
catch (DbUpdateException ex)
{
  ex.Entries.Count(); // 1
}
```
Only the one record is in Entries.

We expect this to be consistent and only have the 1 Entry that failed.

The cause of this happening is the InitAsync, which is attempting to read the first result - fails and throws an exception.

https://github.com/mysql-net/MySqlConnector/blob/dd518bf99fa385104111a1de7be9f28b2db39e9f/src/MySqlConnector/MySqlDataReader.cs#L482

That exception is caught and EF Core selects all Entries whereas in ConsumeAsync, it only selects the current command Entry.

https://github.com/dotnet/efcore/blob/42e6cfbd0c5b431a89b1923e7b73296705cf7ddf/src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs#L383

ExecuteReaderAsync should return a reader, but perhaps shouldn't read anything. Not sure what other implementations are doing though.

**Comment by philvmx1** [comment]
After further investigation, I think this is more about EF Core. Submitted issue there: https://github.com/dotnet/efcore/issues/33098

Seems that the ODIC provider does the same as MySqlConnector. There's a comment in that code so it seems to be the intent.

**Comment by bgrainger** [comment]
This seems like a Pomelo or EF Core issue; please reopen if there's specific behaviour in MySqlConnector (that can be reproduced just with ADO.NET) that needs to be changed.

**Comment by philvmx1** [comment]
agreed, this is an ef core issue I opened the issue there.
