### ISSUE TITLE
[Question] I would like to know from which version started supporting TLS 1.3 

### ISSUE THREAD

**Issue by tsaiggo** [mysql-net/MySqlConnector#1453]
SDK Version: 0.55
Windows server: Disable TLS 1.3
MySql server: Enforce TLS 1.3
Test result: connect to mysql server failed.

When I enabled TLS1.3 on the Windows server, I can successfully connect to the server.

I want to know the reason for the difference between these two results.
I did not see any code related to TLS1.3 in the source code of v0.55

**Comment by bgrainger** [comment]
It was probably https://github.com/mysql-net/MySqlConnector/commit/e4c8aece30ecda2a737897961be7b9c9057fbf30 released in [0.37.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.37.0).
