### ISSUE TITLE
MySqlBulkCopy Column Mappings Set

### ISSUE THREAD

**Issue by InvincibleDRT** [mysql-net/MySqlConnector#1461]
**Unable to pass in custom order of column in DataTable to bulkcopy.**
https://github.com/mysql-net/MySqlConnector/blob/d9e59c7995592c9ea11300382a6aa8914b5a60ab/src/MySqlConnector/MySqlBulkCopy.cs#L46

**Describe the solution you'd like**
Change `	public List<MySqlBulkCopyColumnMapping> ColumnMappings { get; }` to `	public List<MySqlBulkCopyColumnMapping> ColumnMappings { get; set;}`

**Comment by bgrainger** [comment]
It sounds like you're asking for `bulkCopy.ColumnMappings = myList;`.

Instead of doing that, can you use `bulkCopy.ColumnMappings.AddRange(myList);`?

**Comment by bgrainger** [comment]
(The reason for the current design is that it allows object + collection initialization syntax.)

**Comment by InvincibleDRT** [comment]
I have tried that syntax as well. This is the error i see 
![image](https://github.com/mysql-net/MySqlConnector/assets/16821809/c42c8161-dca4-459d-a110-2a71e6e517f5)

AddRange worked. But may be you can implicitly generate column mapping in writetoserverasync from using DataTable instead of table from db!?

**Comment by InvincibleDRT** [comment]
With something like this 
`var mappings = (from DataColumn col in dt.Columns
select new MySqlBulkCopyColumnMapping(col.Ordinal, col.ColumnName)).ToList();`

**Comment by bgrainger** [comment]
> But may be you can default to column mapping in DataTable instead of defaulting to mapping from table in db!?

This may be a duplicate of https://github.com/mysql-net/MySqlConnector/issues/1375?

**Comment by InvincibleDRT** [comment]
Closing since its duplicate
