### ISSUE TITLE
`CommandBehavior.SchemaOnly` not working as expected.

### ISSUE THREAD

**Issue by guptaheena** [mysql-net/MySqlConnector#1463]
**Software versions**
MySqlConnector version:
Server type (MySQL, MariaDB, Aurora, etc.) and version:  MySQL

**Describe the bug**
The SchemaOnly command behaviour is not working as expected for DML commands such as insert/update. 
When executing CommandBehaviour.SchemaOnly on insert/update statements, it executes the command in the backend which is not the desired behaviour for this command.

**Code sample**
string query ="<insert command>"
using var command = new MySqlCommand(query, connection) { CommandTimeout = connection.ConnectionTimeout };
MySqlDataReader mysqlDataReader = (MySqlDataReader)await command.ExecuteReaderAsync(CommandBehavior.SchemaOnly, requestCancellationToken).ConfigureAwait(false);

**Expected behavior**
Only the schema of the table should be returned. The query should not be executed.

**Comment by bgrainger** [comment]
> When executing CommandBehaviour.SchemaOnly on insert/update statements, it executes the command in the backend which is not the desired behaviour for this command.

What should it do instead?

----

`CommandBehavior.SchemaOnly` is implemented via [`sql_select_limit`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_select_limit), which affects `SELECT` queries only. Its behavior is undefined for other types of queries.

**Comment by guptaheena** [comment]
> > When executing CommandBehaviour.SchemaOnly on insert/update statements, it executes the command in the backend which is not the desired behaviour for this command.
> 
> What should it do instead?

Shouldn't it be functioning in the same way how it is working SQL. In SQL CommandBehaviour.SchemaOnly works for select, insert, update as well.

so why is it undefined in MySQL? Also, is there any other way to get the schema for insert and update statements?

**Comment by bgrainger** [comment]
> Shouldn't it be functioning in the same way how it is working SQL. In SQL CommandBehaviour.SchemaOnly works for select, insert, update as well.

MySQL Server is a different database than Microsoft SQL Server; the "same" features may be implemented slightly differently.

> Also, is there any other way to get the schema for insert and update statements?

What information do you want to retrieve? If the query were `INSERT INTO Users(Email) VALUES(@Email)` or `UPDATE Users SET Email = @Email WHERE UserId = @UserId` what schema do you want to retrieve?

Can `MySqlConnection.GetSchema` provide the information you want?

Can you provide a concrete example of what you are hoping to accomplish?
