### ISSUE TITLE
MySqlBulkCopy Conflict Option "Update"

### ISSUE THREAD

**Issue by InvincibleDRT** [mysql-net/MySqlConnector#1476]
**Is your feature request related to a problem? Please describe.**
When a unique key constraint is triggered for duplicate inserts, BulkCopy is changing primary key with "Replace" option

**Describe the solution you'd like**
Another Conflict Option like Update which will keep the primary key same and updates values

**Comment by bgrainger** [comment]
`MySqlBulkCopy` is simply implemented with the `LOAD DATA` statement. It offers `REPLACE` and `IGNORE` options: https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-error-handling.
