### ISSUE TITLE
Documentation Possible Bug

### ISSUE THREAD

**Issue by MarcelChirtes** [mysql-net/MySqlConnector#1481]
Isn't this a problem on https://mysqlconnector.net/connection-options/ where  **ConnectionReset** default value says is **true**.?

Source code is: https://github.com/mysql-net/MySqlConnector/blob/master/docs/content/connection-options.md?plain=1#L213

For  MySql.Data.MySqlClient **ConnectionReset** default value is **false** based on https://dev.mysql.com/doc/dev/connector-net/latest/api/data_api/MySql.Data.MySqlClient.MySqlConnectionStringBuilder.html

**Comment by bgrainger** [comment]
The default value of `Connection Reset` is `true` in this library: https://github.com/mysql-net/MySqlConnector/blob/9efc679afa3d662fef2684adc89fe4152e272817/src/MySqlConnector/MySqlConnectionStringBuilder.cs#L334

The difference from MySql.Data (which is a different library) is covered in the documentation: https://mysqlconnector.net/tutorials/migrating-from-connector-net/#connection-string-differences.

**Comment by MarcelChirtes** [comment]
> The default value of `Connection Reset` is `true` in this library:
> 
> https://github.com/mysql-net/MySqlConnector/blob/9efc679afa3d662fef2684adc89fe4152e272817/src/MySqlConnector/MySqlConnectionStringBuilder.cs#L334
> 
> https://github.com/mysql-net/MySqlConnector/blob/9efc679afa3d662fef2684adc89fe4152e272817/src/MySqlConnector/MySqlConnectionStringBuilder.cs#L1112-L1114
> 
> The difference from MySql.Data (which is a different library) is covered in the documentation: https://mysqlconnector.net/tutorials/migrating-from-connector-net/#connection-string-differences.

Understood, my mistake, then still I feel there's is issue here, even with default ConnectionReset being true, is not applied on the connection string, or I don't understand how it should work.

Let me know if my expectancy is wrong, or indeed there's a issue, see bellow xUnit tests I expect to pass all the asserts, but is not happening.

```
using MySqlConnector; // 2.3.5
using Xunit;

namespace MySqlConnectorTests;

public class MySqlConnectionTest
{
    [Fact]
    public void MysqlConnectionStringBuilder()
    {
        var conn1WithConnectionResetExplicitTrue = new MySqlConnectionStringBuilder
        {
            Server = "my_server",
            Port = 3306,
            Password = "my_pass",
            UserID = "my_user",
            Database = "my_datase",
            MaximumPoolSize = 100,
            TreatTinyAsBoolean = true,
            ConnectionReset = true
        };

        var conn2WithoutConnectionReset = new MySqlConnectionStringBuilder
        {
            Server = "my_server",
            Port = 3306,
            Password = "my_pass",
            UserID = "my_user",
            Database = "my_datase",
            MaximumPoolSize = 100
        };

        Assert.Contains("Connection Reset", conn1WithConnectionResetExplicitTrue.ToString());
        Assert.Contains("Connection Reset", conn2WithoutConnectionReset.ToString()); // fails
        Assert.Equal(conn1WithConnectionResetExplicitTrue.ToString(), conn2WithoutConnectionReset.ToString()); // fails
    }

    [Fact]
    public void MysqlConnectionStringBuilderRaw()
    {
        var conn1WithConnectionResetTrue = new MySqlConnectionStringBuilder("Server=my_server;Port=3306;User ID=my_user;Password=my_pass;Database=my_datase;Connection Reset=True;Maximum Pool Size=100;Treat Tiny As Boolean=True");

        var conn2WithoutConnectionReset = new MySqlConnectionStringBuilder("Server=my_server;Port=3306;User ID=my_user;Password=my_pass;Database=my_datase;Maximum Pool Size=100;Treat Tiny As Boolean=True");

        Assert.Contains("Connection Reset", conn1WithConnectionResetTrue.ToString());
        Assert.Contains("Connection Reset", conn2WithoutConnectionReset.ToString()); // fails
        Assert.Equal(conn1WithConnectionResetTrue.ToString(), conn2WithoutConnectionReset.ToString()); // fails
    }
}


```

**Comment by bgrainger** [comment]
Your expectation is incorrect. `new MySqlConnectionStringBuilder().ToString()` does not print the value of every single connection string option by default. (Which would be required for `Assert.Contains("Connection Reset", conn2WithoutConnectionReset.ToString());` to succeed.)

That is, you're assuming that `new MySqlConnectionStringBuilder().ToString()` would print `Server=;Certificate File=;Certificate Password=;Certificate Store Location=None;Certificate Thumbprint=;Connection Reset=True;Allow Load Local Infile=False;Allow Public Key Retrieval=False;Allow User Variables=False;Allow Zero DateTime=False;Application Name=;Auto Enlist=True;Cancellation Timeout=2;Character Set= ......`, which it does not.

Testing a connection string with `Assert.Contains` is the wrong approach to see if a setting is set. Instead, test `new MySqlConnectionStringBuilder(connectionStringToTest).ConnectionReset` to find out if `Connection Reset` (or any other connection string option) is set.

**Comment by MarcelChirtes** [comment]
Acknowledged, Thank you, @bgrainger
