### ISSUE TITLE
BeginTransactionAsync hangs on 5.7.mysql_aurora.2.11.5

### ISSUE THREAD

**Issue by rtnextable** [mysql-net/MySqlConnector#1482]
**Software versions**
MySqlConnector version: 2.3.7
Server type (MySQL) and version: 5.7.mysql_aurora.2.11.5
.NET version:  Standard 2.0

I am porting an application from Mysql client and have found that wherever I have a BeginTransactionAsync it will just hang. I have tried async and non-async with the same results.

connection string: `SSL Mode=None;Pooling=True;Minimum Pool Size=2;Maximum Pool Size=10;Allow User Variables=True;Convert Zero DateTime=True;Default Command Timeout=20`

`using (var transaction = await con.BeginTransactionAsync(cancellationToken)) {}`

What could be causing this?

**Comment by bgrainger** [comment]
Have you tried adding `Pipelining=false` to your connection string?

https://mysqlconnector.net/troubleshooting/aurora-freeze/

**Comment by rtnextable** [comment]
I had not. Once the .Open/async worked I forgot about it. `Pipeling=false` did stop the freeze, thank you.
