### ISSUE TITLE
Function call raise exception with set datatype

### ISSUE THREAD

**Issue by daikoz** [mysql-net/MySqlConnector#1491]
**Software versions**
MySqlConnector version: 2.3.7
Server: MariaDB [10.5.23-MariaDB-0+deb11u1-log]
.NET version: .NET SDK Version  8.0.300

**Describe the bug**

Create function:

```SQL
CREATE FUNCTION TestFunction2(ColSet set('set1','set2','set3'))
RETURNS smallint
BEGIN
	RETURN 0;
END
```

**Call this function**

```csharp
            using MySqlConnector.MySqlConnection conn = new("XXXXXXXXXX");
            conn.Open();

            using DbCommand sqlCmd = conn.CreateCommand();
            sqlCmd.Connection = conn;
            sqlCmd.CommandText = @"TestFunction2";
            sqlCmd.CommandType = System.Data.CommandType.StoredProcedure;

            DbParameter param23 = sqlCmd.CreateParameter();
            param23.ParameterName = "@ColSet";
            param23.Value = "set1";
            sqlCmd.Parameters.Add(param23);

            DbParameter paramXXX = sqlCmd.CreateParameter();
            paramXXX.ParameterName = "@ReturnValue";
            paramXXX.Direction = System.Data.ParameterDirection.ReturnValue;
            sqlCmd.Parameters.Add(paramXXX);

            var result = sqlCmd.ExecuteScalar();
```

**Exception on ExecuteScalar**

  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"Object reference not set to an instance of an object."} | System.NullReferenceException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2147467261 | int
  | HelpLink | null | string
  | ▶ InnerException | null | System.Exception
  | Message | "Object reference not set to an instance of an object." | string
  | Source | "MySqlConnector" | string
  | StackTrace | "   at MySqlConnector.Core.TypeMapper.GetMySqlDbType(String typeName, Boolean unsigned, Int32 length)\r\n   at MySqlConnector.Core.CachedParameter..ctor(Int32 ordinalPosition, String mode, String name, String dataType, Boolean unsigned, Int32 length)\r\n   at MySqlConnector.Core.CachedProcedure.<FillAsync>d__0.MoveNext()\r\n   at MySqlConnector.MySqlConnection.<GetCachedProcedure>d__90.MoveNext()\r\n   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext()\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at MySqlConnector.MySqlCommand.<ExecuteScalarAsync>d__80.MoveNext()\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at MySqlConnector.MySqlCommand.ExecuteScalar()\r\n   at ConsoleApp12.Program.Main(String[] args) in C:\\XXXX\\source\\repos\\ConsoleApp12\\ConsoleApp12\\Program.cs:line 30" | string
  | ▶ TargetSite | {MySqlConnector.MySqlDbType GetMySqlDbType(System.String, Boolean, Int32)} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

**Comment by bgrainger** [comment]
Added in [2.4.0](https://github.com/mysql-net/MySqlConnector/releases/tag/2.4.0).
