### ISSUE TITLE
Frequent Calls to` SET NAMES utf8mb4` and `SET sql_select_limit = ?` 

### ISSUE THREAD

**Issue by SwimmingHwang** [mysql-net/MySqlConnector#1492]
https://github.com/mysql-net/MySqlConnector/blob/67946419631a047032d3baccb7c506d7e39bb45d/src/MySqlConnector/Core/ServerSession.cs#L494-L505

Hi,

I'm using the MySQL connector in my .NET application, and I've noticed that the connector frequently calls the following commands:

```sql
SET NAMES `utf8mb4`
SET `sql_select_limit` = ?
```

I would like to understand why these commands are being called so frequently. Additionally, these frequent calls are consuming resources, which is becoming a concern.

Could you please provide some guidance on why this is happening and suggest possible solutions to mitigate the resource usage?

Thank you!

**Comment by bgrainger** [comment]
> `SET NAMES utf8mb4`

Sent when resetting the connection, i.e., when a connection is retrieved from the pool and needs to be put in a "fresh" state. This statement is necessary to work around a MySQL Server bug: https://bugs.mysql.com/bug.php?id=97633; cf. https://github.com/mysql-net/MySqlConnector/issues/66. (See https://github.com/mysql-net/MySqlConnector/issues/1236 for a case to eliminate this for servers that don't need it.)

You can "work around" this by adding `Connection Reset=false;` but that will have the (generally negative) side-effect of not clearing server-side variables, temp tables, etc.

> `SET sql_select_limit =`

This is sent to implement `CommandBehavior.SchemaOnly` or `CommandBehavior.SingleRow`. Issuing this query is presumably more efficient than allowing the server to return all rows. If that's not true, stop using those flags in your code.

> Additionally, these frequent calls are consuming resources, which is becoming a concern.

What metrics do you have to indicate that these two calls are consuming significant amount of server resources?

**Comment by sirantd** [comment]
> You can "work around" this by adding `Connection Reset=false;` but that will have the (generally negative) side-effect of not clearing server-side variables, temp tables, etc.

Doesn't look like a proper "work around" it would be nice if I can precisely disable only "SET NAMES" when my character set == server character set and I don't want to have all mentioned side-effects.
