### ISSUE TITLE
Question: use of current redirection

### ISSUE THREAD

**Issue by rusher** [mysql-net/MySqlConnector#1495]
Hi @bgrainger. A question about redirection starting with "Location: mysql://". Is there real use of that ? or was it based on initial spec for https://jira.mariadb.org/browse/MDEV-15935 ? If this is the case i'll provide a PR with released spec, I just need to know what to do of current implementation. (and this will also allow me to know how to implement another PR corresponding to the changes to use SSL without any configuration on the client side https://mariadb.org/mission-impossible-zero-configuration-ssl/ )

**Comment by bgrainger** [comment]
The current implementation was made for Azure Database for MySQL Single Server, which Microsoft is [retiring this year](https://learn.microsoft.com/en-us/azure/mysql/migrate/whats-happening-to-mysql-single-server). (IIRC the MariaDB spec wasn't finished when that code was developed.)

Given that it is being retired, I think the existing implementation could be removed; it (hopefully) shouldn't be a breaking change for anyone.

**Comment by rusher** [comment]
ok, thanks
