### ISSUE TITLE
Unexpected Result (-1) from MySqlCommand’s Async Method with Cancelled CancellationToken

### ISSUE THREAD

**Issue by rubenfreire** [mysql-net/MySqlConnector#1496]
**Software versions**
MySqlConnector version: 2.3.7
Server type (MySQL) and version: 8.0.31
.NET version: .NET6

**Describe the bug**
When I call an Async method from MySqlCommand with a long running query, passing a CancellationToken, it returns -1 after the token is cancelled.

This is possibly caused by some misunderstanding on my part of the documentation and what I'm trying to test.

**Code sample**

```csharp
using MySqlConnector;
using System.Diagnostics;

var cancellationTokenSource = new CancellationTokenSource();

var stopWatch = new Stopwatch();
try
{
    await using var connection = new MySqlConnection("Server=localhost;Port=3306;Database=<db>;Uid=<user>;Pwd=<pass>");
    await connection.OpenAsync();

    Console.WriteLine("Executing a long running query...");
    stopWatch.Start();

    using var command = new MySqlCommand("SELECT SLEEP(5);", connection);
    var task = command.ExecuteNonQueryAsync(cancellationTokenSource.Token);

    await Task.Delay(500);
    cancellationTokenSource.Cancel();
    Console.WriteLine($"Cancelling the query after {stopWatch.Elapsed.TotalMilliseconds}ms.");

    var result = await task;

    Console.WriteLine($"Query Completed after {stopWatch.Elapsed.TotalMilliseconds}ms with result: {result}");
}
catch (OperationCanceledException)
{
    stopWatch.Stop();
    Console.WriteLine($"Operation was cancelled as expected after {stopWatch.Elapsed.TotalMilliseconds}ms.");
}
catch (Exception ex)
{
    stopWatch.Stop();
    Console.WriteLine($"An exception occurred after: {stopWatch.Elapsed.TotalMilliseconds}ms. Message: {ex.Message}\nStackTrace: {ex.StackTrace}");
}
```

**Expected behavior**
Reading the [documentation ](https://mysqlconnector.net/overview/command-cancellation/) and checking the unit tests [examples](https://github.com/mysql-net/MySqlConnector/blob/e6bb115e49a3d21386062fb562046562fa5fa0ab/tests/MySqlConnector.Tests/CancellationTests.cs#L187), I expected that an OperationCanceledException should be throw after I cancel the ct. The query is canceled but it returns the number of rows (-1 in this case).

> Executing a long running query...
> Cancelling the query after 745.4734ms.
> Operation was cancelled as expected after 753.6106ms.

**Actual behavior**

> Executing a long running query...
> Cancelling the query after 745.4734ms.
> Query Completed after 753.6106ms with result: -1

If I change the code to cancel the ct after a delay, it works as expected, throwing an OperationCanceledException. 

```diff
- var cancellationTokenSource = new CancellationTokenSource();
- cancellationTokenSource .Cancel();
+ var cancellationTokenSource = new CancellationTokenSource(1000);
```

**Comment by bgrainger** [comment]
This is a side-effect of the "long running query" you're using for testing. `SLEEP(n)` is an interruptible method and the "soft cancellation" that MySqlConnector uses causes it to be gracefully cancelled.

If you use a "real" query, you'll get the cancellation behaviour you expect, e.g.,

```csharp
using var command = new MySqlCommand("""
	with ints as (select * from (values row(1), row(2), row(3), row(4), row(5), row(6), row(7), row(8), row(9)) temp)
	select * from ints a join ints b join ints c join ints d join ints e join ints f join ints g join ints h;
	""", connection);
```

**Comment by rubenfreire** [comment]
Thanks!

I did the test and it behaves as expected, a OperationCanceledException is thrown.
