### ISSUE TITLE
Implement MySqlBulkLoader

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#15]
Clone the `MySqlBulkLoader` API (specified here: https://dev.mysql.com/doc/connector-net/en/connector-net-programming-bulk-loader.html).

As an extension, support a `Stream` property instead of a `FileName`. Behind the scenes, create a GUID and pass that to MySQL as the `LOAD DATA LOCAL INFILE` file name (https://dev.mysql.com/doc/refman/5.7/en/load-data.html).

When the [`LOCAL_INFILE_Request`](https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-Protocol::LOCAL_INFILE_Request) is received with that GUID as the name, stream the in-memory data to the server.

**Comment by gitsno** [comment]
I'm working on this - I'm also intending to create a MySqlBulkCopy class that works like the SqlBulkCopy class does with MS SQL Server - so it will create an INSERT ... VALUES statement with multiple rows for a given enumerable.

**Comment by VitaliyMF** [comment]
@gitsno just a notice, original MySqlBulkCopy uses LOAD DATA INFILE syntax and I think it offers much better performance for large datasets; 
I assume that efficiency of INSERT .. VALUES (row1), (row2) ... (rowN) syntax is very close to several insert statements executed with one MySqlCommand. This approach works for any database (not only MySql/MsSql), and this use-case is already covered by many data access libs. What do you think?

**Comment by gitsno** [comment]
Agreed - I'm not suggesting that it's preferred over LOAD DATA INFILE, but given that developers are used to working with SqlBulkCopy and it does work well, I figure it would be nice to have it as an alternative for the MySql client. If you already have the records in a .NET DataTable or IEnumerable you have to write extra code to get them into the file format that LOAD DATA INFILE expects, whereas if the SqlBulkCopy is implemented you can insert them easily.

**Comment by bgrainger** [comment]
No objection to adding a `MySqlBulkCopy` class that exposes the same/similar API to `SqlBulkCopy`.

For this issue specifically, a `MySqlBulkLoader` class should implement the existing MySQL API and use `LOAD DATA INFILE`.

**Comment by gitsno** [comment]
Just added, see PR #148

**Comment by bgrainger** [comment]
Implemented in [0.13.0](https://www.nuget.org/packages/MySqlConnector/0.13.0).
