### ISSUE TITLE
Issue with Cached Procedures and Parameter Mismatch in MySqlConnector

### ISSUE THREAD

**Issue by ritwik-singh** [mysql-net/MySqlConnector#1504]
Hi,

I'm currently caching my parameters in .NET, and whenever I update a routine parameter, I ensure to clear the cache. However, I'm encountering an issue where MySqlConnector throws an error stating that "only 6 parameters were required, but 7 were sent."

I suspect this might be related to the cached procedure in MySqlConnector. Could this be the case? If so, is there a way to clear the cached procedure manually, or is it possible to disable this feature altogether, considering that I'm already handling parameter caching within my API?

I appreciate any guidance you can provide on this.

Best Regards,
Ritwik

**Comment by bgrainger** [comment]
> If so, is there a way to clear the cached procedure manually

I think you can clear the cache by running `MySqlConnection.ClearAllPools` or `MySqlConnection.ClearPool(connection)`. Does that work around this issue?

> is it possible to disable this feature altogether

Possible duplicate of https://github.com/mysql-net/MySqlConnector/issues/1175.

**Comment by ritwik-singh** [comment]
Hi Bradley,

Thanks for the suggestion! By using MySqlConnection.ClearAllPools, I was able to fix my situation. I appreciate the help.

Best Regards,
Ritwik
