### ISSUE TITLE
Clarification on Passing `null` Values from .NET to MySQL Stored Procedure

### ISSUE THREAD

**Issue by ritwiksingh39** [mysql-net/MySqlConnector#1505]
Hello,

I'm encountering a situation when calling a MySQL stored procedure from a .NET application, and I need some clarification.

Issue:
When I pass null values from .NET to the stored procedure, I'm unsure whether these values are being passed as plain NULL or as @Null. This distinction is crucial for my application logic.

Question:

    Can you clarify whether .NET passes literal value NULL or @Null when null values are sent to a MySQL stored procedure?
    If there's a difference, could you explain how to ensure the correct literal NULL value is passed?
   

Thank you for your assistance!

Best regards,
Ritwik

**Comment by bgrainger** [comment]
> I'm unsure whether these values are being passed as plain NULL or as @null. 

They're passed as a `NULL` value (which can be serialized differently based on whether the text or binary protocol is being used, whether the command is "prepared" or not, etc.).

I'm not familiar with `@null`. Is this just a user-defined variable that has the name `null`? If so, why would that be used to pass stored procedure parameters?

> This distinction is crucial for my application logic.

Why? Can you explain more?
