### ISSUE TITLE
CommandTimeout reached fails to kill query

### ISSUE THREAD

**Issue by SamuelMoisan98** [mysql-net/MySqlConnector#1511]
**Software versions**
MySqlConnector version: 9.0.0 & 8.0.33
Server type (MySQL, MariaDB, Aurora, etc.) and version: 
.NET version: 4.7.2
Tested against MariaDB 10.6.19 and MySQL 8.0.39
(Optional) ORM NuGet packages and versions: 
Tested on MySql.Data 9.0.0 and 8.0.33

**Describe the bug**
When a CommandTimeout is set and it is reached, the query fails to be killed, thus the database engine continues the execution of the query needlessly.

**Exception**
MySql.Data.MySqlClient.MySqlException
  HResult=0x80004005
  Message=Fatal error encountered during command execution.
  Source=MySql.Data
  StackTrace:
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Test.Test.Test() in D:\Code\Test\Test\Test\Test.cs:line 30

Inner Exception 1:
MySqlException: Fatal error encountered attempting to read the resultset.

Inner Exception 2:
MySqlException: Reading from the stream has failed.

Inner Exception 3:
IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Inner Exception 4:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Code sample**
```csharp
var connectionString = $"server=localhost;port=7020;user id=root;password={password};persistsecurityinfo=True;database=test_db";
using (var conn = new MySqlConnection(connectionString))
{
    conn.Open();
    using (var cmd = new MySqlCommand("SELECT SLEEP(600)", conn))
    {
        cmd.CommandTimeout = 5;
        cmd.ExecuteNonQuery();
    }
}
```

**Expected behavior**
The query is killed once the command timeout is reached.

**Additional context**
Documentation supporting the fact that this should be the expected behaviour: https://mysqlconnector.net/overview/command-cancellation/

Specifically, these parts:

...
_Soft. A “soft”, or “logical”, cancellation instructs the MySQL Server to stop executing the command. This is accomplished by sending a KILL QUERY command to the server. Because the MySQL protocol doesn’t permit multiplexing of commands, the KILL QUERY command has to be sent on a different network connection to the same MySQL server. Using a proxy or a Layer 4 load balancer may interfere with the ability to send the KILL QUERY command to the same server and prevent cancellation from occurring. If the cancellation is successful, the underlying MySqlConnection remains usable._

...

_CommandTimeout. Each MySqlCommand has a CommandTimeout property that specifies a timeout in seconds. (This is initialized from the [DefaultCommandTimeout](https://mysqlconnector.net/connection-options/#DefaultCommandTimeout) setting in the connection string.) If this timeout is not 0, then a soft cancellation will be attempted when the timeout expires. If successful, the ExecuteX(Async) method will throw a MySqlException with MySqlErrorCode.CommandTimeoutExpired; its inner exception will be a MySqlException with MySqlErrorCode.QueryInterrupted._

...

**Comment by bgrainger** [comment]
This is the repo for [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/). You appear to be reporting a bug in MySql.Data.

Its bug reporting site is https://bugs.mysql.com/ and you can report bugs there. But I would strongly encourage you to uninstall that package and switch to MySqlConnector instead to benefit from its improved performance and much greater reliability; cf. https://mysqlconnector.net/tutorials/migrating-from-connector-net/#fixed-bugs.
