### ISSUE TITLE
MySqlConnection.DataSource returns null when using Unix Domain Socket

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#152]
[DbConnection.DbConnection](https://docs.microsoft.com/en-us/dotnet/core/api/system.data.common.dbconnection#System_Data_Common_DbConnection_DataSource) abstract method should return:

> The name of the database server to which to connect. The default value is an empty string.

- Adjust to return filename of Unix Domain Socket if connected via UDS.
- Adjust to return empty string if not connected.

**Comment by bgrainger** [comment]
Fixed in [0.9.2](https://www.nuget.org/packages/MySqlConnector/0.9.2).
