### ISSUE TITLE
Unable to get access to table alias name in data reader

### ISSUE THREAD

**Issue by AlexKerman** [mysql-net/MySqlConnector#1521]
When used multiple joins to the same table there no way to find out which alias current column belongs to.

`SELECT * FROM Orders o LEFT JOIN Users u1 ON o.CreatedUserId = u1.Id LEFT JOIN Users u2 ON o.UpdatedUserId = u2.Id`

Both users has BaseTableName "Users" in DbColumn, but no fields have "u1" and "u2" aliases. 
ColumnDefinitionPayload class has PhysicalTableName and Table, but Table does not copy into MySqlDbColumn class.

**Comment by bgrainger** [comment]
Fixed in [2.4.0](https://github.com/mysql-net/MySqlConnector/releases/tag/2.4.0); thanks for the contribution!
