### ISSUE TITLE
Not compatible with .net 4.5.1

### ISSUE THREAD

**Issue by Kagamine** [mysql-net/MySqlConnector#154]
@caleblloyd, The following depedencies refered to `System.Runtime` and the `Guid` in mscorlib will conflict with the `Guid` based in `System.Runtime`

![image](https://cloud.githubusercontent.com/assets/2216750/21493554/fa1e87d2-cc46-11e6-8749-1b6441ba6bad.png)

![image](https://cloud.githubusercontent.com/assets/2216750/21493580/2572036e-cc47-11e6-87be-346ca5fa0d5c.png)

I don't know why Full .NET Framework lib need refer to the .net standard lib.

**Comment by caleblloyd** [comment]
I started a new .NET 4.5.1 project and loaded MySqlConnector up just fine.  What's your whole `App.config` / `project.json` look like

These 3 dependencies are not in the .NET Standard lib so they must be imported as packages

**Comment by caleblloyd** [comment]
My Visual Studio 2015 added this binding redirect in `App.config`

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
        <startup> 
            <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1" />
        </startup>
      <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="System.Runtime.InteropServices.RuntimeInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
          </dependentAssembly>
        </assemblyBinding>
      </runtime>
    </configuration>

**Comment by Kagamine** [comment]
I think `net451` is better than `net45`, because ASP.NET Core requires .NET 4.5.1.  
Besides, the dependencies in full .NET is not `>=`, it is `=`. So it limited full .net must use the specified version.

**Comment by caleblloyd** [comment]
@Kagamine the new MSBuild stuff is tricky.  I'm not 100% convinced that moving the minimum to .NET 4.5.1 will fix the issue.

But I do think moving to .NET 4.5.1 as a minimum is a good idea.  [MySql.Data-Pre](https://www.nuget.org/packages/MySql.Data/7.0.6-IR31) and [System.Data.Common 4.1.0](https://www.nuget.org/packages/System.Data.Common/4.1.0) both have .NET 4.5.1 as a minimum also, so it seems like a reasonable bar to set.

@bgrainger do you see a reason to stick to 4.5 or is it OK to move up to 4.5.1?

**Comment by bgrainger** [comment]
Fixed in [0.10.0](https://www.nuget.org/packages/MySqlConnector/0.10.0).
