### ISSUE TITLE
Varying Async Write Times

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#168]
When performing 100K serial inserts [via the performance test](https://github.com/mysql-net/MySqlConnector/blob/master/tests/MySqlConnector.Performance/Controllers/AsyncController.cs#L102), async insert time varies quite a bit.  I've tested 0.11.5, my experimental LibUV branch, and also tested https://github.com/caleblloyd/MySqlConnector/commit/c09bf4408fb4379ef010f337482a48fb99e2a2ed which puts back the write buffer in SocketByteHandler.

```
SocketByteHandler Async (SocketAwaitable) Without Write Buffer:
"Async: Inserted 100000 records in 00:00:21.8551230"
"Async: Inserted 100000 records in 00:00:27.5332450"
"Async: Inserted 100000 records in 00:00:47.1947310"

SocketByteHandler Async (SocketAwaitable) With Write Buffer:
"Async: Inserted 100000 records in 00:00:33.6649370"
"Async: Inserted 100000 records in 00:00:22.0176500"
"Async: Inserted 100000 records in 00:00:13.8164500"

SocketByteHandler Sync:
"Sync: Inserted 100000 records in 00:00:11.7224070"
"Sync: Inserted 100000 records in 00:00:09.0819600"
"Sync: Inserted 100000 records in 00:00:13.1233600"

StreamByteHandler Async:
"Async: Inserted 100000 records in 00:00:35.0536740"
"Async: Inserted 100000 records in 00:00:29.9859750"
"Async: Inserted 100000 records in 00:00:43.7822220"

StreamByteHandler Sync:
"Sync: Inserted 100000 records in 00:00:10.2828520"
"Sync: Inserted 100000 records in 00:00:09.9139170"
"Sync: Inserted 100000 records in 00:00:11.4057720"

LibUV Pipeline Async:
"Async: Inserted 100000 records in 00:00:13.8066410"
"Async: Inserted 100000 records in 00:00:14.2722870"
"Async: Inserted 100000 records in 00:00:12.2135030"

LibUV Pipeline Sync
"Sync: Inserted 100000 records in 00:00:08.3462260"
"Sync: Inserted 100000 records in 00:00:08.1966820"
"Sync: Inserted 100000 records in 00:00:08.1956210"
```

I'm a bit puzzled form the results here - there must be some configuration LibUV is using that we are not.  I tried adding `m_socket.NoDelay = true` in `MySqlSession.cs`, but that didn't change the variance in results.

I need to get more accurate timing (like real/total/user/sys timing like in #164 ).  @bgrainger do you know of a way to get that sort of profiling information within a single function, since these tests are accessed through a web app?

**Comment by bgrainger** [comment]
I was using [`Process.TotalProcessorTime`](https://msdn.microsoft.com/en-us/library/system.diagnostics.process.totalprocessortime.aspx) (and related functions) to get that information for the process.

I'm not sure I understand your question about "within a single function"; are you wanting to ignore any other requests the web server is handling simultaneously? If so, it seems that that might require something akin to a profiler (e.g., that can sample call stacks every millisecond and filter down to the ones of interest)?

**Comment by bgrainger** [comment]
If we're talking about maximising raw insert performance, then I would suggest changes to the application itself, e.g., `Execute("INSERT INTO x VALUES (a, b, c); INSERT INTO x VALUES (d, e, f); ...")` or `Execute("INSERT INTO x VALUES (a, b, c), (d, e, f), ...")`.

When one `INSERT` statement is executed at a time, the library needs to wait for a response from the server to know if the command was executed successfully, get the last insert row ID, etc. There would seem to be limited (or no) opportunities for pipelining queries, batching writes, etc. in the library itself.

However, these types of bulk queries are a lot harder to generate with an ORM and tend to require custom generation of SQL (with string concatenation). (And if you're using command parameters for the values, as you should, the official connector has a [performance bug](https://bugs.mysql.com/bug.php?id=72564) that probably eliminates any speedups you would get from these bulk inserts.)

So this style of 10K sequential inserts is likely to be a real-world use case, and one worth optimising. However, we should probably provide some advice in our docs on how to avoid fundamental throughput limitations via batching.

**Comment by caleblloyd** [comment]
> I'm not sure I understand your question about "within a single function"

Since the webserver is long-running it will show times in regards to when the webserver was started.  Looks like I could parse `Process.TotalProcessorTime` at the beginning and end of the function, or use a profiling library

> If we're talking about maximising raw insert performance...

Batching is certainly always better for raw insert performance.  This is more of the "ORM" test case you are talking about though, where the ORM wants to know the insert ID of every object that is inserted.  A batching test would stress socket writes a lot more than this does since as you pointed out every single `INSERT` in this test waits for a response from MySql.

**Comment by bgrainger** [comment]
Yes, I essentially just used:

```
var total = Process.GetCurrentProcess().TotalProcessorTime; // and user, and privileged
DoSomething();
total = Process.GetCurrentProcess().TotalProcessorTime - total; // and user, and privileged
```

I wrapped it up into a really simple class: https://gist.github.com/bgrainger/d1076ee2953d15a29502920c5a1783a3

**Comment by bgrainger** [comment]
This issue is three years old, and I'm not sure if there's a specific ask.

We are currently measuring performance using the TechEmpower Framework Benchmarks suite; if there are specific improvements that can improve performance on TFB, they should be opened as separate issues.
