### ISSUE TITLE
Switch authentication command fails with Azure MySQL

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#169]
Forked from PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#181.

When connecting to MySQL on Azure, even if the selected MySQL version is 5.7, the server announces its version as `5.5.0.0`. This causes the [`ServerVersions.SupportsResetConnection` test](https://github.com/mysql-net/MySqlConnector/blob/db8179046f652e18292037553adf6321f549549b/src/MySqlConnector/Serialization/MySqlSession.cs#L113) to be `false` because MySQL Server 5.5 didn't support the "reset connection" command. The code then tries to reset the connection by switching users. Azure MySQL sends an authentication method switch request packet. We send a response, which is rejected by the server.

The same failure to log in can be reproduced with `MySql.Data` by setting the `ConnectionReset=true` connection string setting (it's false by default). This seems to indicate it may be a problem with Azure MySQL, and not with the client.

One workaround would be to detect server version `5.5.0.0` as >= 5.7.3. This may be safe because MySQL never uses four-part version numbers (that's a Microsoft kind of thing to do), so we should never see that number when connecting to a real MySQL Server 5.5 instance. Additionally, the first GA version of MySQL Server 5.5 was 5.5.8 according to [the release notes](https://dev.mysql.com/doc/relnotes/mysql/5.5/en/). Where this might fail is if the user is actually running MySQL Server 5.5 on Azure; presumably it would also announce its version as `5.5.0.0`.

**Comment by bgrainger** [comment]
Now that Azure Database for MySQL is available globally, I've been able to reproduce this issue and [report it in the MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/adb35274-2f20-4968-8026-49a8d7ade1f0/comchangeuser-command-not-supported?forum=AzureDatabaseforMySQL).

**Comment by bgrainger** [comment]
If we change the auth method in [`ChangeUserPayload.Create`](https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/Serialization/ChangeUserPayload.cs#L18), e.g., `unsupported_auth`, I would expect Azure Database for MySQL to respond with an authentication method switch request payload, because `unsupported_auth` is not an auth plugin name that it recognises. Instead, it still replies directly with an error packet with `Access denied for user`.

**Comment by Kagamine** [comment]
@bgrainger could you have a try now, we have a new deploy yesterday.

**Comment by bgrainger** [comment]
@kagamine It still appears that `COM_CHANGE_USER` only works if I strip everything after the `@` sign in the UserID (as per #288). Are you expecting that it should work with a user ID of `username@database`?

**Comment by Kagamine** [comment]
It should work with both username@database or username only. I will ask my teammate about this.

**Comment by bgrainger** [comment]
@Kagamine I tested this again and found that `COM_CHANGE_USER` still doesn't work with a username of `userid@database`. Should I keep waiting for the server to support this, or do I need to introduce an Azure-specific workaround?

**Comment by elemount** [comment]
@bgrainger , advise you should not do any specific workaround for Azure MySQL. Let Azure MySQL team fix it because this is its bug not MySqlConnector's bug.

**Comment by bgrainger** [comment]
From [the linked issue](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/390#issuecomment-333007497):

> this bug has been already fixed but not deployed in all region, I assume it will be deployed soon

I tested again and was not able to reproduce the failure. Closing this as an external bug that has been (or will soon be) fixed in all Azure Database for MySQL regions.
