### ISSUE TITLE
Checks for OS fail on AWS/Lambda

### ISSUE THREAD

**Issue by SebastianC** [mysql-net/MySqlConnector#170]
When executed on within AWS/Lambda, the following line throws a `PlatformNotSupportedException`

```csharp
RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
```

This function is used by `ConnectionSettings` and a few other classes to modify their behavior by platform (such as attempting to use unix sockets vs tcp).  While I have an open support issue with the Lambda team, I don't believe they will resolve this anytime soon.

**Comment by bgrainger** [comment]
Fixed in [0.11.6](https://www.nuget.org/packages/MySqlConnector/0.11.6).
