### ISSUE TITLE
Support Reading into DateTimeOffset

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#175]
#172 adds support for using `DateTimeOffset` in parameters.

MySqlDataReader should also support reading into a `DateTimeOffset` object.

`DateTimeOffset` objects should always be set to UTC timezone when read.

**Comment by bgrainger** [comment]
Fixed in [0.12.0](https://www.nuget.org/packages/MySqlConnector/0.12.0).
