### ISSUE TITLE
Update documentation with DateTime(Offset) known issues

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#176]
Due to limitations with the MySQL [`DATETIME` data type](https://dev.mysql.com/doc/refman/5.7/en/datetime.html), properties of the .NET `DateTime` and `DateTimeOffset` will be lost when added as a `MySqlParameter` value (see #172 for more background).

* `DateTime.Kind` will be lost; `MySqlDataReader.GetValue` will read back the value with `Unspecified` kind.
* `DateTimeOffset.Offset` will be lost; the `DateTimeOffset.UtcDateTime` will be stored in the DB column (but, again, will be read back with an `Unspecified` kind).

The documentation should be updated with these known issues (and possibly some test cases that demonstrate the various issues clearly should be added as a reference).

**Comment by Thejacques1** [comment]
Running into the same issues here. This should be documented and most people will tend to blame their ORM first.

**Comment by ejball** [comment]
It would be great to also document one or more reasonable techniques for storing and retrieving a `DateTimeOffset` without losing its `Offset`, e.g. as a string, or by combining a `DATETIME` and a `TIME`.
