### ISSUE TITLE
Support GetColumnSchema on .NET Core

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#182]
.NET Core adds a new column schema API (to replace `GetSchemaTable` from the .NET Framework): dotnet/corefx#5915

Implement `IDbColumnSchemaGenerator.GetColumnSchema` on `MySqlDataReader` and return schema information.

**Comment by hlngo** [comment]
@bgrainger Thanks for the great work. Do you have any date for this one as well as the others in milestone 1.0?

**Comment by bgrainger** [comment]
Added in [0.27.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.27.0).
