### ISSUE TITLE
Implement MySqlDataAdapter

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#183]
`DataAdapter`, `DataTable`, `DataSet`, etc. are being added in netstandard-2.0: dotnet/corefx#12426

This would allow us to implement `MySqlDataAdapter` in packages targeting netstandard-2.0 or .NET 4.5 (or later).

**Comment by hugosmarques** [comment]
Hello anyone knows when the MySQLDataAdapter will be available?

**Comment by hugosmarques** [comment]
@bgrainger when the MySQLDataAdapter will be available?

**Comment by bgrainger** [comment]
@hugosmarques there is no timeline for when `MySqlDataAdapter` will be added to this library. (And since it's a `netstandard2.0` feature, probably after that's generally available, at the earliest.)

**Comment by bgrainger** [comment]
Implemented in 0.33.0.
