### ISSUE TITLE
[bug] LastInsertedId is always 0

### ISSUE THREAD

**Issue by dotWasim** [mysql-net/MySqlConnector#184]
Hello, _LastInsertedId_ is always 0 even when I don't use async
I used exactly same code from [tutorial page
](https://mysql-net.github.io/MySqlConnector/tutorials/net-core-mvc/)
```
  public async Task InsertAsync()
        {
            var cmd = Db.Connection.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"INSERT INTO `BlogPost` (`Title`, `Content`) VALUES (@title, @content);";
            BindParams(cmd);
            await cmd.ExecuteNonQueryAsync();
            Id = (int) cmd.LastInsertedId;
        }
```

**Comment by caleblloyd** [comment]
That's odd, this is a heavily tested codepath in the connector. Maybe there's a bug in the tutorial though.

What version of MySQL are you using?

**Comment by dotWasim** [comment]
@caleblloyd MySQL Workbench Community (GPL) for Windows version 6.3.8 CE build 1228 (64 bit).
I can send the source code and mysql script to your email if you want to give it a try

**Comment by caleblloyd** [comment]
Sure caleblloyd at gmail dot com

Or you can also put it all in a git repository if you prefer

**Comment by dotWasim** [comment]
@caleblloyd sent to your email

**Comment by bgrainger** [comment]
> That's odd, this is a heavily tested codepath in the connector.

There aren't actually any explicit tests for `LastInsertId`; we should add some. (Although the returned values are obviously DB-dependent, it seems like it would be safe to assume that the returned ID would be `1` in a newly-created table. Or set it explicitly with `CREATE TABLE (...) AUTO_INCREMENT = 1234`.)

**Comment by dotWasim** [comment]
if I couldn't get last created Id, then I have to do explicitly new search (select) query to get the created ID. This will be wast of resources.

**Comment by caleblloyd** [comment]
@dotWasim from what you emailed me, it looks like you are incrementing `company_id` (and potentially other IDs as well) in a stored procedure.

It's my understanding that the MySql Protocol will only set `MySqlCommand.LastInsertId` if the statment affects an `AUTO_INCREMENT` column.  I'm pretty it has the same requirements as the [LAST_INSERT_ID](https://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_last-insert-id) function

To take advantage of this, check out [AUTO_INCREMENT](https://dev.mysql.com/doc/refman/5.7/en/example-auto-increment.html)

**Comment by caleblloyd** [comment]
> There aren't actually any explicit tests for `LastInsertId`

Added one in https://github.com/mysql-net/MySqlConnector/pull/185.  Should be able to merge after we clear up what I believe is an unrelated issue with AppVeyor

**Comment by dotWasim** [comment]
@caleblloyd thanks for your help, you are right.. I changed it to be Auto Increment column, everything is fine now.. thanks
