### ISSUE TITLE
What is the provider name?

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [mysql-net/MySqlConnector#186]
I am working on NLog for mysql [NLog](http://nlog-project.org/documentation/v2.0.1/html/T_NLog_Targets_DatabaseTarget.htm) Which require provider name.

**Comment by jemiller0** [comment]
I think you can use whatever name you want, but, you have to add something like the following to your App.config. I used the same name that Oracle's driver uses. However, I pointed it to the MySqlConnector class instead.

```
  <system.data>
    <DbProviderFactories>
      <add name="MySQL Data Provider" invariant="MySql.Data.MySqlClient" description=".Net Framework Data Provider for MySQL" type="MySql.Data.MySqlClient.MySqlClientFactory, MySqlConnector" />
    </DbProviderFactories>
  </system.data>

```
