### ISSUE TITLE
Possible to use this driver with Entity Framework 6?

### ISSUE THREAD

**Issue by jemiller0** [mysql-net/MySqlConnector#187]
I'm not sure if this is the right place to ask a question. If not, please let me know where to post it and this can be deleted. 

Is it possible to use this driver for Entity Framework 6? I know it works with Entity Framework Core. I have that working, but, I would like to use it with EF 6 as well because there are still issues (missing features and the like) with EF Core.

I've ran into issues with Oracle's driver with regard to timing out connections randomly. So, I would rather use this driver and unfortunately, EF Core isn't yet a workable solution for what I need.

**Comment by bgrainger** [comment]
I'm not really familiar with EF, but I believe that to use EF6 with MySqlConnector, you would need to have an implementation of [`DbProviderServices`](https://msdn.microsoft.com/en-us/library/system.data.common.dbproviderservices.aspx) (and related classes) that implements all the EF functionality and then uses MySqlConnector to talk to MySQL Server.

Oracle has written all that code, but of course it's hard-coded to use their MySql.Data library. It might be possible to fork [their code](https://github.com/mysql/mysql-connector-net/tree/6.9/Source/MySql.Data.EntityFramework6) and replace its underlying ADO.NET connector with this one, but I suspect it would be a maintenance nightmare.

I'm not aware of any non-Oracle project that is working on this (and it's not a goal of this library).

So as far as I know, the anwer is "no, it's not possible".
