### ISSUE TITLE
Support for Stored Procedure command type

### ISSUE THREAD

**Issue by Aerendel** [mysql-net/MySqlConnector#19]
Current version of MySqlCommand only supports CommandType = Text. Supporting stored procedure commands is a must for any realistic migration from the official MySQL Connector.

ps: nice work so far!

**Comment by sjones204g** [comment]
This is really important for my project as well.

**Comment by caleblloyd** [comment]
I have begun work on this here: https://github.com/caleblloyd/MySqlConnector/commit/65701f8ea9e1424376967bc1da6abc5432c9d67c

**Comment by bgrainger** [comment]
Support for stored procedures is available in [0.7.0](https://www.nuget.org/packages/MySqlConnector/0.7.0); please test it out and let us know of any problems!
