### ISSUE TITLE
MSBuild Implicit Reference to NETStandard.Library

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#190]
With RTM tooling, we are now implicitly referencing [NETStandard.Library/1.6.1](https://www.nuget.org/packages/NETStandard.Library/1.6.1).  This implicit requirement will install version `4.3.0` of all of the `System.*` libraries, so we should go ahead and update dependencies to target those.

[The MSDN Blog about NETStandard.Library](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) says that it shims every framework version so that they all appear to provide the same set of APIs.

Once .NET Core 2.0 ships, NETStandard.Library 2.0 will likely also ship and we can ditch the majority of the conditional compile logic because NETStandard.Library 2.0 is supposed to target the .NET 4.6.1 API.

There's 2 options right now:

1. Update `System.*` dependencies to 4.3.0
2. Remove the implicit `NetStandard.Library` reference

From the blog, it appears that the path forward is to use `NETStandard.Library`, and option (1) seems the most sensible for that path.  I'll go ahead and implement a PR for option (1), but if I seemed to have overlooked anything please post here

**Comment by bgrainger** [comment]
I didn't immediately pick up on the distinction between ".NETStandard 1.3" and "NETStandard.Library 1.6.1"; having now read some more: :+1:

**Comment by automagic** [comment]
My understanding is that NETStandard.Library 1.6.1 is not compatible with netcoreapp1.0.   The library seems to work fine when compiled into a netcoreapp1.0 project, but tools that check for netcoreapp1.0 compatiblilty (Amazon.Lamba.Tools 1.5.0+) reject the dependency due to NETStandard.Library 1.6.1.  They claim NETStandard.Library 1.6.0 is the proper one to use with dotnet core 1.0.

Can someone set me straight?

**Comment by caleblloyd** [comment]
@automagic `NETStandard.Library` is irrelevant from a compatibility standpoint.  What's important is the `netstandard` version, which in this library's case we target `netstandard1.3`.  [Here is the version compatibility matrix](https://docs.microsoft.com/en-us/dotnet/standard/library), `netstandard1.0` - `netstandard1.6` are compatible with .NET Core 1.0.

`NETStandard.Library` is just a reference package that defines a set of libraries that are known to work together.  In Microsoft's switch to `.csproj`, they now [implicitly reference](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#implicit-package-references) `NETStandard.Library`, so you will find many packages that reference it.  Still, for compatibility purposes refer to the `netstandard` version, not the `NETStandard.Library` version.

The naming similarity between the two is confusing.
