### ISSUE TITLE
Korean character broken when character_set_database = utf8mb4

### ISSUE THREAD

**Issue by rkttu** [mysql-net/MySqlConnector#192]
I'm using existing database configured with 'character_set_database' = utf8mb4. When I try to run the code below with latest version of MySqlConnector (nuget version 0.7.3), returned Korean string corrupted.

```
            var connectionString = "Server=...;Port=...;Database=...;User Id=...;Password=...;CharSet=utf8mb4";
            using (var mySqlConn = new MySqlConnection(connectionString))
            {
                mySqlConn.Open();
                var cmd = mySqlConn.CreateCommand();
                cmd.CommandText = "select * from `students`";
                var reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    if (String.Equals(reader["name"] as string, "abcd", StringComparison.OrdinalIgnoreCase))
                        continue;

                    Console.WriteLine(reader["name"]);
                }
            }
```

When I try to use Oracle's connector (version 7.0.6-IR31) with this sample code, it displays Korean character normally. I tested connection string's CharSet option with utf8, utf8mb4, euc-kr, but it does not work.

ps. I'm using MariaDB 10.0.21-MariaDB-log (version() function)

**Comment by bgrainger** [comment]
The latest published version of MySqlConnector is 0.14.0; could you re-test with that to ensure this isn't a bug that has already been fixed?

> it displays Korean character normally

Do you mean that `Console.WriteLine` displays it correctly? If so, can you debug this with Visual Studio and verify that the string is still wrong in memory? (`Console.WriteLine` can be affected by console code page settings, so it may be part of the problem here.)

What are the expected and actual values that you're seeing?

**Comment by rkttu** [comment]
Thanks to your reply. As you said, I added a line begin of the program like below and problem solved. And also, debugger shows correct string encoding.

Console.OutputEncoding = Encoding.Unicode;

But one more question, how can Oracle's official driver shows correct characters without modifying Console.OutputEncoding static property? This workaround seems temporary solution.

**Comment by bgrainger** [comment]
> But one more question, how can Oracle's official driver shows correct characters without modifying Console.OutputEncoding static property?

Does the string have the right characters in memory (when inspecting it with the debugger) with Oracle's connector?

**Comment by bgrainger** [comment]
I'm not able to reproduce this yet. What is the charset of the column in your table? You can find out by executing this query:

```
SELECT character_set_name FROM information_schema.`COLUMNS` 
WHERE table_schema = -- fill in "Database" from your connection string here
  AND table_name = "students"
  AND column_name = "name";
```

**Comment by bgrainger** [comment]
I'm now suspecting that if the charset of your column is `euckr`, the official Oracle connector doesn't correctly convert data in that column to Unicode when retrieving it, but is "converting" it to (invalid) Unicode code points corresponding to the DBCS bytes used in the EUC-KR encoding. Then, these are probably rendered "correctly" using the default code page in the Windows command prompt. However, they're the wrong characters, so they will not interop incorrectly with other programs and will eventually cause data corruption.

If so, this is a bug in the Oracle connector (but correct behaviour in this one).

**Comment by rkttu** [comment]
SELECT character_set_name FROM information_schema.`COLUMNS` 
WHERE table_schema = "..."
  AND table_name = "genre"
  AND column_name = "genre_name";

-- Result: utf8mb4

**Comment by rkttu** [comment]
> Does the string have the right characters in memory (when inspecting it with the debugger) with Oracle's connector?
Yes. without console output encoding setup. (Version: 7.0.6-IR31)

**Comment by bgrainger** [comment]
I'm a little confused, because in the original bug report you used `students` and `name`, and above you used `genre` and `genre_name`.

Nevertheless, it sounds like everything is working correctly to me; conversion of characters from Unicode to the current console encoding is outside the scope of this project. Is there anything else outstanding?

**Comment by rkttu** [comment]
Ah. I tested different table on same database. Anyway, thanks for your aid. Currently, I cannot choose Oracle's implementation because it still under construction, so I will stick to MySqlConnector instead Oracle's one.
