### ISSUE TITLE
Connector incorrectly assumes ~all @ -starting words in sql to require user supplied parameter

### ISSUE THREAD

**Issue by jezeri** [mysql-net/MySqlConnector#193]
Consider the following sql:
`SELECT 1 INTO @var;`

This will fail with error "Parameter 'var' must be defined."
I assume that also any other valid sql with @ mark will fail with similar error
`SET @foo = 1;`

Looking at MySqlParser.cs / IsVariableName I can see that one can currently get around this issue using variable names with chars that are not listed in method (eg. ä,ö,å). (This in it self might also be another bug.)  
`SELECT 1 INTO @ö;` 
should work just fine, but for example using these chars in other situations could cause error:
`SELECT * FROM Table WHERE Id = @ö;`

**Comment by bgrainger** [comment]
To enable user variables, you must specify `Allow User Variables=true` in the connection string. This is currently done for compatibility with MySql.Data (see the [official connection string options reference](https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html)).

See also this [StackOverflow answer](http://stackoverflow.com/a/5530583).

**Comment by bgrainger** [comment]
This is currently by design; opened #194 to discuss whether we should change the current behaviour.
