### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException: FUNCTION does not exist

### ISSUE THREAD

**Issue by dotWasim** [mysql-net/MySqlConnector#197]
Hello, I am trying to execute a stored procedure using this code, but it through exception "**MySql.Data.MySqlClient.MySqlException: FUNCTION sys.Confirm_Booking does not exist**" 
```

public int ConfirmBooking()
        {
            var cmd = Db.Connection.CreateCommand() as MySqlCommand;
            cmd.CommandText = "Confirm_Booking";
            cmd.CommandType = CommandType.StoredProcedure;
            MySqlParameter is_booked = cmd.Parameters.Add("@p_status", DbType.Int32);
            is_booked.Direction = ParameterDirection.ReturnValue;
            BindIdWithP_(cmd);
            BindStatus(cmd);
            cmd.ExecuteNonQuery();
            if ((int)cmd.Parameters["@p_status"].Value == 1)
            {
                return appt_number;
            }

            return 0;
        }
```

**Comment by caleblloyd** [comment]
```
            MySqlParameter is_booked = cmd.Parameters.Add("@p_status", DbType.Int32);
            is_booked.Direction = ParameterDirection.ReturnValue;
```

[Stored Procedures](https://dev.mysql.com/doc/connector-net/en/connector-net-tutorials-stored-procedures.html) don't have return values, [Functions](https://dev.mysql.com/doc/refman/5.7/en/functions.html) do have return values.

If `Confirm_Booking` is in fact a Stored Procedure and not a function, this should either be `ParameterDirection.Output`, or if it is returned by your last SQL statement in your procedure you could get the value with `cmd.ExecuteScalar()`

**Comment by caleblloyd** [comment]
Closing, please reopen if you still have issues.

**Comment by dotWasim** [comment]
yes it was my mistake, it fixed the bug.. thanks
