### ISSUE TITLE
Connection Pool Reaper Job

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#217]
This issue is to track a Connection Pool Reaper as discussed by @bgrainger in https://github.com/mysql-net/MySqlConnector/issues/211#issuecomment-290528075:

A relevant quote from [Using Connector/Net with Connection Pooling](https://dev.mysql.com/doc/connector-net/en/connector-net-programming-connection-pooling.html):

> Starting with MySQL Connector/Net 6.2, there is a background job that runs every three minutes and removes connections from pool that have been idle (unused) for more than three minutes. The pool cleanup frees resources on both client and server side. This is because on the client side every connection uses a socket, and on the server side every connection uses a socket and a thread.
> 
> Prior to this change, connections were never removed from the pool, and the pool always contained the peak number of open connections. For example, a web application that peaked at 1000 concurrent database connections would consume 1000 threads and 1000 open sockets at the server, without ever freeing up those resources from the connection pool. Connections, no matter how old, will not be closed if the number of connections in the pool is less than or equal to the value set by the `Min Pool Size` connection string parameter.

MySqlConnector does not currently implement any logic like this; for now you could accomplish something similar by setting `wait_timeout=180` on the server and letting it expire idle connections.

**Comment by bgrainger** [comment]
Shipped in [0.17.0](https://www.nuget.org/packages/MySqlConnector/0.17.0).
