### ISSUE TITLE
Strong name the assembly

### ISSUE THREAD

**Issue by rabidkitten** [mysql-net/MySqlConnector#224]
I have included the MySqlConnector NuGet package in my .NET Core Project and once I signed my assembly, I could no longer build because MySqlConnector is not signed. Can we get this package signed?

**Comment by bgrainger** [comment]
[Microsoft's Guidance](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md):

> For the most part, the majority of applications and libraries do not need strong-names.

Can you explain your use case that requires strong-naming?

**Comment by rabidkitten** [comment]
I didn't realize that Microsoft had changed their position. When I run code analysis on a non-.NET Core solution inside of VS 2017, even today, I receive the warning CA2210 'Sign ... with a strong name key'. Of course, I continued this practice in my .NET Core solution and when adding your package, it being unsigned, resulted in the error above. It results in an error because I turned on Warnings as Errors to prevent developers from checking in code that has warnings (that haven't been addressed). But okay, I will actually unsign my assemblies as a result of the guidance they are providing now. It is interesting though they have not corrected Code Analysis.

**Comment by bgrainger** [comment]
As well as MiniProfiler, ServiceStack.OrmLite would need this dependency to be strong-named: https://github.com/ServiceStack/ServiceStack.OrmLite/pull/602#issuecomment-338299960

It seems like this will be an issue that potentially blocks more widespread adoption of MySqlConnector, so we should start strong-naming.

**Comment by bgrainger** [comment]
[0.30.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.30.0) is strong-named.
