### ISSUE TITLE
MySqlConnection Failover?

### ISSUE THREAD

**Issue by igorvlassov** [mysql-net/MySqlConnector#225]
Dear Sirs,
We plan to implement linux client that should read data from master db but switch to slave db in case of master unavailability. Is it possible to define several connection points for MySqlConnection to achieve this automatically?
Thanks in advance,
Igor

**Comment by bgrainger** [comment]
The [`Server` connection string option](https://mysql-net.github.io/MySqlConnector/connection-options/) can take a comma-delimited list of servers to connect to.

It is not guaranteed that the connector will always try the first server, then fall back to a slave; it may round-robin between them. If you absolutely need to connect to one primary server then fall back to a secondary, then you'll probably need to manage that yourself, e.g.,

```
MySqlConnection connection;
try
{
    connection = new MySqlConnection(primaryConnectionString);
    connection.Open();
}
catch (MySqlException)
{
    connection = new MySqlConnection(secondaryConnectionString);
    connection.Open();
}
// connection is now connected to primary or secondary; use it...
```

**Comment by igorvlassov** [comment]
Thanks a lot for the clarification.
