### ISSUE TITLE
Is this connector supports XA Transactions that work with TransactionScope?

### ISSUE THREAD

**Issue by shisoft** [mysql-net/MySqlConnector#240]
We are working on the project that require distributed transaction feature. `TransactionScope` seems convenient and feasible but it require the underlying connector to work with it. It seems [XA Transactions](https://dev.mysql.com/doc/refman/5.7/en/xa.html) is built for this job on server but I did't see any actual implementation in this connector. I am not sure wether it is supported in other way so I opened this issue for a an answer. 

This is a yes no question if the answer is no, that is fine we can totally use raw sql to do it on our own.

Thanks for your attention

**Comment by bgrainger** [comment]
This connector does not currently support XA Transactions. Issue #13 (not yet implemented) tracks the use of `TransactionScope` (for .NET platforms that support it).

Thanks for bringing XA Transactions to my attention; I'll make a note to investigate them when implementing `TransactionScope` support.

**Comment by Kagamine** [comment]
@bgrainger, Shisoft is a member of Pomelo Foundation. We need this feature now, is there any plans to implement this?

**Comment by bgrainger** [comment]
@Kagamine I have another client that needs `TransactionScope` support, so it's high on my priority list to implement. I've just added it to the [1.0 milestone](https://github.com/mysql-net/MySqlConnector/milestone/1).

**Comment by shisoft** [comment]
@bgrainger Great to hear that. Thanks.

**Comment by bgrainger** [comment]
@Kagamine @shisoft FYI opened #241 to add `TransactionScope` support using XA Transactions.
