### ISSUE TITLE
Azure database for MySQL instance

### ISSUE THREAD

**Issue by Kagamine** [mysql-net/MySqlConnector#262]
@bgrainger 

Please ensure this server will be used in test scene, not business.

**Comment by bgrainger** [comment]
@Kagamine Thank you!

I'm getting a connection error `Client with IP address 71.227.223.X is not allowed to access the server.`

Can you open access to all IP addresses, or for the following ranges:

* 71.227.223.0-71.227.223.255 (my home; dynamic, don't know how often it changes)
* 24.113.118.82 (my office)
* [Appveyor IPs](https://www.appveyor.com/docs/build-environment/#ip-addresses)
  * 74.205.54.20
  * 104.197.110.30
  * 104.197.145.181
  * 146.148.85.29
* [Travis CI IPs](https://docs.travis-ci.com/user/ip-addresses/)
  * 52.45.220.64
  * 52.54.40.118
  * 54.89.89.104
  * 54.82.137.203

FWIW, I would find it convenient to be able to test both with and without SSL but I understand if SSL needs to be required for security.

**Comment by Kagamine** [comment]
I've allowed 0.0.0.0 to 255.255.255.255 and disabled SSL.

**Comment by bgrainger** [comment]
The stored procedure tests are failing because my test user can't create procedures or functions.

If I execute:

```
CREATE FUNCTION echof (
	name VARCHAR(63)
) RETURNS VARCHAR(63)
BEGIN
	RETURN name;
END;
```

then I get:

> ERROR 1418: This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)

If I change it to:

```
CREATE FUNCTION echof (
	name VARCHAR(63)
) RETURNS VARCHAR(63)
DETERMINISTIC
BEGIN
	RETURN name;
END;
```

then I get:

> ERROR 1419: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)

If I try:

```
SET GLOBAL log_bin_trust_function_creators = 1;
```

then I get:

> Error Code: 1227. Access denied; you need (at least one of) the SUPER privilege(s) for this operation

How can I create stored procedures in Azure Database for MySQL?

**Comment by Kagamine** [comment]
I've help you switched on log_bin_trust_function_creators, could you try again?

**Comment by bgrainger** [comment]
@Kagamine Same errors as before (1418 without `DETERMINISTIC` and 1419 with `DETERMINISTIC`).

**Comment by bgrainger** [comment]
@Kagamine Just tried to connect right now, but the instance no longer appears to exist:

```
C:\>nslookup yiszheng-test.mysql.database.azure.com 8.8.8.8
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

*** google-public-dns-a.google.com can't find yiszheng-test.mysql.database.azure.com: Non-existent domain
```

Is there a more permanent server I can rely on?

**Comment by Kagamine** [comment]
I have created a new instance for you.
