### ISSUE TITLE
GetFieldValue<T> error with Booleans

### ISSUE THREAD

**Issue by pabloordonez** [mysql-net/MySqlConnector#266]
I'm having some general issues with booleans, even using TreatTinyAsBoolean=true, but the most important is:
GetFieldValue<T> and GetFieldValueAsync<T> is throwing: 
"Unable to cast object of type 'System.SByte' to type 'System.Boolean'."

There are no alternative async method for GetBoolean or Get[Type] methods, so it forcing me to use sync methods to map from DataReaders. 

Thanks in advance, and great job!!

**Comment by bgrainger** [comment]
Firstly, there's no benefit to using `GetFieldValueAsync`: by the time `ReadAsync` (or `Read`) returns, all the data is already in memory and the synchronous call can return it immediately, while the asynchronous call incurs the overhead of allocating a `Task<bool>` to return it. (So, just use `GetBoolean`.)

Secondly, `GetFieldValue<bool>` is tested [here](https://github.com/mysql-net/MySqlConnector/blob/6d3a0d272645906ef0544133afa197f3178947c1/tests/SideBySide/DataTypes.cs#L158) (via `DoQuery`) and it "works on my machine".

Can you provide more details of your MySQL Server software and version, your table schema, or (ideally) a small self-contained example that repros the bug?

**Comment by bgrainger** [comment]
> there's no benefit to using `GetFieldValueAsync`

Just saw that [our documentation](https://github.com/mysql-net/MySqlConnector/blob/fc5c777e7a11c0867a0399aaf9e5bceef66eac74/docs/content/tutorials/best-practices.md#always-use-async-when-possible) doesn't reflect this; I will have to fix it.

**Comment by pabloordonez** [comment]
Thank you for the fast response. The GetBoolean works, in fact I changed back to GetBoolean as it was before. The one throwing the error is GetFieldValue<bool>(index) method. 
The Db Version is 5.7.17 x86_64 standard configuration.

The table i'm using to test is:

CREATE TABLE IF NOT EXISTS `Project`(
	`Id`					INT AUTO_INCREMENT NOT NULL,
	`Name`				NVARCHAR(200) NOT NULL,

	`RegistrationDate`		DATETIME NOT NULL,
	`ClientId`				INT NOT NULL,
	`Active`				TINYINT NOT NULL,
	`Notes`				TEXT,

	`CreationUserId`		INT NOT NULL,
	`CreationDate`			DATETIME NOT NULL,
	`ModificationUserId`	INT NOT NULL,
	`ModificationDate`		DATETIME NOT NULL,

	CONSTRAINT `PK_Project`				PRIMARY KEY (`Id` ASC),
	CONSTRAINT `FK_Project_ClientId`			FOREIGN KEY (`ClientId`) REFERENCES `Client` (`Id`),
	CONSTRAINT `FK_Project_CreationUser`	FOREIGN KEY (`CreationUserId`) REFERENCES `User` (`Id`),
	CONSTRAINT `FK_Project_MOdificationUser`	FOREIGN KEY (`ModificationUserId`) REFERENCES `User` (`Id`)
)ENGINE=INNODB;


But other than that, the other part of your response already make my day. I'm currently working on scaffolding /code generation tool and a new ORM for .NET core with DbFirst capabilities, and I'm generating the code for some of the classes required. I was experiencing slowdowns when concurrent requests were accessing data, so I was studying if some of the method chain wasn't fully async and I so the documentation using GetFieldValue instead.

Let me know if you need any more info about the error. But your answer already gave me what  I needed. Thanks!

**Comment by bgrainger** [comment]
In MySQL, you need to use

```
`Active`			TINYINT(1) NOT NULL,
```

or 

```
`Active`			BOOL NOT NULL,
```

to create a column that is treated as a `bool` in .NET. (`BOOL` is a MySQL alias for `TINYINT(1)`.)

**Comment by pabloordonez** [comment]
I firstly used BOOL instead, but when you retrieve the schema, is being treated as TINYINT.
So, for the simplicity of it, I just leaved TINYINT for the test tables. Also, GetBoolean works
just fine with TINYINT. I Should test it out with GetFieldValue against BOOL, but  as you already said, it's just an alias.

**Comment by bgrainger** [comment]
MySQL doesn't natively support a Boolean column type; instead you use `TINYINT(1)`. There's a difference between plain `TINYINT` and `TINYINT(1)`. Both use just one byte, but the latter has a display length of `1`; this is a signal to the connector library to treat the column as a Boolean and not a one-byte integer.

(In the C# library you can opt out of this by setting `TreatTinyAsBoolean=false`, `true` is the default.)
