### ISSUE TITLE
(InvalidOperationException) "Invalid state: None"

### ISSUE THREAD

**Issue by zsakszabolcs** [mysql-net/MySqlConnector#27]
Maybe i have found bug.

Reproduction:

```
            using (MySqlConnection connection = await <OpenConnectionFunction()> )
            using (MySqlCommand command = new MySqlCommand("select 1; select 1 from mysql.abc;select 1;", connection))
            using (DbDataReader reader = await command.ExecuteReaderAsync())
            {
                <Some code...>
                await reader.NextResultAsync();
                <Some code...>
                await reader.NextResultAsync();
                <Some code...>
            }
```

The 2nd select in the CommandText is invalid, because the table "abc" does not exist, but I get this exception:
          (InvalidOperationException) "Invalid state: None".

Reason:
1. "MySqlDataReader.Dispose" function tries to close the reader 
2. "MySqlDataReader.DoClose" function tries to read the remaining result sets: `while(NextResult()){}`
3. "MySqlDataReader.NextResultAsync" is not ready for "State.None" state, and throws an exception hiding the original: MySql.Data.MySqlClient.MySqlException - Table 'mysql.abc' doesn't exist

**Comment by bgrainger** [comment]
This was already partially fixed in 601600335883122c293678ab4ae81a0dcc6b6ae3 (which hasn't shipped to NuGet yet); however, I encountered a hang in `ReadAsync` when writing a test to verify this test case is fixed.

**Comment by bgrainger** [comment]
Fixed in https://www.nuget.org/packages/MySqlConnector/0.1.0-alpha08

**Comment by zsakszabolcs** [comment]
Thank you!
