### ISSUE TITLE
Add netstandard2.0 Compile Target once RTM

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#270]
Explore new APIs in [NetStandard.Library: 2.0-*](https://www.nuget.org/packages/NETStandard.Library/2.0.0-preview1-25301-01)

If all of our conditional compile APIs are now supported, this will allow us to target only NetStandard: 1.3 in the library code and drop specific targeting for the full framework.  We should still test against both the full framework and .NET Core so that we can detect platform-specific anomalies.

Code changes should happen in a branch that gets merged to master once .NET Core/Standard 2.0 RTM is released.

**Comment by caleblloyd** [comment]
I think that my previous understanding of NetStandard.Library was incorrect.  NetStandard.Library: 2.0 does not polyfill older versions of `netstandard1.x` to support new APIs.

NetStandard.Library is really just a metapackage that links to other packages, as explained in [this blog post](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/)

That means that in order to make advantage of the new APIs in `netstandard2.0`, we will have to build a package for `netstandard2.0`.  `netstandard2.0` targets:

- .NET Core >= 2.0
- .NET >= 4.6.1

Therefore in order to maintain backwards compatibility we would still need to build:

- `net451` for .NET `[4.5.1 - 4.6.1)` support
- `netstandard1.3` for .NET Core `[1.0.0, 2.0.0)` support

All we should need to do when .NET Standard 2.0 RTM lands is add `netstandard2.0` as a target.  All of our conditional compile flags for `netstandard1.3` will stay as-is.

Since .NET Core 2.0 is supported on all of the same platforms as .NET Core 1.0, it should be reasonable to expect developers to upgrade rather quickly.  Support for `netstandard1.3` in future development could be phased out rather quickly, maybe a year or so after 2.0 RTM.

Once `Windows 8.1` and `Windows Server 2012 R2` are no longer supported we could drop support for `net451` in future development releases, but that likely won't be for a few years.

There's really not all that many conditional compilation flags in the codebase now, and most are for `netstandard1.3`.  The difficulty will be keeping up with testing against different versions of the framework.

**Comment by caleblloyd** [comment]
Regarding end of life dates for Microsoft products:

- [Windows Server 2012 End of Mainstream Support](https://support.microsoft.com/en-us/lifecycle/search?alpha=windows%20server%202012) is currently 10/9/2018
- [.NET Core 1.0 and 1.1 End of Support](https://www.microsoft.com/net/core/support) will be 1 year after .NET Core 2.0 is released

Since .NET Core 2.0 will be released Q3 2017, these dates will coincidentally be very close.  Pending the needs of one of this project's stakeholders, we could likely switch to only targeting `netstandard2.0` in October 2018.

We would need to publish a major version (`1.0`) by then, and once we made the change would  need to increment another major version (`2.0`).

**Comment by Kagamine** [comment]
need support net45

**Comment by caleblloyd** [comment]
@Kagamine  MySqlConnector will continue to support `net451` and up.  It is just additionally adding `netstandard2.0` as a target.

**Comment by Kagamine** [comment]
Our team still using .net 4.5 not451

**Comment by caleblloyd** [comment]
@Kagamine can't they upgrade to `net451`?  `net45` is very old. Windows 8.1 and Windows Server 2012 R2 come with `net451` out of the box, that is all we should need to support since earlier versions of windows are no longer under support.

**Comment by Kagamine** [comment]
Nope, the structure was built by the engineers in redmond, we cannot modify their codes.

**Comment by caleblloyd** [comment]
Could you open a separate issue? It may be as easy as changing `net451` references to `net45`

**Comment by caleblloyd** [comment]
NET Standard 2.0 is now [finalized](https://github.com/dotnet/announcements/issues/24) and the announcement of .NET Core 2.0 will be on September 18-19.

**Comment by Kagamine** [comment]
@caleblloyd The 2.0.0 rtm libraries is ready in nuget
