### ISSUE TITLE
Implement MySqlHelper.EscapeString(string)

### ISSUE THREAD

**Issue by nvivo** [mysql-net/MySqlConnector#277]
There is a simple utility method that escapes strings that is present in the original driver and missing from this implementation.

`MySqlHelper.EscapeString(string)`;

**Comment by bgrainger** [comment]
It seems like this would only be used to build SQL statements by concatenating strings, which I'd normally strongly discourage (use parameterised statements instead).

However, there are some high-performance use cases (e.g., bulk-inserting tens of thousands of rows by building a SQL string) that would benefit from such a function, so I can see value in adding it.

**Comment by nvivo** [comment]
Exactly, I usually create huge commands 1Mb in size each to do bulk inserts or updates in mysql, and it's much faster than using dapper with parameters. This method is handy in these cases.

**Comment by bgrainger** [comment]
Added in [0.21.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.21.0).
