### ISSUE TITLE
Specify Acceptable Server CA / Expose SslStream?

### ISSUE THREAD

**Issue by dhakimTRX** [mysql-net/MySqlConnector#278]
I'm reading through MySqlSession.cs, and it looks like I have no control over the creation of the underlying SslStream  or the remote certificate validation callback.  I would like to pin the server certificate by thumbprint or public key in my application, but this does not appear to be exposed.  

Is there a way to specify an SSL CA certificate to validate the server's cert with (besides installing it as a trusted CA on the client)?  

If not, then as a feature request, can I have more direct access to the SslStream's remote certificate validation callback?  

I'm not 100% sure how certificate pinning is done with MySql in general, but if you know where to put it in the connector api, I can possibly submit a patch.

**Comment by caleblloyd** [comment]
I think that adding a way to verify a self-signed CA is a good idea.  Most people use self-signed certs for MySql and dealing with platform-specific certificate stores can be painful.

[This answer](https://stackoverflow.com/a/9734013/1419658) on SO has the basic way to do this, it would be added to the [remote certificate callback](https://github.com/mysql-net/MySqlConnector/blob/d518c8cbeb969205d02d89dcc2e45b9893112df9/src/MySqlConnector/Serialization/MySqlSession.cs#L550)

We have two options:

1. Take a `SslCa` connection string parameter to a `pem` encoded CA filepath.  This could be validated when using client certs or not
2. Force the CA to be added to the `.pfx` file when client certs are used.  This could only be validated when using client certs

I lean towards option 1, and additionally would like to add the option to provide a `pem` encoded client cert.  Generating the PFX is a pain in the ass and I've only ever seen that used on Windows.  Everything else just uses PEM encoded certs.

@bgrainger do you have an opinion?

**Comment by bgrainger** [comment]
Option 1 sounds good to me. I assume that `SslCa` is similar to the [`--ssl-ca` command-line option](https://dev.mysql.com/doc/refman/5.7/en/secure-connection-options.html#option_general_ssl-ca)? And this would make `VerifyCA` actually have an effect?

(I just checked the Connector/Net docs and I didn't see any equivalent option, so I also assume this is an enhancement to functionality beyond what Connector/Net offers?)

**Comment by caleblloyd** [comment]
Yes, it would be similar to the `SslCa` flag. I'll try to mirror command line naming, although `SSL` is showing its age since `TLS` took over.

`VerifyCA` should work for certificates issued through public CAs recognized through the OS certificate store. This would make it easier to work for self signed CAs without going through the trouble of adding the CA cert as trusted on the OS store.

Yes, I do not see this option in Oracle's official connector. It would be a bonus for MySqlConnector
