### ISSUE TITLE
Decimal data type returns odd, incorrect value

### ISSUE THREAD

**Issue by ScottAllSet** [mysql-net/MySqlConnector#29]
First of all, I'd like to give a big THANKS for putting in the effort to write the community a MySQL driver. This is a life saver!

I'm running into some odd behavior with decimal types.

My table is this:

```
CREATE TABLE `t_test` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `currency` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
```

My C# is this:

```
var conn = new MySqlConnection("Server=127.0.0.1;Database=ccdev;Uid=root;Pwd=password;");
            conn.Open();
            var cmd = conn.CreateCommand();
            cmd.CommandText = "select * from t_test;";
            var reader = cmd.ExecuteReader();
            var testItems = new List<Test>();
            while(reader.Read())
            {
                var t = new Test{
                    id=reader.GetInt64(0),
                    name=reader.GetString(1),
                    currency=reader.GetDecimal(2)
                };
                testItems.Add(t);
            }
```

When I insert a row like so:
`insert into t_test(name, currency) values('Sarah', 85.3);`

The currency value comes back from reader.GetDecimal(2) wrong like this: 44415315.52
It's not consistent but it's always wrong and always a really big number.

Am I doing something wrong?

**Comment by bgrainger** [comment]
I would expect your code to work (based on [some existing tests](https://github.com/bgrainger/MySqlConnector/blob/master/tests/SideBySide.New/DataTypes.cs#L123-L134)) but it's quite possible there's some edge case not being correctly handled yet. Thanks for supplying a concise repro; I'll try to use it to repro the bug you describe soon.

What version of MySQL Server are you running, and on what OS?

**Comment by sjones204g** [comment]
OS: Mac OSX 10.11.6
MySQL 5.7.13 (current GA) running locally
dotnet core 1.0.0-preview2-003121

I will try on MySQL 5.6 shortly.

**Comment by sjones204g** [comment]
I just validated that I'm getting the issue with 5.6.31 as well:
https://dev.mysql.com/downloads/file/?id=463211

**Comment by sjones204g** [comment]
I validated a couple other things just to weed out some possibilities:
1) it happens when I only select the currency column and retrieve it via ordinal 0 (such as your test)
2) it happens when I change the column order to force select * to return it as ordinal 0.

**Comment by bgrainger** [comment]
I installed MySQL Server 5.7.13 on Mac OS X 10.10.5 but couldn't reproduce with a similar (not exactly the same) test case: 909990cfea7d17142ea43959da1f77f499d83fc0 (also passed on Linux).

Are you inserting the row with this connector? Using a literal statement, or using a parameterised insert? Can you verify that the DB does actually contain `85.3` (e.g., with MySQL Workbench)?

It definitely seems consistent with your currency column, but I can't figure out yet what's different.

**Comment by bgrainger** [comment]
> It's not consistent but it's always wrong and always a really big number.

Can you give some more examples of the other bad values you get? There may be some kind of pattern in them that gives a clue to the cause of the bug.

**Comment by sjones204g** [comment]
<img width="579" alt="screen shot 2016-07-28 at 9 38 25 am" src="https://cloud.githubusercontent.com/assets/5465089/17214519/4e515eb4-54a7-11e6-8a3e-9207316c042b.png">
Here's a screenshot of the commands I ran in MySQL workbench and the output.

**Comment by bgrainger** [comment]
If you change your table creation to `currency decimal(13,3) DEFAULT NULL` do you start getting larger "random" numbers, e.g., 4534471829.345?

**Comment by sjones204g** [comment]
I don't get larger whole numbers but the mantissa does increase to 3 digits:
<img width="247" alt="screen shot 2016-07-28 at 1 35 48 pm" src="https://cloud.githubusercontent.com/assets/5465089/17222897/546d9ca6-54c8-11e6-9366-54074f656c3b.png">

**Comment by bgrainger** [comment]
Is it possible you could share the whole `ConsoleApplication.Test` solution (e.g., attach a ZIP to this issue)?

**Comment by sjones204g** [comment]
Certainly!
Here's the code I'm using. I also included the SQL.
[tester.zip](https://github.com/bgrainger/MySqlConnector/files/389621/tester.zip)

**Comment by sjones204g** [comment]
Is it possible the use of invariant culture when parsing the decimal is the problem? Mine is en-US, are you using the same? I'm just spit-balling here.

**Comment by bgrainger** [comment]
Thanks. I can reproduce your problem now, and I think it's a bug in the VS Code debugger.

If I add the following two lines before `testItems.Add(t)`:

```
var currency = t.currency;
var currencyString = t.currency.ToString();
```

then I get the following output in the Variables window:

<img width="251" alt="screenshot 2016-07-28 17 57 50" src="https://cloud.githubusercontent.com/assets/188129/17234351/e8fb14ec-54ec-11e6-9da6-985e000588f9.png">

`t.currency` has the correct value if I store it in another variable, but the property value isn't displayed accurately in VS Code. (Additionally, `System.Console.WriteLine(t.currency)` also prints the expected value.) This may also explain why the value changes each time but is consistent for one run of the program (if it depends on something in the current debugging session).

**Comment by bgrainger** [comment]
I can reproduce the problem with one line of code: ` var t2 = new Test { id = 1, name = "Sarah", currency = 85.3m };`.

In the Variables pane in the debugger, `t.currency` shows the wrong value.

I searched [vscode issues for decimal](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20decimal) but didn't find anything. You may need to report this as a new issue to the VS Code team.

**Comment by bgrainger** [comment]
BTW, you can work around the bug by making `currency` a public field (i.e., `public decimal currency;`) instead of a property (`public decimal currency {get;set;}`). This indicates to me that it might be a problem with Code correctly reading the compiler-generated backing field for the property.

Indeed, if we write the property out in full:

```
public decimal currency
{
    get { return _currency; }
    set { _currency = value; }
}
private decimal _currency;
```

we get the following Variable output:

<img width="236" alt="screenshot 2016-07-28 18 08 56" src="https://cloud.githubusercontent.com/assets/188129/17234501/7911262e-54ee-11e6-8c4d-82c370723ec0.png">

**Comment by bgrainger** [comment]
I've filed this as Microsoft/vscode#9929.

**Comment by sjones204g** [comment]
Thank you very much!
