### ISSUE TITLE
Byte column data type

### ISSUE THREAD

**Issue by edwinloubser** [mysql-net/MySqlConnector#296]
The value of a byte column is incorrectly being mapped to a bool.

**Comment by caleblloyd** [comment]
Is your byte column mapped to `tinyint(1)`? If so you probably want to set `TreatTinyAsBoolean=false` in your connection string. Here's the [connection options](https://mysql-net.github.io/MySqlConnector/connection-options/)

**Comment by edwinloubser** [comment]
It is indeed. Is there anyway to do this without setting it in the connection string?

**Comment by caleblloyd** [comment]
> Is there anyway to do this without setting it in the connection string?

If you want to keep the field a `tinyint`, you could make it a `tinyint(2)` or `tinyint(3)`. It will take up the same storage size, the number after `tinyint` is just [the width property](https://stackoverflow.com/a/5749976)
