### ISSUE TITLE
Implement MySqlCommandBuilder

### ISSUE THREAD

**Issue by yukozh** [mysql-net/MySqlConnector#303]
I'm still working on switch the client into MySqlConnector for Azure database for MySQL, There was an important class MySqlCommandBuilder which you have not supported. 

So, is there any plan for supporting this?

**Comment by bgrainger** [comment]
This should probably be implemented as part of #183 (or shortly thereafter).

Since this type requires `.netstandard2.0` support, it's currently lower-priority than finishing other items in the 1.0 milestone.

**Comment by bgrainger** [comment]
@yukozh Is there anyone on your team who could contribute this code?

**Comment by yukozh** [comment]
Maybe nobody.

**Comment by bgrainger** [comment]
Implemented in [0.34.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.34.0).

The `DeriveParameters` method is yet to come: #419 

@yukozh Please let me know if the implementation added for this case meets your needs.
