### ISSUE TITLE
Add MySqlConnection.CloseAsync

### ISSUE THREAD

**Issue by Rodrigo-Andrade** [mysql-net/MySqlConnector#309]
So we can avoid https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlClient/MySqlConnection.cs#L388

Is there an alternative?

**Comment by Rodrigo-Andrade** [comment]
So we can avoid https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlClient/MySqlConnection.cs#L388

**Comment by bgrainger** [comment]
I don't understand the problem you're indicating with that line of code; can you elaborate?

**Comment by caleblloyd** [comment]
We tried this in #264 and determined that it leads to synchronous thread pool lockups. See the discussion in #264 for more details.

**Comment by Rodrigo-Andrade** [comment]
An unexpected syncronous io call on dispose.

**Comment by Rodrigo-Andrade** [comment]
I edited the title, for some reason the first edit didn't work.

**Comment by bgrainger** [comment]
`Dispose()` is a synchronous method; it performs synchronous I/O by design. And it only happens if you've disabled connection pooling, at which point synchronous I/O is not your biggest problem. :smile:

There is no .NET pattern for asynchronous dispose, but we could add a `CloseAsync` method that extends the functionality of the `DbConnection` interface (just as `BeginTransactionAsync` is an addition).

**Comment by Rodrigo-Andrade** [comment]
> Dispose() is a synchronous method; it performs synchronous I/O by design.

Not questioning this fact, I am just suggesting an api for async dispose/close, I am willing to implement the dispose pattern by hand while something like IAsyncDispose is not implemented.

`BeginTransactionAsync`  is exactly it. 

As to it not doing IO, i just looked at the surface, since it was a task returning method with `IOBehavior.Synchronous` i guessed it was doing some blocking IO 😸 .

It's like we go async for 95% of the code and block at the dispose (if that is the case, gonna look deeper to check)

Thank you very much for your patience.

**Comment by caleblloyd** [comment]
Do you use connection pooling (it is turned on by default)? `MySqlConnection.Dispose` does not do any I/O if connection pooling is used.

**Comment by Rodrigo-Andrade** [comment]
You are right, i missed the return to pool bit, but it seems that when returning the connection do the pool, if the connection is unhealthy, we try again to dispose it using synchronous IO? but for my use case it seems everything will be async most of the time.

Thank you for the in prompt answers
