### ISSUE TITLE
Implement Compression

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#31]
Docs: https://dev.mysql.com/doc/internals/en/compression.html

`MySqlConnectionStringBuilder.UseCompression` already exists, but must be set to `false`; relax this restriction.

**Comment by bgrainger** [comment]
Need to test compressed packets that span the 16MiB boundary (see [implementation note here](https://dev.mysql.com/doc/internals/en/example-several-mysql-packets.html)); the MySql.Data library does not currently handle those correctly:

* http://bugs.mysql.com/bug.php?id=83329
* http://bugs.mysql.com/bug.php?id=83330

**Comment by mguinness** [comment]
When running a specific LINQ query (using Pomelo.EntityFrameworkCore.MySql) and with UseCompression set to true I get `System.InvalidOperationException: Packet received out-of-order. Expected 2; got 93.` error.  This is reproducible.

**Comment by mguinness** [comment]
I did some more investigation and it appears related to the size of the data being returned.  In the example below the InvalidOperationException is raised, but if I set the limit to 74 it is not.

```C#
var cmd = db.CreateCommand();
cmd.CommandText = "SELECT * FROM `companies` LIMIT 75";

using (var rdr = cmd.ExecuteReader())
{
    while (rdr.Read()) { } //Packet received out-of-order. Expected 2; got 100.
}
```

It should also be noted that the loop works for the first 74 iterations, but it fails on the final one.

The following SQL returns 975 KB for the table in question if that is of any help.

```SQL
SELECT ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024) AS `Size (KB)` 
FROM information_schema.TABLES
WHERE TABLE_NAME = 'companies'
```

**Comment by bgrainger** [comment]
@mguinness The repro is probably highly dependent on the exact size of the data (either before or after compression). Would it be possible for me to get a copy of the data (solely for creating a repro of this bug, and to be deleted immediately afterwards)? My contact details are on my GitHub profile page.

**Comment by bgrainger** [comment]
Splitting this bug out to #146.
