### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fatwa** [mysql-net/MySqlConnector#314]
https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/Serialization/HandshakeResponse41Packet.cs

(cs.UseAffectedRows ? 0 : ProtocolCapabilities.FoundRows)
should be changed to
(cs.UseAffectedRows ? ProtocolCapabilities.FoundRows : 0)

**Comment by bgrainger** [comment]
Please explain what the bug is, and why this change is appropriate to fix it.

The proposed change would break these tests: https://github.com/mysql-net/MySqlConnector/blob/04c2ce380ccf1a30a23c91f37e673466399caa3d/tests/SideBySide/UpdateTests.cs#L114-L142
