### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation version 4.0.0 in netfx45

### ISSUE THREAD

**Issue by Kagamine** [mysql-net/MySqlConnector#320]
![image](https://user-images.githubusercontent.com/2216750/30009581-07d7c39a-915c-11e7-9915-c6c1bad26a00.png)

We have added mysqlconnector into our E2E tests, but fails in .NET Framework 4.5

There was an same issue: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/377

**Comment by bgrainger** [comment]
`Pomelo.EntityFrameworkCore.MySql` [requires `netstandard2.0`]( https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.0.0-rtm-10062), which is only supported by .NET 4.7. It is not possible to run a `netstandard2.0` library on .NET 4.5 (because .NET 4.5 [only supports `netstandard1.1`](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)).

Please let me know if I've misunderstood the issue.

**Comment by mguinness** [comment]
@bgrainger Minor correction .NET Standard 2.0 supports .NET Framework 4.6.1 and up, but the rest holds true.

**Comment by bgrainger** [comment]
Thanks for the typo correction (it was even in the article/chart I linked to 😊 ).

**Comment by Kagamine** [comment]
This is NOT pomelo project. This is the Azure database for MySQL.

**Comment by Kagamine** [comment]
As a one branch project(Microsoft internal project), we don't have app.config, we can only add the reference in .csproj file, so the solution which you post in the Pomelo is not work.

**Comment by Kagamine** [comment]
Force added the above lib, there was a new one throw:

![image](https://user-images.githubusercontent.com/2216750/30015326-ccd98432-9182-11e7-8bbe-6bc1303c4adb.png)

If you can, please remove the dependency `System.Runtime.InteropServices.RuntimeInformation `

**Comment by bgrainger** [comment]
Ah, sorry, I misread the OP. You're saying that if you create a new .NET 4.5 project and reference MySqlConnector, it throws this exception at runtime? I'll try to recreate that bug, and also see if there's a way to remove that reference (since on .NET 4.5, we could theoretically use BCL APIs to see if we're running on Windows or Linux (with Mono)).

**Comment by bgrainger** [comment]
I used Visual Studio 2013 to create a new .NET 4.5 C# Console application, and added a reference to MySqlConnector 0.26.1. The program ran successfully. Here is my packages.config:

```
<packages>
  <package id="MySqlConnector" version="0.26.1" targetFramework="net45" />
  <package id="System.Buffers" version="4.0.0" targetFramework="net45" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.0.0" targetFramework="net45" />
  <package id="System.Threading.Tasks.Extensions" version="4.0.0" targetFramework="net45" />
</packages>
```

Here is my .csproj:

```
  <ItemGroup>
    <Reference Include="MySqlConnector, Version=0.26.1.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>packages\MySqlConnector.0.26.1\lib\net45\MySqlConnector.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Buffers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Buffers.4.0.0\lib\netstandard1.1\System.Buffers.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>packages\System.Runtime.InteropServices.RuntimeInformation.4.0.0\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Threading.Tasks.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Threading.Tasks.Extensions.4.0.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

What is the packages.config in your solution? Can you provide any other information that might be useful for trying to reproduce this?

**Comment by Kagamine** [comment]
So, we must refer to all the things which mysqlconnector depended yes?

**Comment by Kagamine** [comment]
The only refer to MySqlConnector will not work.
