### ISSUE TITLE
Issue with Query when there is comment in the query

### ISSUE THREAD

**Issue by RBSProjects** [mysql-net/MySqlConnector#321]
Hi,
Today we faced an issue with the driver and after debugging and investigation found that when there is comment " -- " in the query then its not throwing any error and returns 0 results.

Will you please look into it? it should throw error or like other drivers it should run the query successfully and returns the data.

Thanks,
Fahad

**Comment by bgrainger** [comment]
Please provide more details, such as the query that is failing and code to reproduce the problem.

You can see [from here](https://github.com/mysql-net/MySqlConnector/blob/master/tests/SideBySide/DataTypesFixture.cs#L177) that the tests run a query with an embedded comment without any problems.

**Comment by RBSProjects** [comment]
Something like:

**NOTE**: Query also have Tiny(1) columns which we use for Boolean in .net code with Dapper.

                 SELECT
                    c.Id,
                    c.Name,
                    c.Description,
                    c.Value,
                    c.CreatedOn,
                    -- c.ModifiedOn,
                    -- c.CreatedBy,
                    c.ModifiedBy,
                    c.StateCode,
                    uc.FirstName AS CreatedByName,
                    um.FirstName AS ModifiedByName
                FROM Configuration c
                    LEFT JOIN User uc on c.CreatedBy = uc.Id
                    LEFT JOIN User um on c.ModifiedBy = um.Id
                WHERE c.Id = @configurationId
	                AND c.StateCode = 0

**Comment by bgrainger** [comment]
I added a test to try to reproduce the problem of returning 0 rows with your query, but it successfully returned the (single) expected row: c09050af9f6f649a21a776b2ffb612f30e9e6362

Can you upload a minimal test case (with source code) that reproduces the issue?

**Comment by bgrainger** [comment]
Will reopen if a reproducible test case is given.
