### ISSUE TITLE
HasRows returns false after Read returns false

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#327]
After `MySqlDataReader.Read()` returns `false` (i.e., there are no more rows to read), `MySqlDataReader.HasRows` starts returning `false`. It should still return `true` because the current reader did have rows. 

(This is an incompatibility with Connector/Net; it's also different than SqlClient's behaviour.)

**Comment by jovana** [comment]
I want to add something to the HasRows property.
I found a very strange behavior.

The value of MySqlDataReader.HasRows has changed the moment you request the value of the property. In my opinion it should always the same, right? It seems like it only changed the first and second time you request the value.

```
Dim rs As MySqlDataReader = cmd.ExecuteReader
Dim HasRows As Boolean
HasRows = rs.HasRows    ' <-- this will returns True (this is good)
HasRows = rs.HasRows    ' <-- this will returns False (why, what is changed on the first call?)
HasRows = rs.HasRows    ' <-- this will returns True (again, this is good)
HasRows = rs.HasRows    ' <-- this will returns True (again, now it keeps True al the checkes)
```

**Comment by bgrainger** [comment]
@jovana This is a new bug; I've opened #348 to track it. Thanks for reporting it!
