### ISSUE TITLE
Cannot Open after Dispose

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#331]
Connector/NET allows the following code:

```
var connection = new MySqlConnection("connection string");
connection.Open();
connection.Dispose();
connection.Open();
```

MySqlConnector throws an `ObjectDisposedException` on the last line.

In practice, this could happen if a `MySqlConnection` object was captured by a lambda inside a `using` block, then invoked after the connection is disposed.

**Comment by ejball** [comment]
IMHO, the current behavior is correct and superior; the Connector/NET behavior could mask bugs.

If someone really wants the Connector/NET behavior, e.g. because they don't want to fix legacy code, perhaps we should add (yet) another connection setting?

**Comment by NateMerritt** [comment]
I also agree that MySqlConnector has correct behavior over Connector/NET.  This might be something to mention in the [migration docs](https://mysql-net.github.io/MySqlConnector/tutorials/migrating-from-connector-net/); I don't know if it's worth "fixing" or adding a new connection setting.

**Comment by bgrainger** [comment]
FWIW, `SqlConnection.Dispose()` has the side-effect of clearing the connection string, so this "pattern" doesn't work with it. (It won't throw `ObjectDisposedException`, but `Open` will throw `InvalidOperationException: The ConnectionString property has not been initialized.`)

I haven't tested Npgsql, but `NpgsqlConnection.Open` [calls `Open(...)`](https://github.com/npgsql/npgsql/blob/7e922c89305dbe73c0e394dc5f0d10b88fa3b8b3/src/Npgsql/NpgsqlConnection.cs#L164) which [calls `CheckConnectionClosed`](https://github.com/npgsql/npgsql/blob/7e922c89305dbe73c0e394dc5f0d10b88fa3b8b3/src/Npgsql/NpgsqlConnection.cs#L218) which [calls `CheckDisposed`](https://github.com/npgsql/npgsql/blob/7e922c89305dbe73c0e394dc5f0d10b88fa3b8b3/src/Npgsql/NpgsqlConnection.cs#L1224) which [throws if `_disposed` is true](https://github.com/npgsql/npgsql/blob/7e922c89305dbe73c0e394dc5f0d10b88fa3b8b3/src/Npgsql/NpgsqlConnection.cs#L1231-L1232), and that is [set in `Dispose`](https://github.com/npgsql/npgsql/blob/7e922c89305dbe73c0e394dc5f0d10b88fa3b8b3/src/Npgsql/NpgsqlConnection.cs#L667). So it appears this wouldn't work with Npgsql either.

I think updating the documentation is the correct approach here.
