### ISSUE TITLE
"command 17 not supported now" when using TiDB

### ISSUE THREAD

**Issue by yuuhhe** [mysql-net/MySqlConnector#339]
var conn = new MySql.Data.MySqlClient.MySqlConnection();
            using (conn)
            {
                conn.Open();
            }
            conn = new MySql.Data.MySqlClient.MySqlConnection();
            using (conn)
            {
                conn.Open();    // Crash here!!!
            }

when close connection then use another one, crash on open method with the exception:
MySql.Data.MySqlClient.MySqlException:“ERROR 1105 (HY000): command 17 not supported now”

**Comment by yuuhhe** [comment]
the TiDB project
https://github.com/pingcap/tidb

**Comment by yuuhhe** [comment]
fix with ConnectionReset=false in connectionstring

**Comment by bgrainger** [comment]
This looks like a bug in TiDB itself: pingcap/tidb#4640; it claims to be MySQL Server 5.7.1 but doesn't understand the complete MySQL protocol.

As you discovered, you can work around it by setting `Connection Reset=false` in the connection string.

Note that I get dozens of failures when I run the MySqlConnector integration tests against TiDB, so you may encounter other issues with this database.
