### ISSUE TITLE
HasRows return value is inconsistent

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#348]
@jovana writes (split from #327):

I want to add something to the HasRows property.
I found a very strange behavior.

The value of MySqlDataReader.HasRows has changed the moment you request the value of the property. In my opinion it should always the same, right? It seems like it only changed the first and second time you request the value.

```
Dim rs As MySqlDataReader = cmd.ExecuteReader
Dim HasRows As Boolean
HasRows = rs.HasRows    ' <-- this will returns True (this is good)
HasRows = rs.HasRows    ' <-- this will returns False (why, what is changed on the first call?)
HasRows = rs.HasRows    ' <-- this will returns True (again, this is good)
HasRows = rs.HasRows    ' <-- this will returns True (again, now it keeps True al the checkes)
```

**Comment by jovana** [comment]
Thanks for the fix!

**Comment by bgrainger** [comment]
Fixed in [0.28.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.28.0).

**Comment by Topcoder01** [comment]
I don't think this is fixed, I'm getting the same behavior on the latest version

**Comment by bgrainger** [comment]
@Topcoder01 There's a test that verifies that the OP's bug is fixed: https://github.com/mysql-net/MySqlConnector/blob/518513bc4865a89ebfc365afd5f9c1bc1cf2b260/tests/SideBySide/QueryTests.cs#L817-L847

Do you have steps to reproduce the problem?
