### ISSUE TITLE
Creating a unique index on an existing key used in a relation fails

### ISSUE THREAD

**Issue by softlion** [mysql-net/MySqlConnector#359]
Assume you have this schema
table User
   UserId

table UserDetail
   UserDetailId
   UserId <= set as foreign key to User.UserId

When adding a unique index on UserDetail.UserId in a migration, the scaffolded migration:
- drops the existing index on UserDetail.UserId 
- creates a new unique index on UserDetail.UserId 

This fails when executed on mysql, as mysql enforces the existence of an index on foreign keys columns.

The scaffolded migration should instead:
- rename the existing index to something else, Ex: "IX_UserDetail_UserId_ToDelete"
- create the new unique index
- drop the index IX_UserDetail_UserId_ToDelete

**Comment by softlion** [comment]
moved to Pomelo.EntityFrameworkCore.MySql

**Comment by bgrainger** [comment]
This project just provides the low-level connection from .NET code to MySQL Server; it does not perform any scaffolding or ORM operations.

If you're using Pomelo.EntityFrameworkCore.MySql, please open a bug at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues.
