### ISSUE TITLE
Is "Start Transaction" and "Commit" supported?

### ISSUE THREAD

**Issue by Topcoder01** [mysql-net/MySqlConnector#360]
I remember this working and then I started getting some collisions after switching...

**Comment by bgrainger** [comment]
Transactions are supported, and should be managed with the `MySqlConnection.BeginTransaction(Async)` and `MySqlTransaction.Commit(Async)` methods. See https://github.com/mysql-net/MySqlConnector/blob/master/tests/SideBySide/Transaction.cs in the integration tests for some examples.

It may be possible to manually manage transactions by executing `START TRANSACTION` and `COMMIT` SQL statements, but that seems inadvisable as it would make the connector's internal state out-of-sync with the server. If you're experiencing a regression after switching from Connector/NET, please post more details or a reproducible test case.

**Comment by Topcoder01** [comment]
Thanks, I switched it over to the new way, but I'm having issues with the #349. That I had to revert back to the old driver.
