### ISSUE TITLE
Documentation: Samples need to be updated to .NET Core 2.0

### ISSUE THREAD

**Issue by dustinsoftware** [mysql-net/MySqlConnector#372]
I'll open a PR that moves away from `project.json` references 

Here's the pages so far that I've found:

- [ ] https://mysql-net.github.io/MySqlConnector/tutorials/net-core-mvc/
- [ ] https://mysql-net.github.io/MySqlConnector/tutorials/best-practices/
- [ ] https://mysql-net.github.io/MySqlConnector/overview/installing/

**Comment by bgrainger** [comment]
Fixed by #373.
