### ISSUE TITLE
Support restrictions for GetSchema

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#374]
The `MySqlConnection.GetSchema(string, string[])` overload should support a user-specified list of [restrictions](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/schema-restrictions) on the schema being requested.

`GetSchema("Restrictions")` should return a `DataTable` containing all the available restrictions.

Not implemented as part of #361.

**Comment by dechristo** [comment]
Hi @bgrainger! Can I work on this one? and also on [#494](https://github.com/mysql-net/MySqlConnector/issues/494)

**Comment by bgrainger** [comment]
Yes. Thanks!

I think the implementation should be fairly straightforward in `SchemaProvider.cs`, with a little change in `MySqlConnection.cs` to pass the restrictions through.

**Comment by dechristo** [comment]
Hi @bgrainger !
I opened this [PR](https://github.com/mysql-net/MySqlConnector/pull/616) already because I think it will be easier for you to point my mistakes and also for me to solve my doubts instead of message ping pong.

Thanks for your attention so far!

**Comment by phillipc** [comment]
Hello everybody, we have implemented the restrictions in https://github.com/mysql-net/MySqlConnector/pull/1188

**Comment by bgrainger** [comment]
Implemented in https://github.com/mysql-net/MySqlConnector/pull/1190.
