### ISSUE TITLE
Adding nuget to VS 2017 and while attempt to publish using AWS 2017 toolkit seeing error

### ISSUE THREAD

**Issue by mzd555** [mysql-net/MySqlConnector#377]
... invoking 'dotnet publish', .....
......
......

Error: Project is referencing NETStandard.Library version 1.6.1. Max version supported by netcoreapp1.0 is 1.6.0.
Error: NETStandard.Library 1.6.1 is used for target framework netcoreapp1.1.
Error: Check the following dependencies for versions compatible with netcoreapp1.0:
Error: 	Amazon.Lambda.Serialization.Json : 1.1.0
Error: 	MySqlConnector : 0.29.1

**Comment by bgrainger** [comment]
Try the workaround given here: aws/aws-lambda-dotnet#157

**Comment by mzd555** [comment]
tried the workaround but no luck, still getting the error.

**Comment by mzd555** [comment]
Here is the solutions, 

https://github.com/aws/aws-sdk-net/issues/779

Basically, demoted to version 0.13, did the trick.
