### ISSUE TITLE
Version 0.29.4 no longer on NuGet?

### ISSUE THREAD

**Issue by jemiller0** [mysql-net/MySqlConnector#398]
I have been using MySqlConnector 0.29.4 with Pomelo.EntityFrameworkCore.MySql 2.0.0.1. It appears that Pomelo binds to version 0.29.2 of MySqlConnector. I upgraded to version 0.31.0, but, I found that I was unable to create a binding redirect to get it to work. I think this is because MySqlConnector has publicKeyToken now where it was null before. I tried reverting to the version I had before, but, it no longer appears on NuGet. I think 0.30.0 was where the problem was introduced. The next version down is 0.26,4. I'm wondering if 0.29.4 could be added back to NuGet. If it's a big deal, probably 0.26.4 will work, although I think there were some bugs fixed since then that I ran into. Ideally, I would prefer to use the latest MySqlConnector. However, I'm assuming Pomelo will need to upgrade their library to make it work.

**Comment by bgrainger** [comment]
The assembly was strong-named starting in [0.30.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.30.0): #224 

I thought Pomelo.EntityFrameworkCore.MySql had a release that depended on the strong-named version (and removed a dependency on the `BufferResultSets` connection string setting), but I see now that that hasn't been released.

I've re-released the 0.29.4 release on NuGet, which is the last version compatible with Pomelo.EFCore 2.0.0.1.

**Comment by jemiller0** [comment]
You have amazingly fast turn around. Thanks a lot. I greatly appreciate it.
