### ISSUE TITLE
Possible to implement a bulk import method similar to NpgsqlConnection.BeginBinaryImport()?

### ISSUE THREAD

**Issue by jemiller0** [mysql-net/MySqlConnector#399]
I'm guessing the answer to this is no, since as far as I know the most efficient method to bulk load tables using MySQL is using LOAD DATA which expects to read from text files. But, one of the things I like better about PostgreSQL is that I'm able to use NpgsqlConnection.BeginBinaryImport() (http://www.npgsql.org/doc/copy.html) to stream data from one database server to another without having to first write the data to files. The databases are large, so, I don't want to write them to files (and have to do things like encode/decode fields to/from text). I want to just stream the data across, but, have it loaded in the most efficient/fast manner possible. Would it be possible to create a method in your bulk import class to do this? I suspect this is just wishful thinking since I'm assuming it would need to use LOAD DATA, which as far as I know doesn't support this. But, I thought I would ask. The best solution I've been able come up with for this is to use INSERT statements with multiple sets of  VALUES. However, I have found that this is still considerably slower than using binary import with PostgreSQL or SqlBulkCopy with SQL Server. I'm assuming this is an enhancement request that I would have to submit to Oracle, but, figured I would ask. If you had something like this in your driver, I think it would be a huge bonus.

**Comment by bgrainger** [comment]
According to https://dev.mysql.com/doc/refman/5.7/en/insert-optimization.html, `LOAD DATA` is the fastest way to insert data into MySQL.

MySqlConnector already supports a `MySqlBulkLoader.SourceStream` property, which lets you load data from a .NET `Stream` (without necessarily having to use text files).

If you had a "single-use double-ended Stream class" (that let a producer write bytes to the back of the stream and a consumer pull bytes off the front, and freed memory once it was read), then it seems that you could write the rows from a `MySqlDataReader` to that Stream in CSV format, while simultaneously passing that stream to a `MySqlBulkLoader` (on a different server/connection).

However, this would still route all data through the .NET client; for maximum efficiency it seems that you'd want the two servers to talk directly to each other. I haven't tried this but it looks like [federated tables](https://dev.mysql.com/doc/refman/5.7/en/federated-storage-engine.html) might be your answer (h/t https://stackoverflow.com/a/23822887). For this, you wouldn't need any additional API in MySqlConnector; just execute the SQL statements necessary to create the federated table then [`CREATE TABLE ... SELECT`](https://dev.mysql.com/doc/refman/5.7/en/create-table-select.html) a new local table.

**Comment by jemiller0** [comment]
Thanks Bradley, I think SourceStream is exactly what I was looking for. I will give that a try. If I can get that to work, I think it will be a major improvement and solve some problems that I've been running into for a while. Thanks for your help.

**Comment by bgrainger** [comment]
FYI, MySqlConnector now implements `MySqlBulkCopy` to efficiently load data from a `DataTable` or `IDataReader`: #737.

**Comment by jemiller0** [comment]
Thanks @bgrainger. Much appreciated. I will check it out.

**Comment by bgrainger** [comment]
@jemiller0 There have been a few reports of problems with `MySqlBulkCopy` that didn't exist with `MySqlBulkLoader`. If you have any issues, let me know, and I'll look into it.

**Comment by jemiller0** [comment]
OK, thanks
