### ISSUE TITLE
Issue on rowcount through ExecuteNonQuery() under Transaction

### ISSUE THREAD

**Issue by Mimetis** [mysql-net/MySqlConnector#403]
I'm working with stored procedures.  
I was going crazy with a weird bug.. took my day to point where it *could probably* comes...   

Here is the setup:
* Make an update through a stored procedure
* Use a transaction
* Get the row affected count through the `ExecuteNonquery` method.
* Make this call 5 times

Bug:
Sometimes i get the correct result and sometimes, I get a 0.

``` chsarp
using (var connection = new MySqlConnection(connectionString))
{
    connection.Open();

    using (var t = connection.BeginTransaction(IsolationLevel.ReadCommitted))
    {

        string procName = "servicetickets_update";
        using (var cmd = connection.CreateCommand())
        {
            cmd.CommandText = procName;
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Transaction = t;

            MySqlParameter p = new MySqlParameter();
            p.ParameterName = "inServiceTicketID";
            p.MySqlDbType = MySqlDbType.Guid;
            p.Value = new Guid("04d07d89-3f32-449e-8879-c017ef75d950");
            cmd.Parameters.Add(p);

            p = new MySqlParameter();
            p.ParameterName = "inTitle";
            p.MySqlDbType = MySqlDbType.String;
            p.Value = "A";
            cmd.Parameters.Add(p);

            var rowCount = cmd.ExecuteNonQuery();

            Console.WriteLine("Row count : " + rowCount);

            t.Commit();
        }
        connection.Close();
    }
}
```

I made 5 itérations and here are the results:

```
Row count : 1
Row count : 0
Row count : 1
Row count : 0
Row count : 0
```
I made another iteration:
```
Row count : 1
Row count : 0
Row count : 0
Row count : 0
Row count : 0
```
And another one:
```
Row count : 1
Row count : 1
Row count : 0
Row count : 0
Row count : 0
```
I made a test **without** the transaction. The results become corrects:
```
Row count : 1
Row count : 1
Row count : 1
Row count : 1
Row count : 1
```

Here are some screens:

First pass:
![image](https://user-images.githubusercontent.com/4592555/33224962-b56601a4-d16f-11e7-8c5a-a05af95e06cb.png)

Second pass:
![image](https://user-images.githubusercontent.com/4592555/33224974-d84f32ee-d16f-11e7-8e23-e1568ef2b192.png)

I made a test with `MySQL.Data` and it's working as expected:

![image](https://user-images.githubusercontent.com/4592555/33224983-f103c94e-d16f-11e7-9c15-80a1638d93e8.png)

**Comment by Mimetis** [comment]
The stored procedure is a little bit tricky, here is a light version:

```
CREATE DEFINER=`root`@`localhost` PROCEDURE `servicetickets_update2`(

	inServiceTicketID VARCHAR(36),
	inTitle LONGTEXT
)
BEGIN
UPDATE `servicetickets`
SET  `Title` = inTitle
WHERE `ServiceTicketID` = inServiceTicketID;

/* Since the update 'could' potentially returns 0 as row affected count when we make a double update with the same values, to be sure, make a fake update on metadatas time column */
UPDATE `servicetickets_tracking` 
SET `timestamp` = ROUND(UNIX_TIMESTAMP(CURTIME(4)) * 1000)
WHERE `ServiceTicketID` = inServiceTicketID;

END
```

As you can see, potentially the rowcount comes from an underlying table (here `servicetickets_tracking` )

**Comment by bgrainger** [comment]
Thanks for the detailed bug report. Unfortunately, I've been unable to reproduce this yet with the sample code; see my test implementation here: https://github.com/bgrainger/MySqlConnector/commit/bd571820773842fb55fa4263e0a02ba4e9bf2844

Any advice on what I might have overlooked, or a link to your original code that has the problem?

**Comment by bgrainger** [comment]
One thing to note is that MySql.Data defaults `UseAffectedRows` to `false`, while MySqlConnector uses `UseAffectedRows=true`, to better match the documented behaviour of ADO.NET. I don't think this would affect this situation, because an explicit update is always made in the stored procedure. However, you can change that connection string setting if you need an exact match to MySql.Data behaviour.
