### ISSUE TITLE
Strong Naming and update issues

### ISSUE THREAD

**Issue by nvivo** [mysql-net/MySqlConnector#404]
Since the assembly has been strong named, I had a ton of issues upgrading MySqlConnector in my projects.

I have references that depend on MySqlConnector that now need to be recompiled every time this library updates. The binding redirects are being generated, but for some reason they're not working or they don't work for referenced assemblies.

So far I decided to downgrade to 0.29.4 to avoid these issues, but this is not a good solution.

Since strong naming is not recommended anymore, is there any chance a non-strong named version can be provided? Or better yet, a strong named assembly can be provided as an alternative package instead of the main one?

**Comment by bgrainger** [comment]
Can you give some more information about your project structure? Is it set up with NuGet package references, or project references? Are you using VS2015, VS2017, `dotnet build`, other? Are there compiler errors, or runtime, or both? In what way are the binding redirects "not working"?

FWIW, I've heard (from credible sources that have done it in the past) that publishing two different packages (e.g., `MySqlConnector` and `MySqlConnector.StrongName`) causes more problems than it solves, so I'm unlikely to go that route.

(I know it doesn't help right now, but I'm planning/hoping that the update frequency will reduce post-1.0, to lessen the burden on consumers. Right now, I'm in a "release early, release often" mode which exacerbates the problem.)

**Comment by nvivo** [comment]
In my case, the issue is that I have a hard reference to a DLL that depends on MySqlConnector 0.24 that was compiled a few months ago and that I need to track down the source to recompile it.

I read somewhere that if you change the sign key, binding redirects won't help. So, my problem may be that I compiled without a strong name and now it has, and I need to recompile everything to be able to use binding redirects.

I'll see if that fixes the issue.

**Comment by bgrainger** [comment]
Yes, unfortunately (by strong naming) the identity of the assembly changed, so MySqlConnector <= 0.29.4 and MySqlConnector >= 0.30.0 are two completely different assemblies (from the .NET runtime perspective). All dependencies will need to be updated to >= 0.30.0.

Sorry for the inconvenience.

**Comment by nvivo** [comment]
No problem. I removed that dependency and worked around it, and now the upgrade seems to work.
