### ISSUE TITLE
Row.GetString(int Ordinal) throws exception when columnType can not be directly cast to string.

### ISSUE THREAD

**Issue by robertbeuligmann** [mysql-net/MySqlConnector#406]
Due to the way MySqlConnector is casting values from [GetValue(int)](https://github.com/mysql-net/MySqlConnector/blob/a6852887d928d1289b060eee7e6508fc9252b8d7/src/MySqlConnector/Core/Row.cs#L254) it throws 

`"Unable to cast object of type 'System.Int64' to type 'System.String'."` 

when trying to convert a LongLong columnType when calling [MySqlConnector.Core.Row.GetString()](https://github.com/mysql-net/MySqlConnector/blob/a6852887d928d1289b060eee7e6508fc9252b8d7/src/MySqlConnector/Core/Row.cs#L228) 

Mysql.Data will attempt to convert any row to a string when calling [Mysql.Data.DataReader.GetString(int)](https://github.com/mysql/mysql-connector-net/blob/fcb0843b4140e648195be7ff2ef0f20dda14e45b/Source/MySql.Data/datareader.cs#L683) by calling the final values `.ToString()` method.

**Comment by bgrainger** [comment]
Yes, currently MySqlConnector only allows `GetString` for `TEXT` etc. columns. A workaround is to call `GetValue(int).ToString()` to get a (culture-sensitive) rendering.

**Comment by bgrainger** [comment]
I added numeric/string conversion tests here: https://github.com/mysql-net/AdoNetApiTest/commit/3d8dbc69b7159e7cdd7deffdb753174270bcf82f

While MySql.Data does perform implicit conversions to `string` for numeric types, SqlClient and npgsql do not. 

I've decided to deliberately use the more strict behaviour because implicit conversions to `string` are a notorious source of locale-dependent bugs, and because `GetValue(x).ToString()` is an available workaround.

**Comment by bgrainger** [comment]
[MySql.Data 8.3.0](https://dev.mysql.com/doc/relnotes/connector-net/en/news-8-3-0.html) now deprecates the implicit conversion to string for non-textual columns:

> Calling the MySqlDataReader.GetString() method now throws an `InvalidCastException` exception if the associated column is not a string type.
> 
> The `OldGetStringBehavior` connection option was added to allow (by setting it to `true`) restoring previous behavior by logging a deprecation warning instead of throwing the exception. This option defaults to `false`.
> 
> This option will be removed in the near future, potentially in version 9.0.0.
