### ISSUE TITLE
`System.Char` parameters not supported.

### ISSUE THREAD

**Issue by marcrocny** [mysql-net/MySqlConnector#412]
Attempting to use a char `MySqlParameter` with type `Char` causes an exception at `AppendSqlString()`:
>  System.NotSupportedException: Parameter type Char (DbType: StringFixedLength) not currently supported. 

Workaround: call `ToString()` on the character value when creating the `MySqlParameter`, but kind of annoying. Requires a shim or property type change if using Dapper or other ORM. Connector/NET handles this OOTB.

---
Seems like it should be a quick fix, I'll try to come back to this later. Trying to get tests to pass locally before modifying anything.

**Comment by bgrainger** [comment]
Fixed in [0.33.2](https://www.nuget.org/packages/MySqlConnector/0.33.2).
