### ISSUE TITLE
Implement Command and Exception Interceptors

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#420]
https://dev.mysql.com/doc/connector-net/en/connector-net-interceptors.html

> The BaseCommandInterceptor lets you perform additional operations when a program issues a SQL command. 

It's configured by the connection string and loaded (via reflection) at runtime.

**Comment by bgrainger** [comment]
### Command Interceptors

The existing API is not compatible with async command execution (a big selling point of this library). Although it could be changed to be so, that would introduce significant additional complexity.

It's likely that supporting these would require code refactoring that would hurt performance (e.g., removing `ValueTask`) for all users, not just users who actually add a command interceptor at runtime.

It's also not clear to me what a compelling use case for these interceptors is; moreover, they can easily be implemented via the "Decorator" pattern (e.g., this is how Dapper works).

I tried to search GitHub for uses of command interceptors but only found copies of Connector/NET source code itself (not clients defining derived types).

### Exception Interceptors

Many of the same arguments apply. It's also possible to wrap exceptions (or suppress them, which isn't possible with MySQL's exception interceptors) via the decorator pattern.

**Comment by mguinness** [comment]
I'd raised this previously in https://github.com/mysql-net/MySqlConnector/issues/140.  This would be analogous to [IDbCommandInterceptor](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.interception.idbcommandinterceptor) in EF 6, but isn't yet supported in EF Core - tracked in [Lifecycle hooks](https://github.com/aspnet/EntityFrameworkCore/issues/626) but yet to be implemented.

In terms of use cases it could be useful to define session variables like `SET time_zone = '+00:00';` as there's no other way to achieve this in Entity Framework without command interception.

**Comment by bgrainger** [comment]
> I'd raised this previously in #140.

Hmm, I must have forgotten about that when I created this issue; sorry.

> In terms of use cases it could be useful to define session variables like `SET time_zone = '+00:00';`

Does the suggestion at https://github.com/mysql-net/MySqlConnector/issues/519#issuecomment-397829071 solve this use case? (Assuming you can use the underlying ADO.NET library and attach that event handler when using EF.)

**Comment by mguinness** [comment]
I'd forgotten about that workaround, but that should do the trick.
