### ISSUE TITLE
Version mismatch in NuGet package: .NET Standard 2.0 but only .NET Framework 4.6 (should also have 4.6.1)

### ISSUE THREAD

**Issue by netandrights** [mysql-net/MySqlConnector#421]
Summary: 
we think the .NET Framework Dll within the NuGet package should also target version 4.6.1

Explanation:
We are unable to use the NuGet package of the latest version (0.34.0) in the following situation:

We have a vs 2017 solution with two projects:
1) a Dll that targets .NET Standard 2.0 and uses MySqlConnector 0.34.0

2) a .NET WinForms application that targets .NET Framework 4.6.1 and uses the above described Dll

The project will build and start fine, however the first call of a function within the dll which uses MySqlConnector throws an error:

Could not load file or assembly 'MySqlConnector, Version=0.34.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92' or one of its dependencies. The system cannot find the file specified.

If on the other side we call the same function within the dll from a .NET Core 2.0 Console application all is fine.

The reason is as follows:

The NuGet packages contains Dlls for
a) netstandard2.0
b) net46
but none for net461

The .NET Standard 2.0 Dll as well as the .NET Core 2.0 Console app use Dll a).
But for the WinForms application there is no matching Dll since it targets .NET framework 4.6.1

We think this is inconsequent because .NET framework 4.6.1 is the minimum required to use netstandard2.0 dlls:
https://github.com/dotnet/standard/blob/master/docs/versions.md

Hence we cannot switch the WinForms application back to 4.6 as it then cannot consume our Dll anymore.

MySqlConnector version: 0.34.0
VS version: 15.5.2
Nuget Package Manager Version: 4.5.0.4685
OS version: win10 v1703 (15063.786)

**Comment by bgrainger** [comment]
Is it possible for you to change your WinForms app to target .NET 4.7.1, or must it be restricted to .NET 4.6.1 for some reason?

If it is possible to change, I'd like to know whether that resolves the problem.

**Comment by bgrainger** [comment]
Does dotnet/standard#481 describe your issue? If so, you may need to try the workarounds listed there.

**Comment by bgrainger** [comment]
It appears that `MySqlConnector.dll` is not copied to the `bin` folder of the WinForms app, even though it's a dependency of the netstandard2.0 class library.

One workaround would be to add MySqlConnector to the WinForms app explicitly using NuGet.

**Comment by bgrainger** [comment]
> It appears that MySqlConnector.dll is not copied to the bin folder

This appears to be covered by the "Missing binaries" section of dotnet/standard#481. Closing this an external issue; changing the target frameworks in the MySqlConnector NuGet package will not fix the issue.

**Comment by bgrainger** [comment]
Confirmed that adding `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` (as suggested by the linked issue) to a WinForms application fixes the problem.
