### ISSUE TITLE
bug in StatementPreparer

### ISSUE THREAD

**Issue by Atygayev** [mysql-net/MySqlConnector#429]
If an sql statement has a comment it can be prepared wrongly, without passing parameters in it.
I have a unit test for reproducing the issue:
https://gist.github.com/anonymous/ee94694a0d3c617cc236bc479fdd399f

**Comment by bgrainger** [comment]
Thanks for the test case; I can confirm this bug.

**Comment by bgrainger** [comment]
Fixed in [0.36.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.36.0).
