### ISSUE TITLE
Cannot build on Mono, nuget issues

### ISSUE THREAD

**Issue by Code7R** [mysql-net/MySqlConnector#432]
Precondition:

Debian Sid
Latest mono 5.x from Mono Project's downloads, including nuget 2.12.0.0
Working on master HEAD 78328bbd58848516e79becbce2ba225bfb8545a7

msbuild call fails:
``
"/data/tests/heaptest/MySqlConnector/MySqlConnector.sln" (default target) (1) ->
"/data/tests/heaptest/MySqlConnector/src/MySqlConnector/MySqlConnector.csproj" (default target) (2) ->
"/data/tests/heaptest/MySqlConnector/src/MySqlConnector/MySqlConnector.csproj" (Build target) (2:5) ->
(RunResolvePackageDependencies target) -> 
  /usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file '/data/tests/heaptest/MySqlConnector/src/MySqlConnector/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/data/tests/heaptest/MySqlConnector/src/MySqlConnector/MySqlConnector.csproj]
``

Calling `nuget update` fails too, with `No packages.config, project or solution file specified. Use the -self switch to update NuGet.exe.`

Is something missing in the repo? Are there any user-friendly installation instructions for mono? Those from https://mysql-net.github.io/MySqlConnector/overview/installing/ seem to be made for Windows environment only, and I cannot see any other INSTALL.md file or similar.

**Comment by bgrainger** [comment]
The `dotnet add package MySqlConnector` command works on Linux and macOS (it's not Windows-only), but it requires .NET Core. I haven't personally tried to install this package using Mono, but I would expect it to "just work".

**Comment by bgrainger** [comment]
I think I misread your bug report; you're trying to build with Mono, not just consume the NuGet package in a Mono solution? Please try using .NET Core on Linux to build instead: https://www.microsoft.com/net/download/linux

**Comment by bgrainger** [comment]
The MySqlConnector team uses .NET Core to build & test on Linux (`dotnet build`); mono is not a supported build environment.

I can't find any documentation to suggest that `mcs` supports C# 7.1 or C# 7.2, so I don't think it's worth opening a PR to add support for mono if it doesn't support the latest C# language features.

**Comment by Code7R** [comment]
Alright, I installed the pre-built version from nuget repos in MonoDevelop and it seems to work sufficiently well.

But still, it would be nice to see the build dependencies documented prominently.
