### ISSUE TITLE
Add MySqlDataReader.GetX(string column)

### ISSUE THREAD

**Issue by caspChristian** [mysql-net/MySqlConnector#435]
It seems that only `GetX(int ordinal)` is implemented while Oracles connector implements string column variants for most if not all of the Get methods. Is there any specific reason for this that I have not been able to find?

**Comment by bgrainger** [comment]
Connector/NET adds `GetX(string column)` methods (that aren't part of the `DbDataReader` API). The implementation should be fairly simple:

```
GetInt16(string column) => GetInt16(GetOrdinal(column));
GetInt32(string column) => GetInt32(GetOrdinal(column));
GetInt64(string column) => GetInt64(GetOrdinal(column));
// etc.
```

**Comment by caspChristian** [comment]
Yep, not hard to implement, just wondered if there was any particular reason for it not to be that I had missed.

So in accordance with "Cloning the full API of Connector/NET is not a goal of this project, although it will try not to be gratuitously incompatible. For common scenarios, this package should be a drop-in replacement." ... this should be nice to have (if anyone are up to implementing it) also as I understands the tags: "enhancement", "up for grabs" ;)

**Comment by bgrainger** [comment]
No reason for them not to be implemented; just no one's asked for them before. 😀

(I've never used them; most ORMs seem to use the ordinal-based variants, which would be a little more efficient.)

**Comment by bgrainger** [comment]
Added in [0.36.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.36.0).
