### ISSUE TITLE
CertificateFile without Bundled Key does not use Mutual Authentication

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#436]
Both a Client Certificate and a Client Key are needed to perform [Mutual Authentication](https://en.wikipedia.org/wiki/Mutual_authentication)

`X509Certificate2` allows loading a PEM encoded certificate from CertificateFile, but the [X509Certificate2.HasPrivateKey](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509certificate2.hasprivatekey(v=vs.110).aspx) property will be false.  The SSL connection will still succeed, but will not be mutually authenticated - [SslStream.IsMutuallyAuthenticated](https://msdn.microsoft.com/en-us/library/system.net.security.sslstream.ismutuallyauthenticated(v=vs.110).aspx) will be `false`.  To the user, this is unexpected behavior; when they provide a Client Certificate and the connection succeeds, they would assume the connection is using Mutual Authentication.

Loading separate Certificate and Key files has spotty support - it is possible in `netstandard2.0` but not elegant: https://github.com/dotnet/corefx/issues/17892.  If we wanted to support it, it'd probably be better to find a third-party library (BouncyCastle?) that handles loading and validating certificates in different formats.

I think that the best path forward that does not involve adding dependencies would be to only allow pkcs12 (.pfx) certificates with a bundled Certificate and Private Key in the `CertificateFile`.

**Comment by bgrainger** [comment]
Sounds good. Is the backwards compatibility workaround (for consumers that are currently using `CertificateFile` with a PEM file) to just remove that option from the connection string (i.e., if there's no private key, it doesn't do anything anyway)? (That is, there's no need to add another `DisableMutualAuthentication=true` connection string option to be backwards-compatible?)

**Comment by caleblloyd** [comment]
> Is the backwards compatibility workaround (for consumers that are currently using CertificateFile with a PEM file) to just remove that option from the connection string

That is correct

**Comment by bgrainger** [comment]
Fixed in [0.36.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.36.0).
