### ISSUE TITLE
Stability issues when calling stored procedures in parallel

### ISSUE THREAD

**Issue by sazarubin** [mysql-net/MySqlConnector#444]
MySqlConnector v0.36
MySQL ver. 5.6.36-82.1

When using MySqlConnector under load, we experience serious stability issues. When calling several stored procedures simultaneously in parallel mode we got timeout exception. We suspect that it is connected to procedure caching mechanism, because we have lots of log messages like this:
```
*************************** 121. row ***************************
           Id: 63294
         User: ****
         Host: ****
           db: ****
      Command: Query
         Time: 21
        State: System lock
         Info: SELECT ORDINAL_POSITION, PARAMETER_MODE, PARAMETER_NAME, DATA_TYPE, DTD_IDENTIFIER
                                        FROM information_schema.parameters
                                        WHERE SPECIFIC_SCHEMA = 'redacted' AND SPECIFIC_NAME = 'redacted'
                                        ORDER BY ORDINAL_POSITION
    Rows_sent: 0
Rows_examined: 0
```
Because these queries are performed with locks, they are performed sequentially and affect all users of the DB server

We reproduce this issue by calling many procedures in parallel, please see [tests in the gist](https://gist.github.com/sazarubin/6809950f1929a97a1811f1eb1642e523)

**Comment by bgrainger** [comment]
I ran your tests (thanks for the thorough code sample!) but couldn't reproduce any problems (against MySQL Server 5.7.21 for Windows). With `DegreeOfParallelism = 100`, all the tests completed in 0.17s. I increased it to 500 and the tests took 1.05s (using a maximum of 21 pooled connections so there were never that many simultaneous connections to the DB).

I also tested against MySQL Server 5.6.21 on a Unix server; with `DegreeOfParallelism = 200` all tasks ran to completion in 2.6s.

Do you have any suggestions on how I might be able to reproduce the problem you're experiencing?

> Because these queries are performed with locks

Can you provide more detail on this? There are no transactions, `LOCK TABLES`, etc. in the MySqlConnector client code, so I'm not sure what locks you might be referring to.

**Comment by sazarubin** [comment]
I'm extremely sorry, we cannot reproduce it too now.
Initially, there was an idea that it takes a lot of time to read information_schema.parameters concurrently, but we had realized that even if parameters table contains 300k rows, it works fast.

Also, we misunderstood information in processlist, so we supposed that the procedure cache locked information_schema.parameters, but it was wrong.
