### ISSUE TITLE
Unable to connect on Linux to address "localhost" when using "--bind-address=::1"

### ISSUE THREAD

**Issue by YandyZaldivar** [mysql-net/MySqlConnector#448]
I am using this configuration without problems on Windows, but it doesn't works on Linux. After changing the MySQL option to `--bind-address=127.0.0.1` it worked fine. Also works fine if I use `::1` as address.

The curious part here is that this works perfectly on Windows, whenever I use `localhost` on my connection string it connects to either MySQL running on `127.0.0.1` or `::1`

### Further technical details

MySQL version: Tested with 5.7.x and 8.x
Operating systems: (linux-x64 Ubuntu 16.04) + (Windows 10 x64)
Provider: Pomelo.EntityFrameworkCore.MySql version: 2.0

**Comment by bgrainger** [comment]
What `dotnet --version` are you running? (Or mono?)

Is there a specific exception message and call stack that you get for this error?

**Comment by YandyZaldivar** [comment]
I am using .NET Core 2.0 through [Pomelo](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql)

The exception I get is `Unable to connect to any of the specified MySQL hosts`

```
C:\Users\Yandy>dotnet --version
2.1.100

C:\Users\Yandy>dotnet --info
.NET Command Line Tools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

On my linux machine I don't have dotnet installed, I am just running the published files from Windows.

**Comment by caleblloyd** [comment]
@YandyZaldivar what does your `/etc/hosts` file say?

For example, mine is:

```
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
```

So I would have to use `ip6-localhost` on my Linux machine to connect to `::1`, my `localhost` is ipv4 only

**Comment by YandyZaldivar** [comment]
@caleblloyd 
You can try `::1` as the server address for the mysql connection string on a database configured with `--bind-address=::1`. If that works for you it means you are reaching the server through IPv6 and then the fix would be allowing the connection using `localhost` as the server address.

Generally on sockets in the IPv6 world `localhost` should also refer to IPv6 loopback address unless you give the option to the user to prefer IPv4 addresses over IPv6. As an advantage a server listening on an IPv6 address can also accept clients from IPv4 addresses if desired.

```
127.0.0.1       localhost
127.0.1.1       Yandy-Laptop.localdomain        Yandy-Laptop

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by caleblloyd** [comment]
@YandyZaldivar does connecting to `ip6-localhost` on your machine work with `--bind-address=::1`

What if you change the line in your `/etc/hosts` to:

```
::1     ip6-localhost ip6-loopback localhost
```

After making that change, does connecting to `localhost` work with `--bind-address=::1`

**Comment by YandyZaldivar** [comment]
@caleblloyd thanks, it works. The same file on Windows seems to be configured similarly.

The conclusion is then not to assume a connection to localhost will succeed even when a server is listening on a loopback address.

```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
```
