### ISSUE TITLE
Trouble restoring a project using MySqlConnector on current Debian

### ISSUE THREAD

**Issue by Atastor** [mysql-net/MySqlConnector#449]
_First: I DO have a workaround for the following issue, but as I doubt that this is like it should be, I post it. The workaround is a downgrade to 0.32.0 of MySqlConnector from the latest 0.36.1_

Starting a new dotnet core 2 webapi project, with dev on a Win10 machine and deploying to a Debian 9 one. The so far very basic project runs as it should on the windows machine including mysql access and mysql scaffolding via Pomelo's stuff.

When trying to put it onto the debian machine, it fails trying to restore the MySqlConnector: 
```
error NU1100: Unable to resolve 'MySqlConnector (>= 0.36.1)' for '.NETCoreApp,Version=v2.0'.
```

The `dotnet --info` output of the windows machine:
```
.NET-Befehlszeilentools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

```
And the `dotnet --info` output on the debian 9 machine:
```
.NET-Befehlszeilentools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : fdf361624c1087ec874615382781754392e69118


```

**Comment by bgrainger** [comment]
Is it the `dotnet restore` command that is failing? Can you paste in the full output from running that command on Debian 9?

(BTW, this sounds like a `dotnet` or NuGet problem and should be reported on one of their repositories. Once I upload the package to NuGet, this isn't under my control anymore. The MySqlConnector dependencies haven't changed from 0.32.0 to 0.36.1 so I'm not sure why your workaround would make a difference.)

**Comment by Atastor** [comment]
Well ... thats not much:

```
# dotnet restore
Restoring packages for /<mypath>/MyProject/MyProject.csproj...
/<mypath>/MyProject/MyProject.csproj : error NU1100: Unable to resolve 'MySqlConnector (>= 0.36.1)' for '.NETCoreApp,Version=v2.0'.
Generating MSBuild file /<mypath>/MyProject/obj/MyProject.csproj.nuget.g.props.
Restore failed in 1,56 sec for /<mypath>/MyProject/MyProject.csproj.
Restore completed in 63,31 ms for /<mypath>/MyProject/MyProject.csproj.
Restore completed in 451,04 ms for /<mypath>/MyProject/MyProject.csproj.

```

If I crank up the verbosity of the `dotnet restore` the line number increases, but MySqlConnector is mentioned exactly like above.

**Comment by bgrainger** [comment]
As far as I can tell, this is a `dotnet` (and/or NuGet) issue that I can't diagnose or support. (`MySqlConnector.csproj` and its list of dependent packages haven't changed in a long time.) Unless there's specific information on what should change in MySqlConnector to resolve this problem, I'm going to close it as an external issue.

I suggest filing a bug report at https://github.com/dotnet/cli where `dotnet` experts may be able to help you.

**Comment by Atastor** [comment]
Ok, thank! I 'll see what i can achieve there.
