### ISSUE TITLE
Connection closed on command timeout

### ISSUE THREAD

**Issue by vaintroub** [mysql-net/MySqlConnector#453]
Connector/NET does not close connection when command timeout occurs . Instead, it cancels running query. If I remember correctly, SqlClient would not close a connection either. (Also JDBC drivers from both Oracle and MariaDB would keep the connection open whenever command times out).

Only in MySqlConnector, the command timeout is fatal.

**Comment by bgrainger** [comment]
In MySqlConnector, the command timeout functionality doesn't cancel a running query but destroys the connection; see discussion at https://github.com/mysql-net/MySqlConnector/issues/67#issuecomment-337244578 and https://github.com/mysql-net/MySqlConnector/issues/455#issuecomment-373390188.

The workaround is to either call `MySqlCommand.Cancel()` or use an `ExecuteXAsync` overload with a timeout-based `CancellationToken`.

I understand that this is a change from other ADO.NET connectors. I outlined a plan for improving it here: https://github.com/mysql-net/MySqlConnector/issues/455#issuecomment-373395827

**Comment by bgrainger** [comment]
> Connector/NET does not close connection when command timeout occurs

This appears to have changed in 8.0.11; a timeout exception has now become `Fatal error encountered during command execution` (inner exception `Fatal error encountered attempting to read the resultset`), which closes the connection: https://github.com/mysql-net/MySqlConnector/pull/492/commits/dd0b53a99a26d703069db4efa25c254485c0487a#diff-997601572c07dd2ca5e054c35564cf2eL84

I'm not saying that we shouldn't fix this (because Connector/NET now does the same thing), but just that MySqlConnector's behaviour may now be less of a breaking change.

**Comment by bgrainger** [comment]
Executing `SELECT SLEEP(10);` with `MySqlCommand.CommandTimeout = 1`:

### MySql.Data 6.9.11

```
MySql.Data.MySqlClient.MySqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 System.TimeoutException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
  System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

Afterwards, `MySqlConnection.State == ConnectionState.Open`.

### MySql.Data 6.10.4 / 8.0.11

```
MySql.Data.MySqlClient.MySqlException: Fatal error encountered during command execution.
 MySql.Data.MySqlClient.MySqlException: Fatal error encountered attempting to read the resultset.
  MySql.Data.MySqlClient.MySqlException: Reading from the stream has failed.
   System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
    System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

Afterwards, `MySqlConnection.State == ConnectionState.Closed`.

**Comment by JanBN** [comment]
any update ? Having the same issue

**Comment by ErikWitkowski** [comment]
Thanks @bgrainger for the info! Btw can we get our old TimeoutException back? I just lost a couple of time here on research until I finally found this topic. I don't think it's a problem to get the connection closed, but the exception itself is now misleading.

**Comment by bgrainger** [comment]
> Btw can we get our old TimeoutException back?

MySqlConnector (this library) has never thrown a `TimeoutException`.

If you're referring to changes in Connector/NET (MySql.Data), that library is owned by Oracle and you need to report bugs/feature requests at https://bugs.mysql.com/.

**Comment by carlos-ferreira** [comment]
We had a similar issue.

We experienced timeouts on some queries, when the timeout occurred, the queries would just keep running on MySQL although on the backend we would have an exception.

Users would then retry the operation , which made things worse.

We are not using async on our server, so using cancellation token wasn't an option for us,

So we created a "wrapper" connection object that executes the operation on the database, but before that it grabs the process id so we can kill it in case things go wrong, like a timeout.

Something like this (**this code is incomplete**):

// Execute command method

```
// Class property
MySQLProcessID = -1;

try
{
	this.Connection.Open();
	MySQLProcessID = GetProcessID();


	// Execute the command here
	
}
catch (Exception ex)
{
	KillProcess();
	throw ex;
}
finally
{
	this.Connection.Close();
}
```

// Get Process ID

```
private int GetProcessID()
{
	MySqlConnection connection = (MySqlConnection)this.Connection;
	return connection.ServerThread;
}
```
// Kill Process

```
private void KillProcess()
{
	if (MySQLProcessID != -1)
	{
		// We'll try to kill the process if it's still up
		try
		{
			var processes = this.Connection.Query<MySQLProcess>("SHOW FULL PROCESSLIST", commandType: CommandType.Text);
			if (processes.Any(p => p.Id == MySQLProcessID))
			{
				var killCommand = $"KILL {MySQLProcessID}";
				this.Connection.Execute(killCommand, commandType: CommandType.Text);
			}
		}
		catch (Exception ex)
		{
			// log exception here
		}
	}

	MySQLProcessID = -1;
}
```

**Comment by bgrainger** [comment]
FWIW `MySqlCommand.Cancel` already implements that logic; however, I don't think I've tested calling it from inside a `catch` block.

**Comment by carlos-ferreira** [comment]
Thing is we use Dapper, so i don't have access to the MySQL commands, that's why we implemented it this way.

**Comment by bgrainger** [comment]
Fun fact: if you use Dapper's `GridReader`, it will `Cancel` the command when it's disposed if an exception is thrown: https://github.com/StackExchange/Dapper/blob/1922ef4a8d1fa7e87e9d3fa72daaf18e2ae327cd/Dapper/SqlMapper.GridReader.cs#L425

This may provide an alternate pattern for your code; something like:

```
using (var reader = connection.QueryMultiple(sql))
{
    var data = reader.Read<DataObject>();
} // the command will be cancelled here if reading wasn't successful
```

**Comment by carlos-ferreira** [comment]
Didn't know that, that's pretty cool :) !

The workaround we implemented is actually for those situations where you have one or many Connection.Query<T> on the same method.

Thanks for sharing.

**Comment by bgrainger** [comment]
> Connector/NET does not close connection when command timeout occurs . Instead, it cancels running query. ... Only in MySqlConnector, the command timeout is fatal.

There is now a proposal to implement server-side cancellation (and keep the connection open) for `CommandTimeout`: https://github.com/mysql-net/MySqlConnector/issues/455#issuecomment-702424012

Closing this as a duplicate.
