### ISSUE TITLE
Support named pipe connections

### ISSUE THREAD

**Issue by vaintroub** [mysql-net/MySqlConnector#454]
Named pipe connections on Windows are not supported. (Unlike e.g Unix domain socket connections, which are supported).
When implemented well (*not* like in C/NET, but e.g like in MariaDB's JDBC ), local named pipe connections can be a lot faster than TCP.

**Comment by bgrainger** [comment]
> When implemented well (_not_ like in C/NET)

@vaintroub I'm not familiar with C/NET's implementation (I try to not look at their code) but am wondering what you consider the hallmarks of a "good" implementation?

I already have a transport layer that works over `Stream`; is using that with `NamedPipeClientStream` going to be good enough, or would more low-level operations be needed to get good performance?

**Comment by bgrainger** [comment]
I've got some initial performance numbers back, and they're not great.

### TCP

Method |      Mean |
------------------- |----------:|
OpenFromPoolAsync |  61.57 µs |
OpenFromPoolSync |  44.11 µs |
ExecuteScalarAsync | 112.51 µs |
ExecuteScalarSync |  85.40 µs |
ReadBlobsAsync | 178.99 µs |
ReadBlobsSync | 150.11 µs |
ManyRowsAsync | 803.64 µs |
ManyRowsSync | 752.27 µs |

### Named Pipe

Method |     Mean |
------------------- |---------:|
OpenFromPoolAsync | 180.8 µs |
OpenFromPoolSync | 155.5 µs |
ExecuteScalarAsync | 186.5 µs |
ExecuteScalarSync | 171.8 µs |
ReadBlobsAsync | 315.5 µs |
ReadBlobsSync | 332.5 µs |
ManyRowsAsync | 847.5 µs |
ManyRowsSync | 828.5 µs |

OTOH, they're much better than MySql.Data 8.0.11:

### MySql.Data 8.0.11 Named Pipe

Method |         Mean |
------------------- |-------------:|
OpenFromPoolAsync |     431.5 µs |
OpenFromPoolSync |     441.5 µs |
ExecuteScalarAsync |     764.5 µs |
ExecuteScalarSync |     774.3 µs |
ReadBlobsAsync |   1,109.3 µs |
ReadBlobsSync |   1,093.1 µs |
ManyRowsAsync | 130,283.0 µs |
ManyRowsSync | 133,221.1 µs |

I'd love to benchmark local TCP/IP connections with [SIO_LOOPBACK_FAST_PATH](https://blogs.technet.microsoft.com/wincat/2012/12/05/fast-tcp-loopback-performance-and-low-latency-with-windows-server-2012-tcp-loopback-fast-path/) enabled; that might be the best way to get high-performance local communication on Windows. (But I assume that would require building a custom version of MySQL Server.)

I plan on shipping the feature with these current performance numbers, and potentially revisiting it in the future based on user feedback.

**Comment by vaintroub** [comment]
I doubt that any TCP even with FAST path is better than named pipe. Can you share your code?
MariaDBs JDBC is substantially faster via named pipe, as is native C connector.  IIRC, JDBC is using BufferedStream for input. Also, the pipe name is important , \\.\<pipename> is much better than \\<hostname>\pipename

**Comment by bgrainger** [comment]
Named pipe is opened in this function: https://github.com/mysql-net/MySqlConnector/blob/dce98defdffaf8ccffb4b795187157d096e13f17/src/MySqlConnector/Core/ServerSession.cs#L824

Reading/writing the stream happens here: https://github.com/mysql-net/MySqlConnector/blob/dce98defdffaf8ccffb4b795187157d096e13f17/src/MySqlConnector/Protocol/Serialization/StreamByteHandler.cs

I/O is buffered here: https://github.com/mysql-net/MySqlConnector/blob/dce98defdffaf8ccffb4b795187157d096e13f17/src/MySqlConnector/Protocol/Serialization/BufferedByteReader.cs

`.` is used as the host name if possible: https://github.com/mysql-net/MySqlConnector/blob/dce98defdffaf8ccffb4b795187157d096e13f17/src/MySqlConnector/Core/ConnectionSettings.cs#L26

Does the JDBC driver use a "stream" abstraction, just talk directly to the Win32 API, something else?

**Comment by vaintroub** [comment]
JDBC uses java.io.RandomAccessFile for reading and writing ( but it extends Socket , because this is how different transports are implemented in this driver). 
https://github.com/MariaDB/mariadb-connector-j/blob/master/src/main/java/org/mariadb/jdbc/internal/io/socket/NamedPipeSocket.java

It uses native code,  only for "busy pipe" workaround (Java would throw FileNotFoundException on many concurrent connect requests). If native code is not possible, there is just retry after some sleep.
