### ISSUE TITLE
Row.GetChar(int ordinal) always fails due to invalid cast

### ISSUE THREAD

**Issue by billlx** [mysql-net/MySqlConnector#456]
As currently implemented, this call always fails because the underlying data type returned by Row.GetValue(ordinal) is a string. The MySQL.Data behavior is to return the .NET char data type when the db field definition is char (with no length specification). This could perhaps be resolved by having Row.GetChar cast the Row.GetValue result to string and then applying subscripting, although I am not sure it would behave properly in all cases. In any event, the existing Row.GetChar API is non-functional.

**Comment by bgrainger** [comment]
Fixed in [0.38.0](https://www.nuget.org/packages/MySqlConnector/0.38.0).
