### ISSUE TITLE
MySqlCommand.IsValid() does not allow the Transaction to default to Connection.CurrentTransaction

### ISSUE THREAD

**Issue by billlx** [mysql-net/MySqlConnector#457]
As currently implemented, MySqlCommand.IsValid(out Exception exception) does not check for a null value before requiring its Transaction instance to match Connection.CurrentTransaction. This behavior diverges from MySQL.Data, which does accept such commands. The workaround is not difficult (explicitly assign the MySQLCommand.Transaction property before issuing it), but it would seem worth following the MySQL.Data behavior for interoperability reasons.

**Comment by bgrainger** [comment]
The current (strict) behavior was a deliberate choice (see https://github.com/mysql-net/MySqlConnector/issues/405#issuecomment-347019542) but may need to be changed for compatibility (e.g., see #452).

**Comment by billlx** [comment]
Sorry, I hadn't noticed this earlier issue.

**Comment by bgrainger** [comment]
In MySqlConnector 0.39.0, you can opt in to the Connector/NET behaviour by adding `IgnoreCommandTransaction=true` to your connection string.
