### ISSUE TITLE
MySqlDbType.String not respected when assigning an enum to MySqlParameter Value.

### ISSUE THREAD

**Issue by Naragato** [mysql-net/MySqlConnector#459]
[https://github.com/Naragato/OrmLiteMySQLClientTests](url)

Using the official oracle client with and setting a MySQL param as MySqlDbType.String, and using an enum value results in the string value of the enum inserted into the database. However using mysql-net, int is inserted.

**Comment by bgrainger** [comment]
Fixed in [0.37.1](https://github.com/mysql-net/MySqlConnector/releases/tag/0.37.1).
