### ISSUE TITLE
Serilog logging integration

### ISSUE THREAD

**Issue by marcrocny** [mysql-net/MySqlConnector#463]
Need an IMySqlConnectorLoggerProvider for Serilog. Willing to build/contribute if there isn't one hanging about out there.

**Comment by bgrainger** [comment]
There is not one already; thanks for offering to contribute one!

Please follow the pattern of [MySqlConnector.Logging.log4net](https://github.com/mysql-net/MySqlConnector/tree/master/src/MySqlConnector.Logging.log4net) or [MySqlConnector.Logging.Microsoft.Extensions.Logging](https://github.com/mysql-net/MySqlConnector/tree/master/src/MySqlConnector.Logging.Microsoft.Extensions.Logging): the logging adapter should be a (very small) separate project that implements `IMySqlConnectorLoggerProvider` and adapts it to Serilog's public API.

The project should be named `MySqlConnector.Logging.Serilog`.

Given that MySqlConnector's logging targets the lowest-common denominator, I'm not sure if it's possible to take much advantage of Serilog's structured logging. (But I don't know that much about Serilog so I'll refrain from further comments on the implementation.)

**Comment by bgrainger** [comment]
Published [to NuGet](https://www.nuget.org/packages/MySqlConnector.Logging.Serilog).
