### ISSUE TITLE
Exception when use Sphinx Search

### ISSUE THREAD

**Issue by zokiad** [mysql-net/MySqlConnector#466]
Hi,

I use .net core 2.1 preview 1 and last mysql connector and default sphinx search on debian.
Sphinx search allow to connect with mysql connector.
http://sphinxsearch.com/docs/latest/sphinxql.html

The first connextion to sphinx search work fine but the second, i have this error:

MySqlException: unknown command (code=17)�

MySqlConnector.Core.ServerSession.TryAsyncContinuation(Task<ArraySegment<byte>> task) in ServerSession.cs, line 1067

    Stack Query Cookies Headers 

    MySqlException: unknown command (code=17)�
        MySqlConnector.Core.ServerSession.TryAsyncContinuation(Task<ArraySegment<byte>> task) in ServerSession.cs
        System.Threading.Tasks.ContinuationResultTaskFromResultTask<TAntecedentResult, TResult>.InnerInvoke()
        System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state)
        System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot)
        MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, IOBehavior ioBehavior, CancellationToken cancellationToken) in ServerSession.cs
        MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in ConnectionPool.cs
        MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable<IOBehavior> ioBehavior, CancellationToken cancellationToken) in MySqlConnection.cs
        MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable<IOBehavior> ioBehavior, CancellationToken cancellationToken) in MySqlConnection.cs

With oracle mysql connector, no exception.

Regards

**Comment by bgrainger** [comment]
By default MySqlConnector attempts to reset the connection to a known state, by sending either a ResetConnection or ChangeUser command. It appears that Sphinx doesn't support these commands, so it's giving an error.

To work around this, add `ConnectionReset=false` to your connection string. (Connector/NET does this by default, which is why it works with Sphinx.)

**Comment by zokiad** [comment]
Thanks, work fine with ConnectionReset=false

**Comment by JackRipVim** [comment]
@mguinness :-), I will try the reset.
