### ISSUE TITLE
Implement MySqlConnection.CloseAsync

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#467]
Connector/NET exposes a `MySqlConnection.CloseAsync` API (albeit implemented synchronously).

We could add the same API for clients who want to close the connection asynchronously; however note that in most cases this is just returning the connection to the pool, which is a synchronous operation (so `CloseAsync` would just add overhead).

**Comment by sazarubin** [comment]
Since it isn't an asynchronous operation, is not part of ADO.NET `DbConnection`'s interface, and is needed only for backwards compatibility with Connector/NET, I think it's better to be implemented as an extension, maybe even in a separate package.

**Comment by bgrainger** [comment]
> (so `CloseAsync` would just add overhead).

This can mostly be avoided by not implementing it as an `async` method and instead just returning `Task.CompletedTask`.
