### ISSUE TITLE
ConnectionPools that lose the race hang around, continue reaping

### ISSUE THREAD

**Issue by marcrocny** [mysql-net/MySqlConnector#468]
Since they are empty, this seems like a low-overhead problem, but I'm assuming this isn't desired.

**Comment by bgrainger** [comment]
This was an unwanted side effect of ec8d2090813ee55b49c6c1ae601d52021b730e4c interacting with 97f659f126bce0ff66b81a12f77fd687087a3bb4; it is not intentional (nor desirable).

**Comment by bgrainger** [comment]
Fixed in [0.38.0](https://www.nuget.org/packages/MySqlConnector/0.38.0).
