### ISSUE TITLE
Instrument with DiagnosticSource

### ISSUE THREAD

**Issue by yang-xiaodong** [mysql-net/MySqlConnector#471]
Hello , Thanks for the great work.  

I'm working on APM-related work. Using diagnostics allows users to get more runtime event data, which is helpful for distributed tracking systems.

EntityFramewokCore has provided support for diagnostics, but if users do not use EF, it is difficult for them to obtain these event data, so is there any plan to provide some diagnostic event data at the driver level?

Diagnositics doc :
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md

**Comment by yuleyule66** [comment]
@bgrainger 
I did not find some ADO.NET related "standard", I think maybe we can refer to the SqlClient implementation to do it.

**Comment by jiangjinnan** [comment]
There is not such a diagnostic "standard", you just need to name your diagnostic source and event following your naming convention, and specify the event specific payload.

In general, you can provide the following instrumentation activities:
- Open-Connection
- Close-Connection
- Commit-Transaction
- Rollback-Transaction
- Command-Execution

For each instrumentation activity, it's better define the following events:

- Start: Diagnostic event fired when starting instrumentation activity
- Stop: Diagnostic event fired when stopping instrumentation activity
- Error: Diagnostic event fired when throwing exception.

The following is a demo:
`public static class DiagnosticLogger
{
    private static readonly DiagnosticSource _source = new DiagnosticListener("MySql.Data.MySqlClient");

    public static void OnCommandExecuting(MySqlCommand command, long timestamp)
    {
        if (_source.IsEnabled("MySql.Data.MySqlClient.CommandExecution.Start"))
        {
            _source.Write("MySql.Data.MySqlClient.CommandExecution.Start", new { Command = command, Timestamp = timestamp });
        }
    }

    public static void OnCommandExecuted(MySqlCommand command, TimeSpan slaped)
    {
        if (_source.IsEnabled("MySql.Data.MySqlClient.CommandExecution.Stop"))
        {
            _source.Write("MySql.Data.MySqlClient.CommandExecution.Stop", new { Command = command, Slaped = slaped });
        }
    }

    public static void OnCommandError(MySqlCommand command, Exception exception)
    {
        if (_source.IsEnabled("MySql.Data.MySqlClient.CommandExecution.Error"))
        {
            _source.Write("MySql.Data.MySqlClient.CommandExecution.Error", new { Command = command, Exception = exception });
        }
    }
}

internal class TextCommandExecutor : ICommandExecutor
{
    public Task<int> ExecuteNonQueryAsync(string commandText, MySqlParameterCollection parameterCollection, IOBehavior ioBehavior, CancellationToken cancellationToken)
    {
        var command = new MySqlCommand(commandText);
        DiagnosticLogger.OnCommandExecuting(command);
        var sw = Stopwatch.StartNew();
        try
        {
            //...
            DiagnosticLogger.OnCommandExecuted(command, sw.Elapsed);
        }
        catch (Exception ex)
        {
            DiagnosticLogger.OnCommandError(command, ex);
        }
    }
}`

**Comment by holyslon** [comment]
Hello folks. We really need this functionality. We need it for integration with OpenTracing. May be is there any way we can help you do this?

**Comment by bgrainger** [comment]
I haven't looked into OpenTracing much yet. Would it be possible to integrate with OpenTracing by writing a wrapper `DbDataReader` that delegates to an underlying database provider, but sends spans to an OpenTracing collector? I've written something similar before: https://github.com/Faithlife/FaithlifeTracing/tree/master/src/Faithlife.Tracing.Data (and it's vendor-neutral).

**Comment by martinjt** [comment]
Is/has anyone picking/picked this up?

**Comment by bgrainger** [comment]
Just answered here: https://github.com/mysql-net/MySqlConnector/pull/493#issuecomment-705229536

**Comment by bgrainger** [comment]
Superseded by https://github.com/mysql-net/MySqlConnector/issues/1036.

**Comment by bgrainger** [comment]
Available in [2.0.0-beta.5](https://github.com/mysql-net/MySqlConnector/releases/tag/2.0.0-beta.5).
