### ISSUE TITLE
In `MySqlConnection`, connection settings access is inconsistent.

### ISSUE THREAD

**Issue by marcrocny** [mysql-net/MySqlConnector#473]
Some connection-settings based properties use `m_connectionSettings` directly, some use `GetConnectionSettings()`. `m_connectionSettings` is `null` until set directly there or in `CreateSessionAsync`.

The upshot is that if an accessor like `AllowUserVariables => m_connectionSettings.AllowUserVariables` is called before one like `DefaultCommandTimeout => GetConnectionSettings().DefaultCommandTimeout` and before trying to `Open`, it will throw a `NullReferenceException`.

I'll submit a PR tonight (if Brad doesn't beat me to it).

**Comment by bgrainger** [comment]
What's the code path that causes a `NullReferenceException` to be thrown? (I tried to add sufficient tests to ensure this didn't happen, e.g., e0ea838651c88382fba819ac6c76b79c85280dc1, 188d6ee27bb6dfa893e2365d7413f8d6033d88b2, but it sounds like I may have missed some?)

The reason to not always call `GetConnectionSettings()` is to a) avoid unnecessary object creation and b) the properties that access it directly were intended to only be accessed once the connection was in an open state.

**Comment by bgrainger** [comment]
There are inconsistent access patterns in the code (for performance reasons), but there are no known problems caused by them.
