### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired

### ISSUE THREAD

**Issue by squalsoft** [mysql-net/MySqlConnector#485]
I have this problem several months and i can't find the reason why this is happens. 
When i have high load on my website, connections to database from .net core increases to max value of my connection string (maximumpoolsize=100). And after that i receive multiple Connect timeouts. In meanwhile database is free, without locks, queries from another systems executes immediately (less than a second).
So my connection pool is full, queries to database is not executed and database in this time works well. It seems that system can't get connection from pool because old connections are hang. What can it be? Please help me. 

```
MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired. ---> System.OperationCanceledException: The operation was canceled.
Apr 18 10:33:00 web portal[962]:    at System.Threading.CancellationToken.ThrowOperationCanceledException()
Apr 18 10:33:00 web portal[962]:    at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__32.MoveNext()
Apr 18 10:33:00 web portal[962]: --- End of stack trace from previous location where exception was thrown ---
Apr 18 10:33:00 web portal[962]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Apr 18 10:33:00 web portal[962]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Apr 18 10:33:00 web portal[962]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Apr 18 10:33:00 web portal[962]:    at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
Apr 18 10:33:00 web portal[962]:    at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__0.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 30
Apr 18 10:33:00 web portal[962]: --- End of stack trace from previous location where exception was thrown ---
Apr 18 10:33:00 web portal[962]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Apr 18 10:33:00 web portal[962]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Apr 18 10:33:00 web portal[962]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Apr 18 10:33:00 web portal[962]:    at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 355
Apr 18 10:33:00 web portal[962]:    at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 370
Apr 18 10:33:00 web portal[962]: --- End of stack trace from previous location where exception was thrown ---
Apr 18 10:33:00 web portal[962]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Apr 18 10:33:00 web portal[962]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Apr 18 10:33:00 web portal[962]:    at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__19.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 160
```

**Comment by squalsoft** [comment]
<img width="500" alt="mysql stats" src="https://user-images.githubusercontent.com/1629660/38931174-faf3248c-431a-11e8-8000-fd439c93e246.png">

**Comment by squalsoft** [comment]
As you can see from screenshot server is free, cpu is free, a lot of free memory and selects per second: 0. This is Ubuntu 16.04 server with "Pomelo.EntityFrameworkCore.MySql" Version="2.0.1" which uses  MySqlConnector (>= 0.32.0). I use EF Core but also I tried to execute just plain mysql commands and no luck. They use same connections pool and all commands die in one queue.

**Comment by bgrainger** [comment]
Which version of MySqlConnector are you using? A serious leak was fixed in 0.38.0 (see #469, though note it isn't the same exception you report, so it may be a different issue), so please update to at least 0.38.0 and let me know if you can still reproduce the problem.

**Comment by bgrainger** [comment]
> When i have high load on my website, connections to database from .net core increases to max value of my connection string (maximumpoolsize=100). … So my connection pool is full, queries to database is not executed … It seems that system can't get connection from pool because old connections are hang.

This could be expected behaviour. What is "high load" on your website? Is it possible you have more than 100 concurrent requests executing, and each is opening a database connection and keeping it open (not returning it to the pool)?

**Comment by squalsoft** [comment]
I use 0.32 version from Pomelo.EntityFrameworkCore.MySql latest package. I will change to latest MySqlConnector 0.40.1 and give it a try.
I have sometimes more than 100 simultaneous requests to my Nginx reverse proxy. I register Entity framework context as default dependency injection and inject it in my MVC Controller's constructor. I don't dispose it manually.

**Comment by marcrocny** [comment]
@squalsoft, If it is that pathological, is it possible you're leaking (not disposing) connections in your code? That would be the first thing to rule out.

I am currently using/testing MySqlConnector in a high-load scenario, I haven't seen anything quite like this. Do note, that the connection time-out is not related to a MySQL time-out, but rather the wait to get a connection from the pool. In my situation, I set the `ConnectionTimeout` to a relatively large value, and hook into the `MySqlConnection.StateChange` event to log warnings when wait times start to go above 30% of the full timeout. This keeps timeouts from causing service failure, but allows me to keep an eye on strain.

**Comment by marcrocny** [comment]
Close. I conveniently already had a "context" wrapper around each connection, for DI purposes. I am able to attach to the event within the context instance. The handler starts/stops/observes a `Stopwatch` on the `Connecting`/`Open` transitions.

**Comment by squalsoft** [comment]
Thank you! With explicitly added package <PackageReference Include="MySqlConnector" Version="0.40.1" /> i have no more than 50 connections in high load time. It seems that problem resolved. 👍

**Comment by hack2root** [comment]
in my case, problem was database table changes during commits, so after finalizing all commits, all went ok

**Comment by gauravpandey404** [comment]
> Thank you! With explicitly added package i have no more than 50 connections in high load time. It seems that problem resolved. 👍

Hi, which explicitly added package helped you to resolve the issue? I am also stuck and had faced this issue on my production environment 3-4 times. Please help

**Comment by squalsoft** [comment]
> > Thank you! With explicitly added package i have no more than 50 connections in high load time. It seems that problem resolved. 👍
> 
> Hi, which explicitly added package helped you to resolve the issue? I am also stuck and had faced this issue on my production environment 3-4 times. Please help

I think this is slow database problem. Now i have Galera cluster configuration and no have this issue. Try to monitor database load.

**Comment by panjung** [comment]
Although it is closed, I would like to mention that I solved the error by specifying Time out in the connection string.  It was a little time-consuming on Google search to find out this: Add "default command timeout=120; " at the connection string.

See here: https://dev.to/solrevdev/mysqlexception-0x80004005-the-command-timeout-expired-before-the-operation-completed-khj

**Comment by codeprefect** [comment]
I just encountered this issue in one application, reverting to version 2.2.5 fixes it though.
