### ISSUE TITLE
Improved Guid support

### ISSUE THREAD

**Issue by ejball** [mysql-net/MySqlConnector#497]
We should add a `GuidFormat` connector option that specifies how the `Guid` type is read/written.

| Option | Description |
| --- | --- |
| `Char36` | All columns of `CHAR(36)` are read/written as `Guid` using lowercase hex and hyphens. (Current default behavior.) |
| `Char32` | All columns of `CHAR(32)` are read/written as `Guid` using lowercase hex without hyphens. |
| `Binary16` | All columns of `BINARY(16)` are read/written as `Guid` using big-endian byte order. Matches [`UUID_TO_BIN(x)`](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid-to-bin). |
| `TimeSwapBinary16` | All columns of `BINARY(16)` are read/written as `Guid` using big-endian byte order with time parts swapped. Matches [`UUID_TO_BIN(x,1)`](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid-to-bin). |
| `OldBinary16` | All columns of `BINARY(16)` are read/written as `Guid` using little-endian byte order. (Current behavior when `OldGuids=True`.) |
| `None` | `Guid` is not supported. `CHAR(36)` and `CHAR(32)` are read/written as strings; `BINARY(16)` is read/written as a byte array. |

**Comment by ejball** [comment]
Work in progress: https://github.com/mysql-net/MySqlConnector/compare/master...ejball:guids

**Comment by bgrainger** [comment]
Added in [0.41.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.41.0).
