### ISSUE TITLE
Does MySqlConnector support nHibernate ORM? 

### ISSUE THREAD

**Issue by Johpilliar** [mysql-net/MySqlConnector#511]
We are migrating our database from MSSQL to Aurora(MYSQL). The application is using .net and NHibernate. We would like to know if  MySqlConnector will work with NHibernate 5.1?

**Comment by bgrainger** [comment]
Based on the comments at nhibernate/nhibernate-core#1375 (and the linked, empty repository), it appears that this is planned but not yet implemented. 

There shouldn't be any reason it wouldn't work in theory, but would just need a small amount of glue code to be written. 

I'm not very familiar with NHibernate but using it with MySqlConnector might be as simple as writing a copy of this class (in your project) with the `MySql.Data` assembly name changed: https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Driver/MySqlDataDriver.cs

**Comment by fedesasso** [comment]
I'm currently using MySqlConnector with NHibernate.
Other than the suggested customized version of MySqlDataDriver with the changed assembly name, I had to add support in MySqlConnector of the ADO.NET "ReservedWords" schema collection, though.
So far all the rest seems to work fine (still testing it).

**Comment by razzmatazz** [comment]
I have  a PR for this in https://github.com/nhibernate/NHibernate.MySqlConnector/pull/1
