### ISSUE TITLE
Strong name Pomelo.EntityFrameworkCore.MySql.dll

### ISSUE THREAD

**Issue by dougbu** [mysql-net/MySqlConnector#514]
Building a project using the with a recent .NET Core SDK results in the following warning:
```
CSC : warning CS8002: Referenced assembly 'Pomelo.EntityFrameworkCore.MySql, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [Project.csproj]
```
This warning is of course treated as an error if `$(WarningsAsErrors)` is `true` -- which is fairly common. In other words, the lack of a strong name can often fail builds.

If that project also targets .NET Framework (which EF Core supports), you'll hit a runtime failure:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Pomelo.EntityFrameworkCore.MySql, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

In essence I'm suggesting reopening #224 given ASP.NET Core packages can be used in "full framework" .NET Framework projects and given the recent warnings about strong naming. In addition, Microsoft is now recommending strong naming. See https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies for example.

**Comment by bgrainger** [comment]
This repo is for MySqlConnector, which is already strong-named: #224 

Did you mean to open this issue at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql ?

**Comment by dougbu** [comment]
My apologies. Yes, that's exactly what I meant to do.
