### ISSUE TITLE
Implement ENUM data type

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#52]
Implement support for ENUM.

http://dev.mysql.com/doc/refman/5.7/en/enum.html

Required for #4 and PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#36

**Comment by caleblloyd** [comment]
Does Connector/NET support `SET` or `ENUM`?  I can't seem to find it.

**Comment by bgrainger** [comment]
I don't think it has specialised .NET types to wrap them, but does support deserializing them (both to `string` I think). I was just looking for the same level of basic support in this case.

**Comment by bgrainger** [comment]
`ENUM` column values are returned as strings by MySQL Server and will be exposed as strings by `MySqlDataReader.GetValue`.
