### ISSUE TITLE
Availability of Old Version

### ISSUE THREAD

**Issue by gaurangmajithiya** [mysql-net/MySqlConnector#521]
Hi bgrainger,

We have started using this MySqlConnector, and it's working very well. But we just found one issue yesterday when we updated NuGet package for our project. We were using version 0.40.4, but when we built our project it automatically updated to 0.42.*. And when we deployed on our server it threw some exceptions because it requires dotnetcore 2.1. And then we tried to uninstall this NuGet package and tried to find 0.40.4 version we didn't get that version.

So I would like to request you to keep older version available if you upgrade.

Also, it would be great if you make 0.40.4 available now.

Thanks,
Gaurang

**Comment by bgrainger** [comment]
0.42.0 adds support for `netcoreapp2.1`, but doesn't _require_ it; it's just another supported platform (along with `netstandard1.3` and `netstandard2.0`). So it should still work. However, I've made 0.40.4 available again (since it was the last pre-`netcoreapp2.1` version).
