### ISSUE TITLE
Detecting Changes in table in order to detect when any changes

### ISSUE THREAD

**Issue by Vijaykumarj** [mysql-net/MySqlConnector#522]
Receive Notifications when a table record changes between an asp.net web application and an instance of mysql like **SQLDependency in SQL Server**.

thanks in advance

**Comment by bgrainger** [comment]
MySQL Server doesn't support the server-side features necessary to make this possible. (In SQL Server, it's based on the [Service Broker infrastructure](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/query-notifications-in-sql-server), which doesn't exist in MySQL.)

You'll have to implement some sort of polling based on the shape of the data in your tables (e.g., does it have a `TIMESTAMP` column or some other value that always changes?):
* https://stackoverflow.com/a/26395181
* https://stackoverflow.com/a/3768609

**Comment by mguinness** [comment]
FWIW Devart has a [MySqlDependency](https://www.devart.com/dotconnect/mysql/docs/Devart.Data.MySql~Devart.Data.MySql.MySqlDependency.html) class, but that is also based on polling.
