### ISSUE TITLE
Support DbProviderFactories.RegisterFactory

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#526]
[`DbProviderFactories.RegisterFactory`](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbproviderfactories.registerfactory?view=netcore-2.1) is a new API (dotnet/corefx#20903) in `netcoreapp2.1`.

Consider adding a convenience `MySqlClientFactory.Register()` method that registers the instance with `DbProviderFactories`.

Add documentation that shows how to use the old app.config/web.config way (see #525) on .NET Framework, and the deferred string-based registration on .NET Core.

**Comment by bgrainger** [comment]
This will be in `netstandard2.1`: dotnet/standard#356

**Comment by layer07** [comment]
No updates on this issue yet? I am still unable to understand why it is not agnostic between .NET and .NETCore. Everyone is having to rewrite a bunch of code.

**Comment by bgrainger** [comment]
The API is coming in `netstandard2.1`, which hasn't been released yet.

Can you be more specific about what you need?

**Comment by layer07** [comment]
Hi bgrainger, thanks for answering! 

Well, actually what I wanted is more broad... 
`DbProviderFactories.RegisterFactory` works just fine on .netcore, but won't work on regular .NET (lets say 4.7.2) More an issue with MS itself.

**Comment by bgrainger** [comment]
Since [.NET 4.8 won't support `netstandard2.1`](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/) it looks unlikely that it'll be on the full .NET Framework. (Unless they choose to just implement that one method, but I'm not sure why that would be necessary when there's already the `app.config` way of registering additional factories.)

**Comment by bgrainger** [comment]
Added in [0.50.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.50.0).
