### ISSUE TITLE
Huge Memory Consumption in Batch Insert/Updates in 0.42.2

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#528]
Upstream issue reported at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/633

Insert/Update queries that use Batching in EF Core used to consume ~4MiB of memory are now consuming 2000-5000MiB of memory.

Mitigation was to downgrade from 0.42.2 to 0.42.1: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/638

Possible root cause commits solely based on the version number are these 2:

- https://github.com/mysql-net/MySqlConnector/commit/0f78099d819d2d37c264e93ab2b2116b08459a43 (Add ResizableArray)
- https://github.com/mysql-net/MySqlConnector/commit/69080de2b4e1ceddeb105bf3244de1f5a30cede7 (Remove result set buffering.)

**Comment by bgrainger** [comment]
The excess memory usage appears to be related to `ResizableArray`:

![image](https://user-images.githubusercontent.com/188129/42384370-a4527fb2-80ee-11e8-839c-6447c0ade0ba.png)

**Comment by bgrainger** [comment]
@caleblloyd I'll ship a fix for this as soon as the Appveyor build stops having spurious failures.

**Comment by bgrainger** [comment]
Fixed in [0.42.3](https://github.com/mysql-net/MySqlConnector/releases/tag/0.42.3).
