### ISSUE TITLE
TINYINT(1) UNSIGNED is returned as bool

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#530]
A column with type `TINYINT(1) UNSIGNED` is returned as a `bool` by MySqlConnector, but as `byte` by Connector/NET (the same as `TINYINT UNSIGNED`). We should also return `byte`.

**Comment by tcsaddul** [comment]
+1 "byte" is the correct return value and for compatibility with Connector/NET.   On Wednesday, July 11, 2018, 12:52:23 AM GMT+8, Bradley Grainger <notifications@github.com> wrote:  
 
 
A column with type TINYINT(1) UNSIGNED is returned as a bool by MySqlConnector, but as byte by Connector/NET (the same as TINYINT UNSIGNED). We should also return byte.

**Comment by bgrainger** [comment]
Fixed in [0.43.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.43.0).
