### ISSUE TITLE
Save chinese data to db error

### ISSUE THREAD

**Issue by heyixiaoran** [mysql-net/MySqlConnector#531]
I use 0.42.3 version. Then I save some data to db.  like "这里是中文字符" .It's Chinese words. 
 But it's ??????? in the db.  I uninstall it. It's correct.

**Comment by bgrainger** [comment]
Please provide sufficient information to reproduce the problem, including MySQL Server version, table schema information, and sample code.

**Comment by mzji** [comment]
@heyixiaoran 
兄弟，你数据库编码是啥啊？我这里用utf8mb4没问题的
@bgrainger 
Could I use my native language to talk with him/her? I will post the English dialogue here at the same time.
Above Chinese text means "Dude, what's your Database encoding? I'm using utf8mb4 as my DB encoding and everything works fine."

**Comment by heyixiaoran** [comment]
@bgrainger @mzji 
I use Pomelo.EntityFrameworkCore.MySql  and I install the newest MySqlConnector.  I changed hangfire to mysql . The I start a BackgroudJob . The value of the job is ??????. 
But I uninstall MySqlConnector . It's  correct. So I think it's a issue about MySqlConnector.

**Comment by mzji** [comment]
@heyixiaoran 
没有用过 hangfire ，它是怎么连的数据库？传给 MysqlConnector 又用的是啥连接字符串？
Never used hangfire before, do you know how it connects to the database？And what is the connection string used by hangfire to connect to the database?

**Comment by mzji** [comment]
@heyixiaoran 
另外我看到 Pamelo.EntityFrameworkCore.Mysql 的官方说明里面第一段就提到说：
> 1. Recommended Server CharSet
> 
> We recommend you to set utf8mb4 as your MySQL database default charset. The following statement will check your DB charset:
> 
> ```show variables like 'character_set_database';```

所以还是希望你能确认一下你数据库的encoding是否已经配置为utf8mb4

BTW The first paragraph of the `Getting Started` document of Pame.EntityFrameworkCore.MySql said:
> 1. Recommended Server CharSet
> 
> We recommend you to set utf8mb4 as your MySQL database default charset. The following statement will check your DB charset:
> 
> ```show variables like 'character_set_database';```

So I still hope that you could confirm your database has been configured to use the utf8mb4 encoding.

**Comment by bgrainger** [comment]
> Could I use my native language to talk with him/her?

Yes, please do; thanks for your help!

**Comment by mzji** [comment]
> > Could I use my native language to talk with him/her?

> Yes, please do; thanks for your help!

Glad to hear that ;)

Anyway, seems like he/she is using a combine of several different libraries with their default configuration, so that figuring out where the problem is a hard job. Hope I could help him/her to find out the root cause.

**Comment by heyixiaoran** [comment]
@mzji 

我的字符集确实不是 utf8mb4 ， 我用了 utf8 -- UTF-8 Unicode 

hangfire 我用的是 Hangfire.MySqlStorage 来支持 mysql 的

Pamelo.EntityFrameworkCore.Mysql 引用了 MySqlConnector 0.42.1，默认是好使的，但是我又单独加了 MySqlConnector 0.42.3 就产生了这个问题，去掉多加的 MySqlConnector 0.42.3 就没问题了，好吧，下次我把字符集换了，多谢帮助

**Comment by mzji** [comment]
@heyixiaoran 
看了你的回答我觉得问题可能就出在utf8 <-> utf8mb4这里
如果有条件的话你可以等 Pamelo.EntityFrameworkCore.MySql 更新依赖之后再试试看
After read your reply, I think the problem is the mismatch between the utf8 and the utf8mb4 encoding.
If you can, you could try again after Pemolo.EntityFramework.Mysql upgrades its dependency of MySqlConnector to a newer version.
@bgrainger 
heyixiaoran uses Hangfire.MySqlStorage and Pamelo.EntityFramework.MySql as the backstorage for Hangfire, and after he/she upgrades the dependency of MySqlConnector from 0.42.1 to 0.42.3, the issue happened (all chinese character showed as question marks instead of normal chars).
Will the MySqlConnector version upgrade be the problem? There is no change about encoding between MySqlConnector 0.42.1 and 0.42.3.

**Comment by bgrainger** [comment]
I can't see anything in [the changes from 0.42.1 to 0.42.3](https://github.com/mysql-net/MySqlConnector/compare/0.42.1...0.42.3) that would affect the encoding of Chinese (or any Unicode) characters.

For me to debug any further I would really need to see a sample application that reproduces the problem.

I'm also a little confused about which component is being used. It looks like Hangfire.MySqlStorage uses MySqlConnector directly in [1.1.0-beta](https://www.nuget.org/packages/Hangfire.MySqlStorage/1.1.0-beta) and later. Pomelo.EntityFrameworkCore.MySql also uses MySqlConnector directly. Which of these other libraries (if any) is being used to write Chinese to the DB, and what does that code look like?

Finally, a mismatch between `utf8` and `utf8mb4` shouldn't be a problem until you try to store non-BMP characters (i.e., `U+10000` and above). MySqlConnector will always request `utf8mb4` (i.e., "true" Unicode) on the wire and MySQL Server should successfully easily convert between `utf8` and `utf8mb4`.

**Comment by mzji** [comment]
@heyixiaoran 
你用的 Hangfire.MySqlStorage 是哪个版本？1.0.6还是1.1.0-alpha或之后的版本？
Which is the version of Hangfire.MySqlStorage you used? Version 1.0.6, or the version 1.1.0-alpha or higher?

**Comment by bgrainger** [comment]
@heyixiaoran If you're using Hangfire.MySqlStorate 1.1.0-alpha, or 1.0.6 or earlier, then it will be loading MySql.Data as one of its dependencies, and using it to communicate with the database. If so, this other library may be introducing the character encoding issues; please try updating to 1.1.0-beta or later.

**Comment by heyixiaoran** [comment]
Hangfire.MySqlStorage  1.0.6

**Comment by bgrainger** [comment]
Hangfire.MySqlStorage 1.0.6 uses MySql.Data 6.9.9, which may be causing your problem. Try updating to 1.1.2-beta (you will need to check "Show Prerelease" in NuGet Package Manager to see/select it) to see if that fixes the problem.

**Comment by heyixiaoran** [comment]
@bgrainger  Yes . You are right.  Update to 1.1.2-beta is OK.   Thanks for all of your help. @mzji
