### ISSUE TITLE
We should join the .NET Foundation

### ISSUE THREAD

**Issue by rocketRobin** [mysql-net/MySqlConnector#535]
Maybe that will provide more help for this project or something else. the [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql:issue:Should we join the .NET Foundation? #646](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/646) is preparing to join, I think we need too.

**Comment by caleblloyd** [comment]
Pomelo is currently in the exploration phase. I'm hoping to talk to someone from the .NET foundation soon and learn more.

**Comment by bgrainger** [comment]
[The benefits](https://dotnetfoundation.org/projects/why-join) aren't super compelling and the [recent drawbacks in the news](https://news.ycombinator.com/item?id=28760169) are concerning (along with general loss of autonomy). 

There hasn't been any strong need for this (or heavy interest in this issue) in the last three years, so I'm closing for now.
