### ISSUE TITLE
Add support for CertificateStoreLocation and CertificateThumbprint in connection strings

### ISSUE THREAD

**Issue by hajekj** [mysql-net/MySqlConnector#536]
Since .NET Core can deal with Windows's certificate store, it should be supported in connection string just like in [full .NET Framework versions](https://dev.mysql.com/doc/connector-net/en/connector-net-tutorials-ssl.html).

**Comment by bgrainger** [comment]
Looks like the [`X509Store` class](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509store?view=netstandard-1.3) is available in `netstandard1.3` and higher.

**Comment by hajekj** [comment]
Okay, I have the initial code working now. I added some basic tests for connection string parsing, not sure how to approach the test against certificate store itself - should it attempt to write testing certificate to the store and then use that for tests? Or simply write the function requiring the input through InlineData? Eg. CertificateStoreLocation and the thumbprint?

**Comment by hajekj** [comment]
@bgrainger What is the release schedule for this package on Nuget? Do you think it would be possible to make a new release containing this change?

**Comment by bgrainger** [comment]
Added in [0.43.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.43.0).
