### ISSUE TITLE
SUM of INT column returns Decimal

### ISSUE THREAD

**Issue by bazzilic** [mysql-net/MySqlConnector#538]
Hi,

Not completely sure if this is the right place to report this (neither if this is actually a bug). The following code returns `Decimal` instead of `Int32`:

```csharp
q = new MySqlCommand("CREATE TABLE t (c INT)", conn);
q.ExecuteNonQuery();

q = new MySqlCommand("INSERT INTO t (c) VALUES (1),(2),(3)", conn);
q.ExecuteNonQuery();

q = new MySqlCommand("SELECT SUM(c) FROM t", conn);
var r = q.ExecuteReader();

while(r.Read())
{
    r.GetFieldType(0) // <-- this is System.Decimal
}
```

Tested with the latest version of MySQL 5.7

**Comment by bgrainger** [comment]
This is the specified behaviour of MySQL Server. From [Aggregate (GROUP BY) Function Descriptions](https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html):

> The `SUM()` and `AVG()` functions return a `DECIMAL` value for exact-value arguments (integer or `DECIMAL`)

I assume the reason for this is that it would be very easy to overflow an `Int32` if a column had several large `INT` values in it, e.g., see [this test](https://github.com/mysql-net/MySqlConnector/blob/0eb9ddbb08509c7855d472d61be78c2f2d653fd7/tests/SideBySide/QueryTests.cs#L596-L616).

MySqlConnector reflects the behaviour of MySQL Server in this instance (as does Connector/NET).

**Comment by bazzilic** [comment]
Thanks! I tried but didn't find this in the docs.
