### ISSUE TITLE
Connection not open

### ISSUE THREAD

**Issue by gmgiordano** [mysql-net/MySqlConnector#542]
Hello, I would to try to connect to remote MySql Server.
I have  a c# class:
`public class clsOpenCon
	{
public static MySqlConnection CN                 = new MySqlConnection("server=mySqlServer;user id=Userr;persist security info=True;port=3308;database=MyDb;Allow User Variables=True");
}`
and I try to open connection in main form with
 `Classes.clsOpenCon.CN.Open();`
but not find the server.

In .NET Connector worked, but I would to use this connector, if could be possible.

My environment: Win 7 64 bit/VS 2013 configuration debug and plattform Any CPU/ target framework .NET 4.5.1

Thanks

**Comment by bgrainger** [comment]
What's the exact exception message?

**Comment by bgrainger** [comment]
System.Buffers is supposed to be compatible with .NET 4.5.1 (but I haven't explicitly tested it).

Is it possible for you to target a newer version of .NET Framework? .NET 4.5.1 is almost five years old.

Alternatively, try adding System.Buffers (either 4.4.0 or 4.5.0) to your main application/service/website.

**Comment by gmgiordano** [comment]
Thanks for reply. I have added manually System.buffer in my application, and work.
Thanks!
