### ISSUE TITLE
Interpretated character issue

### ISSUE THREAD

**Issue by gmgiordano** [mysql-net/MySqlConnector#544]
Hi,
I have a mistake on particular character. 
The sign "±" is displayed/interpreted as "�".

My environment is:VS 2013 /.NET 4.5/ Mysql server 5.1.4.2/winform in C#.

Thanks in advance.

**Comment by bgrainger** [comment]
Please provide sufficient details to reproduce the problem, e.g., `CREATE SCHEMA` and `CREATE TABLE` statements, C# code, etc.

Note that MySqlConnector has integration tests that verify that Unicode characters can be round-tripped succesfully: https://github.com/mysql-net/MySqlConnector/blob/91f50689bd170fbee152578b2e689e77ff4ca209/tests/SideBySide/DataTypes.cs#L337-L346
