### ISSUE TITLE
Add "Application Name" connection string setting

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#547]
SqlClient supports a `Application Name` [connection string option](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnectionstringbuilder.applicationname.aspx) that is visible in various server monitoring tools.

MySQL Workbench supports showing an application name via the [`program_name` connection attribute](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-connection-attribute-tables.html). 

We could add a connection string setting (default `null`) that, if set, is used to initialise that attribute.

Example requests for such a setting:
* https://stackoverflow.com/questions/51848391/add-application-name-in-mysql-connection-string/
* https://stackoverflow.com/questions/29947364/set-program-name-for-display-in-mysql-process-list

**Comment by bgrainger** [comment]
Npgsql [also uses](https://www.npgsql.org/doc/connection-string-parameters.html#misc) `Application Name`.

**Comment by bgrainger** [comment]
MySQL/J [uses](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html) `connectionAttributes=program_name:YOUR_NAME`.

My inclination is not to support a `Connection Attributes` setting that allows the client to send arbitrary values to the server, but instead to add single-purpose settings (that may end up setting a connection attribute).

**Comment by bgrainger** [comment]
Added in [0.44.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.44.0).

**Comment by investagrams** [comment]
How to use this in the connection string?

**Comment by investagrams** [comment]
Is there a way to put this in the c# code level? Like we want to set it based on the current executable assembly name (since we have multiple web projs and services)

**Comment by bgrainger** [comment]
Use `MySqlConnectionStringBuilder.ApplicationName`.

**Comment by investagrams** [comment]
@bgrainger how can we use that? This is how we instantiate and create our connection:

MySqlConnection connection = new MySqlConnection(ConnectionString);

**Comment by investagrams** [comment]
@bgrainger  we have tried using this on our code:

MySqlConnectionStringBuilder connStringSb = new MySqlConnectionStringBuilder(ConnectionString);

connStringSb.ApplicationName = "<Assembly Name>";

connection = new MySqlConnection(connStringSb.ToString());

Would this be okay? Would there be any performance issue? Every DB calls uses this method and it creates new instance of MySqlConnectionStringBuilder, setting the application name and creating new string via the ToString(), and create the new MySqlConnection,

**Comment by bgrainger** [comment]
Firstly, I assume you're not actually setting `ApplicationName` to an empty string, as that accomplishes nothing.

Secondly, this is very unlikely to cause a performance problem, but the only way to know for sure is to run a performance profiler on your code with your input and measure it.
