### ISSUE TITLE
Question: Failed to read the result set

### ISSUE THREAD

**Issue by zerobounce** [mysql-net/MySqlConnector#550]
A lot of times, when I'm debugging and stepping through code. I get this error a lot. I don't have any strict time-outs that I can think of.  The faster I step through the code, this doesn't occur, it's only when I take 20-30 seconds thinking about something. 

Is there a setting I'm missing? Or can you explain what's happening?

**Comment by bgrainger** [comment]
Based on the description, it sounds like you're running into the "default command timeout", which is set to 30 seconds by default.

To disable all timeouts (e.g., for debugging), add the following to your connection string: `ConnectionTimeout=0;DefaultCommandTimeout=0;`.
