### ISSUE TITLE
Method not found: 'IntPtr System.Runtime.CompilerServices.Unsafe.ByteOffset'

### ISSUE THREAD

**Issue by jesseomega** [mysql-net/MySqlConnector#551]
```
MissingMethodException: Method not found: 'IntPtr System.Runtime.CompilerServices.Unsafe.ByteOffset(!!0 ByRef, !!0 ByRef)'
     at System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
     at System.SpanHelpers.PerTypeValues`1..cctor()

TypeInitializationException: The type initializer for 'PerTypeValues`1' threw an exception.
    at System.Span`1..ctor(T[] array, Int32 start, Int32 length)
    at MySqlConnector.Protocol.Payloads.InitialHandshakePayload.Create(PayloadData payload)
    at MySqlConnector.Core.ServerSession.<ConnectAsync>d__56.MoveNext()
```

Using this with netstandard2.0 and netcoreapp2.1.

I'm using visual studio 15.8, and dot net core SDK v2.1.401

I've tried setting the compiler language settings to latest minor 7.3.

**Comment by bgrainger** [comment]
The exception is coming from the static constructor of `System.Span`, so it doesn't have much to do with MySqlConnector (other than this library uses that type).

Maybe your application is targeting the wrong version of .NET Framework or .NET Core, or your .NET installation is corrupted somehow.

**Comment by bgrainger** [comment]
I don't really know much about MSBuild tasks, sorry. My best guess would be that the framework version that MSBuild is targeting doesn't have the necessary dependencies (even though MySqlConnector does support back to `net45`).

The article [you linked to](https://natemcmaster.com/blog/2017/11/11/msbuild-task-with-dependencies/) seems to imply this is the case, and that a `MissingMethodException` is not an atypical failure.

**Comment by bgrainger** [comment]
> We ran into a few hiccups with connection timeouts with the connection pool, but that was due to our mishandling of connection objects not being disposed properly (small difference with how MySql.Data handles connections).

I think this is a fairly common "pattern" in code in the wild, so I'd like to automatically recover from it whenever possible. If you have an example of the code that was timing out, I'd like to see if we can handle it. (You could file it as a new issue.)

> Also found several instances of dapper queries that had intended to have been passed a transaction object, but hadn't. 

See #474 for an extended discussion of this and other potential workarounds (although making your code more "strict" to pass in the current transaction is a great solution).

**Comment by jesseomega** [comment]
Specifically, we were looking at a disposed transaction, for a reference to a connection object, and then tried to dispose of that. MySqlConnector properly nulls that out, while the MySql.Data left the reference in tact. It was a few line change where we just needed to hold a reference to the original connection object.

I was fortunate enough to find #474 very quickly, and applied this pattern with success.

**Comment by bgrainger** [comment]
> MySqlConnector properly nulls that out, while the MySql.Data left the reference in tact.

This sounds like #61 (where we deliberately chose to follow other ADO.NET libraries and break compatibility with Connector/NET).

**Comment by jesseomega** [comment]
Yes, exactly.
