### ISSUE TITLE
Cannot add or update a child row: a foreign key constaint fails

### ISSUE THREAD

**Issue by jesseomega** [mysql-net/MySqlConnector#552]
A chain of commands and queries within a MySql.Data transaction work just fine. Moving to MySqlConnector I can't do a simple parent child relationship insertion within a transaction?

I insert the parent, then try to insert a child which has a foreign key constraint pointing to the parent's id (we're using varchar(36) for Ids, utf8_bin collation, on MariaDB 10.2, just tried 10.3.9 same issues), and get the following issue:

MySql.Data.MySqlClient.MySqlException: Cannot add or update a child row: a foreign key constraint fails (`test-dev1`.`reportitem`, CONSTRAINT `reportitem_ibfk_2` FOREIGN KEY (`FooId`) REFERENCES `foo` (`FooId`) ON DELETE CASCADE ) ---> 

This seems so fundamental, what am I missing?

**Comment by bgrainger** [comment]
Are you using `TransactionScope` or just a regular `connection.BeginTransaction()`?

Can you provide an example schema and sample code that reproduces the problem? 

I'm struggling to think why changing the client library would affect foreign key constraints on the server.

**Comment by jesseomega** [comment]
Might be a logic issue, I think I just saw a difference in the returned number of affected rows. Insert on a duplicate where the value in the row being updated is the same as previous. In MySqlConnector, it returned 0 affected rows, MySql.Data returned 1....

**Comment by jesseomega** [comment]
Setting UseAffectedRows=false gives similar behavior to default MySql.Data?

**Comment by jesseomega** [comment]
That was the ticket, setting UseAffectedRows=false. Curious, why is this not the default?

**Comment by bgrainger** [comment]
The default is `true` in MySqlConnector to align better with the ADO.NET documentation and other connectors' behavior; see discussion at https://github.com/mysql-net/MySqlConnector/issues/104#issuecomment-255137225 ff.

**Comment by bgrainger** [comment]
Check this documentation for more information about changes from Connector/NET that you may need to account for in your connection string: https://mysql-net.github.io/MySqlConnector/tutorials/migrating-from-connector-net/
