### ISSUE TITLE
MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.

### ISSUE THREAD

**Issue by VimalKumarS** [mysql-net/MySqlConnector#554]
HI

Getting following exception using mysql connector 
MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.'

Sample Code throws exception

```csharp
      using (IDbConnection db = new MySqlConnection("Server=127.0.0.1;Uid=root;Pwd=root;Database=UnitTesting.dbo;IgnoreCommandTransaction=true;Maximum Pool Size=40;Connect Timeout=120;Connection Lifetime=240;"))
            {
                db.Open();
                var tran = db.BeginTransaction();               
                Parallel.ForEach(Enumerable.Range(0, 100).ToArray(), () => 0, (j, loop, x) =>
                {
                    db.Query("INSERT INTO `unittesting.dbo`.`testmodeltwodapper` (`Group`,`Name`,`Value`,`TestModelTwoDapper`)VALUES('g1','n1','v1',null)", transaction: tran as System.Data.IDbTransaction);
                    return x;
                }, (x) => { });
                tran.Commit();
            }
```

Using dotNet core 2.0, Dapper

Any pointer?

thanks
vimal

**Comment by bgrainger** [comment]
A `MySqlConnection` object may not be shared across multiple threads; it must only be used by one thread at a time.

You will need to open a new `MySqlConnection` within the `Parallel.ForEach` loop body.

**Comment by bgrainger** [comment]
Alternatively, if you need to insert all the rows within one transaction, you will have to do all the work just on one thread.
