### ISSUE TITLE
Performance Benchmark - How To?

### ISSUE THREAD

**Issue by lastboy** [mysql-net/MySqlConnector#561]
Hi,

I can see a on your front page a very nice benchmark. Is it something that I can use?
Any suggestions of how can I  benchmark mysql connector will be very much appreciated.

Thank you,
Arik

**Comment by bgrainger** [comment]
The benchmark code is in https://github.com/mysql-net/MySqlConnector/tree/master/tests/Benchmark

Start a MySQL Server and create a user that has permission to create/drop schemas. Update the hard-coded connection string with the login details. Run the benchmarks with `dotnet run -c Release`.
