### ISSUE TITLE
There is already an open DataReader associated with this Connection which must be closed first.

### ISSUE THREAD

**Issue by marekhanzlik** [mysql-net/MySqlConnector#562]
Hi i have few problems when switching from Mysql.Data to MySqlConnector

when i create Insert comands in bulk (generate insert commands in FOR loop) and immediatelly ExecuteNonQueryAsync() saving its task to array and then await Task.WhenAll(allTasks);
It throws an `There is already an open DataReader associated with this Connection which must be closed first.` exception

This doesn't happen with Mysql.Data

Edit: Is it even good idea or even possible to execute multiple commands at once over single connection or should i `await` them sequentialy one after another?

Second problem is #563

**Comment by bgrainger** [comment]
> Is it even good idea or even possible to execute multiple commands at once over single connection 

No, this is not supported. There may only be one in-flight operation on a `MySqlConnection` object.

(It "works" with MySql.Data because the "Async" methods actually execute synchronously, so each will run one-at-a-time, and all will actually complete before you even call `Task.WhenAll`.)
