### ISSUE TITLE
Can expose inner exception when occur MysqlException.CreateForTimeout?

### ISSUE THREAD

**Issue by kyohei0806** [mysql-net/MySqlConnector#575]
Hi, please see following line.

https://github.com/mysql-net/MySqlConnector/blob/3619321e1d4a3e618b9ff9257423dac250007e42/src/MySqlConnector/MySql.Data.MySqlClient/MySqlException.cs#L35

Can this `innerException` contains to new instance of MySqlException?
Because, This code is running at my project.
I would detail of its inner-exception to investigate problem.
Thanks.

**Comment by bgrainger** [comment]
This looks like an oversight when the code was added in https://github.com/mysql-net/MySqlConnector/commit/e28347543296d201b7ff658b419d2d302b8f21bc#diff-d50df248b8fcbea14a9c293a78bbff95R36; `innerException` should be getting passed to the new `MySqlException`.

**Comment by kyohei0806** [comment]
Thanks!!

**Comment by bgrainger** [comment]
Fixed in [0.46.2](https://github.com/mysql-net/MySqlConnector/releases/tag/0.46.2).
