### ISSUE TITLE
NullReferenceException when using GetSchemaTable() with NHibernate

### ISSUE THREAD

**Issue by richardversluis** [mysql-net/MySqlConnector#580]
Hi,

I'm using NHibernate in combination with MysqlConnector. I'm running into the same issue that is described here: https://github.com/npgsql/npgsql/issues/712, specifically this comment: https://github.com/npgsql/npgsql/issues/712#issuecomment-209616386

NHibernate tries to use `MySqlDataReader.GetSchemaTable()` on a moment it shouldn't (?). This results in a `NullReferenceException` on this line:

    schemaTable.MinimumCapacity = colDefinitions.Length;

https://github.com/mysql-net/MySqlConnector/blob/eff609ae9c54a0415b58c892e3cd11be1b3235a2/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs#L308

The fix in npqsql is to let `GetSchemaTable()` to return `null` in line with the `SqlClient` (https://github.com/npgsql/npgsql/commit/c2dfb0b7d2b8c79f3ebbe2c581a0dd78fdd047b6)

**Comment by bgrainger** [comment]
Fixed in [0.47.1](https://github.com/mysql-net/MySqlConnector/releases/tag/0.47.1).

**Comment by richardversluis** [comment]
You're fast, thanks :)
