### ISSUE TITLE
Implement ICloneable on MySqlCommand

### ISSUE THREAD

**Issue by ghd258** [mysql-net/MySqlConnector#583]
public object Clone()
        {
            DataCommand cmd = new DataCommand();
            if (m_DbCommand != null)
            {
                if (m_DbCommand is ICloneable)
                {
                    cmd.m_DbCommand = ((ICloneable)m_DbCommand).Clone() as DbCommand;
                }
                else
                {
                    throw new ApplicationException("A class that implements IClonable is expected.");
                }
            }
            cmd.m_DatabaseName = m_DatabaseName;
            return cmd;
        }

**Comment by bgrainger** [comment]
This is required for API compatibility with Connector/NET. 

`ICloneable` was implemented on `MySqlParameter` recently: #567.

**Comment by ghd258** [comment]
MySql.Data can use this method, but MySqlConnector can correct it.
