### ISSUE TITLE
Implement MySqlConnection.InfoMessage event

### ISSUE THREAD

**Issue by ststeiger** [mysql-net/MySqlConnector#594]
MySqlConnector lacks support for InfoMessage. 

https://dev.mysql.com/doc/dev/connector-net/8.0/html/E_MySql_Data_MySqlClient_MySqlConnection_InfoMessage.htm

```
static void myConnection_InfoMessage(object sender, System.Data.SqlClient.SqlInfoMessageEventArgs e)
{
    System.Console.WriteLine(e.Message);
}


    ((System.Data.SqlClient.SqlConnection) con).InfoMessage += new System.Data.SqlClient.SqlInfoMessageEventHandler(myConnection_InfoMessage);
```

NpgSql has this, too

```
    using (Npgsql.NpgsqlConnection con = new Npgsql.NpgsqlConnection(csb.ConnectionString))
    {
        con.Notice += NoticeEventHandler;
        con.Notification += NotificationEventHandler;

```

**Comment by bgrainger** [comment]
Need to add:

* `MySqlError` class
* `MySqlInfoMessageEventArgs` class
*` MySqlConnection.InfoMessage` event
* routine to execute `SHOW WARNINGS` and raise the event with the parsed warnings
