### ISSUE TITLE
Replace ConnectionIdlePingTime with ConnectRetryCount

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#596]
`ConnectionIdlePingTime` was added in 14d90bb7b7178a98092ac5a8d5426f84656fdc81 as a way to opt out of pinging the server when retrieving a connection from the pool.

SqlClient offers a [`ConnectRetryCount`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder.connectretrycount) option, which (at first glance) seems like it might control similar behaviour. Adding this option and not pinging if it's explicitly set to 0 would provide robustness by default but permit faster connections if desired.

**Comment by FireInWinter** [comment]
If ConnectionIdlePingTime is a non zero value, then my understanding is that it will assume the connection is valid and just use it out of the pool without verifying it is valid.  If it isn't, you get an exception when you try to execute a query.  ConnectRetryCount for SqlClient takes effect during connect.  If the connection isn't valid, then it will establish a new connection.  This is similar behavior if ConnectionIdlePingTime is zero, as it will always be sure the connection is valid before returning a connection object and will create a new connection if it isn't valid.

**Comment by bgrainger** [comment]
`ConnectRetryCount` might also provide a solution for https://github.com/mysql-net/MySqlConnector/issues/621#issuecomment-489131915 and similar, where retrying on open is desirable.

**Comment by bgrainger** [comment]
Retry policies seem best left to a higher-level library like [Polly]https://github.com/App-vNext/Polly), instead of being built into just certain code paths in MySqlConnector.
