### ISSUE TITLE
Add performance benchmarks for high latency connections to README.md

### ISSUE THREAD

**Issue by FireInWinter** [mysql-net/MySqlConnector#598]
I think a good way to highlight some of the advantages of MySqlConnector would be to add some performance info for high latency connections.  I've done some basic tests and have noticed a huge difference.  I've seen a huge difference even if I disable connection pooling.  

On a 60 ms rtt link, with connection pooling disabled, it takes over a minute for Connector/Net to run 100 trivial queries (connect and then execute) vs 24 seconds for MySqlConnector.  The best I could get for Connector/Net was 19 seconds with connectionreset=false, but MySqlConnector did the same thing in 6.7 seconds.

There's a few connection string options that can change the performance, but highlighting some of the improvements could catch more peoples attention to this project. Some of them I can think of are ConnectionReset, ConnectionIdlePingTime, and Pooling.

**Comment by bgrainger** [comment]
> On a 60 ms rtt link

This sounds equivalent to having your application server on the US West Coast and the DB on the East Coast. Is that a common or realistic scenario?

Obviously it exacerbates any inefficiencies in the I/O layer (and MySqlConnector has been tuned to reduce those as much as possible, as it has a direct impact on the [TechEmpower Benchmarks](https://www.techempower.com/benchmarks/)), so it makes the differences clearer, but I'm not sure if it's helpful to provide benchmarks for an artificial use case.

Maybe with the rise of cloud-hosted MySQL providers it's becoming more common to move the DB further from the application? I'm not sure.

**Comment by FireInWinter** [comment]
As this was meant as a quick suggestion, I'm going to close this out to not distract from other issues.
