### ISSUE TITLE
Why there is no value for unable to connect error in MySqlErrorCode

### ISSUE THREAD

**Issue by vanbukin** [mysql-net/MySqlConnector#599]
As I see there are two places ([here ](https://github.com/mysql-net/MySqlConnector/blob/0.48.2/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs#L245)and [here](https://github.com/mysql-net/MySqlConnector/blob/0.48.2/src/MySqlConnector/Core/ServerSession.cs#L283)) in a whole codebase where that exception could be thrown. So the problem there is no error code for that exception types. And when we want to handle situation when there is no connecton to MySQL database, we need to check the error code (it should be 0) and additionaly check exception message. I think it would be better to add additional enum value into MySqlErrorCode to handle that situation ([specially with `when` clauses](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching#when-clauses-in-case-expressions)).

**Comment by bgrainger** [comment]
The "why" is mostly oversight and backwards-compatibility with Connector/NET (which also does't have a specific error code for this situation AFAIK).

It seems like we could safely add a new negative enum value, as was done for [`CommandTimeoutExpired`](https://github.com/mysql-net/MySqlConnector/blob/717c3ecaf9582ab106d586180350e3b690756594/src/MySqlConnector/MySql.Data.MySqlClient/MySqlErrorCode.g.cs#L9-L12).

**Comment by vanbukin** [comment]
@bgrainger Maybe we can reuse that one? https://github.com/mysql-net/MySqlConnector/blob/0.48.2/src/MySqlConnector/MySql.Data.MySqlClient/MySqlErrorCode.g.cs#L229

Looks like it doesn’t used now

**Comment by bgrainger** [comment]
The defined error codes are generally expected to be returned by the server in an [error packet](https://dev.mysql.com/doc/internals/en/packet-ERR_Packet.html).

It's possible that that particular one is reserved for clients to signal connection failure; if so, it would be appropriate to reuse. (Thanks for the pointer.)

**Comment by bgrainger** [comment]
`MySqlErrorCode.UnableToConnectToHost` is used by Connector/NET for failure to connect.

**Comment by bgrainger** [comment]
I wonder if Connector/NET may have co-opted `ER_BAD_HOST_ERROR` (1042) to mean "can't connect to server"? The "right" client-side error code might be `CR_CONNECTION_ERROR` (2002) or `CR_CONN_HOST_ERROR` (2003). Nevertheless, the precedent for .NET is set now.

**Comment by bgrainger** [comment]
Fixed in [0.49.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.49.0).
