### ISSUE TITLE
MySqlException is not serializable

### ISSUE THREAD

**Issue by EranOfer** [mysql-net/MySqlConnector#601]
MSDN:
"Exception(SerializationInfo, StreamingContext), which is a protected constructor that initializes a new exception object from serialized data. **You should implement this constructor if you've chosen to make your exception object serializable**"

Could you please make all custom exception serializable?

For example :
```
internal MySqlException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {}
```

Thanks in advance

**Comment by bgrainger** [comment]
Fixed in [0.49.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.49.0).
