### ISSUE TITLE
Add string overloads to MySqlDataReader.Get*()

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#607]
From https://github.com/dotnet/corefx/issues/31595#issuecomment-458677042.

Many were already added in #435. The missing overloads are:

```csharp
public partial class MySqlDataReader
{        
    public long GetBytes(string name, long dataOffset, byte[] buffer, int bufferOffset, int length);
    public long GetChars(string name, long dataOffset, char[] buffer, int bufferOffset, int length);
    public DbDataReader GetData(string name);
    public string GetDataTypeName(string name);
    public T GetFieldValue<T>(string name);
    public Type GetProviderSpecificFieldType(string name);
    public object GetProviderSpecificValue(string name);
    public TextReader GetTextReader(string name);
    public object GetValue(string name);
    public bool IsDBNull(string name);
}
```

**Comment by roji** [comment]
@bgrainger note that the idea is to add all the string-based overloads to DbDataReader, so they should *not* exist on provider-specific reader classes (e.g. MySqlDataReader). In fact, I think providers should ideally have cross-target .NET Standard 2.1 when it comes out, and not define any of these overloads in that version to prevent confusion.

**Comment by bgrainger** [comment]
Right, in `netstandard2.1`, the base class implementations will be available. The question is whether to expose an equivalent API for other frameworks. 75% of it already is in MySqlConnector (for API compatibility with Connector/NET). The question is whether to bring it to 100%.

> and not define any of these overloads in that version

That would be a binary-breaking change when switching from the `netstandard2.0` to the `netstandard2.1` library (because methods on `MySqlDataReader` would effectively be removed). 

That may be an argument against conditionally implementing these "missing" methods; it's still unclear what to do about the existing methods. For maximum safety, they should probably be retained.

One extreme possibility would be to convert them all to extension methods on `MySqlDataReader` right now. That would of course be a breaking change, but I'm willing to do that in v0.x. It still allows people to migrate source code using the Connector/NET API (by recompiling) and results in no binary API changes when moving from `netstandard2.0` to `netstandard2.1`.

**Comment by roji** [comment]
> That would be a binary-breaking change when switching from the netstandard2.0 to the netstandard2.1 library (because methods on MySqlDataReader would effectively be removed).

That's a valid point - if you want to support the scenario where the user swaps the netstandard2.0 assembly version of your provider with the new netstandard2.1 assembly version, that would break. I think that's a pretty high bar to set - at least in Npgsql I've always assumed that a change of dependency assembly is supposed to accompanied by compilation. I had a similar situation when .NET 4.5.1 (I think) introduced Scale and Precision to DbParameter, although every provider out there had them as non-virtual, provider-specific properties before that. The version cross-targeting net451 (and later) only provider a overriding versions of Scale and Precision, so an assembly-swap would probably fail there too (I've never actually had any complaints).

But there's no real downside in retaining the methods in the provider either, and every provider can decide on their own policy.

**Comment by bgrainger** [comment]
I'm thinking of the scenario:
A targets netstandard2.0 and uses MySqlConnector
A targets netstandard2.0 and uses MySqlConnector
A takes a dependency on B
A updates to netstandard2.1 and installs the new netstandard2.1 MySqlConnector library
B is now broken because it hasn't been recompiled (maybe it's a third-party NuGet dependency). A gets a `MissingMethodException` at runtime when it calls some method implemented in B.

**Comment by roji** [comment]
> I'm thinking of the scenario:

Makes sense!

> One extreme possibility would be to convert them all to extension methods on MySqlDataReader right now. That would of course be a breaking change, but I'm willing to do that in v0.x. It still allows people to migrate source code using the Connector/NET API (by recompiling) and results in no binary API changes when moving from netstandard2.0 to netstandard2.1.

I'm not sure this has great value - it seems to push forward the breaking change to happen earlier rather than later... But if it helps in term of your 0.x vs. 1.0 releases then why not...

**Comment by bgrainger** [comment]
> One extreme possibility would be to convert them all to extension methods

I was thinking it could be a porting "shim" for Connector/NET users, but they still can't be removed in the future without breaking binary compatibility, so it doesn't really gain much.

**Comment by bgrainger** [comment]
There's no compelling reason to add these methods downlevel, as they would have to be kept on the public API to avoid a binary break. We'll just multitarget for `netstandard2.1` when it's available.
