### ISSUE TITLE
Use COM_RESET_CONNECTION for MariaDB >= 10.2.4

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#613]
COM_RESET_CONNECTION is supported in MariaDB starting in v10.2.4: https://mariadb.com/kb/en/library/com_reset_connection/

**Comment by MosheL** [comment]
it can solve the #612  ?

**Comment by bgrainger** [comment]
Unsure, as we don't yet know the cause of #612. This is just taking advantage of a possibly-faster way to reset pooled connections.

**Comment by MosheL** [comment]
It will be faster. I was found the old connection reset method can take a ~ 20ms sometimes.

Thanks for all.

**Comment by bgrainger** [comment]
Added in [0.50.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.50.0).
