### ISSUE TITLE
Cannot Open when State is Connecting

### ISSUE THREAD

**Issue by sam-wheat** [mysql-net/MySqlConnector#615]
I tried to run an integration test I had not run in several months and received the error below.  The last time I ran the test and it passed I was using 0.38.0 which no longer appears on nuget.

Works:

    <Reference Include="MySqlConnector, Version=0.38.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92, processorArchitecture=MSIL">
	    <HintPath>..\packages\MySqlConnector.0.38.0\lib\net46\MySqlConnector.dll</HintPath>
    </Reference>

Fails:

    <PackageReference Include="MySqlConnector">
      <Version>0.49.3</Version>
    </PackageReference>

Fails when getting row counts from tables:

	public async Task Reload()
        {
            Task<List<Category>> CategoryTask = db.Categories.ToListAsync();
            Task<List<CategoryTag>> CategoryTagTask = db.CategoryTags.ToListAsync();
            Task<List<DataProvider>> DataProviderTask = db.DataProviders.ToListAsync();
            Task<List<DataSetModelRefFilter>> DataSetModelRefFilterTask = db.DataSetModelRefFilters.ToListAsync();

            Task<List<DataSet>> DataSetTask = db.DataSets.ToListAsync();
            Task<List<DataSetSeries>> DataSetSeriesTask = db.DataSetSeries.ToListAsync();
            Task<List<DataSetSeriesModelRefFilter>> DataSetSeriesModelRefFilterTask = db.DataSetSeriesModelRefFilters.ToListAsync();
            Task<List<DataSetSeriesUserFilter>> DataSetSeriesUserFilterTask = db.DataSetSeriesUserFilters.ToListAsync();
            Task<List<DataSetUserFilter>> DataSetUserFilterTask = db.DataSetUserFilters.ToListAsync();

            Task<List<ModelReference>> ModelReferenceTask = db.ModelReferences.ToListAsync();
            Task<List<NativeFrequency>> NativeFrequencyTask = db.NativeFrequencies.ToListAsync();
            Task<List<Observation>> ObservationTask = db.Observations.ToListAsync();
            Task<List<ObsModelReference>> ObsModelReferenceTask = db.ObsModelReferences.ToListAsync();
            Task<List<RelatedCategory>> RelatedCategoryTask = db.RelatedCategories.ToListAsync();

            Task<List<Release>> ReleaseTask = db.Releases.ToListAsync();
            Task<List<ReleaseDate>> ReleaseDateTask = db.ReleaseDates.ToListAsync();
            Task<List<ReleaseSeries>> ReleaseSeriesTask = db.ReleaseSeries.ToListAsync();
            Task<List<ReportingFrequency>> ReportingFrequenciesTask = db.ReportingFrequencies.ToListAsync();
            Task<List<Series>> SeriesTask = db.Series.ToListAsync();
            Task<List<SeriesCategory>> SeriesCategoryTask = db.SeriesCategories.ToListAsync();

            Task<List<SeriesTag>> SeriesTagTask = db.SeriesTags.ToListAsync();
            Task<List<SourceRelease>> SourceReleaseTask = db.SourceReleases.ToListAsync();
            Task<List<Source>> SourceTask = db.Sources.ToListAsync();
            Task<List<User>> UserTask = db.Users.ToListAsync();

            Task<List<Vintage>> VintageTask = db.Vintages.ToListAsync();
            Task<List<WatchListItem>> WatchListItemsTask = db.WatchListItems.ToListAsync();

			// Fails here
			
            await Task.WhenAll(
                CategoryTask,  CategoryTagTask, DataProviderTask, DataSetModelRefFilterTask,
                DataSetTask, DataSetSeriesTask, DataSetSeriesModelRefFilterTask, DataSetSeriesUserFilterTask, DataSetUserFilterTask,
                ModelReferenceTask, NativeFrequencyTask, ObservationTask, ObsModelReferenceTask, RelatedCategoryTask,
                ReleaseTask, ReleaseDateTask, ReleaseSeriesTask, ReportingFrequenciesTask, SeriesTask, SeriesCategoryTask,  
                SeriesTagTask, SourceReleaseTask, SourceTask, UserTask, 
                VintageTask, WatchListItemsTask);
				
		}

	at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__27.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 226
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenDbConnectionAsync>d__48.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__45.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.FastQueryAsyncEnumerable`1.FastQueryAsyncEnumerator.<MoveNext>d__9.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 120
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by bgrainger** [comment]
How many distinct `MySqlConnection` objects do you have? One for each property getter on `db`, or one shared object that all property implementations use?

It is not permitted to share a single `MySqlConnection` object across multiple threads, which I suspect is the underlying cause of this exception.

**Comment by sam-wheat** [comment]
In the code I posted db is a single instance of `DbContext`.  Each property of db i.e. db.Categories is simply `DbSet<T>`.

**Comment by bgrainger** [comment]
Running multiple operations on the same `DbContext` concurrently is not permitted. See:

* https://stackoverflow.com/questions/48767910/entity-framework-core-a-second-operation-started-on-this-context-before-a-previ/48768221
* https://stackoverflow.com/questions/6126616/is-dbcontext-thread-safe

Change your code to be:

```csharp
public async Task Reload()
{
    List<Category> Category = await db.Categories.ToListAsync();
    List<CategoryTag> CategoryTag = await db.CategoryTags.ToListAsync();
    List<DataProvider> DataProvider = await db.DataProviders.ToListAsync();
    // ...
```

**Comment by sam-wheat** [comment]
Task is async…. I am not spinning up any new threads.
This code works perfectly on MSSQL.

**Comment by bgrainger** [comment]
Async operations will complete asynchronously on an I/O completion port thread, which can cause the same object to be accessed from two different threads.

I've pointed at two separate pieces of documentation which say this isn't allowed. (And, by default in C#, one would not expect multiple concurrent operations on the same object to be allowed.) I'm happy to investigate further if you can find evidence that this _should_ be supported.

**Comment by sam-wheat** [comment]
You are 100% correct.  This code is a variance from a client wrapper that I normally use that news up a `DbContext` for each call.    I've been using it so long I forgot why I use it.
