### ISSUE TITLE
Version string of MariaDB on Windows doesn't contains a dash after `MariaDB` signature

### ISSUE THREAD

**Issue by mzji** [mysql-net/MySqlConnector#617]
The version string on wire of MariaDB on Windows doesn't contains a dash character after `MariaDB` signature:
![default](https://user-images.githubusercontent.com/23279426/54006122-03bb8980-4197-11e9-9d3a-f1f16516a019.png)

The code added in 24f037b1 won't correctly parse this version string since the [signature string](https://github.com/mysql-net/MySqlConnector/commit/24f037b16c9766dc71a8a2331aa2784f3074c37e#diff-1fc99617b591f127c46f8469281da94dR49) contains an extra dash character. To fix this, we could just drop the extra character.

**Comment by bgrainger** [comment]
Thanks.

All the examples I had found (which were from Docker containers) did contain the trailing hyphen. I agree we should drop it.
