### ISSUE TITLE
What connection string to pass from AsyncController class in .NET Core MVC?

### ISSUE THREAD

**Issue by shunjid** [mysql-net/MySqlConnector#633]
I have been following the .NET Core MVC Connection tutorial from https://mysql-net.github.io/MySqlConnector/tutorials/net-core-mvc/

What happens is, in AsyncController class in all this lines program asks for a connection string which is not defined in documentation:

```
using (var db = new AppDb())
            {
```

The problem statement shows in VSCode is:

`There is no argument given that corresponds to the required formal parameter 'connectionString' of 'AppDb.AppDb(string)' (CS7036) [mysql-tester]`

Here is the AppDb.cs code

```
using System;
using MySql.Data.MySqlClient;

namespace mysql_tester
{
    public class AppDb : IDisposable
    {
        public MySqlConnection Connection;

        public AppDb(string connectionString)
        {
            Connection = new MySqlConnection(connectionString);
        }

        public void Dispose()
        {
            Connection.Close();
        }
    }
}
```

How to solve this problem?

**Comment by bgrainger** [comment]
As per https://mysql-net.github.io/MySqlConnector/tutorials/net-core-mvc/#update-configuration-files, store your connection string in `appsettings.json`.

Then, as per https://mysql-net.github.io/MySqlConnector/tutorials/net-core-mvc/#net-core-startup, in your `ConfigureServices` method, load the connection string from configuration and use it to initialise `AppDb`.

You should usually have different connection strings for test and production, so you will create environment-specific settings files with different connection strings.

To learn how to create a connection string, visit https://www.connectionstrings.com/mysql-connector-net-mysqlconnection/.
