### ISSUE TITLE
DataAdapter - Batching

### ISSUE THREAD

**Issue by danspam** [mysql-net/MySqlConnector#635]
Are there any plans to support batching on the DataAdapter? I am looking into using NHibernate with MySqlConnector and this is something that is used a lot.

**Comment by bgrainger** [comment]
This should be possible to implement, although it's not immediately obvious to me what the right way to test it is; do you have example client code that would exercise a batching implementation?

**Comment by danspam** [comment]
There is an [article on the Microsoft Ado.Net documentation site](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/performing-batch-operations-using-dataadapters) with an example that may possibly help.

NHibernate [uses reflection on the DataAdapter](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/AdoNet/MySqlClientSqlCommandSet.cs) to execute the batching.

I had a poke around mysql-connector-net to see what they do. I can see there is the special case for the multiple insert syntax. I can also see that there is code to ensure the size of the batch does not get too large but my unfamiliarity with that code base doesn't allow me to get much further.

**Comment by bgrainger** [comment]
Implemented in [0.54.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.54.0).

**Comment by bgrainger** [comment]
This currently provides a simple (but reliable) implementation that just sequentially executes the commands in the batch. It fixes the problem of `NotSupportedException` being thrown when trying to use batch updates.

It will not, for example, combine multiple `INSERT INTO table(x,y) VALUES(@x, @y);` commands into one `INSERT INTO table(x, y) VALUES(@x1, @y1),(@x2, @y2),...,(@xn, @yn);` command (which might  more execute more efficiently).

Further improvements to batching will most likely wait until a new ADO.NET API is available: https://github.com/dotnet/corefx/issues/35135
