### ISSUE TITLE
MySqlConnector not working when using Visual Studio 2019

### ISSUE THREAD

**Issue by DoubleDBE** [mysql-net/MySqlConnector#644]
I wanted to try Visual Studio 2019 with my project which uses MySqlConnector.

However, I immediately get an exception when using `ExecuteReader()` from the `MySqlDataReader` class:

`System.TypeLoadException: Could not resolve type with token 01000092 from typeref (expected class 'System.Buffers.StandardFormat' in assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') occurred`

I've tried adding those references manually using NuGet, but no luck.

The project is a Xamarin.Forms project, using .NET Standard 2.0.3

**Comment by bgrainger** [comment]
.NET Core 2.0.3 is end of life, and over 18 months old.

Can you try a more recent release, such as .NET Core 2.1.11 (LTS) or .NET Core 2.2.5 (current)?

**Comment by DoubleDBE** [comment]
I'm not sure how I could update that, as my Xamarin.Forms project uses the latest NETStandard.Library available on NuGet.

Maybe it's something VS specific because on VS 2017 I don't get these exceptions and it's working great.

**Comment by bgrainger** [comment]
I'll take a look when I get a VS2019 license. Are you able to post a simple repro project on GitHub?

**Comment by DoubleDBE** [comment]
I've tested it by creating an entire new Xamarin.Forms project in VS 2019. When trying to reproduce it on Android, it seems to be working without any issue...

However when trying to compile for iOS i get the following compile error:

`Can't resolve the reference 'System.Buffers.StandardFormat System.Buffers.StandardFormat::op_Implicit(System.Char)', referenced from the method 'System.Void MySql.Data.MySqlClient.MySqlParameter::AppendSqlString(MySqlConnector.Protocol.Serialization.ByteBufferWriter,MySqlConnector.Core.StatementPreparerOptions)' in 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.	MySqlConnectorTest.iOS	`

Linker behaviour is set to "Link Framework SDKs Only"

When I find out how I can post a repro project, i'll let you know when it's done.

**Comment by bgrainger** [comment]
It sounds like something might be wrong with the reference assemblies for just that one platform? My code is just referencing `System.Buffers` and `System.Memory`; I would expect them to have the same API surface in all platforms supporting `netstandard2.0`.

There are newer versions of both those packages on NuGet; it might help to update dependencies? Ican test this when I get VS2019.

**Comment by bgrainger** [comment]
Because this is a Xamarin build time issue, I think you need to file it at https://github.com/xamarin/xamarin-macios (and https://github.com/xamarin/xamarin-android for the Android side).

This error looks similar to (but not exactly the same as) https://github.com/xamarin/xamarin-macios/issues/4168. I suspect it will need investigation and resolution from people more familiar with Xamarin tooling and the linking process.

**Comment by bgrainger** [comment]
(I feel like I should add that it seems like an unusual design to put the database client (i.e., MySqlConnector) directly in the Android/iOS app. That implies that your database server is publicly accessible from the Internet, which is a security risk, and your client might be reverse engineered to extract the database credentials. More typically, a web service communicates with the database (which is behind a firewall) and exposes an API (REST, gRPC, etc. over HTTPS) that the mobile app interacts with.)
