### ISSUE TITLE
Create the data specified code utf8mb4, the input data is unsuccessful

### ISSUE THREAD

**Issue by ghd258** [mysql-net/MySqlConnector#648]
CREATE DATABASE tlhjobv2
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;
Create the data specified code utf8mb4, the input data is unsuccessful

**Comment by bgrainger** [comment]
Please provide the following details:
* Which version of MySqlConnector are you using?
* Which version of .NET Framework or .NET Core? Which OS?
* What variety and version of MySQL Server?
* A small code sample (SQL and C#) that reproduces the problem.
