### ISSUE TITLE
Useing with  Parallel loop

### ISSUE THREAD

**Issue by aghilimc** [mysql-net/MySqlConnector#649]
i want to insert some records by /Parallel.ForEach. but i get exception and how i have open connection for all taskes?

```
Parallel.ForEach(_titleList,   _title => {
 _appdb.Connection.Open ();
                using (var cmd = _appdb.Connection.CreateCommand())
                {

                    cmd.CommandText = Query;
                    cmd.Parameters.AddWithValue("@historyID", expLog.History_ID);
                    cmd.Parameters.AddWithValue("@titelID", expLog.Title_ID); 
                    resault =    cmd.ExecuteNonQuery  ();
                }

  } );
```

**Comment by bgrainger** [comment]
Using the same connection simultaneously on multiple threads (with `Parallel.ForEach`) is not permitted. You must open a _new_ connection for each thread.

See https://mysql-net.github.io/MySqlConnector/troubleshooting/connection-reuse/ for more information.
