### ISSUE TITLE
无法访问已释放的对象。对象名：”MySqlConnection“。

### ISSUE THREAD

**Issue by ghd258** [mysql-net/MySqlConnector#653]
无法访问已释放的对象。对象名：”MySqlConnection“。
![QQ图片20190617165823](https://user-images.githubusercontent.com/4811375/59597551-b010f280-912c-11e9-9c7b-71db60feb7e9.png)
![QQ图片20190617182050](https://user-images.githubusercontent.com/4811375/59597552-b010f280-912c-11e9-86b2-24ca03c55f1b.png)

**Comment by bgrainger** [comment]
You're (implicitly?) calling `MySqlConnection.Open` on a connection that has already been disposed. This is not permitted.

(You can `Close` and `Open` a connection multiple times, but it may not be reused after it's been disposed.)
