### ISSUE TITLE
Handle ERR packet sent out of order

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#662]
If the server sends an unexpected `ERR` packet, the client should throw a `MySqlException` based on that packet, instead of "Packet received out of order". Example at https://github.com/mysql-net/MySqlConnector/issues/612#issuecomment-506301772.

**Comment by markus456** [comment]
I've learned that this problem will be fixed in [future MariaDB releases](https://jira.mariadb.org/browse/MDEV-19893) but older versions can still send these sorts of packets.

**Comment by bgrainger** [comment]
Fixed in [0.57.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.57.0).
