### ISSUE TITLE
GetDouble and GetFloat less type auto conversion

### ISSUE THREAD

**Issue by dczuo** [mysql-net/MySqlConnector#664]
simple example:
using (var reader = new MySqlCommand("select 1 / 3 from tablename", conn).ExecuteReader())
{
	reader.Read();
	reader.GetDouble(0);    // InvalidCastException
	reader.GetFloat(0);     // InvalidCastException
}

**Comment by bgrainger** [comment]
MySqlConnector currently only performs a small number of known "safe" conversions; see #481 and #406. 

Note that a `decimal` column can be retrieved as an int (#54) so it may make sense to allow implicit conversion to `float`/`double` (which would be less lossy).

Like similar issues, this needs testing in AdoNetApiTest first.

**Comment by bgrainger** [comment]
Added to AdoNetApiTest: https://github.com/mysql-net/AdoNetApiTest/commit/2a48acc59148b1f299d16cbb19c440fa068e9527

Conversions from a decimal column (or implicit decimal result) will be handled automatically by `GetDouble` and `GetFloat`.

**Comment by bgrainger** [comment]
Fix shipped in [0.57.0-rc1](https://www.nuget.org/packages/MySqlConnector/0.57.0-rc1).

**Comment by dczuo** [comment]
thanks
