### ISSUE TITLE
Inspection of object state in debugging objects of type System. Delegate is not supported in this context

### ISSUE THREAD

**Issue by ghd258** [mysql-net/MySqlConnector#668]
The Mysql.data is good, but with MySql Connector there is this error.
![QQ图片20190705171054](https://user-images.githubusercontent.com/4811375/60711714-0d3bdf00-9f48-11e9-8262-196780f890bb.png)
![QQ图片20190705171103](https://user-images.githubusercontent.com/4811375/60711720-10cf6600-9f48-11e9-9455-25efb0461325.png)

**Comment by bgrainger** [comment]
This doesn't provide enough information to reproduce the problem.

It also sounds like a problem with the Visual Studio debugger, or perhaps with your code. MySqlConnector does not use `System.Delegate`.

Finally, `ExecuteReaderAsync().Result` is "sync over async". This will very often cause deadlocks and should be avoided: https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

If you need a synchronous method, call `ExecuteReader` instead.

**Comment by ghd258** [comment]
private delegate Task<T> RetryHandlerAsync<T>();

 /// <summary>
        /// Create By:Wiggins
        /// Create On:2018年1月16日10:25:14
        /// LastUpdate By:
        /// LastUpdate On:
        /// Remark:
        /// returns the number of rows affected.
        /// </summary>
        /// <returns></returns>
        public async Task<int> ExecuteNonQueryAsync()
        {
            try
            {
                return await RetryAsync<int>(delegate
                {
                    
                        return MyCommand.ExecuteNonQueryAsync();
                    
                });
            }
            catch (Exception ex)
            {
                Exception result = DataAccessLogger.LogExecutionError(m_DbCommand, ex);
                throw result;
            }
        }
 /// <summary>
        /// Create By:Wiggins
        /// Create On:2018年1月16日10:27:43
        /// LastUpdate By:
        /// LastUpdate On:
        /// Remark:
        /// </summary>
        /// <returns></returns>
        private async Task<T> RetryAsync<T>(RetryHandlerAsync<T> function)
        {
            if (function == null)
            {
                throw new ArgumentNullException("function can not be null.");
            }

            int retryTimes = 5;
            double intervalSeconds = 0.1;

            // 10054 为下面这个异常的 Number。
            // A transport-level error has occurred when sending the request
            // to the server. (provider: TCP Provider, error: 0 - An existing
            // connection was forcibly closed by the remote host.)
            int errorNumber = 10054;

            T t = default(T);
            string databaseType = m_DatabaseName.Split('_')[0].ToLower();

            if (databaseType == "SqlServer".ToLower())
            {
                for (int i = 0; i < retryTimes; i++)
                {
                    try
                    {
                        t = await function();
                        break;
                    }
                    catch (SqlException ex)
                    {
                        if (ex.Number == errorNumber)
                        {
                            if (i == retryTimes - 1)
                            {
                                throw;
                            }
                            else
                            {
                                SqlConnection.ClearAllPools();
                                System.Threading.Thread.Sleep(TimeSpan.FromSeconds(intervalSeconds));
                            }
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
            }
            else
            {
                for (int i = 0; i < retryTimes; i++)
                {
                    try
                    {
                        t = await function();
                        break;
                    }
                    catch (MySqlException ex)
                    {
                        if (ex.Number == errorNumber)
                        {
                            if (i == retryTimes - 1)
                            {
                                throw;
                            }
                            else
                            {
                                MySqlConnection.ClearAllPools();
                                System.Threading.Thread.Sleep(TimeSpan.FromSeconds(intervalSeconds));
                            }
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
            }

            return t;
        }
