### ISSUE TITLE
Support SSH tunnel connections

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#671]
Connector/NET 8.0.17 added the following connection string options: `SshHostName`, `SshPort`, `SshUserName`, `SshPassword`, `SshKeyFile`, `SshPassPhrase`.

These set up an encrypted SSH tunnel, as documented here: https://dev.mysql.com/doc/connector-net/en/connector-net-ssh-tunneling.html

SSH support appears to be provided by [SSH.NET](https://www.nuget.org/packages/SSH.NET/).

I don't want to add a new dependency for an optional (and probably infrequently-used) feature. A first step could be writing canonical documentation on how to use SSH.NET in the application to set up a SSH tunnel (before connecting to MySQL). The SSH connection string properties could be added, but throw an exception that refers to the documentation.

If this is important to add, the implementation could perhaps be provided by an extension assembly/package, which adds the SSH.NET dependency.

**Comment by jkuek** [comment]
This would be a useful feature for me.

Our DB is in AWS, only accessible by tunneling through SSH. The other tools I use do support SSH natively, but when using MySqlConnector I have to set up the tunnel manually.

**Comment by bgrainger** [comment]
Documentation page created: https://mysqlconnector.net/tutorials/connect-ssh/

**Comment by bgrainger** [comment]
From [MySQL 8.0.24 release notes](https://dev.mysql.com/doc/relnotes/connector-net/en/news-8-0-24.html):

> The SSH Tunneling (port forwarding) feature, which was added to support MySQL products in making secure connections on Windows, is no longer needed by other products. Now, using an alternative such as OCI or SSH.NET to create a tunnel is preferred. The related connection options (`SshHostName`, `SshKeyFile`, `SshPassPhrase`, `SshPassword`, `SshPort`, and `SshUserName`) are no longer valid when making Connector/NET connections, starting with this release.
