### ISSUE TITLE
TransactionScope and AWS DMS problem

### ISSUE THREAD

**Issue by paulflo150** [mysql-net/MySqlConnector#676]
Hello,
I have a bit of an odd issue with transactions and AWS replication from MYSQL 8 to a SQL Server (DMS). If I use transaction scope the data gets committed just fine in MYSQL, however it does not get replicated. If I remove the transaction everything works just fine.

I have tested MySql.Data v8.0.17 as well, and everything works as expected there.

Any ideas what could be going on?

Here is a basic example that "breaks" AWS DMS:

```csharp
var task = Task.Run(async delegate
{
using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
var test = await class1.ConnectionTest(configuration.GetConnectionString("somedb"));
scope.Complete();
}
});
task.Wait();

public async Task<int> ConnectionTest(string connectionString)
{
using (var connection = new MySqlConnection(connectionString))
{
await connection.OpenAsync();
using (var command = new MySqlCommand("FlightInsertUpdate", connection))
{
command.CommandType = CommandType.StoredProcedure;
```

**Comment by bgrainger** [comment]
I'm going to guess that the immediate cause is that MySqlConnector uses XA (distributed) transactions for `TransactionScope`, but Connector/NET doesn't.

As per https://mysqlconnector.net/tutorials/migrating-from-connector-net/#transactionscope you can get behaviour equivalent to MySql.Data 8.0.17 by setting `UseXaTransactions=false` in your connection string.

It's not mentioned at https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.MySQL.html#CHAP_Source.MySQL.Limitations but I would guess that MySQL XA Transactions aren't supported by AWS DMS.

**Comment by paulflo150** [comment]
Fanatastic, that was indeed what I was missing.

Thank you for the quick response, and for a great library!
