### ISSUE TITLE
DbDataReader.GetString() is less flexible than Connector/NET's

### ISSUE THREAD

**Issue by Timovzl** [mysql-net/MySqlConnector#684]
After being very satisfied with this connector in our new projects, we intend to migrate our existing projects to it as well, moving away from Connector/NET.

However, we run into an issue that seems challenging to fix in a large codebase.

On the data reader, `GetString(int ordinal)` is less flexible than Connector/NET's implementation. If the data type is not string, MySqlConnector throws, whereas Connector/NET calls `ToString()` on the data. I'm not sure if it converts _any_ type, but definitely simple ones like the various integral types.

Would you consider this behavior for MySqlConnector, to make it easier for people to migrate from Connector/NET? It seems relatively harmless to _not_ throw on this, and the result is about exactly what you would expect. In fact, it could be considered a feature, if you don't care about the data types and want string for everything - perhaps when generating CSV reports.

The only way an implementation could depend on the current implementation is by deliberately using `GetString()` on non-string data, catching the exception, and counting on that. In other words, it's unlikely that anyone depends on the current behavior.

**Comment by bgrainger** [comment]
Discussed previously at #406:

> I've decided to deliberately use the more strict behaviour because implicit conversions to string are a notorious source of locale-dependent bugs, and because `GetValue(x).ToString()` is an available workaround.

**Comment by bgrainger** [comment]
See also https://mysqlconnector.net/tutorials/migrating-from-connector-net/#implicit-conversions.

**Comment by Timovzl** [comment]
Sorry for the duplicate. Your reasoning makes perfect sense. Oh, it was even in the migration guide. I should have looked better!

**Comment by bgrainger** [comment]
MySql.Data 8.3.0 is changing this long-standing behaviour: https://github.com/mysql-net/MySqlConnector/issues/406#issuecomment-1905259518.
