### ISSUE TITLE
Connection string for Azure SQL, Unable to connect

### ISSUE THREAD

**Issue by vasilijgla** [mysql-net/MySqlConnector#688]
I get MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts.
In standart System.Data.SqlClient all work fine...
```
var str = "Server=tcp:servername.database.windows.net,1433;Initial Catalog=dbname;Persist Security Info=False;User ID=readOnlyFuncUser;Password=passus;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
using (SqlConnection conn = new SqlConnection(str))
{
conn.Open();
}
```
After switching to MySql.Data.MySqlClient I had to delete some unsupported properties from connection string...
```
var constr = "Server=tcp:servername.database.windows.net,1433;Initial Catalog=dbname;Persist 
Security Info=False;User ID=readOnlyFuncUser;Password=passus;Connection Timeout=30;";
// also tried
//var constr ="host=servername.database.windows.net;port=1433;user id=readOnlyFuncUser;password=passus;database=dbname;SslMode=Required;";
using (MySqlConnection conn = new MySqlConnection(constr))
{
conn.Open();//MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts.
}

```
What I've made wrong with new connection string? what should it be?

**Comment by bgrainger** [comment]
It looks like you're using a SQL Server connection string. This won't work for Azure Database for MySQL. See https://mysqlconnector.net/connection-options/ for valid options.

Try:

```
host=servername.database.windows.net;user id=readOnlyFuncUser;password=passus;database=dbname;SslMode=Required;
```

(`Port=1433` is definitely wrong; MySQL Server typically listens on port 3306 and this option should be omitted unless there is a good reason to use a non-standard port.)

**Comment by vasilijgla** [comment]
> Try:
> 
> ```
> host=servername.database.windows.net;user id=readOnlyFuncUser;password=passus;database=dbname;SslMode=Required;
> ```
> 
MySql.Data.MySqlClient.MySqlException: The connection string may not be right.
