### ISSUE TITLE
Test stored procedure creation with batching

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#691]
`CREATE PROCEDURE` statements have embedded semicolons. For this reason, MySQL Workbench introduces a `DELIMITER` command that overrides the standard way of breaking a string into multiple statements.

MySqlConnector hasn't needed to support this in the past (#645), but it may now be necessary with the code that splits up statements when they are being prepared. Test whether this is the case and whether `MySqlBatch` is a workaround.

**Comment by badbod99** [comment]
It's not only MySQL Workbench, this is supported through MySQL on the command line also.  See https://dev.mysql.com/doc/refman/8.0/en/stored-programs-defining.html

We use this when joining together all our database scripts for an release.  Running as one script is more practical than opening and submitting several thousand SP files.

**Comment by bgrainger** [comment]
In both cases, it's a workaround for a client-side limitation (i.e., a simplistic SQL parser that splits statements at semicolons).

The current MySqlConnector code should be able to submit thousands of SP scripts as one `MySqlCommand` (without `DELIMITER`); this issue is to verify that that's the case.

**Comment by bgrainger** [comment]
For example, this long SQL string (comprising multiple `CREATE PROCEDURE` statement) can be successfully executed with one `MySqlCommand.ExecuteNonQuery` (wrapped here with Dapper):

https://github.com/mysql-net/MySqlConnector/blob/027dcc255a3a98216f3c9a091fba8f5740f0f118/tests/SideBySide/StoredProcedureFixture.cs#L10-L127

**Comment by bgrainger** [comment]
`CREATE PROCEDURE` is not supported in prepared statements (https://dev.mysql.com/worklog/task/?id=2871), so this test can't ever succeed. Even if it's parsed incorrectly locally, the server will fail with the message ` This command is not supported in the prepared statement protocol yet`.

**Comment by badbod99** [comment]
CREATE PROCEDURE does however work via Connector/Net, it is used via WebDeploy.  I guess they are not using prepared statements for this.

**Comment by bgrainger** [comment]
It works in MySqlConnector, too; see the code I linked to above.

This issue is about testing an edge case that hadn't been tested before. (And testing revealed it's not supported by the _server_, so there's no client-side bug here to fix.)
