### ISSUE TITLE
Delimitter issue

### ISSUE THREAD

**Issue by JamesLoyd** [mysql-net/MySqlConnector#692]
Hi I am using version 0.56.0 though this also happens in 0.52.0.

I have a slight issue where when I create a stored procedure it errors out on the delimiter part:
```
MySql.Data.MySqlClient.MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $$
CREATE PROCEDURE GetCustomerById
```

It appears to also happen in the Oracle .Net Connector: https://bugs.mysql.com/bug.php?id=46429

Is there any known workarounds or plan to fix this? Or maybe an interim solution? 

OS: Dockers for Windows, .NET Core 2.2

**Comment by bgrainger** [comment]
Remove `DELIMITER` from your SQL: https://github.com/mysql-net/MySqlConnector/issues/645#issuecomment-495767223
