### ISSUE TITLE
Improve command timeout handling

### ISSUE THREAD

**Issue by tohghua** [mysql-net/MySqlConnector#694]
using (var conn = new MySqlConnection("..."))
{
	conn.Open();
	var cmd = new MySqlCommand("select sql_no_cache count(*) from a_big_table a, a_big_table b", conn);
	cmd.CommandTimeout = 1; //let it timeout soon
	var a = new MySqlDataAdapter(cmd);
	var t = new DataTable();
	a.Fill(t);
}

With MySql.Data library, above code will kill the query automatically when the command timeout,
but with MySqlConnector, the sql continue runs in the server, wasting resource.
I hope the behavior can be compatible with MySql.Data.
Thanks!

**Comment by bgrainger** [comment]
Possibly a duplicate of #455.

**Comment by tohghua** [comment]
I know it's duplicated, yet the issue is still there.

**Comment by bgrainger** [comment]
Closing as duplicate.
