### ISSUE TITLE
Question using MySqlConnector in a Blazor app

### ISSUE THREAD

**Issue by jensrodi** [mysql-net/MySqlConnector#696]
I'm trying to use MySqlConnector in a new Blazor, connecting to a servers I know is working, one local and one remote. But whatever I do, I get "Unable to connect to any of the specified MySQL hosts". I know that the connection string is valid. I use it with a desktop .NET application.

So the question is: Have anybody else tried to get this working in a Blazor app (with the current release of VS2019Preview)?

Please regard this as a question, not an issue. Hope somebody can give me a hint...

Thanks,
Jens

**Comment by caleblloyd** [comment]
It does work, but you need to make sure if you are using database access (directly or via services) in your blazor components that your are using Blazor server side.

https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0

If you are using blazor web assembly (client side) then you should create a backed project that hosts an API that is separate from the blazor project. Use normal MVC to make a rest API with your db calls in the backed project then pull resources in the blazor project with Blazors Http client service.

https://learn-blazor.com/architecture/rest-api/

Accessing the database directly in WebAssembly is insecure as it would expose your connection string, plus I'm not even sure TCP connections are supported in WebAssembly.

**Comment by jensrodi** [comment]
Thank you very much for the the reply and advise in this matter.

I was attempting to do a pure client-side app, as I was under the impression that the web technologies had evolved to a level where that could be possible. I was wrong and having code running the server as well sort of undermines half my purpose of Blazor, as the target server runs PHP (not supporting ASP.NET), at least for the initial release.

Regarding having the connection string accessible in the client, I don't see how that is solved by moving it to the server. I would still need some sort of authentication between the client and the server, which would exchange a password or similar.

But thanks again. I got a way forward, though not as ideal as I wanted, it is easy enough to implemented and I know I can get that working without much hassle.

Yours,
Jens
