### ISSUE TITLE
read DbNull to string bug

### ISSUE THREAD

**Issue by weianmeng** [mysql-net/MySqlConnector#698]
String type field does not assign value to save to the number library is dbnull, when read the dbnull strong turn string here will be abnormal error

see error

\"Unable to cast object of type 'System.DBNull' to type 'System.String'.\",\"ExceptionType\":\"InvalidCastException\",\"Source\":\"MySqlConnector\",\"HelpLink\":null,\"HResult\":-2147467262,\"StackTrace\":\"   at MySql.Data.MySqlClient.MySqlDataReader.GetString(Int32 ordinal) in C:\\\\projects\\\\mysqlconnector\\\\src\\\\MySqlConnector\\\\MySql.Data.MySqlClient\\\\MySqlDataReader.cs:line 215

**Comment by bgrainger** [comment]
This is how the ADO.NET API works. Use `MySqlDataReader.IsDBNull` to check whether the column is `NULL` before calling `MySqlDataReader.GetString`.
