### ISSUE TITLE
Support for NO_BACKSLASH_ESCAPES

### ISSUE THREAD

**Issue by lauxjpn** [mysql-net/MySqlConnector#701]
As previously discussed here:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/827

A connection string setting as an opt-in feature activates a special mode in the state machine of `SqlParser` to handle the `sql_mode` `NO_BACKSLASH_ESCAPES` correctly for strings, when translating parameters into inline literals (e.g. when calling `MySqlCommand.Execute`) or splitting the statements (e.g. when calling `Prepare`).

**Comment by bgrainger** [comment]
Two possible ways of approaching this problem:

* Add `NoBackslashEscapes` (default `false`); when `true`, performs string escaping and SQL parsing in a way compatible the `NO_BACKSLASH_ESCAPES` SQL mode.
* Add `DetectSqlMode` (default `false`); when `true`, executes `SELECT @@sql_mode;` when a connection is made, and automatically turns on backslash escaping if `NO_BACKSLASH_ESCAPES` is detected.

Advantages of the latter: user doesn't have to specify (or guess) the escaping mode; extensible in the future to other modes (`ANSI_QUOTES`? `NO_ZERO_DATE` (although already handled by `AllowZeroDateTime`)?); no functional harm from always setting it to `true`; not a breaking change to default it to `true` in the future.

Disadvantages of the latter: performance penalty for checking `sql_mode` at connect time; there's already precedence (`AllowZeroDateTime`) for a connection string setting controlling one aspect of SQL Mode functionality.

AFAIK there is no relevant Connector/NET option to be compatible with here. (I think it may always check `@@sql_mode` on each connection.)

**Comment by bgrainger** [comment]
`NoBackslashEscapes` is the simplest thing that could possibly work, and is compatible with how Pomelo will use this library.

`DetectSqlMode` could be added in the future and override the default value of `NoBackslashEscapes`.

**Comment by lauxjpn** [comment]
> DetectSqlMode could be added in the future and override the default value of NoBackslashEscapes.

Absolutely. Also consider this approach:

> To track the mode, the incomming queries would need to be parsed to some extend. Probably looking for sql_mode = and if so, querying the sql_mode and saving it after executing the original query.
So the cost would be an additional roundtrip when sql_mode appears in a query.

It would have the advantage to not trigger an automatic round trip when opening the connection, but only, when the mode is being changed and would detect changes in the mode during the lifetime of the connection.

**Comment by lauxjpn** [comment]
> `NoBackslashEscapes` is the simplest thing that could possibly work, and is compatible with how Pomelo will use this library.

The connection string option is now all that is left to do. Do *you* want to implement it, or should *I*?

**Comment by bgrainger** [comment]
I can do it.

**Comment by lauxjpn** [comment]
Perfect! I close this one then.

**Comment by bgrainger** [comment]
I plan to ship an updated package later today.

**Comment by bgrainger** [comment]
Added in [0.58.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.58.0).
