### ISSUE TITLE
Implement SET data type

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#71]
Implement support for `SET`.

http://dev.mysql.com/doc/refman/5.7/en/set.html

Required for #4.

**Comment by GetLu5k** [comment]
@bgrainger hey
can you explain meaning of this feature? You need structure like SET?

**Comment by bgrainger** [comment]
MySQL allows a column type to have a type of `SET` (see the documentation linked above).

This library needs to allow clients to query columns of that data type, insert new data, etc. It should expose the same .NET types as MySql.Data does, for compatibility with that library.

At a minimum, new tests that use this data type need to be added to test the level of support that currently exists and show what's missing.
