### ISSUE TITLE
FieldCount throws InvalidOperationException in 0.60.1

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#728]
> Fixed in [0.60.1](https://github.com/mysql-net/MySqlConnector/releases/tag/0.60.1).

There are cases when we check the data reader **FieldCount** property, in order to know if we should read the data reader. With the latest update, all these checks on the data reader are throwing exceptions, when the reader is empty and only output parameters are returned.

This breaks some of our property checks on the data reader, where until now no exception was expected.

Also, executing a query that, by its nature, does not return rows (such as a DELETE query), should set FieldCount to 0. What about the HasRows property?

_Originally posted by @kostebudinoski in https://github.com/mysql-net/MySqlConnector/issues/722#issuecomment-544519226_

**Comment by bgrainger** [comment]
This was an unintentional regression in 0.60.1.

(There are tests for `FieldCount` and `HasRows` for a "regular" empty `MySqlDataReader`, but not for the pseudo-empty one that represents a stored procedure with only output parameters.)

**Comment by kostebudinoski** [comment]
Great! Thanks!

**Comment by bgrainger** [comment]
Fixed in [0.60.2](https://github.com/mysql-net/MySqlConnector/releases/tag/0.60.2).
