### ISSUE TITLE
Add MySqlConnection.CloneWith

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#736]
Add a new method, `MySqlConnection.CloneWith(string connectionString)` that returns an unopened copy of an existing connection, but with a new connection string. If the new connection string doesn't supply a password, the current connection's password is used.

This would allow (for example) pooling to be changed without disclosing the existing connection's password or requiring the calling code to know it.

Examples:

```csharp
var newCsb = new MySqlConnectionConnectionStringBuilder(existingConnection.ConnectionString)
{
    Database = "",
    Pooling = false,
};
var newConnection = existingConnection.CloneWith(csb.ConnectionString);
```

From https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/908#issuecomment-549466074 and similar to https://github.com/npgsql/npgsql/blob/7c44dd30144c224995e688d526276f5373c93de7/src/Npgsql/NpgsqlConnection.cs#L1297-L1315.

**Comment by bgrainger** [comment]
Added in [0.61.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.61.0).

**Comment by rgarrison12345** [comment]
I would actually like to see this added onto the base class DbConnection as well
