### ISSUE TITLE
CommandText should be an empty string by default

### ISSUE THREAD

**Issue by roji** [mysql-net/MySqlConnector#743]
[As per the docs](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand.commandtext?view=netframework-4.8#System_Data_Common_DbCommand_CommandText).

I'd also consider throwing if null is set, although that would be a slightly bigger breaking change.

**Comment by bgrainger** [comment]
> I'd also consider throwing if null is set

It appears that only npgsql does this: https://mysql-net.github.io/AdoNetResults/#CommandText_is_coerced_to_empty_string

Most other drivers silently coerce `null` to `""`. (Sqlite leaves it as `null`.) This is also the general behaviour for `DbConnection.ConnectionString`, even for npgsql.

I plan to default to `""` and coerce `.CommandText = null` to `""`.

**Comment by roji** [comment]
Makes sense.

**Comment by bgrainger** [comment]
Changed in [0.62.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.62.0).
