### ISSUE TITLE
Consider forcing upper limit for connection pool by blocking

### ISSUE THREAD

**Issue by lauxjpn** [mysql-net/MySqlConnector#747]
There is an [issue on StackOverflow](https://stackoverflow.com/questions/59049481/how-to-use-pomelo-entityframeworkcore-mysql-provider-for-ef-core-3-in-async-mode) regarding a (seemingly) unbounded number of connections that can be opened.

This is consistent with the description from the [docs](https://mysqlconnector.net/connection-options/):

> **Pooling:**
> Enables connection pooling. When pooling is enabled, MySqlConnection.Open retrieves an open connection from the pool if one is available (opening a new connection if not), and Close/Dispose returns the open connection to the pool.

I first considered this expected, as it is the responsibility of the user to take care of the number of connections he wants.

But there is a great talk from @roji about [lock-free database pool development](https://youtu.be/YQHFbYl38SE?t=1464) that makes a strong counter case for forcing an upper limit and blocking/waiting when exceeded.

(BTW, the talk is directly about #462 and with a lot of useful low level information.)

Maybe this behavior could be made the default, so users don't create too many connections by accident (as in the StackOverflow case), and the previous one opt-in?

**Comment by bgrainger** [comment]
This is a documentation error, if you are interpreting the docs to mean that you can create an unlimited number of connections.

When pooling is true, each connection pool (there is one per unique connection string) only allows `MaximumPoolSize` connections to be open simultaneously. Each additional call to `MySqlConnection.Open` _will block_ until a connection is returned to the pool.

When pooling is false, there is no limit to the number of connections that can be opened simultaneously; it's up to the user to manage the concurrency.

**Comment by bgrainger** [comment]
I can look into this if you have a repro (e.g., with `Pooling=true;MaxPoolSize=10` in the connection string) that opens more than 10 connections.

There's a test that verifies that the connection pool blocks `OpenAsync` when it's exhausted:

https://github.com/mysql-net/MySqlConnector/blob/05df17a6f4e2f6c899598e00f0790badc7195296/tests/SideBySide/ConnectionPool.cs#L59

**Comment by lauxjpn** [comment]
Okay thanks! I will see if I can reproduce the described behavior in the SO post.

**Comment by bgrainger** [comment]
I pushed a docs change: ff3da11688460853670e3c1024b177f116ed9b01
