### ISSUE TITLE
"Unable to connect to any of the specified MySQL hosts" Error while attempting to connect to AWS MySQL Server

### ISSUE THREAD

**Issue by asyncswin** [mysql-net/MySqlConnector#764]
I am able to connector with other MySql data providers. Some examples would be really useful. 

**Connection String:**
Server=<server>.amazonaws.com;User Id=user;Database=dbname;Password=pw;Connection Timeout=6000

**Exception:**
  | Name | Value | Type
-- | -- | -- | --
  | Message | "Unable to connect to any of the specified MySQL hosts." | string
  | Number | 1042 | int

**Comment by bgrainger** [comment]
> Server=.amazonaws.com

This is not a valid hostname. MySqlConnector expects a valid host name (or IP address) as the `Server` connection string option.
