### ISSUE TITLE
Change DbDataReader.{GetSchemaTable,GetColumnSchema} to return empty results when there is no resultset

### ISSUE THREAD

**Issue by roji** [mysql-net/MySqlConnector#770]
As discussed in dotnet/runtime#509. This would be a small breaking change (so ideally done in the upcoming 2.0.0), which would make these methods more consistent and more usable in the new null-annotated world.

/cc @ajcvickers @bricelam

**Comment by bgrainger** [comment]
Duplicate of #744

**Comment by bgrainger** [comment]
This has already been implemented in the 0.62.0-beta5 release.

**Comment by roji** [comment]
Great, thanks @bgrainger!
