### ISSUE TITLE
Transaction isolation levels are not supported for special databases

### ISSUE THREAD

**Issue by ich-wangxf** [mysql-net/MySqlConnector#772]
I‘m a developer in China, When I use the aliyun Distributed Relational Database Service (https://help.aliyun.com/product/29657.html), the product does not support the transaction isolation level, only supports basic transaction, for example "start transaction"，hope can through configuration to decide whether to enable the transaction isolation level,  at present can only solve by modifying the key code, the code is as follows

`using (var cmd = new MySqlCommand("start transaction;", this))

//using (var cmd = new MySqlCommand("set transaction isolation level " + isolationLevelValue + "; start transaction;", this))
 await cmd.ExecuteNonQueryAsync(ioBehavior, cancellationToken).ConfigureAwait(false);`

**Comment by billsking** [comment]
I have the same problem. It may be more flexible to change it to a configurable way.

**Comment by bgrainger** [comment]
What do you think of the following possible solution: if `BeginTransaction` is called with `IsolationLevel.Unspecified` then the `set transaction isolation level X` command is not emitted?

That is, using `IsolationLevel.Unspecified` (which is the default) will use the database's default isolation level. An explicit `IsolationLevel` value would have to be passed to `BeginTransaction` in order to send a `set transaction isolation level X` command and set the isolation level.

**Comment by ich-wangxf** [comment]
> What do you think of the following possible solution: if `BeginTransaction` is called with `IsolationLevel.Unspecified` then the `set transaction isolation level X` command is not emitted?
> 
> That is, using `IsolationLevel.Unspecified` (which is the default) will use the database's default isolation level. An explicit `IsolationLevel` value would have to be passed to `BeginTransaction` in order to send a `set transaction isolation level X` command and set the isolation level.

May I ask how to disable the default transaction isolation level? When I transfer the key code in your component ("set transaction isolation level "+ isolationLevelValue + ";Start the transaction.") to "start transaction", use the Aliyun DRDS can be used normally. Of course, I also consulted the database engineer of Aliyun, and they replied that "set transaction isolation level repeatable read;start start transaction" is not supported; "set transaction isolation level repeatable read" this transaction level is invalid in the DRDS setting, and only the " start transaction" can be used.
