### ISSUE TITLE
Support ColumnMappings in MySqlBulkCopy

### ISSUE THREAD

**Issue by themagicis** [mysql-net/MySqlConnector#773]
I'm using MySqlBulkCopy to load data from a data reader into a MariaDb 10.4 database.
I'm using EF core and Pomelo. Code first way to create the database.
It doesn't work if the column order of the data reader doesn't match the database column order.
The EF migration creates the db tables with some ordering of the columns. 
The issue occurs when I try to use MySqlBulkCopy and I pass a data reader with different order of the columns. I checked the sql query - the LOAD DATA statement orders the columns as they are in the database, but when the data is sent to the server, the column are written as they are in the data reader. So I got an error that string value cannot be inserted into a numerical column.
The data reader is a FastMember ObjectReader. If I change the columns order of the object reader to match the database order, MySqlBulkCopy is working as exepcted.

**Comment by bgrainger** [comment]
As you've discovered, `MySqlBulkCopy` currently requires that the bulk copy source contain data for all database columns (i.e., you can't rely on `DEFAULT` values) and that they be in the same order as the destination table.

This restriction will probably be relaxed by implementing a `ColumnMappings` property similar to [`SqlBulkCopy.ColumnMappings`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopy.columnmappings).

I haven't decided what the API shape of that should be yet, and if it should support expressions (like `MySqlBulkLoader`).

> If I change the columns order of the object reader to match the database order, MySqlBulkCopy is working as exepcted.

This is the current workaround you'll need to use.

**Comment by bgrainger** [comment]
Added this known issue to the documentation: 46783e380640dc86f03e311dde12093a893342d5

**Comment by themagicis** [comment]
Thanks, having option like SqlBulkCopy.ColumnMappings would be very useful. Especially when using ORMs and cases where the data source has different column names compared to the database.

**Comment by MickaelBillet** [comment]
Thanks, having option like SqlBulkCopy.ColumnMappings would be very useful. Especially when using ORMs and cases where the data source has different column names compared to the database.

**Comment by mikeTWC1984** [comment]
+1. This is also useful if destination table has autoincremental column.

**Comment by bgrainger** [comment]
The initial API I'm thinking of going with is:

```csharp
class MySqlBulkCopyColumnMapping
{
    public int SourceOrdinal { get; set; }
    public string DestinationColumn { get; set; }
    public string Expression { get; set; }
}
```

`SourceColumn` would require enumerating the input source (of which there can be many different types) to map column names to ordinals. `DestinationOrdinal` would require getting the columns of the destination table to make positions to column names. These would both be less efficient (and more complicated) than simply mapping source ordinals to destination column names so I would omit them from the initial implementation unless there's user feedback that they'd be necessary.

`Expression` would be an optional expression (accepted by `LOAD DATA`) that transforms an input column to a destination column.

**Comment by bgrainger** [comment]
Added in [0.65.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.65.0); would like to hear your feedback.

Documentation at https://mysqlconnector.net/api/mysql-bulk-copy/.

**Comment by mikeTWC1984** [comment]
Good work. I think in most cases mapping would come from some dictionary though (key as source, value as destination). Also ordinal look a bit more tricky than column name.  MSSQL uses mapping collection which is a property on bulkcopy object, and you can add new mapping just like that: bcp.ColumnMappings.Add("srcName", "dstName").

**Comment by bgrainger** [comment]
> MSSQL uses mapping collection which is a property on bulkcopy object, and you can add new mapping just like that: bcp.ColumnMappings.Add("srcName", "dstName").

Its custom collection type (probably?) predates generics, and certainly predates usability enhancements in the C# language, e.g., collection initialisers. I think it's overkill to implement a custom collection type right now, and it will become even easier to use in C# 9 with [target-typed new](https://github.com/dotnet/csharplang/blob/master/proposals/target-typed-new.md):

```csharp
var bulkCopy = new MySqlBulkCopy
{
    DestinationTableName = "table",
    ColumnMappings =
    {
        new(0, "colA"),
        new() { SourceOrdinal = 1, DestinationColumn = "colB" },
    }
};
```

> Also ordinal look a bit more tricky than column name.

Adding `SourceColumn` and automatically mapping it to the corresponding `SourceOrdinal` is a reasonable future extension (for input sources that can support such a lookup).

**Comment by bgrainger** [comment]
> it will become even easier to use in C# 9 with target-typed new

Example:

https://github.com/mysql-net/MySqlConnector/blob/2cbc4ddcdf52cbdd9a705d8c9ff6c8be5cc335d5/tests/SideBySide/BulkLoaderSync.cs#L773-L782
