### ISSUE TITLE
Add transaction savepoint API

### ISSUE THREAD

**Issue by roji** [mysql-net/MySqlConnector#775]
MySQL supports the SQL Standard for savepoints: https://dev.mysql.com/doc/refman/8.0/en/savepoint.html. SqlClient and Npgsql expose APIs for this their DbTransaction implementation, and https://github.com/dotnet/runtime/issues/33397 tracks adding the relevant APIs in System.Data.

**Comment by bgrainger** [comment]
Added in [0.63.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.63.0).
