### ISSUE TITLE
Connection Lifetime is not working

### ISSUE THREAD

**Issue by yuguixiao** [mysql-net/MySqlConnector#778]
Hello, there is such a scenario, because the SDN on the cloud will clean up the connection every 240s, which is insensitive to the client and server, so the client should actively disconnect the connection in 240 seconds.For MySQL Connection pool, I configured Connection Lifetime=60 and the Connection was not actively disconnected.Is there any other requirement for this configuration?Thank you very much!

**Comment by bgrainger** [comment]
It looks like idle connections in the pool aren't automatically pruned once they exceed `ConnectionLifeTime`; it only takes effect when a connection is returned to the pool.

While this matches the documentation, it's probably not useful for controlling the lifetime of a connection, as an idle connection might stay open indefinitely (past its specified lifetime).

**Comment by bgrainger** [comment]
MySqlConnector matches the Connector/NET behaviour, which is documented as follows:

> When a connection is returned to the pool, its creation time is compared with the current time and the connection is destroyed if that time span (in seconds) exceeds the value specified by `Connection Lifetime`. This option is useful in clustered configurations to force load balancing between a running server and a server just brought online.

I consider this a documentation bug for MySqlConnector, not an implementation bug.

To get the behaviour you want (of no connection living longer than 240s), use something like `ConnectionLifeTime=120;ConnectionIdleTimeout=90` (you may want to tweak the exact values for performance). With these settings, connections that are over two minutes old will be closed immediately when returned to the pool, and connections that have been in the pool over 90 seconds will automatically be closed. Even if a connection is returned when it's 119 seconds old (i.e., 1:59), it should be cleaned up by the idle connection pruner before four minutes are up.

**Comment by bgrainger** [comment]
Documentation bug was introduced in fbc06081ea96c7259d4138792dbfaa611e0ab1b8.
