### ISSUE TITLE
Expression to sql error

### ISSUE THREAD

**Issue by zhanglofeing** [mysql-net/MySqlConnector#779]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '& (`r`.`State` = 0)' at line 3

C#:
new[] { user }.RisksAsAssignee().And(item => item.State == RiskState.Open).AsQuery(projectContext).Count()

generates sql:
SELECT COUNT(*)
      FROM `Risks` AS `r`
      WHERE `r`.`AssigneeId` IN ('PM') & (`r`.`State` = 0);

C#:
Expression<Func<Task, bool>> expression = item => item.State == TaskState.Normal;
                var total2 = expression.And(new[] { user }.TasksAsCreator()).AsQuery(projectContext).Count();

generates sql:
SELECT COUNT(*)
      FROM `Tasks` AS `t`
      WHERE (`t`.`State` = 0) & `t`.`CreatorId` IN ('PM');

The SQL generated by the first expression cannot be executed, the second generated can be executed.
The difference between these is the position change of enum comparison.
![image](https://user-images.githubusercontent.com/37825566/77055418-ce818280-6a0b-11ea-9dff-52f270e36ef9.png)

**Comment by bgrainger** [comment]
MySqlConnector (this library) doesn't generate SQL. You need to file a bug against the library that generates the invalid SQL. (I don't recognise `ProjectContext`, `AsQuery`, etc., so I can't suggest where the bug should be filed.)

**Comment by zhanglofeing** [comment]
> MySqlConnector (this library) doesn't generate SQL. You need to file a bug against the library that generates the invalid SQL. (I don't recognise `ProjectContext`, `AsQuery`, etc., so I can't suggest where the bug should be filed.)

Thank you very much. The problem has been solved. It's our own framework problem!
