### ISSUE TITLE
MySqlParameter ctor issue

### ISSUE THREAD

**Issue by yukozh** [mysql-net/MySqlConnector#787]
Can I pass the sourceColumn without MySqlDbType and let the MySqlConnector determine the type automatically? Or can I pass the string format DB type like 'varchar(100)'?

**Comment by bgrainger** [comment]
`MySqlParameter.SourceColumn` is only used by `MySqlDataAdapter`, which is primarily implemented by the .NET Framework. I don't know if it can do type inference based solely on the column name. Can you give an example?

`SourceColumn` has to be a column name, not a DB type string.
