### ISSUE TITLE
Allow Isolation level Snapshot

### ISSUE THREAD

**Issue by battyejp** [mysql-net/MySqlConnector#788]
Hi we would like to be able to use a transaction 'with consistent snapshot' (https://dev.mysql.com/doc/refman/5.7/en/commit.html). Would you be open to a pull request to update MySqlConnection.cs to allow the method BeginDbTransactionAsync to be updated to allow the snapshot isolation level to be used that executes the correct sql.

Thanks

**Comment by bgrainger** [comment]
Yes, PRs are welcome!

Is the plan to make `IsolationLevel.Snapshot` set the `REPEATABLE READ` isolation level, then add `WITH CONSISTENT SNAPSHOT`?

**Comment by battyejp** [comment]
Yes that is exactly what I was planning on doing

**Comment by bgrainger** [comment]
Fixed by #791.

**Comment by bgrainger** [comment]
Added in [0.63.2](https://github.com/mysql-net/MySqlConnector/releases/tag/0.63.2).
