### ISSUE TITLE
Not support for datatype "geography" and "hierarchyid" of MSSQL

### ISSUE THREAD

**Issue by victor-wiki** [mysql-net/MySqlConnector#790]
When i use the "geography" and "hierarchyid" type of MSSQL which map to .net type  "SqlGeography" and "SqlHierarchyId", which in Microsoft.SqlServer.Types library, and i define "longtext" for "geography" , "varchar(1000)" for "hierarchyid" in MySql table. When i use MySqlBulkCopy to copy data from MSSQL to MySql, it throws NotSupportedException. But the MySqlBulkLoader of MySql.Data can handle them properly. I think it's better provide a custom type converter mechanism to support something like this.

**Comment by bgrainger** [comment]
FWIW, MySqlConnector also supports `MySqlBulkLoader`, so you could use that as a workaround.

> I think it's better provide a custom type converter mechanism to support something like this.

That might be something that could be implemented as part of ColumnMappings: #773

**Comment by bgrainger** [comment]
If both `SqlGeography` and `SqlHierarchyId` (or any other unhandled type) have a `ToString()` implementation that returns a correctly-formatted value, the `MySqlBulkCopy` code could just call `ToString()` on all otherwise-unhandled objects.

**Comment by victor-wiki** [comment]
I tried it and the exception was thrown from method "WriteValue" of MySqlBulkCopy. So, i have changed the column type and value data type of the DataTable before calling WriteToServerAsync.

**Comment by bgrainger** [comment]
My comment was proposing a (future) change to the `MySqlBulkCopy` implementation that might accommodate your scenario.

If you've found a workaround, that sounds good to use for now.

**Comment by victor-wiki** [comment]
got it, thanks as well.
