### ISSUE TITLE
MySqlBulkLoader load only first record

### ISSUE THREAD

**Issue by mortalV** [mysql-net/MySqlConnector#797]
On some combination of MySqlBulkLoader flags and (maybe) field types from file imported only first record. 

For test create this table

```SQL
 CREATE TABLE tmp_sale_descriptors (
  id bigint(20) unsigned NOT NULL DEFAULT '0',
  id_account int(11) unsigned NOT NULL,
  body blob NOT NULL,
  image_directory varchar(255) DEFAULT NULL,
  id_profile bigint(20) unsigned DEFAULT NULL,
  gen bigint(20) unsigned DEFAULT NULL,
  creator_device_id bigint(20) DEFAULT NULL,
  changer_device_id int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

Try load this file
[sale_descriptors.txt](https://github.com/mysql-net/MySqlConnector/files/4464284/sale_descriptors.txt)

```C#
var loader = new MySqlBulkLoader(objCon)
            {
                FileName = "c:/sale_descriptors.txt",
                FieldTerminator = ",",
                FieldQuotationCharacter = '"',
                LineTerminator = @"\n",
                TableName = "tmp_sale_descriptors",
                CharacterSet = "binary",
                Local = true
            };
            loader.Columns.AddRange("id,id_account,creator_device_id,changer_device_id,image_directory,id_profile,body,gen".Split(','));
loader.Load();
```

As result only first record from file but must be 3.

Using regular SQL like this 

```SQL
LOAD DATA local INFILE 'c:/sale_descriptors.txt'
    INTO TABLE tmp_sale_descriptors
    CHARSET binary
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
(id,id_account,creator_device_id,changer_device_id,image_directory,id_profile,body,gen);
```

works as expected. 3 records in table.

If set Local = false then I get error " MySqlException: Incorrect integer value: 'N\x0A27436251086861' for column 'gen' at row 1 ".
With manual SQL command all works as expected.

I've tried version 0.63.2 , 0.63 and got errors.
But on version 0.60 all works fine with local true and false.

**Comment by mortalV** [comment]
I just enable logging and found difference between versions

On version 0.60 ENCLOSED BY '"' LINES TERMINATED BY '\n'
On version 0.63.2 ENCLOSED BY '\"' LINES TERMINATED BY '\\n'

**Comment by bgrainger** [comment]
Thanks for the diagnosis; this may have been a regression introduced by #759.

**Comment by bgrainger** [comment]
I think this is an error:

```csharp
LineTerminator = @"\n",
```

That specifies that the line terminator is the literal string `\n`, including the backslash. To specify a linefeed, use just `"\n"` (with no leading `@`). 

For example, see the official documentation at https://dev.mysql.com/doc/connector-net/en/connector-net-programming-bulk-loader.html which just specifies `bl.LineTerminator = "\n";`.

**Comment by mortalV** [comment]
Yes. You are right.
Now it works.

Thanks.
