### ISSUE TITLE
Cannot set MySqlCommand.Connection when there is an open DataReader for this command

### ISSUE THREAD

**Issue by fish-li** [mysql-net/MySqlConnector#799]
The same testcase,
MySqlConnector is failed, MySql.Data works!

```cs
[TestMethod]
public void Test_DateTime_DataType2()
{
    string connectionString = "Server=FishDbServer;Database=MyNorthwind;Uid=user1;Pwd=qaz1@wsx;Allow Zero Datetime=True;Convert Zero Datetime=True;";
    string sql = "select now()";

    using( MySqlConnection conn2 = new MySqlConnection(connectionString) ) {
        using( DbDataReader reader = GetDbDataReader(conn2, sql) ) {
            reader.Read();
            DateTime time = reader.GetDateTime(0);

            Assert.AreEqual(DateTime.Today, time.Date);
        }
    }            
}


private DbDataReader GetDbDataReader(MySqlConnection conn, string sql)  // mock an internal method
{
    if( conn.State != ConnectionState.Open )
        conn.Open();

    MySqlCommand command = conn.CreateCommand();
    command.CommandText = sql;

    try {
        return command.ExecuteReader();
    }
    finally {
        // MySqlConnector throw error: 
        // System.InvalidOperationException: Cannot set MySqlCommand.Connection when there is an open DataReader for this command; it must be closed first.

        // MySql.Data, It works!
        command.Connection = null;
    }
}
```

**Comment by bgrainger** [comment]
This exception was added for #308.

The behaviour is currently intentional: while a `MySqlCommand` is being used (e.g., a data reader created from it is active), the command can't be mutated.

Is there a reason why setting `command.Connection = null;` is necessary or useful? That whole `try`/`finally` block seems superfluous to me.

See also https://mysqlconnector.net/tutorials/migrating-from-connector-net/ for a list of places where MySqlConnector is deliberately incompatible with MySql.Data's API in order to improve robustness.

**Comment by fish-li** [comment]
The GetDbDataReader method has a public event `BeforeExecute`. it allow outside code access command instance.

So, in finally block, i set `command.Connection = null; command.Transaction = null;`  in order to avoid unknown problems.

**Comment by fish-li** [comment]
The System.Data.SqlClient and Npgsql  also supports this invocation

**Comment by bgrainger** [comment]
> So, in finally block, i set command.Connection = null; command.Transaction = null; in order to avoid unknown problems.

I still don't understand this. Doing this provides no concrete benefit for any ADO.NET provider, and is incompatible with others. In fact, it causes known problems.

> The System.Data.SqlClient and Npgsql also supports this invocation

According to my compatibility tests, it's incompatible with MySqlConnector, Npgsql, and various Sqlite flavours: https://mysql-net.github.io/AdoNetResults/#Connection_throws_when_set_to_null_when_open_reader

**Comment by fish-li** [comment]
All right, I'll take your advice.
