### ISSUE TITLE
Please make MySql.Data.EntityFrameworkCore.Migrations.Internal.MySQLMigrationsSqlGenerator public

### ISSUE THREAD

**Issue by Algorithman** [mysql-net/MySqlConnector#808]
I know i'm not quite right here with this, but maybe someone of oracle (or whoever wrote the EFCore part) reads this too.

I need to base off MySQLMigrationsSqlGenerator to automatically create triggers for my tables which provide me with a very easy to use polling mechanism for database changes.

But since it's internal, i can't do that. Please free the MySQLMigrationsSqlGenerator!

Otherwise i have to switch databases (or go back to EF).

Sincerely 

Algorithman

**Comment by Algorithman** [comment]
Nvm, i'm completely wrong here.

**Comment by bgrainger** [comment]
You may want to consider switching to [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql).

It's based on MySqlConnector, is updated frequently, is less buggy than Oracle's version, and that class already appears to be `public`: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs

**Comment by Algorithman** [comment]
Thx, i did already :)
