### ISSUE TITLE
MySqlBulkCopyColumnMapping expressions, extra 'SET' in generated SQL

### ISSUE THREAD

**Issue by jhonsrid** [mysql-net/MySqlConnector#819]
When using expressions in MySqlBulkCopyColumnMapping for MySqlBulkCopy, (as required to write BIT fields), an extra "SET" seems to be applied to the generated SQL inconsistently.

For instance, with table definitions and data:
```
CREATE TABLE BulkSource (FieldName BIT(1));
CREATE TABLE BulkTarget SELECT * FROM BulkSource;
INSERT INTO BulkSource(FieldName) values(b'1');
```
If you map columns in this manner:
```
bulkCopy.ColumnMappings.Add(new MySqlBulkCopyColumnMapping(0, "@tmp", $"SET FieldName = UNHEX(@tmp)"));
bulkCopy.WriteToServer(dt);
```
(As shown in https://mysqlconnector.net/api/mysql-bulk-copy/), the generated SQL (from MySqlConnector debug), is:

```
LOAD DATA LOCAL INFILE ':SOURCE:xxxxxxxxxxxx' INTO TABLE `BulkTarget` CHARACTER SET utf8mb4 FIELDS TERMINATED BY '       ' ESCAPED BY '\\' LINES TERMINATED BY '
' IGNORE 0 LINES (@tmp) SET SET FieldName = UNHEX(@tmp);
```

Which throws error: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use`

(Note **SET SET** in the statement).

Subsequent fields do not trigger this extra "SET" to be added to them.

This doesn't appear to be a datatype specific issue, (the same happens with other field types like "int", eg: `SET INTFieldName = @tmp` ).

Example program:
```
// DROP TABLE IF EXISTS BulkSource;
// DROP TABLE IF EXISTS BulkTarget;
// CREATE TABLE BulkSource(FieldName BIT(1));
// CREATE TABLE BulkTarget SELECT * FROM BulkSource;
// INSERT INTO BulkSource(FieldName) values(b'1');

using System.Data;
using MySql.Data.MySqlClient;
using MySqlConnector.Logging;

namespace BulkTest
{
    class Program
    {
        static DataTable GetData(MySqlConnection connection)
        {
            var dt = new DataTable();
            using (var cmd = new MySqlCommand("SELECT * FROM BulkSource", connection))
            {
                using var da = new MySqlDataAdapter(cmd);
                da.Fill(dt);
            }
            return dt;
        }

        static void Main(string[] args)
        {
            MySqlConnectorLogManager.Provider = new ConsoleLoggerProvider(MySqlConnectorLogLevel.Debug);
            using (var connection = new MySqlConnection("CONNECTIONSTRINGINCLUDING: AllowLoadLocalInfile=true"))
            {
                connection.Open();
                var bulkCopy = new MySqlBulkCopy(connection);
                bulkCopy.DestinationTableName = "BulkTarget";
                DataTable dt = GetData(connection);
                bulkCopy.ColumnMappings.Add(new MySqlBulkCopyColumnMapping(0, "@tmp", $"SET FieldName = UNHEX(@tmp)"));
                bulkCopy.WriteToServer(dt);
            }
        }
    }
}
```

Tested against MySqlConnector v0.66.0, and also from master branch (which i've just realised is also v0.66.0 right now),

**Comment by bgrainger** [comment]
This is a documentation bug; the keyword `SET` should not be included in the value of `Expression`.

**Comment by bgrainger** [comment]
> as required to write BIT fields

FWIW the next release will automatically handle `BIT` and binary columns, supplying the right expressions as needed: 2e5d127dc32ffbd2191ef356d4dcb7f0e1c81edc

**Comment by jhonsrid** [comment]
> This is a documentation bug; the keyword `SET` should not be included in the value of `Expression`.

Thanks, works great!
