### ISSUE TITLE
Question: Are the prior version < 0.67.0 does no return Task<MySqlSataReader> at ExecuteReaderAsync?

### ISSUE THREAD

**Issue by mikependon** [mysql-net/MySqlConnector#826]

**Comment by bgrainger** [comment]
In 0.66 and later, `MySqlCommand` did not implement `ExecuteReaderAsync`; it was only implemented by the `DbCommand` base class and returned `Task<DbDataReader>`: https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand.executereaderasync?view=netcore-3.1

Now in 0.67.0, `MySqlCommand` implements `new` implementations of that method and changes the return type to `Task<MySqlDataReader>`.

You can see the API diff here: https://www.fuget.org/packages/MySqlConnector/0.67.0/lib/netstandard2.1/diff/0.66.0/
