### ISSUE TITLE
Add ResetConnectionAsync

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#831]
From https://github.com/mysql-net/MySqlConnector/issues/178#issuecomment-641389096

For advanced scenarios, it could be useful to support the following API:

```
class MySqlConnection
{
    public ValueTask ResetConnectionAsync(CancellationToken token = default);
}
```

This would send a [`COM_RESET_CONNECTION` packet](https://dev.mysql.com/doc/internals/en/com-reset-connection.html) to reset the open connection.  By allowing the user to manually reset the connection only when needed (e.g., a temporary table has been created or user variables were set), it would be practical to add `ConnectionReset=false` to the connection string and avoid its overhead when retrieving a pooled connection (see #178).

Since this is an advanced API, is a synchronous version of this method needed? (Probably not.)

**Comment by athoscouto** [comment]
Thanks for doing this @bgrainger!
Will this feature be available on `0.x` or only on `1.x`?

**Comment by bgrainger** [comment]
This is only in the 1.0.0 release.

While it's current tagged as `-beta` in NuGet, this is mostly due to the (breaking) namespace change, rather than any prerelease code quality issues.

**Comment by athoscouto** [comment]
Just tested it and couldn't make it work.

Migrated to `1.0.0-beta.4` and added `ConnectionReset=False` to the connection string.
Before calling `MySqlConnection.DisposeAsync()` I awaited `MySqlConnection.ResetConnectionAsync()`.

I've got an `"Unknown command`" exception. This was at the top of the stack trace:
```
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 806
   at MySqlConnector.MySqlConnection.ResetConnectionAsync(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 436
```

**Comment by bgrainger** [comment]
What server and version are you using? For MySQL Server, you have to be running 5.7.3 or later. For MariaDB, it needs to be 10.2.4 or later. Other MySQL-compatible backends may not support it at all.
