### ISSUE TITLE
Async resultset and database schema APIs

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#835]
API proposal at https://github.com/dotnet/runtime/issues/38028.

Note that `GetSchemaTableAsync` and `GetColumnSchemaAsync` will always run synchronously in MySqlConnector; this should be called out in the documentation.

**Comment by bgrainger** [comment]
Updated API proposal at https://github.com/dotnet/runtime/issues/38028#issuecomment-651967965.

**Comment by roji** [comment]
@bgrainger I've just merged https://github.com/dotnet/runtime/pull/39098 for async schema APIs. If your implementation is sync in any case, there's no real reason to do anything on your side - the new System.Data APIs automatically fall back to their sync counterparts. Though I'm curious why these can only be synchronous on MySQL, is there no network involved?

**Comment by bgrainger** [comment]
@roji When a query is executed, MySQL Server sends the column metadata (for each column in the result set) as the initial response, so this information is always available by the time `GetColumnSchemaAsync` is invoked.

**Comment by roji** [comment]
@bgrainger what about DbConnection.GetSchemaTable, which is supposed to provide the list of tables/columns/views/etc?

For the DbDataReader, the standard seems to be to expose the minimal information that's provided by the server, but if CommandBehavior.KeyInfo is specified on the command, to possibly go back to the database and retrieve any extra information via another query. No idea whether that makes sense for MySQL or not...

**Comment by roji** [comment]
At least for Npgsql, PostgreSQL doesn't send a lot of information with standard resultsets, so I use KeyInfo is an indicator that the user wants me to query additional info from the database. I can provide more details (the relevant file is [DbColumnSchemaGenerator](https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/Schema/DbColumnSchemaGenerator.cs)).

**Comment by bgrainger** [comment]
@roji I was speaking specifically about `(MySqlDataReader).GetSchemaTableAsync` (which will be sync); `MySqlConnection.GetSchemaAsync` does (for many schemas) perform DB I/O and will execute asynchronously.

**Comment by roji** [comment]
Oh I see, thanks for clarifying. Does it make sense to open a separate issue to track implementing DbConnection.GetSchemaTable, or should this one be used (having "database schema" in the title)?

**Comment by bgrainger** [comment]
I conflated them into this issue. The (async) `MySqlConnection.GetSchemaAsync` implementation is here: https://github.com/mysql-net/MySqlConnector/blob/bb39cd80690ff172c28c6440aa73c320b752733a/src/MySqlConnector/MySqlConnection.cs#L537-L562

I'll probably update that code with `#if NET5 ... override` when an updated SDK is available.

**Comment by roji** [comment]
Sounds good.
