### ISSUE TITLE
connection pool problem

### ISSUE THREAD

**Issue by kopan** [mysql-net/MySqlConnector#841]
I set maximumpoolsize to 600 on 8 servers(.net core 3.1), and if I overload the server, 
the connection will be made more than 5233 and there will be too many connection errors. (use aws mysql 5.7 rds)
There is no problem using Mysql.Data Library.

MySqlConnector (0.69.4)
![image](https://user-images.githubusercontent.com/4496324/86096127-d7dfb800-baed-11ea-9b46-3c2d913a0afb.png)

Mysql.Data (8.0.20)
![image](https://user-images.githubusercontent.com/4496324/86096162-e6c66a80-baed-11ea-8482-db9d66cc6817.png)

**Comment by bgrainger** [comment]
I assume you're expecting a maximum of 4,800 connections (8 * 600)? How many connections are coming from each client?

Can you provide a reproducible sample that demonstrates the problem, or logs that show one (or more) clients exceeded `MaxPoolSize`?
