### ISSUE TITLE
Should we use .ConfigureAwait(false) When calling Async ?

### ISSUE THREAD

**Issue by firephantomassasin** [mysql-net/MySqlConnector#843]
Hi,

Should we use .ConfigureAwait(false) when calling the async APIS like ExecuteReaderAsync, ReadAsync, OpenAsync and XXXAsync?

**Comment by bgrainger** [comment]
It depends if you need to continue on the captured context or not.

https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#configure-context
