### ISSUE TITLE
Add same binary and string representation Uuid support

### ISSUE THREAD

**Issue by vanbukin** [mysql-net/MySqlConnector#846]
If we put `0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF` bytes into `System.Guid` ctor, we will get `33221100554477668899aabbccddeeff` string representation, but if we call `.ToByteArray()`, the binary representation will be correct. That happens because `System.Guid` has the following mixed-endian layout
```
int32  - x1
int16  - x2
int8  - x8
```
So when we run that code on little endian (x86 or ARM) machine, the int32 and int16 bytes order will be reversed.
`System.Guid.ToString()` always return not the same string representation of data, that that we actually store in database. So we should choose between correct binary or string representation.

I've create `Uuid` that has same API as `System.Guid`, but with correct byte order. It's available here https://github.com/dodopizza/primitives under MIT license. I hope that it helps to bring Uuid support into MySqlConnector, that has same binary and string representation.

**Comment by bgrainger** [comment]
This is solved in MySqlConnector by using the `GuidFormat` connection string option; see [`MySqlGuidFormat`](https://mysqlconnector.net/api/mysqlconnector/mysqlguidformattype/).

MySqlConnector won't be taking a dependency on an external library at this time; "native" support for this data type might eventually be accomplished via a data type plugin API: https://github.com/mysql-net/MySqlConnector/issues/793.
