### ISSUE TITLE
Wrong guide about Using DbProviderFactories

### ISSUE THREAD

**Issue by joelam789** [mysql-net/MySqlConnector#847]
From page:
https://mysqlconnector.net/overview/dbproviderfactories/

Incorrect Info(?) :
type="MySqlConnector.MySqlClientFactory, MySqlConnector, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92"

The correct one (tested with v0.69.5):
type="MySql.Data.MySqlClient.MySqlClientFactory, MySqlConnector, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92"

**Comment by bgrainger** [comment]
The documentation has already been updated for 1.0 (which changes the namespace: #824). Although it has the `-beta` label in NuGet, it's production-quality so feel free to upgrade.
