### ISSUE TITLE
Implement MySqlException.SqlState

### ISSUE THREAD

**Issue by roji** [mysql-net/MySqlConnector#848]
https://github.com/dotnet/runtime/issues/35601 introduces DbException.SqlState for .NET 5.0, for standard 5-character error codes. 

[MySQL also implements SQLSTATE](https://dev.mysql.com/doc/internals/en/packet-ERR_Packet.html), as well as another, proprietary error code. [SQLSTATE is already exposed on MySqlException](https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySql.Data.MySqlClient/MySqlException.cs#L16), so this would simply be about cross-targeting to net5.0 and overriding DbException.SqlState.

**Comment by bgrainger** [comment]
Implemented in https://github.com/mysql-net/MySqlConnector/commit/caf70185a72c19164bd8609c16182a8c084f84c4 and shipped in [1.1.0](https://github.com/mysql-net/MySqlConnector/releases/tag/1.1.0).
