### ISSUE TITLE
MySqlConnection.GetSchema(string collectionName) should be case insensitive

### ISSUE THREAD

**Issue by yyjdelete** [mysql-net/MySqlConnector#852]
Should `collectionName` in DbConnection.GetSchema(string collectionName) be case insensitive?

I didn't find any document of ado.net of that, but seems some other provider like SqlClient, Npgsql, Mysql.Data treat it as case insensitive.

SqlClient: Check with `ADP.CompareInsensitiveInvariant`(the same as `string.Equals(a, b, StringComparison.InvariantCultureIgnoreCase)`), match case-sensitive first(?looks like something wrong in the logic) and fallback to case-insensitive version if not found;

https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbMetaDataFactory.cs#L268

Npsql/Mysql.Data: Use `string.ToUpperInvariant()` directly;
https://github.com/npgsql/npgsql/blob/a9cab33e4d3a384cbcc05c1bd78c2bf6b80bd314/src/Npgsql/NpgsqlSchema.cs#L25
https://github.com/mysql/mysql-connector-net/blob/68c54371821c87ff40a773acc127ce357b46a5ae/Source/MySql.Data/SchemaProvider.cs#L57

MySqlConnector: `v1.0.0`

**Comment by bgrainger** [comment]
Thanks for the detailed research! This does look like it should be case-insensitive (for compatibility).

**Comment by bgrainger** [comment]
Fixed in [0.69.8](https://github.com/mysql-net/MySqlConnector/releases/tag/0.69.8).

Fix for 1.x is in GitHub Package Registry, 1.0.1-beta.0.11 or later: https://github.com/mysql-net/MySqlConnector/packages/39735

**Comment by bgrainger** [comment]
Fixed in [1.0.1](https://github.com/mysql-net/MySqlConnector/releases/tag/1.0.1).
