### ISSUE TITLE
Undocumented breaking change when migrating from Connector/NET

### ISSUE THREAD

**Issue by laloutre87** [mysql-net/MySqlConnector#857]
Undocumented breaking change between Connector/NET behavior and MysqlConnector behavior.  I think this change should be indicated in  https://mysqlconnector.net/tutorials/migrating-from-connector-net/  documentation. Especially as the problem is silent (only returns no rows instead of the rows returned with Connector/NET) in some cases (namely if "Allow User Variables=true"   is used in the connection string ) . 

The following code snippet illustrate the problem.   It is assumed that we have a "test" database, with a "table1" table and table1_id  varchar column , for which at least 1 row contain the value "test1" . 

MysqlConnector  version 1.0.0 
Connector/NET version 6.9 

```csharp

var connectionStr = "Server=127.0.0.1;User ID=root;Database=test;Allow User Variables=true";
string sqlTxt = null;


using (var connection = new MySql.Data.MySqlClient.MySqlConnection(connectionStr))
{
	connection.Open();

	sqlTxt = "SELECT * FROM table1 where table1_id = @Parameter1 ";

	using (var command = new MySql.Data.MySqlClient.MySqlCommand(sqlTxt, connection))
	{
		var mysqlparam = new MySql.Data.MySqlClient.MySqlParameter();
		mysqlparam.Value = "test1";

		command.Parameters.Add(mysqlparam);

		using (var reader = command.ExecuteReader())
		{
			while (reader.Read())
			{
				Console.WriteLine("oracle's connector reach this line. mysqlconnector does not");
			}
		}
	}

	sqlTxt = "SELECT * FROM table1 where table1_id = ? ";

	using (var command = new MySql.Data.MySqlClient.MySqlCommand(sqlTxt, connection))
	{
		var mysqlparam = new MySql.Data.MySqlClient.MySqlParameter();
		mysqlparam.Value = "test1";

		command.Parameters.Add(mysqlparam);

		using (var reader = command.ExecuteReader())
		{
			while (reader.Read())
			{
				Console.WriteLine("both connector reach this line");
			}
		}
	}
}

````

**Comment by bgrainger** [comment]
It appears that Connector/NET allows unnamed parameters to be referred to as `@Parameter1`, `@Parameter2`, etc. using a 1-based index into the parameter collection.

I don't know yet if this is actual documented behaviour, or just happens as an unexpected side-effect of how the code is structured. 

I generally prefer explicit behaviour (not implicit defaults) so I'm leaning towards not supporting this (also, no one else has discovered/reported it in the last four years), but in that case it should be called out as a breaking change.

**Comment by bgrainger** [comment]
It appears that `MySqlParameter.ParameterName` is set as a side-effect of adding it to a `MySqlParameterCollection`:

```csharp
var command = new MySqlCommand();
command.Parameters.Add(new MySqlParameter());
Console.WriteLine(command.Parameters[0].ParameterName); // Parameter1
```
