### ISSUE TITLE
Undocumented (and possibly problematic) breaking change when migrating from Connector/NET

### ISSUE THREAD

**Issue by laloutre87** [mysql-net/MySqlConnector#858]
The migration guide here https://mysqlconnector.net/tutorials/migrating-from-connector-net/    indicate that no implicit conversion will be performed from numerical/other types to string ( with reader .GetString(   )   ). 

However, it is not mentioned that implicit conversion will not be performed between numerical types ( namely, GetInt32 (  )  on a Double column). 

While I wholeheartedly support the former breaking change, I will have to point out that the second one is unpractical for real-life scenarios.   Because this happens a lot : 
- create an int column for something
- few years pass, many GetInt32( )    target this column in the codebase . 
- someone need more precision for a specific use case. 
- the column is thereby changed to double . 
- having to find where the GetInt32 is performed for this column is unpractical, and sometimes not feasible ( for example it's tough nowadays to recompile for windows mobile devices (which, yes, are still very much in use, and in most cases pretty damn expensive to replace) as it requires a visual studio 2008 ... ) . 

I advise to correct this breaking change, at least with an option on the connector if not by default, 
but even  if you do not  please document the breaking change.

**Comment by bgrainger** [comment]
Previous discussions:

* https://github.com/mysql-net/MySqlConnector/issues/54#issuecomment-246983239 - discusses a "strict mode"
* https://github.com/mysql-net/MySqlConnector/issues/54#issuecomment-247069211 - notes `Convert.ToInt32(reader.GetValue(n))` as a potential workaround
* https://github.com/mysql-net/MySqlConnector/issues/408 - document stricter conversion rules

**Comment by bgrainger** [comment]
> * someone need more precision for a specific use case.
> * the column is thereby changed to double .

I'm not really understanding why this isn't a bug that MySqlConnector is helping catch. It seems odd that more precision is needed, but it's also OK for this extra (necessary) data to be silently ignored by most of the code that reads the column. (And not that I can change your database schema, but if the extra information were truly optional and could be ignored by most code using it, adding `FractionalPart` as a separate column that's simply not retrieved could be a better approach.) Don't each of these call sites need to be examined to determine whether they can safely ignore the fractional part of the value?

> having to find where the GetInt32 is performed for this column is unpractical, and sometimes not feasible ( for example it's tough nowadays to recompile for windows mobile devices (which, yes, are still very much in use, and in most cases pretty damn expensive to replace) as it requires a visual studio 2008 ... ) .

If this code is so difficult to recompile then it seems unlikely that it would be getting upgraded from MySql.Data to MySqlConnector, so a potential breaking change between the two libraries seems irrelevant?

**Comment by laloutre87** [comment]
@bgrainger  on the last point, I meant that the code done today with MySqlConnector is bound to be, at some point in the future,  the "windows mobile"  of tomorrow, it will be a .dll that no one is able to recompile, so it's better if it's a bit resilient to database schema evolution. 
As for the other point, yes,  there are probably other ways to add precision on an existing int.   I am just migrating a 8 yo  project from Connector/NET,  testing and noticing stuff that crashes; and reporting on it because hopefully for the success of this connector, I won't be the last migrating large codebases, and up-to-date documentation is helpful in making the choice : "should I try migrating".

**Comment by bgrainger** [comment]
> I am just migrating a 8 yo project from Connector/NET, testing and noticing stuff that crashes; and reporting on it because hopefully for the success of this connector, I won't be the last migrating large codebases, and up-to-date documentation is helpful in making the choice

Thank you very much for reporting this feedback; it is very helpful in understanding and documenting potential pitfalls or blocking issues.

**Comment by laloutre87** [comment]
@bgrainger  and today I got into the case you mentioned in another issue, the fact that MySQL returns a DECIMAL value for operation like SUM on an INT column, and it does feel weird when a getInt on that fails.  Also it got me wondering if you can still call what Connector/NET do an "implicit" conversion, considering that Int32 is in the name of the method called, and  (int)GetDouble() or doesn't seems much more "explicit" than that.
