### ISSUE TITLE
namespace change on 1.0.0

### ISSUE THREAD

**Issue by daikoz** [mysql-net/MySqlConnector#860]
Hi,

It is not a bug but why do you change the namespace on version 1.0.0 ?

I already migrate several project from official mysql connector to MySqlConnector without code modification.
MySqlConnector work better 👍 (thanks for our work).
Now, I need to modify all namespace.

I use also [DAIKOZ.SQLWrapper](https://github.com/daikoz/SQLWrapper) to generate automatically a sql wrapper from SQL request. Now, I need to modify the template when I use MySqlConnector.

Regards

**Comment by bgrainger** [comment]
The reasons are explained here: #824.
