### ISSUE TITLE
Question: Is there a replacement for MySqlParameter.SetShouldNotEscape(true) in newer versions of your API?

### ISSUE THREAD

**Issue by killswitch1111** [mysql-net/MySqlConnector#864]
I started using your API on a project a couple years ago (2017 I think) and I am dynamically creating a database, creating and updating tables, etc... When I upgraded to the newer version of the connector I noticed SetShouldNotEscape was no longer a method on MySqlParameter.  When I tried running commands such as CREATE TABLE IF NOT EXISTS with a MySqlParameter it fails as bad syntax, which I believe before I was able to get around by setting SetShouldNotEscape to true.  

I did confirm that using AddWithValue (or creating separately) is what is throwing the error.  When I do a replace on the string myself, it does work.

I noticed in the code in the parser you have some options for not escaping certain things, but I am not exactly sure where to set the Parser options (or if this is possible).  Figured I would ask before diving more into the code.  

Thanks and hoping to get some good use out of this! Loved it 2-3 years ago, and glad to see how far it has come!

**Comment by bgrainger** [comment]
`MySqlParameter.SetShouldNotEscape` has never been a method in MySqlConnector. I also can't find any evidence of it in the [MySQL Connector/NET code](https://github.com/mysql/mysql-connector-net/).

A [Google search](https://www.google.com/search?q=SetShouldNotEscape) turns up no results for this keyword.

At this point, I'm not sure what potential functionality you're referring to.

**Comment by bgrainger** [comment]
Just guessing from the name, `MySqlParameter.SetShouldNotEscape` inserts the parameter value into the generated SQL string without escaping it? If so, I don't think there's any benefit in using a parameter (which strongly implies that it _is_ escaped); string concatenation should achieve the same result (and be obviously dangerous)?

**Comment by killswitch1111** [comment]
Interesting! I honestly don't know where it came from.  I wonder if it was another fork of your code back in 2016, because I just searched my version of your forked code on GH from 2016 and it's not there.  Very weird. Oh well.  (String concatenation isn't really an issue in this case, since it is internal code that would already have been sanitized).  I was just wondering because for some reason from this old version I have of it, it was there lol.

I assumed the parameter had other sanitization other than merely escaping/quoting (quotes I believe are the real issue here since when modifying database/table structures you wouldn't use quotes in most places). 

So essentially, use of parameters in SQL statements that are intentionally modifying database structure isn't supported/No need to support.  Sound right?

**Comment by killswitch1111** [comment]
Looks like essentially the old change was this in AppendSqlString:
`
if(!ShouldNotEscape)
	writer.Write((byte) '\'');
writer.WriteUtf8(((string) Value).Replace("\\", "\\\\").Replace("'", "\\'"));
if(!ShouldNotEscape)
	writer.Write((byte) '\'');`

vs what you had back then:
`output.Append('\'');
output.Append(((string) Value).Replace("\\", "\\\\").Replace("'", "\\'"));
output.Append('\'');`

For the string value.  No worries.  I can fork and do the change and just keep up with yours, makes my life easier for this project lol.  Thanks for the quick reply!
