### ISSUE TITLE
Use hardware-accelerated Adler32 computation

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#865]
https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Png/Zlib/Adler32.cs is an Apache 2.0-licensed file that implements a hardware-accelerated implementation of Adler32 in C#.

**Comment by novak-as** [comment]
Not that if I had doubts about benchmark results, but still:

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.804 (2004/?/20H1)
Intel Core i7-8850H CPU 2.60GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.103
  [Host]     : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
  Job-QQDQQD : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT

WarmupCount=10  

```
|        Method |                 data |             Mean |          Error |         StdDev |
|-------------- |--------------------- |-----------------:|---------------:|---------------:|
|  B_AdlerNaive | Syste(...)Byte] [34] |        288.89 ns |       0.362 ns |       0.302 ns |
|  B_AdlerNaive | Syste(...)Byte] [34] |      3,717.99 ns |       9.278 ns |       8.225 ns |
|  B_AdlerNaive | Syste(...)Byte] [34] |  3,852,480.23 ns |   3,814.165 ns |   3,185.000 ns |
|  B_AdlerNaive | Syste(...)Byte] [34] | 61,852,477.78 ns | 116,195.446 ns | 108,689.292 ns |
|    B_AdlerSse | Syste(...)Byte] [34] |         13.72 ns |       0.052 ns |       0.049 ns |
|    B_AdlerSse | Syste(...)Byte] [34] |         41.93 ns |       0.835 ns |       0.781 ns |
|    B_AdlerSse | Syste(...)Byte] [34] |     41,533.86 ns |     111.976 ns |      93.505 ns |
|    B_AdlerSse | Syste(...)Byte] [34] |  1,018,107.32 ns |   5,609.412 ns |   4,379.460 ns |
| B_AdlerScalar | Syste(...)Byte] [34] |         30.99 ns |       0.083 ns |       0.069 ns |
| B_AdlerScalar | Syste(...)Byte] [34] |        381.93 ns |       0.870 ns |       0.771 ns |
| B_AdlerScalar | Syste(...)Byte] [34] |    390,690.20 ns |     508.281 ns |     450.578 ns |
| B_AdlerScalar | Syste(...)Byte] [34] |  6,345,381.67 ns |  56,812.787 ns |  47,441.250 ns |

array sizes were: `80` (min threshold to use compression), `1024`, `1,048,576` and `16,777,215` (i.e max protocol packet size)

**Comment by bgrainger** [comment]
Added in [1.3.0](https://github.com/mysql-net/MySqlConnector/releases/tag/1.3.0).
