### ISSUE TITLE
Lock and thread starvation

### ISSUE THREAD

**Issue by CatalinAdlerDF** [mysql-net/MySqlConnector#872]
I sometimes get thread starvation warnings from asp.net infr.
My code is full async, but i've noticed some ```lock``` statements in the connector code.

I suspect that can also be a cause for the starvation.
The ```lock``` instruction is blocking for the current thread, which is an anti-pattern is fully async code and smth even msft recommends against.

Why was this chosen instead of a semaphore-based implementation, which is async friendly?

My code is .net core 3.1, on linux containers, pretty decent concurrency.

**Comment by bgrainger** [comment]
> which is an anti-pattern is fully async code and smth even msft recommends against

Can you provide a link to this recommendation?

> Why was this chosen instead of a semaphore-based implementation, which is async friendly?

The code generally uses `lock` to protect a very small section of code that a) needs to be atomic, and b) isn't expected to have much contention in practice.

For code blocks where long blocking is expected, a `SemaphoreSlim` is used: https://github.com/mysql-net/MySqlConnector/blob/57947630a2a9587e511dfd312f1e058ad8124d2f/src/MySqlConnector/Core/ConnectionPool.cs#L41

**Comment by CatalinAdlerDF** [comment]
The official best practices [paper](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1) reiterates the common async theme: don't block.

`
**Do not**:

- **Block asynchronous execution** by calling Task.Wait or Task.Result.
- **Acquire locks in common code paths**. ASP.NET Core apps are most performant when architected to run code in parallel.
- Call Task.Run and immediately await it. ASP.NET Core already runs app code on normal Thread Pool threads, so calling Task.Run only results in extra unnecessary Thread Pool scheduling. Even if the scheduled code would block a thread, Task.Run does not prevent that.

**Do**:

Make hot code paths asynchronous.
Call data access, I/O, and long-running operations APIs asynchronously if an asynchronous API is available. Do not use Task.Run to make a synchronous API asynchronous.
Make controller/Razor Page actions asynchronous. The entire call stack is asynchronous in order to benefit from async/await patterns.
`

I can't judge if the locks are used on common/uncommon code paths, but using a semaphoreslim is so easy that I think it's just not worth taking in the risk.

**Comment by bgrainger** [comment]
I performed a quick benchmark of `lock` vs `SemaphoreSlim`: https://gist.github.com/bgrainger/878ccdb3ccdcd434c4218cee4e61ffea

For simple use cases (e.g., atomic updates) it seems clear to me that the overhead of `SemaphoreSlim` isn't worth it, and it should only be used when asynchronous waiting is truly necessary (which also incurs the overhead of allocation).

**Comment by CatalinAdlerDF** [comment]
I wouldn't have expected otherwise; but the risk to focus on is concurrency.
Unfortunately all my issues happen only in prod; the cost of getting good dumps for local analysis is kind of expensive for me.

Also, for simple atomic updates, why not interlocked counterparts where possible?

**Comment by CatalinAdlerDF** [comment]
@bgrainger also found that the disposeasync on the connection can lead to blocking. in case the session is expired.

MySqlConnection.DisposeAsync -> MySqlConnection.CloseAsync -> **m_session.ReturnToPool -> ServerSession.Pool?.Return(this)** -> session.DisposeAsync(IOBehavior.Synchronous, CancellationToken.None).GetAwaiter().GetResult();

Bolded part is the sync slice i found.

**Comment by bgrainger** [comment]
Thanks for the report of this finding.

> in case the session is expired

This should (I hope) be very rare. If returned sessions are being destroyed, the connection pool's efficiency is going to be reduced, causing much more overhead (than of the locking) when new sessions are required.

**Comment by CatalinAdlerDF** [comment]
I got tons of `Pool4 received expired Session4.9733; destroying it`

**Comment by bgrainger** [comment]
https://github.com/mysql-net/MySqlConnector/issues/876

**Comment by bgrainger** [comment]
> I got tons of Pool4 received expired Session4.9733; destroying it

* Are you setting `ConnectionLifeTime` to a non-zero value?
* Are you calling `MySqlConnection.Clear(All)Pool`?

If so, why?

**Comment by bgrainger** [comment]
> 4.9733

This indicates that 9,733 unique connections have been opened. This number seems extremely high; I would want to dig into why so many sessions have been created.

**Comment by CatalinAdlerDF** [comment]
Not setting `ConnectionLifeTime`, but calling `ClearAllPools` when i get a max pool size exception; trying out various solutions to get to the root of this.

>  I would want to dig into why so many sessions have been created.

Me too, don't really know how to track this down.

**Comment by CatalinAdlerDF** [comment]
For reference.
I've reduced concurrency in code a lot; increased pod count so that the load per each pod is significantly less now, though i still cannot observe any improvement.

I've also scoped down everything to 1 code path, which i reviewed thoroughly countless times.

I am using a mysql `wait_timeout` of 180 on server startup, but for an unknown reason, I am just now finding out that at runtime it gets to 28800. This is GCP.

I also use `SET SESSION MAX_EXECUTION_TIME` or the statement-level equivalent, along with `CommandTimeout` and `CancellationTokens`.

Cherry on the cake is that i am using temp tables with bulk copy.

**Comment by mqudsi** [comment]
@CatalinAdlerDF If you're still having issues, [`AsyncLock`](https://github.com/neosmart/AsyncLock) is a drop-in replacement for `lock` that can be used in async contexts - you could recompile the driver with that instead and see if it supports your theory, although having worked extensively with thread pools and async executors, I am also of the opinion that locks around non-IO code are _generally_ OK to use in async context, especially when contention is expected to be minimal.

**Comment by CatalinAdlerDF** [comment]
Thanks @mqudsi but I've taken a different path.

It was becoming too expensive to fight this bug, so i added rate limiting and scaled out.

In my own few lock paths, i am using the semaphore, but they are always io paths, so it's definitely worth it.

@bgrainger I guess this can be closed, since i cannot provide a repro scenario.

Thanks!
