### ISSUE TITLE
[Suggestion] Rename this project

### ISSUE THREAD

**Issue by GitClickOk** [mysql-net/MySqlConnector#878]
I'm aware of https://github.com/mysql-net/MySqlConnector/issues/347, this is a similar suggestion, but with a higher scope.

I work mostly with different databases, and I'm aware of how really bad is the Oracle's default provider for MySql. So I'm very glad because you guys created this project.

But this name "MySqlConnector" really doesn't helps. if you google for "mysql connector", this project appears only in the end of the second page. The Oracle's default one take all links in the first page... :(

If I try remember from memory, the only two differences are (1) NOT from Oracle (2) NOT with a "NET" in end of the name...

The Nuget package alone is funny... I see MySql.Data by Oracle, MySql.Data.Entities by MySql, a lot of others ".MySql" and MySqlConnector and ... it's time to read carefully to select the correct one.

Basically I'm saying you have an awesome project! But it is really really hard give some visibility with these problems I listed. Any "marketing" I can do will probably or inevitably will be lost in this naming confusion.

I think really amazing idea maintain the namespaces and classes names, but no the project name. If you find so drastic changing the name, just append a name while we don't get used to. Some examples: 

- MySql Power Connector _(pun intended)_
- Async/Extended/Ultimate/Perfect MySqlConnector
- Endeavor (former MySqlConnector)
- MySqlConnector Async Edition
- Etc

These were only name/format suggestions, of course. Then, the next step is a relevant icon and some visual identity for the website (including the same ICON in website/github AND nuget). You can even put a pet like an "Elekid" :).

I wish you the best, and thank you for this great project.

**Comment by PhilAtWysdom** [comment]
MySqlNETConnector?
