### ISSUE TITLE
mysqlparameter not exists in version 1.0.0

### ISSUE THREAD

**Issue by omriman12** [mysql-net/MySqlConnector#879]
Using Pomelo.EntityFrameworkCore.MySql 3.1.2 witch only works with MySqlConnector < 1.0.0.
But MySqlConnector < 1.0.0 has no MySqlParameter.
Can you please add the class to 0.X versions

**Comment by bgrainger** [comment]
> Waiting for ver 5.X is impossible for me.

Downgrade MySqlConnector to 0.69.9 for compatibility with Pomelo 3.x

> Do you have any suggestion to an alternative to MySqlParameter?

An alternative isn't needed; the type exists right here: https://github.com/mysql-net/MySqlConnector/blob/1.0.1/src/MySqlConnector/MySqlParameter.cs
