### ISSUE TITLE
Unable to connect from linux

### ISSUE THREAD

**Issue by embix** [mysql-net/MySqlConnector#880]
I intended to use the MySqlConnector from within a linux container but I always get an exception (while it works fine on win-x64):

```
MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 474
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 111
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 140
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 821
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 399
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419
   at ReportFetcher.CLI.GetTopicReportsInInterval(Topic topic, Interval referenceInterval) in C:\git\fetchreports\src\fetchreports\Program.cs:line 241
```

The code builds fine with the `mcr.microsoft.com/dotnet/core/sdk:3.1` image using `dotnet publish -r linux-x64 -c Release`. When running with a plain `debian:10` instead of a dotnet core image you'd need to `apt-get update && apt-get install -y libicu63 libssl-dev` before running the build.

I don't recommend using alpine (which would require building with `dotnet publish -r linux-musl-x64 -c Release`) as I haven't yet figured out what packages are missing.

I tried Version MySqlConnector 1.0.1 as well as 0.69.2 and 0.61.0.

**Comment by bgrainger** [comment]
It sounds like you're trying to run the application from a Docker image that doesn't have the necessary dependencies for .NET Core?

Can you run it using `mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim` if you want a Debian 10 base image? (I don't know if you'd also have to build using `mcr.microsoft.com/dotnet/core/sdk:3.1:3.1-buster`.)

**Comment by bgrainger** [comment]
It seems "by design" that a .NET Core application won't run correctly if all the dependencies aren't installed. If you don't want to use the `runtime-deps` image Microsoft provides, you could look at the Dockerfile to see what you need to include: https://github.com/dotnet/dotnet-docker/blob/c0e8be8a44b47b1dcc2a5b4b2ebd92022087ac0b/src/runtime-deps/3.1/buster-slim/amd64/Dockerfile

**Comment by embix** [comment]
> It sounds like you're trying to run the application from a Docker image that doesn't have the necessary dependencies for .NET Core?

Nope. I tried running the binaries with the following images:

- `mcr.microsoft.com/dotnet/core/sdk:3.1` - got the *MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.*
- `mcr.microsoft.com/dotnet/core/runtime:3.1` - got the *MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.*
- `debian:10` got the ICU and SSL issues, fixed those with said `apt-get` and finally got the *MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.*
- also tried `alpine` with musl binaries, but didn't get far enough to reproduce the *MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.*

> It seems like expected behaviour that a .NET Core application won't run correctly if its dependencies aren't installed.

It should have run at least with the ~ 700MiB SDK image then. What more dependencies can you have? 

The slimmer *runtime* image should have worked too - I expect "regular" netcore builds to work on that. That is basically the purpose of that image.

But I did `dotnet publish -r linux-x64` which [,as they claim, is self contained](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish):

> - --self-contained [true|false]
>
>   Publishes the .NET Core runtime with your application so the runtime doesn't need to be installed on the target machine. Default is true if a runtime identifier is specified and the project is an executable project (not a library project). For more information, see .NET Core application publishing and Publish .NET Core apps with the .NET Core CLI.

So given a glibc and a kernel it should have run almost anywhere.

**Update** when I explicitly add `--self-contained true` the code runs in all of those images🎉. So the *Default is true if a runtime identifier is specified and the project is an executable project*-part is not true. Either their 3.1 SDK is buggy or its documentation is, probably both🤷‍♀️. Even a platform specific build should work with the *runtime* and *sdk* image.

Thanks for looking into it.

**Comment by bgrainger** [comment]
OK, I got confused by your mention of `debian:10`, `libicu63`, etc.

Can you launch a bash prompt inside your container, install `mysql`, and successfully connect to your MySQL Server from within the container?
