### ISSUE TITLE
GetSchema not Working

### ISSUE THREAD

**Issue by nemosmart** [mysql-net/MySqlConnector#884]
Hi, why GetSchema is not working? Im using VS2019 + .NET 4.8 + MySQL 5.6, it return with this error:

Exception thrown: 'MySqlConnector.MySqlException' in mscorlib.dll
The Command Timeout expired before the operation completed.

Here is my code:
`            
Using connection = New MySqlConnection(conStr.ConnectionString)
                connection.Open()
                Dim o As DataTable = connection.GetSchema("Tables", {"uom"})
End Using
`

---
Regards

**Comment by bgrainger** [comment]
Restrictions aren't currently supported in `GetSchema` (https://github.com/mysql-net/MySqlConnector/issues/374) so maybe this is requesting more data than can be retrieved before a timeout occurs?

You could try increasing `DefaultCommandTimeout` in your connection string.
