### ISSUE TITLE
Support MySqlDateTime.IsNull

### ISSUE THREAD

**Issue by maddinthegreat** [mysql-net/MySqlConnector#885]
Hello,

is there a IsNull-property replacement for the original Oracle implementation?

Regards
Martin

**Comment by bgrainger** [comment]
Not currently; do you have examples of when it would be used?

**Comment by maddinthegreat** [comment]
Hi,

i wanted to text whether this value is equal to DBNull.Value. Or can i just do:

MySqlDataReader rdr;
...
var ob = rdr[colIndex];

if (ob  is DBNull) {
}

That should be the same, or?

Martin

**Comment by bgrainger** [comment]
I think that would work, but it would perhaps be a little more efficient to write `if (rdr.IsDBNull(colIndex)) {... }`.

**Comment by bgrainger** [comment]
Implementation Note: Need to check if there are any scenarios where MySqlConnector would create a "null" `MySqlDateTime`.

**Comment by bgrainger** [comment]
Do you have an example of when Connector/NET returns a `MySqlDateTime` object where `IsNull = true`? I'm not yet sure how such a value would be constructed and returned from that library.
