### ISSUE TITLE
Possible sync over async on MySqlCommand.ExecuteNonQueryAsync

### ISSUE THREAD

**Issue by antoniofreire** [mysql-net/MySqlConnector#886]
Hello!

Is there a reason to not call the async version of Dispose of the MySqlDataReader on this line: https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlCommand.cs#L263

I'm experiencing sporadic ThreadPool starvation on my application and i suspect that's because of this behavior.

Best regards.

**Comment by bgrainger** [comment]
`MySqlDataReader.DisposeAsync` can possibly call `NextResultAsync` to consume the data reader. However, this code (`ExecuteNonQueryAsync`) already performs all those operations (asynchronously) before calling `Dispose`. So the net result of `Dispose` _should_ just be marking the connection as not in use, which is a simple synchronous operation, and the async-over-sync-over-async in this method isn't a problem.

Anything specific that makes you suspect this method?

**Comment by antoniofreire** [comment]
Hi @bgrainger. Thanks for the quick answer and clarification.

Nothing specific at the moment, i'm just narrowing some possibilities.
