### ISSUE TITLE
Is this compatible with the new MySQL 8.xx version?

### ISSUE THREAD

**Issue by firephantomassasin** [mysql-net/MySqlConnector#900]
Hi,

Is this library 100% compatible with the new MySQL Server 8.xx version?

And may i know what versions of MySQL Server does this library support or compatible?

**Comment by bgrainger** [comment]
It hasn't been tested yet against MySQL Server 8.0.22 (since that just came out yesterday), but has been tested with MySQL Server 5.5.x, 5.6.x, 5.7.x, 8.0.21; MariaDB 10.2, 10.3, 10.4; Percona; Azure Database for MySQL 5.7 and 8.0; Amazon Aurora RDS; and many others.

**Comment by firephantomassasin** [comment]
Thanks!
