### ISSUE TITLE
 MySQL optimizer choosing different index through MySqlConnector

### ISSUE THREAD

**Issue by mguinness** [mysql-net/MySqlConnector#902]
MySQL 8.0.13 added functional indexes, but when running a query through MySqlConnector the optimizer appears to ignore it, whereas running the same query in Workbench it's used.  I feel like I'm missing something obvious, but I'm hoping someone can reproduce and explain why this occurs.

Below is a code sample that I've put together that demonstrates the issue that I'm seeing.  This was using version 0.69.10 of MySqlConnector.

```C#
static void Main(string[] args)
{
    var logger = new LoggerFactory().AddConsole(LogLevel.Debug);
    MySqlConnectorLogManager.Provider = new MicrosoftExtensionsLoggingLoggerProvider(logger);

    var constr = "server=localhost;port=3306;database=test;user id=root;password=;pooling=false";
    var db = new MySqlConnection(constr);
    db.Open();

    var tbl = @"CREATE TABLE IF NOT EXISTS Log (
        id INT NOT NULL AUTO_INCREMENT,
        email VARCHAR(50) NOT NULL,
        dated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(id),
        INDEX `IX_email` (`email`),
        INDEX `IX_domain` ((SUBSTRING_INDEX(`email`, '@', -1))),
        INDEX `IX_dated` (`dated`));";
    var cmd1 = new MySqlCommand(tbl, db);
    cmd1.ExecuteNonQuery();

    var cmd2 = new MySqlCommand("INSERT INTO Log (email) VALUES ('test@example.com');", db);
    cmd2.ExecuteNonQuery();

    var qry = @"DESCRIBE SELECT COUNT(*) FROM `Log` AS `l` WHERE (SUBSTRING_INDEX(`l`.`email`, '@', -1) = 'example.com');";
    var cmd3 = new MySqlCommand(qry, db);
    using (var rdr = cmd3.ExecuteReader())
    {
        while (rdr.Read())
        {
            var row = new Dictionary<string, object>();
            for (int i = 0; i < rdr.FieldCount; i++)
                row.Add(rdr.GetName(i), rdr.GetValue(i));
            Console.WriteLine(String.Join(Environment.NewLine, row));
        }
    }

    db.Close();
    Console.ReadLine();
}
```

When run, you should see the following output in the console window:

```
[id, 1]
[select_type, SIMPLE]
[table, l]
[partitions, ]
[type, index]
[possible_keys, ]
[key, IX_email]
[key_len, 152]
[ref, ]
[rows, 1]
[filtered, 100]
[Extra, Using where; Using index]
```

Now when I use another query tool with the same query I end up with a different query plan as shown below:

| id | select_type | table | partitions | type | possible_keys | key       | key_len | ref   | rows | filtered | Extra  |
|----|-------------|-------|------------|------|---------------|-----------|---------|-------|------|----------|--------|
| 1  | SIMPLE      | l     | (NULL)     | ref  | IX_domain     | IX_domain | 152     | const | 1    | 100.00   | (NULL) |

I'm stumped as to why it would be different between applications.  Does the client library signal what features it supports?

**Comment by bgrainger** [comment]
What are the charsets/collations of the columns/indexes? MySqlConnector always sets `character_set_client` to `utf8mb4` ... I don't know if this would make MySQL choose a different index?

**Comment by bgrainger** [comment]
> Does the client library signal what features it supports?

Yes, but they're typically protocol features such as "supports EOF": https://dev.mysql.com/doc/internals/en/capability-flags.html

The other client setting is the character set, and that's the only thing I can think of that might affect this. https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse

**Comment by mguinness** [comment]
Great observation, the database is utf8 w/ utf8_unicode_ci collation.  Looking at [Connection String Options](https://mysqlconnector.net/connection-options/), the CharSet setting is ignored?  Is there any workaround to this?  Do you think this is a potential bug with MySQL?

**Comment by bgrainger** [comment]
I can repro with 8.0.13, but not with 8.0.22. This seems like a MySQL Server bug that's already been fixed.

Changing your SQL as follows (i.e., put `_utf8` before `'@'`) caused 8.0.13 to use the `IX_domain` index in my testing, so it may be a viable workaround for you:

```sql
... WHERE(SUBSTRING_INDEX(`l`.`email`, _utf8'@', -1) = 'example.com');
```

Thanks for the detailed repro and writeup!

**Comment by mguinness** [comment]
Thanks for identifying the issue Bradley.  I'm currently on 8.0.16 so I'll look at upgrading.
