### ISSUE TITLE
.NET 5.0 TLS Errors

### ISSUE THREAD

**Issue by iamcarbon** [mysql-net/MySqlConnector#904]
When upgrading to .NET 5.0 on Linux and connecting to Aurora (v5.7), we're getting a OpenSslCryptographicException. 

This occurs due to the default TLS cipher suites changing on .NET 5.0 Linux. It can be fixed by providing a custom CipherSuitesPolicy with a less restrictive cipher set.  

This is a request to be able to configure the CipherSuitesPolicy (directly, or via a connection string) on .NET5.0.

### Stack Trace

```
OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
AuthenticationException: Authentication failed, see inner exception.
MySqlException: SSL Authentication Error

```

### .NET Breaking Changes Notes

```
Default TLS cipher suites for .NET on Linux
.NET, on Linux, now respects the OpenSSL configuration for default cipher suites when doing TLS/SSL via the SslStream class or higher-level operations, such as HTTPS via the HttpClient class. When default cipher suites aren't explicitly configured, .NET on Linux uses a tightly restricted list of permitted cipher suites.

Change description
In previous .NET versions, .NET does not respect system configuration for default cipher suites. The default cipher suite list for .NET on Linux is very permissive.

Starting in .NET 5.0, .NET on Linux respects the OpenSSL configuration for default cipher suites when it's specified in openssl.cnf. When cipher suites aren't explicitly configured, the only permitted cipher suites are as follows:

TLS 1.3 cipher suites
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
Since this fallback default doesn't include any cipher suites that are compatible with TLS 1.0 or TLS 1.1, these older protocol versions are effectively disabled by default.

Supplying a CipherSuitePolicy value to SslStream for a specific session will still replace the configuration file content and/or .NET fallback default.
```

```

**Comment by iamcarbon** [comment]
@bgrainger Is it possible to configure a CipherSuitePolicy directly on the SSL stream?

**Comment by iamcarbon** [comment]
Manually configuring the CipherSuitesPolicy policy in ServerSession fixes the problem. Still trying to find documentation on what ciphers Aurora supports.

@bgrainger What are your thoughts on adding a configuration option to specify a custom cipher suite policy? 

Something like...

```
ciphers=Auora2
```

```
var options = new SslClientAuthenticationOptions
{
	EnabledSslProtocols = SslProtocols.Tls12 | SslProtocols.Tls11,
	ClientCertificates = clientCertificates,
	TargetHost = HostName,
	CipherSuitesPolicy = new CipherSuitesPolicy(new[] {
		TlsCipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
		TlsCipherSuite.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
		TlsCipherSuite.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
		TlsCipherSuite.TLS_RSA_WITH_AES_256_GCM_SHA384,
		TlsCipherSuite.TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384,
		TlsCipherSuite.TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384,
		TlsCipherSuite.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,
		TlsCipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
	}),
	CertificateRevocationCheckMode =  X509RevocationMode.NoCheck
};

await sslStream.AuthenticateAsClientAsync(options).ConfigureAwait(false);
```

**Comment by iamcarbon** [comment]
Submitted a PR #905

**Comment by bgrainger** [comment]
Link to .NET Breaking Changes list: https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0#default-tls-cipher-suites-for-net-on-linux

**Comment by bgrainger** [comment]
@iamcarbon Is modifying the configuration in `/etc/ssl/openssl.cnf` (as suggested in the docs), e.g., in the `Dockerfile` for your application, a viable workaround in your situation?

Obviously there is an advantage to having the library work out-of-the-box with Aurora without extra configuration; I need to research that more.

**Comment by iamcarbon** [comment]
@bgrainger : Yes, this also works, but forgoes the other benefits of a locked down default policy for the rest of the application. 

I'm also not sure if this will work when we upgrade our Lambda functions in the future as the openssl.cnf won't be editable there.

Another approach would be to allow a CipherSuitesPolicy to be set globally (perhaps off a static setter). This would help users avoid editing the openssl.cnf (and reducing security for everything else), and give them explicit control over the ciphers that are used.

**Comment by iamcarbon** [comment]
Revised the PR to allow defining the DefaultCipherSuitesPolicy on .NET5.0.

https://github.com/mysql-net/MySqlConnector/pull/905/commits/4a4033a63a8061694c5b5cd76350379eacdb56b8

**Comment by bgrainger** [comment]
> This is a request to be able to configure the CipherSuitesPolicy (directly, or via a connection string)

Since this setting is connection-specific (more specifically, connection-pool specific), I'm tempted to make it part of the connection string. This would let it be configured without using code, is more like every other connection setting, and would be less "magic" than setting a static property. The downside is that is could be extremely verbose to specify multiple cipher suites. MySqlConnector could support specifying any [`TlsCipherSuite` enum value](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.tlsciphersuite?view=net-5.0) either as a named value (with or without `TLS_` prefix) or the underlying integral value. Your thoughts?

Some examples:

```
Server=aurora;User=test;CipherSuites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
Server=aurora;User=test;CipherSuites=ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,ECDHE_RSA_WITH_AES_256_GCM_SHA384,ECDHE_RSA_WITH_AES_128_GCM_SHA256,ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
Server=aurora;User=test;CipherSuites=49196,49195,49200,49199,49188
```

**Comment by bgrainger** [comment]
To reduce connection string verbosity, an additional mechanism could be `CipherSuiteFile={path-to-file}`, where the specified plain text file contains a list of supported cipher suites, one per line. This would be like `CertificateFile`, `CaCertificateFile`, etc., where the file path is provided in the connection string, but the file itself has to be deployed with the consuming application through some other means.

**Comment by bgrainger** [comment]
MySQL Connector/J uses `enabledSSLCipherSuites` in its connection options: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html; MariaDB Connector/J supports the same option: https://mariadb.com/kb/en/using-tls-ssl-with-mariadb-java-connector/

**Comment by bgrainger** [comment]
In practice, the connection string may not be too verbose; only one (mutually supported) cipher suite needs to be listed in order to establish a connection. That is, the minimal Aurora connection string (for .NET 5.0 on Linux) might just be: `Server=server.region.rds.amazonaws.com;User Id=user;Password=***;CACertificateFile=/rds-combined-ca-bundle.pem;TlsCipherSuite=TLS_DHE_RSA_WITH_AES_256_GCM_SHA384`.

So I'm inclined to just go with that (and not implement `TlsCipherSuiteFile`).

**Comment by iamcarbon** [comment]
A single TlsCipherSuite matching the .NET enum name is also elegant - ensures a strong cipher is used for non-aurora servers - and allows the library to connect to multiple servers in the same process with different settings. :heart:

**Comment by bgrainger** [comment]
Added a PR for this: https://github.com/mysql-net/MySqlConnector/pull/907

**Comment by bgrainger** [comment]
The _right_ answer is probably for Aurora to support modern cipher suites 😀 but I'll try to have a beta release for testing available later today.

**Comment by bgrainger** [comment]
1.1.1-beta.0.1 is available for download from GHPR; are you able to test with that? https://github.com/mysql-net/MySqlConnector/packages/39735

**Comment by iamcarbon** [comment]
Works, and in production now. Thanks again for the thoughtfulness you put into this!

**Comment by RyanGhd** [comment]
@bgrainger, is there any ETA for this version to be available in nuget?

**Comment by bgrainger** [comment]
I can release a non-beta version to NuGet soon (if you can't pull it from GHPR).

**Comment by passuied** [comment]
@bgrainger I'm experiencing the same issue but connecting to Aurora MySQL 5.6 which only supports TLS v1.0.
Trying to figure out which cipher suite to include (currently in the openssl.cnf file)
I have tried the cipher suite you mention (TLS_DHE_RSA_WITH_AES_256_GCM_SHA384=DHE-RSA-AES256-GCM-SHA384) but it seems it is specific to TLS 1.2

I'm not sure how to find the correct one (can't find anything useful in AWS doc)... Do you know which one applies here? and how/where to find this info?

Thanks in advance

**Comment by bgrainger** [comment]
@RyanGhd This is now available on NuGet in [1.2.0](https://github.com/mysql-net/MySqlConnector/releases/tag/1.2.0).

**Comment by RyanGhd** [comment]
@bgrainger , thanks so much! really appreciate it.

**Comment by andre197** [comment]
NuGet version: 1.3.9
.NET version: 5.0
MySql version: 5.6

@bgrainger  i'm having the same issue as @passuied. I have used the same solution which he provides but im receiving the following error

```
MySqlConnector.MySqlException (0x80004005): SSL Authentication Error

---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.

---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.

---> Interop+Crypto+OpenSslCryptographicException: error:141A90B5:SSL routines:ssl_cipher_list_to_bytes:no ciphers available

--- End of inner exception stack trace ---

at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)

at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)

--- End of inner exception stack trace ---

at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

at System.Net.Security.SslStream.ProcessAuthentication(Boolean isAsync, Boolean isApm, CancellationToken cancellationToken)

at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)

at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1359

at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1384

at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 470

at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 376

at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 107

at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 137

at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 863

at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 414

at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 380

at ConsoleApp1.Program.Main(String[] args) in C:\Users\Andrey.I.Andreev\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 32
```

The code i run:
``` csharp
namespace ConsoleApp1
{
    using System;
    using System.Data;
    using System.Threading.Tasks;
    using MySqlConnector;

    class Program
    {
        static void Main(string[] args)
        {
            while (true)
            {
                var csb = new MySqlConnectionStringBuilder(
                    "Server=server;" +
                    "Port=3306;" +
                    "Database=Name;" +
                    "Uid=root;" +
                    "Pwd=password;" +
                    "Connection Timeout=360;" +
                    "default command timeout=340;" +
                    "TlsVersion=\"TLS 1.0\";" +
                    "TlsCipherSuites=TLS_DHE_RSA_WITH_AES_256_GCM_SHA384");

                using (var connection = new MySqlConnection(csb.ConnectionString))
                {
                    try
                    {
                        var command = new MySqlCommand("SELECT 1", connection);
                        command.CommandType = CommandType.Text;

                        connection.Open();
                        command.ExecuteScalar();
                        Console.WriteLine("success");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex);
                    }
                }

                Task.Delay(10_000).GetAwaiter().GetResult();
            }
        }
    }
}
```

**The version of the nuget is 1.3.9 on .net 5.0**

This is the dockerfile

```dockerfile
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["ConsoleApp1/ConsoleApp1.csproj", "ConsoleApp1/"]
RUN dotnet restore "ConsoleApp1/ConsoleApp1.csproj"
COPY . .
WORKDIR "/src/ConsoleApp1"
RUN dotnet build "ConsoleApp1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ConsoleApp1.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

RUN sed -i "s|CipherString = DEFAULT@SECLEVEL=2|CipherString = ADH-AES128-SHA:ADH-AES128-SHA256:ADH-AES256-SHA256:@SECLEVEL=0|g" /etc/ssl/openssl.cnf

ENTRYPOINT ["dotnet", "ConsoleApp1.dll"]
```

Code example can be found in this attachment: [ConsoleApp1.zip](https://github.com/mysql-net/MySqlConnector/files/6638096/ConsoleApp1.zip)

The solution from @passuied didn't help also the solution from here: https://github.com/mysql-net/MySqlConnector/issues/927 
didn't help either. So can you advise on what else can i do?

**Comment by bgrainger** [comment]
Are you connecting to Aurora, or to a privately-hosted MySQL Server?

> SSL routines:ssl_cipher_list_to_bytes:no ciphers available

AFAICT, the connection is failing because your client can't negotiate a secure connection. Check the MySQL Manual on how to configure this: https://dev.mysql.com/doc/refman/5.6/en/encrypted-connection-protocols-ciphers.html#encrypted-connection-protocol-negotiation

If you can establish a secure connection with some other client (e.g., MySQL Workbench) execute `SHOW SESSION STATUS LIKE 'Ssl_cipher';` to see the cipher it's using, then try to use that in your connection string.
