### ISSUE TITLE
Aborted connection on app shutdown

### ISSUE THREAD

**Issue by Amundoz** [mysql-net/MySqlConnector#914]
Hi.

I notice in the unit tests of the project that MySql emits warning in Windows eventlog "Aborted connection xxx to db: 'mysqltest' user: 'root' host: 'localhost' (Got timeout reading communication packets)" and that this happens when test class is torn down. It seems perhaps that the connections to mysql aren't closed properly in the connection pool.

Is there documentation on how this should be handled in a production application using MySqlConnector? I've seen same issue on an application I have that uses MySqlConnector, and adding a call to ClearPoolsAsync on app domain shutdown doesn't seem to fix the issue.

**Comment by bgrainger** [comment]
Yes, calling `MySqlConnection.ClearAllPools` on shutdown should prevent this non-graceful termination of client connections to the server.

MySqlConnector should do that automatically since https://github.com/mysql-net/MySqlConnector/issues/545.

I don't notice any "aborted connections" on shutdown when running the `SideBySide` tests against a Docker container.

Do you have a repro of the problem?

**Comment by Amundoz** [comment]
Hi,

when using docker, do you check the eventlog?
I can reproduce this for example when running SideBySide tests against mariaDb instance on windows. The LeakConnections test is perhaps designed to force such disconnects?
```
		[Fact]
		public void LeakConnections()
		{
			var csb = AppConfig.CreateConnectionStringBuilder();
			csb.Pooling = true;
			csb.MinimumPoolSize = 0;
			csb.MaximumPoolSize = 6;
			csb.ConnectionTimeout = 3u;

			for (int i = 0; i < csb.MaximumPoolSize + 2; i++)
			{
				var connection = new MySqlConnection(csb.ConnectionString);
				connection.Open();

				// have to GC for leaked connections to be removed from the pool
				GC.Collect();
				Thread.Sleep(400);
			}
		}
```

**Comment by bgrainger** [comment]
I think the SideBySide tests do abort one connection, as part of one of the tests.

However, the tests have dozens of open connections across many connection pools and I don't see a slew of "Aborted connection" messages when the tests exit.
