### ISSUE TITLE
Implement MySqlBulkCopy.WriteToServer(DataTable, DataRowState)

### ISSUE THREAD

**Issue by dedpichto** [mysql-net/MySqlConnector#916]
Is it possible to implement MySqlBulkCopy.WriteToServer(DataTable, DataRowState) which will copy only rows that match the supplied row state in the supplied DataTable to a destination table?

**Comment by bgrainger** [comment]
I think this could easily be implemented as a helper method:

```csharp
void WriteToServer(MySqlBulkCopy bulkCopy, DataTable dataTable, DataRowState rowState) =>
    bulkCopy.WriteToServer(dataTable.Rows.Cast<DataRow>().Where(x => x.RowState == rowState), dataTable.Columns.Count);
```

It doesn't seem sufficiently complicated or generally useful to add as a built-in overload.
