### ISSUE TITLE
Using TransactionScope and automatically become XA transaction

### ISSUE THREAD

**Issue by easycode** [mysql-net/MySqlConnector#919]
When I use TransactionScope, the transaction automatically becomes an XA transaction , Even if the same database connection object is used。
And mysql8.0 has an xa transaction defect that causes the database to crash, see: https://jira.percona.com/browse/PS-6018

Can it be judged that it does not become an XA transaction when it is the same database conection object
Mine environment
1.netcore 3.1
2.mysql 8.0，MySqlConnector1.2.1

**Comment by bgrainger** [comment]
> Can it be judged that it does not become an XA transaction when it is the same database conection object

No, because MySqlConnector can't know ahead of time whether multiple connections will be used. To opt out of XA transactions (but still use `TransactionScope`) set `UseXaTransactions=false` in your connection string.

**Comment by easycode** [comment]
Ok, thank you
