### ISSUE TITLE
TransactionScope + UseXaTransactions=false -> System.NotSupportedException: 'Multiple simultaneous connections or connections with different connection strings inside the same transaction are not supported when UseXaTransactions=False.'

### ISSUE THREAD

**Issue by shadow1runner** [mysql-net/MySqlConnector#932]
We're utilizing a self-written `TransactionAspect` which sole responsibility is to start & commit/rollback a transaction by augmenting certain facade methods. We've utilized .net core's **TransactionScope** for this purpose and all was working fine while testing against a local MariaDB. However, when we moved into integration, we had to deal with a Galera Cluster and noticed that using this approach `MySqlConnector` makes use of XA transactions for that purpose, which is not supported by Galera.
Note that incoming http requests might trigger concurrent invocations of DB transactions, but all are heading to the same DB [using the very same connection string], a (Pomelo) `DbContext` per http lifecycle.
Thus, our approach was to simply add the well-documented (thx!) `UseXaTransactions=false;` connection string option but this in turn lead us to the [following exception](https://github.com/mysql-net/MySqlConnector/blob/a433553d97057e26a988ae007588a3daa3fe2287/src/MySqlConnector/MySqlConnection.cs#L287):

> System.NotSupportedException: 'Multiple simultaneous connections or connections with different connection strings inside the same transaction are not supported when UseXaTransactions=False.'

Note that you explicitly have tests for this case [here](https://github.com/mysql-net/MySqlConnector/blob/a433553d97057e26a988ae007588a3daa3fe2287/tests/SideBySide/TransactionScopeTests.cs#L659).

This puzzled us: why shouldn't it be possible that multiple transactions in different DbContexts and (thus I presume) different DbConnections towards the same database can be opened at the same time? Playing around with this, we replaced the usage of `TransactionScope` by directly using `_dbContext.Database.BeginTransaction()` instead and since then all is working fine.

These are the quintessential changes, which made it all work fine (that is: (1) no more XA transactions since it kills Galera, and (2) different connections can open their own respective (not distributed) transaction):
![image](https://user-images.githubusercontent.com/3902045/105487093-dbb47100-5caf-11eb-9231-df6e2fc77185.png)

So sry for the long read but this issue really boils down to a question that bothers me in order to understand this: Is the thing we're seeing the intended behavior when using `TransactionScope` since MySqlConnector is interpreting this as a distributed transaction?
Related: #919, #254 

PS: Using `_dbContext.Database.BeginTransaction()` instead of `using (var transactionScope = new TransactionScope())` doesn't use XA transactions either, even with `UseXaTransactions=true`.

Thanks a lot!

**Comment by bgrainger** [comment]
> This puzzled us: why shouldn't it be possible that multiple transactions in different DbContexts and (thus I presume) different DbConnections towards the same database can be opened at the same time?

Having multiple transactions in different DbContexts at the same time is fine.

Using those transactions within the same `TransactionScope` is an error, because they can't be committed or rolled back atomically, unless you use XA Transactions.

> Is the thing we're seeing the intended behavior when using TransactionScope since MySqlConnector is interpreting this as a distributed transaction?

Yes, that's correct.

> PS: Using _dbContext.Database.BeginTransaction() instead of using (var transactionScope = new TransactionScope()) doesn't use XA transactions either, even with UseXaTransactions=true.

This is by design; to enroll in a distributed transaction, the code needs to explicitly use `System.Transactions` types, not just an ADO.NET transaction.

**Comment by shadow1runner** [comment]
Thanks @bgrainger!
