### ISSUE TITLE
Use StyleCop to help enforce basic coding style

### ISSUE THREAD

**Issue by ejball** [mysql-net/MySqlConnector#94]
Enforcing a few StyleCop rules should help maintain coding style consistency over time.

**Comment by caleblloyd** [comment]
If we're going to add style checks, it should be added with a CI checker at the same time the repository-wide refactor is done to prevent any other un-styled code from getting in

Additionally, this is a lot of rules IMO.  I thought the styling on the repository was fine, except maybe a "use tabs, not spaces" check would be good

**Comment by caleblloyd** [comment]
Also, if there's a style checker added, it needs to be multi-platform, able run from the command line (can't assume what IDE, if any, a contributor may be using), and documented under a CONTRIBUTING section (in README.md or CONTRIBUTING.md)

**Comment by ejball** [comment]
As it stands, broken style rules will break the build (though I forgot to add the reference to the `netstandard1.3` build; I should do that). I know that can be controversial -- worrying about style rules can be a pain during active development -- but that's how [.NET Core StyleCop integration](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DotNetCli.md) works at the moment.

The existing styling on the repository is great; I made just a few minor changes to make it conform. The idea would be to ensure that the consistency continues as the project gets more contributors.

We should certainly be open to changing the rules; are there any in particular that seem unnecessarily restrictive? Many are on by default; `stylecop.rules` mostly lists rules that are turned off. If we hit one we don't like, we can easily add it to that file.

I agree that we should mention the coding style enforcement in CONTRIBUTING, though I'm not sure how detailed we'd want to be.

**Comment by caleblloyd** [comment]
> are there any in particular that seem unnecessarily restrictive?

IMO, any rule that would force braces around a one-line conditional seems restrictive.  Also any rule that forces line breaks at a certain number of characters.

My main worry is that the learning curve on the repo is already pretty high, and adding style requirements could be a tipping point and scare somebody away from contributing.  A lot of folks don't know how to `git reset HEAD~1` and `git push -f` their changes, so the commit log for their PR may end up looking like:

    add some feature
    fix styling
    fix styling again
    aaaaah this styling CI is annoying!

Then the maintainer says "please squash your commits".  Then that person googles how to do an interactive rebase, spends an hour trying to do that, and may just give up.

**Comment by ejball** [comment]
There are certainly pros and cons. Compilation fails if the rules are broken, so pushing commits with style violations seems unlikely.

FWIW, here are the guidelines that correspond to the code changes that I made:

* [SA1402](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1402.md): File may only contain a single class
* [SA1504](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1504.md): All accessors must be single-line or multi-line [that is, both get and set in a given property]
* [SA1508](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1508.md): A closing brace must not be preceded by a blank line.
* [SA1515](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1515.md): Single-line comment must be preceded by blank line
* [SA1519](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1519.md): Braces must not be omitted from multi-line child statement
* [SA1520](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1520.md): Use braces consistently [that is, in a single chained if/else statement]
