### ISSUE TITLE
Connection pool leak when connect time out

### ISSUE THREAD

**Issue by firephantomassasin** [mysql-net/MySqlConnector#947]
Hi @bgrainger,

We experienced an issue this morning, our web app encountered a lot of "Connect Timeout expired. All pooled connections are in use. The operation was canceled.".   Using the latest version: 1.2.1. We are using all ASYNC operations.

and it is weird that only 1 out of 20 instance is encountering this kind of error, and it never stops. I think there is a connection pool and connection leak when connect timeout occurred. After 15 mins since it doesn't stop, we forcedly restart that specific instance only (1 instance). We are using azure web apps with auto scale out rule. After restarting that specific instance, the issue is gone.

Our connection string has a very high value of maxConnection pool already (200) and it is really already sufficient. We didn't encounter any issue like this before, this is the first time.

I think there is a connection leak and connection pool leak here when error occurred like Connect Timeout expired. This is related to this issue: https://github.com/mysql-net/MySqlConnector/issues/836

**Comment by firephantomassasin** [comment]
We have also observed that the ram usage (private bytes) keeps on increasing during these issues.



![image](https://user-images.githubusercontent.com/8090574/107906005-134eca00-6f8b-11eb-8107-cad8e5c18886.png)


And the # of connections that is connected to the DB keeps on increasing as well. It seems that there is really a leaking happening here.

**Comment by badbod99** [comment]
Is this not potentially related to changes made off the back of #942 ? Potentially your code not closing the connection in the case of timeout?  Could check by setting CancellationTimeout to -1 which will cause the connection to close on timeout.

**Comment by bgrainger** [comment]
Do you have any logs from this period (ideally from before all the `Connect Timeout expired` errors occurred)?

If there is a connection leak, then the pool won't be able to provide any additional connections and it would cause a cascade of the errors you're seeing. Logs prior to that failure may provide a clue as to how connections are leaking.

**Comment by firephantomassasin** [comment]
@badbod99 I am closing the connection in case of timeout occurred, The code that I showed is just snippet, all our queries is wrap inside a try catch finally where the finally will close and dispose.  

@bgrainger we only logged exception errors in our prod, upon checking carefully, there was no errors nor any exceptions in the logs happened before the connect timeout expired errors occurred. The first error that we encountered was "Connect Timeout expired. All pooled connections are in use. The operation was canceled." and eventually all request on our web api is already experiencing that kind of exceptions, and suddenly the memory of that instance keeps on increasing already. 

This is our code on how we established connection:


protected async Task<T> ExecuteQueryAsync<T>(Func<Task<T>> queryFunction)

try
                {
                    await OpenConnectionAsync();

                    return await queryFunction(); //This will call the running execute query
                }
                catch (Exception ex)
                {
Logger.LogErrorExceptionOnly(ex, string.Format("Method Name: {0} | Retry {1}.", queryFunction.Method.Name, retry));
                        throw ex;
                }
                finally
                {
                    await CloseConnectionAsync();
                }


public async Task OpenConnectionAsync()
        {
            if (Connection.State != ConnectionState.Open)
            {
                await Connection.OpenAsync();
            }
        }


public async Task CloseConnectionAsync()
        {
            if (Connection.State != ConnectionState.Closed && Transaction == null)
            {
                await Connection.CloseAsync();
                await Connection.DisposeAsync();
                Connection = null;
            }
        }


Connections are properly closed and dispose right after the query,

**Comment by firephantomassasin** [comment]
Hi @bgrainger  it looks like we have resolved this issue by forcing closing & Disposing the connection even though there was a timeout in connecting.

So basically we have modified our close connection code into this:

public async Task CloseConnectionAsync()
        {
if(Transaction == null){

                await Connection.CloseAsync();
                await Connection.DisposeAsync();
                Connection = null;
}
        }


We are not checking if the connection is not closed, we closed and disposed the connection regardless of the status. Is this fine or do you see any possible issues that might occur?

I remember that in oraclle mysql.net, you cannot call the close & dispose connection if the connection status is closed (that is why we have a checker if the connection is not closed).

**Comment by bgrainger** [comment]
When looking at your earlier code, I missed that you were not disposing the connection in some code paths.

As you have discovered, this is not correct for MySqlConnector: every new `MySqlConnection` object that is created _must_ be disposed (whether the connection is open or not).

I still don't understand why you need to check for `if (Transaction == null)`; that seems like another potential bug. 

Generally, I would recommend _not_ reusing a `MySqlConnection` object in your code: they're cheap to create, and it's a frequent source of multi-threading bugs and leaks to not use local variables with a `using` statement. So I would strongly suggest writing your code as follows:

```csharp
protected async Task<T> ExecuteQueryAsync<T>(Func<Task<T>> queryFunction)
{
    // local variable; can use helper method to create it
    // always disposed via 'using'
    await using var connection = CreateConnection(); 
    try
    {
        await connection.OpenAsync();
        return await queryFunction(); //This will call the running execute query
    }
    catch (Exception ex)
    {
        Logger.LogErrorExceptionOnly(ex, string.Format("Method Name: {0} | Retry {1}.", queryFunction.Method.Name, retry));

        // NOTE: 'throw', not 'throw ex', to preserve call stack
        throw;
    }
}
```

**Comment by firephantomassasin** [comment]
Thank you! @bgrainger
