### ISSUE TITLE
Release schedule/roadmap

### ISSUE THREAD

**Issue by grrttedwards** [mysql-net/MySqlConnector#952]
Hello! My organization is interested in some of the upcoming features that are released currently only in Beta (namely the improved connection reset performance #178). There does exist a “roadmap” for versions 1.0 and 2.0, but neither are updated often or relevant here. Are there any plans for a full release of the beta changes soon, or can some information be shared, given beta 1 was released a few months ago?
Thanks for the amazing work!

**Comment by bgrainger** [comment]
I know some organisations are using the beta version ... and it has just as much support as the "stable" version 😀 so if you want to test it out on a few "canary" nodes in your deployment and report if you have any issues, that'd be appreciated.

There are some infrequent reports that https://github.com/mysql-net/MySqlConnector/issues/939 isn't consistently fixed, so I'm trying to track those down and get a consistent repro, then determine how to proceed.

1.3.0 RTM might be in a week or two if that's resolved quickly.

**Comment by bgrainger** [comment]
[1.3.0](https://github.com/mysql-net/MySqlConnector/releases/tag/1.3.0) is released.

There's no concrete roadmap beyond that (except for some ideas for 2.0).

**Comment by grrttedwards** [comment]
Amazing!
