### ISSUE TITLE
Support the new BCL `DateOnly` and `TimeOnly` structs

### ISSUE THREAD

**Issue by roji** [mysql-net/MySqlConnector#963]
New DateOnly and TimeOnly structs are being introduced to .NET 6 as alternatives to DateTime (https://github.com/dotnet/runtime/issues/49036).

**Comment by bgrainger** [comment]
As a parameter value, `DateOnly` could map to `DATE`, and `TimeOfDay` to `TIME`.

When reading (e.g., with `GetFieldValue<T>`?) need to decide if extra data (e.g., `GetFieldValue<DateOnly>` on a `DATETIME` column, or `GetFieldValue<TimeOfDay>` on a `TIME` column that is > 24 hrs) is just truncated/silently dropped, or causes an exception.

**Comment by mattjohnsonpint** [comment]
Please note that the final names for these types are `DateOnly` and `TimeOnly` and that they are now merged into the main branch for the next version of .NET 6 (preview 4 likely).  Please rename the title of this issue accordingly.  Thanks.

**Comment by bgrainger** [comment]
The commit written for this doesn't add support for converting from `MySqlDateTime`. That struct mostly exists for backwards compatibility with MySQL Connector/NET. Converting from it to `DateOnly` has a simple workaround: `DateOnly.FromDateTime(mySqlDateTime.GetDateTime())`.

**Comment by bgrainger** [comment]
@Germs2004 This was implemented in [MySqlConnector 2.0.0](https://github.com/mysql-net/MySqlConnector/releases/tag/2.0.0).

**Comment by bgrainger** [comment]
@Germs2004 I created https://github.com/mysql-net/MySqlConnector/issues/1451 to track changing the default behaviour.
