### ISSUE TITLE
Improve ConnectionReset connection string options

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#967]
_Originally posted by @bgrainger in https://github.com/mysql-net/MySqlConnector/issues/461#issuecomment-806353237_

> The available options one could choose would be:
> 
> * reset connection upon return to pool, ping on retrieval (current default)
> * reset connection upon return to pool, no ping on retrieval
> * reset connection upon retrieval
> * no reset; ping on retrieval
> * no reset; no ping on retrieval
> 
> There are currently three connection string options to control this, and only certain combinations of them are valid; it would be nice to simplify that.

Reset | Ping | `ConnectionReset` | `DeferConnectionReset` | `ConnectionIdlePingTime`
--- | --- | --- | --- | --- 
Background | Yes | `true` (default) | `false` (default) | `0` (default)
Background | No | `true` (default) | `false` (default) | `10000`
On Open | N/A | `true` (default) | `true` | _any_
No | Yes | `false` | _any_ | `0` (default)
No | No | `false` | _any_ | `10000`

The best combination (for correctness and performance) would be background reset with no ping on open. This could run the risk of returning an invalid session, so callers would need to surround (a sequence of) MySQL operations with retry logic (e.g., using Polly). However, this is already a best practice for many reasons (although seldom demonstrated in ADO.NET examples).

`ConnectionIdlePingTime` has always been documented as experimental, so I have no qualms with removing/deprecating it. `DeferConnectionReset` is very recently introduced, so it could be safe to deprecate, too. `ConnectionReset` is longstanding so probably shouldn't be changed, but could be retained in conjunction with a new setting.

Possibly a new setting `ConnectionValidationMode` (exact name TBD) with the following options: `None`, `Ping`, `Reset`.

`ConnectionReset` | `ConnectionValidationMode` | Behaviour
--- | --- | ---
`true` | `None` | reset in background, no ping
`true` | `Ping` | reset in background, ping on `Open`
`true` | `Reset` | reset on `Open`
`false` | `None` | no reset, no ping
`false` | `Ping` | no reset, ping on `Open`
`false` | `Reset` | _invalid combination_

**Comment by firephantomassasin** [comment]
Hi @bgrainger  I think the ConnectionIdlePingTime (in seconds) is useful in order to determine the ping, like if it has been idle for 20 seconds already then I think its good to make a ping rather than no ping at all. 

We have seen an increase in performance in v1.2 using ConnectionReset=false;ConnectionIdlePingTime=10;

**Comment by bgrainger** [comment]
https://github.com/mysql-net/MySqlConnector/issues/1013 will remove the code for `DeferConnectionReset`, so this case won't be necessary.
