### ISSUE TITLE
Support ER_CLIENT_INTERACTION_TIMEOUT

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#970]
In [MySQL 8.0.24](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-24.html#mysqld-8-0-24-connection-management)

> Previously, if a client did not use the connection to the server within the period specified by the wait_timeout system variable and the server closed the connection, the client received no notification of the reason. Typically, the client would see 1Lost connection to MySQL server during query1 (`CR_SERVER_LOST`) or 1MySQL server has gone away1 (`CR_SERVER_GONE_ERROR`).
> 
> In such cases, the server now writes the reason to the connection before closing it, and client receives a more informative error message, `The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.` (`ER_CLIENT_INTERACTION_TIMEOUT`).

We need to handle the Error payload sent by MySQL Server (containing this error message) before it closes the connection.

**Comment by bgrainger** [comment]
Fixed in [1.3.4](https://github.com/mysql-net/MySqlConnector/releases/tag/1.3.4).

**Comment by olx** [comment]
the same problem in version  2.1+ (mysql server 8.0.26) with EF (Pomelo provider)

**Comment by bgrainger** [comment]
> the same problem in version 2.1+ (mysql server 8.0.26) with EF (Pomelo provider)

Please create a new issue with full details of the problem.

**Comment by mguinness** [comment]
> the same problem in version 2.1+ (mysql server 8.0.26) with EF (Pomelo provider)

Also cross posted at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1545#issuecomment-1154717444
