### ISSUE TITLE
Use StringBuilder.GetChunks in MySqlParameter.AppendBinary

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#977]
If `MySqlParameter.Value` is set to a `StringBuilder` instance (#975) and `MySqlCommand.Prepare()` is called, the code currently calls `StringBuilder.ToString()` and writes it as a length-encoded UTF-8 string.

In .NET 5.0, it should be more performant to use `GetChunks`:

1. ~~loop over the chunks and sum the results of `GetByteCount` (for a `UTF8Encoder`)~~ calculate the total length of the UTF-8 string
2. write the length prefix
3. loop over the chunks and write each out (encoding each one into UTF-8)

**Comment by novak-as** [comment]
@bgrainger I can grab this one

**Comment by bgrainger** [comment]
Fixed in [1.3.9](https://github.com/mysql-net/MySqlConnector/releases/tag/1.3.9).
