### ISSUE TITLE
UseAffectedRows with Mysql 8.0.24

### ISSUE THREAD

**Issue by fsaffioti** [mysql-net/MySqlConnector#988]
Even if i added UseAffectedRows=true on my connection string, after an INSERT with ON DUPLICATE KEY UPDATE  the  ExecuteNonQueryAsync return affected rows 2 (when a row is updated)

Working with AspNet core 5  based on .NET 5
Mysql 8.0.24

**Comment by bgrainger** [comment]
Please provide:

* a `docker run` command line that starts a specific version of MySQL Server with the appropriate settings (as command-line arguments)
* a SQL script that creates your schema, tables, and inserts any required rows
* a C# program that demonstrates the bug
