### ISSUE TITLE
vb.net :  MySqlBulkCopy.WriteToServerAsync(Datatable) not working and not writing to MYSQL DB 

### ISSUE THREAD

**Issue by SIBA-FEMD** [mysql-net/MySqlConnector#992]
'Using the same set up as before 
'
'-   Read table from db and display as datatable [ SQL_db_dumptable_as_datatable(db_working_table As String) ] , Working
'
'-  Check if table exists in db [does_db_table_exist(table_name As String)]  , working
'
'-  Write datatable as new DB table [sql_db_write_new_datatable_to_db(wr_dt As DataTable, db_working_table_name As String) ] ',working
'
' - Write datatable as new DB table using the async process from your library **[ !! not working need help !!]**
'      [  sql_db_write_new_datatable_to_db_async(wr_dt As DataTable, db_working_table_name As String) ] 
'
'   Dump of the mysql db level transactions from the db transaction logs can be found at the end of the message 

'++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    Public Function SQL_db_dumptable_as_datatable(db_working_table As String) As DataTable

        ' ---------------------------------------------------------------------------------------------------
        '   
        '    tested Fully working
        '
        '----------------------------------------------------------------------------------------------------
        '
        '  Function to read an whole db-table and dump it to a datatable
        '
        Dim op As String = ""
        Dim dt_op As New DataTable
        Dim dt_table_schema As New DataTable
        Dim row As DataRow

        Dim db_connection As MySqlConnection = New MySqlConnection(sql_connection)

        Using db_connection
            db_connection.Open()
            Dim db_table_select As String = Trim("select * from " + db_working_table + ";")
            Dim db_command As MySqlCommand = New MySqlCommand(db_table_select, db_connection)
            Dim reader As MySqlDataReader
            reader = db_command.ExecuteReader()
            ' 
            '  Continously read the data base table until there are no more rows to read 
            '
            dt_table_schema = reader.GetSchemaTable()   ' get data schema from db and place into table to get column headings and datatype

            For Each row_in_schema As DataRow In dt_table_schema.Rows

                dt_op.Columns.Add(New DataColumn(row_in_schema("ColumnName"), row_in_schema("DataType")))

            Next

            While reader.Read()
                row = dt_op.NewRow()
                For j As Integer = 0 To (reader.VisibleFieldCount - 1)
                    row.Item(j) = reader.GetValue(j)
                Next
                dt_op.Rows.Add(row)
            End While
            db_connection.Close()
        End Using

        Return dt_op
    End Function

    Public Function does_db_table_exist(table_name As String) As Boolean

        ' ---------------------------------------------------------------------------------------------------
        '   
        '    tested Fully working
        '
        '----------------------------------------------------------------------------------------------------
        '
        '  Function to check if table exists in db
        '

        Dim op As Boolean = False

        Dim db_connection As MySqlConnection = New MySqlConnection(sql_connection + ";AllowLoadLocalInfile=true")

        Dim Sql_command_create_table As String = "SHOW TABLES;"

        Dim opx As String = ""

        db_connection.Open()
        Try
            Using db_connection

                '------------------------------------------------
                '  Execute the SQL command to create the new mysql table in the db 
                '
                Dim db_command As New MySqlCommand
                Dim reader As MySqlDataReader
                Dim db_activity_result As Stream
                db_command.CommandText = Sql_command_create_table
                db_command.Connection = db_connection
                reader = db_command.ExecuteReader
                While reader.Read()
                    For j As Integer = 0 To (reader.VisibleFieldCount - 1)
                        opx = opx + reader.GetValue(j).ToString() + vbCrLf
                    Next
                End While
                '------------------------------------------------
                ' Debug.WriteLine(opx)
                'Debug.WriteLine(vbCrLf + vbCrLf + table_name)
                'Debug.WriteLine(vbCrLf + vbCrLf + opx.IndexOf(table_name).ToString + vbCrLf)
            End Using
            If opx.IndexOf(table_name) >= 0 Then op = True Else op = False
        Catch ex As Exception
            op = False
        End Try

        db_connection.Close()

        Return op
    End Function

    Public Function sql_db_write_new_datatable_to_db(wr_dt As DataTable, db_working_table_name As String) As Boolean
        ' ---------------------------------------------------------------------------------------------------
        '   
        '    Tested : Fully working 
        '
        '----------------------------------------------------------------------------------------------------
        '-----------------------------------------------------------------------------------------------------------------
        '
        '  Creates a a new table in the working mysql database using the specified Datatable and the db_working_table_name 
        '  
        '  ref  :  https://mysqlconnector.net/api/mysqlconnector/mysqlbulkcopytype/
        '-----------------------------------------------------------------------------------------------------------------
        '
        Dim op As Boolean = False

        If does_db_table_exist(db_working_table_name) Then
            op = False
            MessageBox.Show("Error db wrt, datatable :: " + db_working_table_name + " -- Already exists")
        Else
            Dim db_connection As MySqlConnection = New MySqlConnection(sql_connection + ";AllowLoadLocalInfile=true")
            Dim Column As DataColumn
            '
            '  Before writing the data from the datatabel to the MYSQL DB create a new tabel which has matching column types 
            '  to the same column data types found in the datatable 
            '
            '-------------------------------------
            ' Create the SQL string that is used to create the new table.
            '------------------------------------

            Dim Sql_command_create_table As String = " CREATE TABLE " + Trim(db_working_table_name) + "("

            Dim data_type As String = ""
            For Each Column In wr_dt.Columns
                Select Case Column.DataType
                    Case GetType(String)
                        data_type = "VARCHAR(" + MARIA_DB_VARCHAR_string_lenght + ")"
                    Case GetType(Date)
                        data_type = "DATETIME"
                    Case GetType(Boolean)
                        data_type = "BOOLEAN"
                    Case GetType(Integer)
                        data_type = "INT"
                    Case GetType(Single)
                        data_type = "FLOAT"
                    Case GetType(Double)
                        data_type = "DOUBLE"
                    Case GetType(Long)
                        data_type = "BIGINT"
                    Case Else
                        data_type = ""
                End Select

                If (data_type.Length > 2) Then

                    Sql_command_create_table = Sql_command_create_table + Trim(Column.ColumnName) + " " + data_type + ","

                End If

            Next

            Sql_command_create_table = Trim(Mid(Sql_command_create_table, 1, (Len(Sql_command_create_table) - 1))) + ");"

            If Sql_command_create_table.Length > 25 Then

                db_connection.Open()
                Try
                    Using db_connection

                        '------------------------------------------------
                        '  Execute the SQL command to create the new mysql table in the db 
                        '
                        Dim db_command As New MySqlCommand
                        db_command.CommandText = Sql_command_create_table
                        db_command.Connection = db_connection
                        db_command.ExecuteNonQuery()
                        '------------------------------------------------
                        '
                        '  Bulk copy the data from the datatable to the newly created MYSQL db table
                        '
                        ' You must add AllowLoadLocalInfile=true; to your MySQL/MariaDB server connection string when you want to load a local file.
                        '
                        ' If using something Like a LOAD LOCAL INFILE command Then add --local_infile = 1 to the command itself And it should work.
                        ' 
                        ' In recent versions of both servers this functionality Is disabled by default And should only be enabled when necessary.

                        '  https://dev.mysql.com/doc/refman/8.0/en/load-data.html

                        Dim bulkCopy As MySqlBulkCopy = New MySqlBulkCopy(db_connection)
                        'MySqlBulkLoader.Local = True

                        bulkCopy.DestinationTableName = db_working_table_name
                        '------------------------------------------------
                        bulkCopy.WriteToServer(wr_dt)  ''  
                        '------------------------------------------------
                    End Using
                    op = True
                Catch ex As Exception
                    op = False
                End Try

                db_connection.Close()

                ' ============
                '  Notes 
                ' ============
                ' The only "trick" was to format the DateTime field so MySQL could parse it:

                ' Public Class CSVItemMap
                '   Inherits CsvClassMap(Of SmSample)
                '
                '   Public Sub New()
                '     AutoMap()
                '       Map(Function(m) m.ItemDate).TypeConverterOption("yyyy-MM-dd")
                '   End Sub
                '
                ' End Class

            Else
                op = False
            End If
        End If
        Return op

    End Function
    Public Function sql_db_write_new_datatable_to_db_async(wr_dt As DataTable, db_working_table_name As String) As Boolean
        ' ---------------------------------------------------------------------------------------------------
        '   
        '    Tested : under test .  Not working . Does not Async write data to table ... Driver level issue
        '
        '----------------------------------------------------------------------------------------------------
        '-----------------------------------------------------------------------------------------------------------------
        '
        '  Creates a a new table in the working mysql database using the specified Datatable and the db_working_table_name 
        '  
        '  ref  :  https://mysqlconnector.net/api/mysqlconnector/mysqlbulkcopytype/
        '-----------------------------------------------------------------------------------------------------------------
        '

        Dim does_table_exist As Boolean = False
        Dim opx As String = ""
        Dim db_connection_chk As MySqlConnection = New MySqlConnection(sql_connection + ";AllowLoadLocalInfile=true")
        'Try
        '------------------------------------------------
        '  Execute the SQL command to check if wanted table name exists in the db
        '
        Using db_connection_chk
            db_connection_chk.Open()

            Dim db_command_chk As New MySqlCommand
            Dim readerx As MySqlDataReader
            db_command_chk.CommandText = "SHOW TABLES;"
            db_command_chk.Connection = db_connection_chk
            readerx = db_command_chk.ExecuteReader()
            While readerx.Read()
                For j As Integer = 0 To (readerx.VisibleFieldCount - 1)
                    opx = opx + readerx.GetValue(j).ToString() + vbCrLf
                Next
            End While

        End Using
        db_connection_chk.Close()

        If opx.IndexOf(db_working_table_name) >= 0 Then does_table_exist = True Else does_table_exist = False
        'Catch ex As Exception
        'does_table_exist = False
        '
        'End Try
        '------------------------------------------------

        Dim op As Boolean = False
        If does_table_exist Then
            op = False
            MessageBox.Show("Error db aysnc wrt, datatable :: " + db_working_table_name + " -- Already exists")
        Else

            Dim Column As DataColumn
            '
            '  Before writing the data from the datatabel to the MYSQL DB create a new tabel which has matching column types 
            '  to the same column data types found in the datatable 
            '
            '-------------------------------------
            ' Create the SQL string that is used to create the new table.
            '------------------------------------

            Dim Sql_command_create_table As String = " CREATE TABLE " + Trim(db_working_table_name) + "("

            Dim data_type As String = ""
            For Each Column In wr_dt.Columns
                Select Case Column.DataType
                    Case GetType(String)
                        data_type = "VARCHAR(" + MARIA_DB_VARCHAR_string_lenght + ")"
                    Case GetType(Date)
                        data_type = "DATETIME"
                    Case GetType(Boolean)
                        data_type = "BOOLEAN"
                    Case GetType(Integer)
                        data_type = "INT"
                    Case GetType(Single)
                        data_type = "FLOAT"
                    Case GetType(Double)
                        data_type = "DOUBLE"
                    Case GetType(Long)
                        data_type = "BIGINT"
                    Case Else
                        data_type = ""
                End Select

                If (data_type.Length > 2) Then

                    Sql_command_create_table = Sql_command_create_table + Trim(Column.ColumnName) + " " + data_type + ","

                End If

            Next
            Sql_command_create_table = Trim(Mid(Sql_command_create_table, 1, (Len(Sql_command_create_table) - 1))) + ");"

            If Sql_command_create_table.Length > 25 Then
                'Try
                Dim db_connection As MySqlConnection = New MySqlConnection(sql_connection + ";AllowLoadLocalInfile=true")
                Using db_connection

                    '------------------------------------------------
                    '  Execute the SQL command to create the new mysql table in the db 
                    '
                    '------------------------------------------------
                    Dim db_command As New MySqlCommand
                    db_connection.Open()
                    db_command.CommandText = Sql_command_create_table
                    db_command.Connection = db_connection
                    db_command.ExecuteNonQuery()
                    db_connection.Close()
                End Using

                Using db_connection
                    db_connection.OpenAsync()
                    Dim bulkCopy As MySqlBulkCopy = New MySqlBulkCopy(db_connection)
                    bulkCopy.DestinationTableName = db_working_table_name
                    '------------------------------------------------
                    bulkCopy.WriteToServerAsync(wr_dt)  ''  <-------- issue here 
                    '------------------------------------------------
                    db_connection.CloseAsync()
                End Using

                op = True
                'Catch ex As Exception
                'op = False
                'End Try

            Else
                op = False
            End If
        End If
        Return op
    End Function
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Maria db Transaction log for the error case 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
210520 10:40:29	     6 Query	SHOW TABLES
		     6 Query	SET NAMES utf8mb4
		     7 Connect	root@localhost on test using TCP/IP
		     7 Query	SET NAMES utf8mb4
		     7 Query	CREATE TABLE test_std_2(event_log_line_number INT,Month_Date_Year VARCHAR(1023),Hour_Minute_Second VARCHAR(1023),Event VARCHAR(1023),PS VARCHAR(1023),Sample_Number VARCHAR(1023),PPN VARCHAR(1023),BV VARCHAR(1023),BL_percent VARCHAR(1023),Operation_Status VARCHAR(1023),PLRF VARCHAR(1023),Analysis_Comments VARCHAR(1023))
		     7 Query	SET NAMES utf8mb4
210520 10:43:33	     6 Quit	
		     7 Quit	
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Analysis by SIBA of the log 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
1.   Table definition is written by normal method using a normal db transaction process 
2.   No error is thrown by the .NET enviroment
3.  ****No data is written to the newly created DB table by the bulkcopyasync()  process**** 

Any Ideas how to fix the problem ???

**Comment by bgrainger** [comment]
You're calling `Async` methods without using the `Await` operator: https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/await-operator

It seems highly likely that the database connection is getting closed before the async operation has completed (or possibly even started).

**Comment by SIBA-FEMD** [comment]
Hi Again 

Yes you work correct again but **Await** does not work in vb.net  with the way you wrote you the mysconnector driver.

I got it working but via another method , its ugly but works

Here is the fixed code
'-------------------------------------------------------------------------------------------------------------------

   Public Function sql_db_write_new_datatable_to_db_async(wr_dt As DataTable, db_working_table_name As String) As Boolean
        ' ---------------------------------------------------------------------------------------------------
        '   
        '    Tested : under test .  Not working . Does not Async write data to table ... Driver level issue
        '
        '----------------------------------------------------------------------------------------------------
        '-----------------------------------------------------------------------------------------------------------------
        '
        '  Creates a a new table in the working mysql database using the specified Datatable and the db_working_table_name 
        '  
        '  ref  :  https://mysqlconnector.net/api/mysqlconnector/mysqlbulkcopytype/
        '-----------------------------------------------------------------------------------------------------------------
        '

        Dim does_table_exist As Boolean = False
        Dim opx As String = ""
        Dim db_connection_chk As MySqlConnection = New MySqlConnection(sql_connection + ";AllowLoadLocalInfile=true")
        'Try
        '------------------------------------------------
        '  Execute the SQL command to check if wanted table name exists in the db
        '
        Using db_connection_chk
            db_connection_chk.Open()

            Dim db_command_chk As New MySqlCommand
            Dim readerx As MySqlDataReader
            db_command_chk.CommandText = "SHOW TABLES;"
            db_command_chk.Connection = db_connection_chk
            readerx = db_command_chk.ExecuteReader()
            While readerx.Read()
                For j As Integer = 0 To (readerx.VisibleFieldCount - 1)
                    opx = opx + readerx.GetValue(j).ToString() + vbCrLf
                Next
            End While


        End Using
        db_connection_chk.Close()

        If opx.IndexOf(db_working_table_name) >= 0 Then does_table_exist = True Else does_table_exist = False
        'Catch ex As Exception
        'does_table_exist = False
        '
        'End Try
        '------------------------------------------------


        Dim op As Boolean = False
        If does_table_exist Then
            op = False
            MessageBox.Show("Error db aysnc wrt, datatable :: " + db_working_table_name + " -- Already exists")
        Else

            Dim Column As DataColumn
            '
            '  Before writing the data from the datatabel to the MYSQL DB create a new tabel which has matching column types 
            '  to the same column data types found in the datatable 
            '
            '-------------------------------------
            ' Create the SQL string that is used to create the new table.
            '------------------------------------

            Dim Sql_command_create_table As String = " CREATE TABLE " + Trim(db_working_table_name) + "("

            Dim data_type As String = ""
            For Each Column In wr_dt.Columns
                Select Case Column.DataType
                    Case GetType(String)
                        data_type = "VARCHAR(" + MARIA_DB_VARCHAR_string_lenght + ")"
                    Case GetType(Date)
                        data_type = "DATETIME"
                    Case GetType(Boolean)
                        data_type = "BOOLEAN"
                    Case GetType(Integer)
                        data_type = "INT"
                    Case GetType(Single)
                        data_type = "FLOAT"
                    Case GetType(Double)
                        data_type = "DOUBLE"
                    Case GetType(Long)
                        data_type = "BIGINT"
                    Case Else
                        data_type = ""
                End Select

                If (data_type.Length > 2) Then

                    Sql_command_create_table = Sql_command_create_table + Trim(Column.ColumnName) + " " + data_type + ","

                End If

            Next
            Sql_command_create_table = Trim(Mid(Sql_command_create_table, 1, (Len(Sql_command_create_table) - 1))) + ");"

            If Sql_command_create_table.Length > 25 Then
                Try
                    Dim db_connection As MySqlConnection = New MySqlConnection(sql_connection + ";AllowLoadLocalInfile=true;")
                    Using db_connection

                        '------------------------------------------------
                        '  Execute the SQL command to create the new mysql table in the db 
                        '  This done synchronusly as this is pretty quick to do 
                        '
                        '------------------------------------------------
                        Dim db_command As New MySqlCommand
                        db_connection.Open()
                        db_command.CommandText = Sql_command_create_table
                        db_command.Connection = db_connection
                        db_command.ExecuteNonQuery()
                        db_connection.Close()
                    End Using


                    '------------------------------------------------
                    '
                    ' Execute write to table async as this better for big  data tables writes.
                    '
                    '------------------------------------------------


                    Dim db_connection_A As MySqlConnection = New MySqlConnection(sql_connection + ";AllowLoadLocalInfile=true;")

                    Using (db_connection_A)

                        Dim db_T_async As Task = db_connection_A.OpenAsync()

                        db_T_async.Wait()

                        Dim bulkCopy As MySqlBulkCopy = New MySqlBulkCopy(db_connection_A)

                        bulkCopy.DestinationTableName = db_working_table_name

                        Dim blk_copy As ValueTask = bulkCopy.WriteToServerAsync(wr_dt)

                        Dim blk_copy_task As Task = blk_copy.AsTask

                        blk_copy_task.Wait()

                        blk_copy_task.Dispose()

                        Dim db_c_async As Task = db_connection_A.CloseAsync()

                        db_c_async.Wait()

                        db_T_async.Dispose()

                        db_c_async.Dispose()

                    End Using


                    op = True
                Catch ex As Exception
                    op = False
                End Try



            Else
                op = False
            End If
        End If
        Return op

    End Function

**Comment by bgrainger** [comment]
There are synchronous methods you could use instead: `MySqlConnection.Open`, `MySqlBulkCopy.WriteToServer`.
