### ISSUE TITLE
Getting lots of exceptions from BackgroundConnectionResetHelper

### ISSUE THREAD

**Issue by CatalinAdlerDF** [mysql-net/MySqlConnector#993]
I've recently gotten a storm of such exception; unexplained as nothing changed, just updated of other nuget packages.
I'm on latest connector version, targeting mysql 8 on gcp.

``` 
"Unhandled exception: System.InvalidOperationException: Expected state to be Connected but was ClearingPendingCancellation.
   at MySqlConnector.Core.ServerSession.VerifyState(State state) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1617
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection owningConnection, Boolean returnToPool, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 614
   at MySqlConnector.Core.BackgroundConnectionResetHelper.ReturnSessionsAsync() in /_/src/MySqlConnector/Core/BackgroundConnectionResetHelper.cs:line 97" 
```

Connection String like:
"Server=<ip>;Database=<db>;Uid=<user_id>;Pwd=<pass>;ConnectionTimeout=30;Pooling=true;AllowLoadLocalInfile=true;Allow Zero Datetime=True;MaximumPoolSize=150;Connection Idle Timeout=60;"

iirc, with default settings, the connection reset happened when connection if returned from the pool, thus why is the background reset helper even active?

**Comment by bgrainger** [comment]
Really not sure how `ClearingPendingCancellation` is ending up as the state here, since that's just set (and cleared) synchronously during `FinishQuerying`. That should happen when `MySqlDataReader` is disposed, which should complete before `MySqlConnection` is disposed.

What does your connection cleanup logic look like? Are you using `using` statements for everything?

**Comment by CatalinAdlerDF** [comment]
yes, using the `[await] using` everywhere i am aware of.
I'll run a linter again to double check.

**Comment by bgrainger** [comment]
This should be improved in [1.3.10](https://github.com/mysql-net/MySqlConnector/releases/tag/1.3.10), which sets  `DeferConnectionReset=true` by default. https://github.com/mysql-net/MySqlConnector/issues/1013 will remove this code.
