### ISSUE TITLE
Unable to connect to a specified MySQL host from AWS ECS 

### ISSUE THREAD

**Issue by apekshab32** [mysql-net/MySqlConnector#996]
I have 2 C# microservices running on an AWS ECS cluster. Both microservices use MySqlConnector to connect (Read and Write) to the same AWS Aurora Database with MySql engine. The DB connection is established when the microservice instance is started and is closed at the end of the instance lifecycle. 

I am seeing intermittent issues where one of the microservice suddenly is unable to connect to the DB (This is a single threaded always running microservice), while the other microservice talking to the same database host is working as expected.

On debugging this further with AWS support, I learned that there were no problems with the Database or the ECS cluster instance. AWS support suspected this could be a MySqlConnector library issue.

Error Message :  

> Unable to connect to any of the specified MySQL hosts.

MySqlConnector NuGet version : 1.0.1
MySql server version : 5.7
Aurora version: 2.08.2
.Net SDK : .Net Core 3.1
SSH.NEt version: 2016.1.0

Code snippet used to connect to the Db:

```
public class AuroraDbContext : DbContext, IAuroraDbContext, IDisposable
{
   private readonly AuroraDbConfig _configOptions;
   protected readonly SshClient _client;
   protected readonly ForwardedPortLocal _local;
   protected readonly MySqlConnection _connection;
   
	public AuroraDbContext(IOptions<DbConfig> configOptions, IConfiguration configuration) {
			 _configOptions =  configOptions.Value.AuroraDbConfig;
	   
			 var builder = new MySqlConnectionStringBuilder {
				Server = _configOptions.Server,
				Port = (uint)_configOptions.Port,
				Database = _configOptions.Database,
				UserID = _configOptions.Username,
				Password = _configOptions.Password,
				SslMode = MySqlSslMode.None,
				PersistSecurityInfo = true,            
			 };
			 if (_configOptions.UseSsh) {
				var keyFile = new PrivateKeyFile($@"{Path.GetDirectoryName(Assembly.GetEntryAssembly().Location)}/{_configOptions.PrivateKeyFileName}");

				_client = new SshClient(configuration["SSHEC2PrivatIP"], _configOptions.SshUsername, keyFile);
				_client.Connect();
				if (_client.IsConnected) {
				   _local = new ForwardedPortLocal("127.0.0.1", _configOptions.Server, (uint)_configOptions.Port);
				   _client.AddForwardedPort(_local);
				   _local.Start();
				}
				builder.Port = _local.BoundPort;
				builder.Server = "127.0.0.1";
				builder.ConnectionTimeout = 600;
				builder.DefaultCommandTimeout = 240;
			 }
			 _connection = new MySqlConnection(builder.ConnectionString);
		  }
}
```

Need help to understand what could be wrong here. Any help is much appreciated. Thank you!

**Comment by bgrainger** [comment]
v1.0.1 is nine months old; I'm not aware of any fixes targeting this problem, but it would still be worth updating.

Are you connecting via SSH? That introduces another variable to investigate as a potential cause of the problem.

For further debugging, I'd recommend enabling and collecting detailed logging; that may help identify a problem.
